 
 ############################## 
 # Country definition for the British Raj # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = U02  
   regular_id             = IND 
   puppet                 = ENG 
   capital                = 1459 
   manpower               = 508 
   dissent = 9
   
   
   relative_manpower = 0.6000 
   # Resource Reserves 
energy                 = 5520
metal                  = 2760
rare_materials         = 1380
   oil                    = 500 
   supplies               = 500 
   money                  = 70 
   transports             = 200 
   escorts                = 20 
  
   
   diplomacy = 
   {   
  relation = {  tag = ENG value = 50 access = yes  }  
    } 
   nationalprovinces      = {
  #Malaysia                 
  1439 1445 1442 1450 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1413 1418 1443 1421 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529    } 
   ownedprovinces         = {   
  #Malaysia                 
  1439 1445 1442 1450 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1413 1418 1443 1421 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529 
   } 
   controlledprovinces    = {    
  #Malaysia                 
  1439 1445 1442 1450 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1413 1418 1443 1421 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529 
   } 
  
   SpyInfo                = {  country = "U02" NumberOfSpies = 3  } 
  
	techapps = {  
	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100    
	# Mountain Division 
	1160 1170 1180 1190 1200 1210 1220 1230 1240   
	# Supply 
	1910 1920 1930 1940 1950 1960 1970 1980   
	# Cavalry Division 
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
	#Motorised Inf
	1396
	# Armoured Car 
	2860 2870 2880 2020   
	# Field Artillery 
	2290 2300 2310 
	# Tank 
	7600 7610 2620 2010 
	# Engineers
	1830 1840 1850 1860
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200
	# Destroyer
	3010 3020 3030 3040 3050 3060
	# Light Cruiser 
	3110 3120 3130 3140 3150
	# Heavy Cruiser 
	3210 3220 3230 3240
	# Fighter 
	4500 4510 4520 4530 4540 4550 4010 4020
	# Bomber 
	4600 4610 4620 4630 4120
	# Computers & cryptography
	5310 54010 54020 54030 5316 5326 5327
	# Manufacturing
	5810 5820 5050 5830 5060
	# Construction Engineering 
	5800 5080 5090 
	# Torpedo & ASW 18
	3720 3730 3736 3740 3750 3900
	# Troopships
	3810 3820
	# Medicine
	5600 5610 5620
	
	# Hospital System 
	14000 14010 14020 14030
	# Naval Doctrines
	8010 8020 8030 8040 8050 8070 8100 8110 8120 8150 8160 8200
	# Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
	9140 9040 9050 9090 9100
	# Great War Land Doctrines (entente)
	6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
	# Defensive Focus Grand Battleplan Path (FRA / UK)
	6560 6030 
	}
inventions = { 3000027 }
  policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 5 
     political_left    = 3 
     freedom           = 3 
     free_market       = 5 
     professional_army = 2 # no conscription 
     defense_lobby     = 3 
     interventionism   = 3 
    } 
   peacetime_ic_mod = 0.6
   wartime_ic_mod = 0.7
   headofstate            = {  type = 9 id = 825001  } 
   headofgovernment       = {  type = 9 id = 825002  } 
   foreignminister        = {  type = 9 id = 825003  } 
   armamentminister       = {  type = 9 id = 825004  } 
   ministerofsecurity     = {  type = 9 id = 825005  } 
   ministerofintelligence = {  type = 9 id = 825006  } 
   chiefofstaff           = {  type = 9 id = 825007  } 
   chiefofarmy            = {  type = 9 id = 825008  } 
   chiefofnavy            = {  type = 9 id = 825009  } 
   chiefofair             = {  type = 9 id = 825010  } 
  
   landunit = 
   {  name     = "Delhi District" 
     location = 1459 
     id       = {  type = 12700 id = 21  } 
     Division = 
     {  id       = {  type = 12700 id = 22  } 
       name     = "Delhi Contingent" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
 Division = 
     {  id       = {  type = 12700 id = 500  } 
       name     = "Delhi Cavalry" 
       type     = cavalry 
	   model    = 9
       strength = 80 
       }   	  
	  
	  
    } 
   landunit = 
   {  name     = "Assam District" 
     location = 1444 
     id       = {  type = 12700 id = 23  } 
     Division = 
     {  id            = {  type = 12700 id = 24  } 
       name          = "Assam Bengal Railway Battalion" 
       type          = infantry 
	   model    = 9
       extra         = artillery 
       brigade_model = 5 
       strength      = 100 
        
      } 
 Division = 
     {  id       = {  type = 12700 id = 501  } 
       name     = "Assam Bengal Cavalry" 
       type     = cavalry 
	   model    = 9
       strength = 80 
       }   
	  
    } 
   landunit = 
   {  name     = "Lower Burma" 
     location = 1415 
     id       = {  type = 12700 id = 25  } 
     Division = 
     {  id       = {  type = 12700 id = 26  } 
       name     = "Rangoon Battalion" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Rangoon Command" 
     location = 1415 
     id       = {  type = 12700 id = 280  } 
     Division = 
     {  id       = {  type = 12700 id = 281  } 
       name     = "Rangoon Defence Force" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      }
	       Division = 
     {  id       = {  type = 12700 id = 502  } 
       name     = "Rangoon Cavalry" 
       type     = cavalry 
	   model    = 9
       strength = 80 
       } 	  
    } 
   landunit = 
   {  name     = "Sind District" 
     location = 1533 
     id       = {  type = 12700 id = 27  } 
     Division = 
     {  id       = {  type = 12700 id = 28  } 
       name     = "The Sind Rifles" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Bikaner District" 
     location = 1527 
     id       = {  type = 12700 id = 29  } 
     Division = 
     {  id       = {  type = 12700 id = 30  } 
       name     = "Punjab Rifles" 
       type     = infantry 
	   model    = 9
       extra    = engineer 
	   brigade_model = 3
       strength = 100 
        
      } 
	Division = 
     {  id       = {  type = 12700 id = 503  } 
       name     = "Punjab Cavalry" 
       type     = cavalry 
	   model    = 9
       strength = 80 
       } 
    } 
   landunit = 
   {  name     = "Vishkahapatnam District" 
     location = 1477 
     id       = {  type = 12700 id = 31  } 
     Division = 
     {  id       = {  type = 12700 id = 32  } 
       name     = "The Madras Guards" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
	Division = 
     {  id       = {  type = 12700 id = 504 } 
       name     = "Madras Cavalry" 
       type     = cavalry
	model    = 9	   
       strength = 80 
       } 	  
    } 
   landunit = 
   {  name     = "Bombay District" 
     location = 1517 
     id       = {  type = 12700 id = 33  } 
     Division = 
     {  id       = {  type = 12700 id = 34  } 
       name     = "Central India Railway Regiment" 
       type     = infantry
		model    = 9	   
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Mangalore District" 
     location = 1503 
     id       = {  type = 12700 id = 35  } 
     Division = 
     {  id       = {  type = 12700 id = 36  } 
       name     = "Poona Rifles" 
       type     = infantry 
	   model    = 9
       extra    = artillery 
	   brigade_model = 5
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Madras District" 
     location = 1494 
     id       = {  type = 12700 id = 37  } 
     Division = 
     {  id       = {  type = 12700 id = 38  } 
       name     = "Southern Mahratta Railway Rifles" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Conchin District" 
     location = 1495 
     id       = {  type = 12700 id = 39  } 
     Division = 
     {  id       = {  type = 12700 id = 40  } 
       name     = "Coorg and Mysore Company" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Madurai District" 
     location = 1504 
     id       = {  type = 12700 id = 41  } 
     Division = 
     {  id       = {  type = 12700 id = 42  } 
       name     = "South Indian Railway Battalion" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "4th Indian Division" 
     location = 1016 
     id       = {  type = 12700 id = 6043  } 
     Division = 
     {  id       = {  type = 12700 id = 6044  } 
       name     = "4th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }  
   landunit = 
   {  name     = "5th Indian Division" 
     location = 796 
     id       = {  type = 12700 id = 6045  } 
     Division = 
     {  id       = {  type = 12700 id = 6046  } 
       name     = "5th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "6th Indian Division" 
     location = 1491 
     id       = {  type = 12700 id = 6047  } 
     Division = 
     {  id       = {  type = 12700 id = 6048  } 
       name     = "6th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "7th Indian Division" 
     location = 1534 
     id       = {  type = 12700 id = 6049  } 
     Division = 
     {  id       = {  type = 12700 id = 6050  } 
       name     = "7th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "8th Indian Division" 
     location = 1029 
     id       = {  type = 12700 id = 6051  } 
     Division = 
     {  id       = {  type = 12700 id = 6052  } 
       name     = "8th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "III Indian Corps" 
     location = 1433 
     id       = {  type = 12700 id = 6053  } 
     Division = 
     {  id       = {  type = 12700 id = 6054  } 
       name     = "9th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
     Division = 
     {  id       = {  type = 12700 id = 6055  } 
       name     = "11th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100       
  
      } 
    }
   landunit = 
   {  name     = "10th Indian Division" 
     location = 1016 
     id       = {  type = 12700 id = 6056  } 
     Division = 
     {  id       = {  type = 12700 id = 6057  } 
       name     = "10th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "14th Indian Division" 
     location = 1529 
     id       = {  type = 12700 id = 6058  } 
     Division = 
     {  id       = {  type = 12700 id = 6059  } 
       name     = "14th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "17th Indian Division" 
     location = 1516 
     id       = {  type = 12700 id = 6060  } 
     Division = 
     {  id       = {  type = 12700 id = 6061  } 
       name     = "17th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "19th Indian Division" 
     location = 1491 
     id       = {  type = 12700 id = 6062  } 
     Division = 
     {  id       = {  type = 12700 id = 6063  } 
       name     = "19th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "Indian Armoured Corps" 
     location = 1459 
     id       = {  type = 12700 id = 6064  } 
     Division = 
     {  id       = {  type = 12700 id = 6065  } 
       name     = "1st Indian Armoured Division" 
       type     = light_armor
	   model    = 1
       strength = 40 
        
      } 
     Division = 
     {  id       = {  type = 12700 id = 6066  } 
       name     = "2nd Indian Armoured Division" 
       type     = light_armor
	   model    = 1
       strength = 40 
        
      } 
    }
	navalunit = { 
		id = { type = 12700 id = 288 } 
		name = "Royal Indian Navy" 
		location = 1517 
		base = 1517 
		division = { 
			id = { type = 12700 id = 284 } 
			name = "HMIS 2nd Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 286 } 
			name = "HMIS 4th Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 2318 } 
			name = "2nd DD. Division" 
			type = destroyer 
			} 
		division = { 
			id = { type = 12700 id = 2319 } 
			name = "3rd DD. Division" 
			type = destroyer 
			} 
		}  
	navalunit = { 
		id = { type = 12700 id = 2332 } 
		name = "1st Squadron" 
		location = 1517 
		base = 1517 
		division = { 
			id = { type = 12700 id = 289 } 
			name = "HMIS 1st Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 285 } 
			name = "HMIS 3rd Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 287 } 
			name = "HMIS Destroyer Flotilla" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 12700 id = 2317 } 
			name = "1st DD. Division" 
			type = destroyer 
			} 
		} 
   airunit = 
   {  location = 1517 
     base     = 1517 
     id       = {  type = 12700 id = 80  } 
     name     = "Royal Indian Air Force" 
     Division = 
     {  id       = {  type = 12700 id = 81  } 
       name     = "Indian Group" 
       type     = tactical_bomber 
       model    = 4
       strength = 100 
      } 
    }

   division_development = 
   {  name  = "20th Indian Infantry Division" 
     type  = infantry 
     model = 9
     cost  = 0.1
     id    = {  type = 12700 id = 7000  } 
     date  = {  year = 1942 month = april day = 1  }   
    }
   division_development = 
   {  name  = "23rd Indian Infantry Division" 
     type  = infantry 
     model = 9
     cost  = 0.1
     id    = {  type = 12700 id = 7001  } 
     date  = {  year = 1942 month = january day = 1  }   
    }
   division_development = 
   {  name  = "1st Burma Infantry Division" 
     type  = infantry 
     model = 9
     cost  = 0.1
     id    = {  type = 12700 id = 7002  } 
     date  = {  year = 1941 month = july day = 14  }   
    }
  }