 
 ############################## 
 # Country definition for SOV # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = SOV 
   regular_id             = RUS 
   intrinsic_gov_type     = leninist 
   ai                     = "sov_1941.ai"
   ground_def_eff         = 0.700
   capital                = 572 
   # Resource Reserves 
energy                 = 12000
metal                  = 6000
rare_materials         = 3000
   oil                    = 2000 
   supplies               = 2000 
   money                  = 100 
   belligerence           = 30
   manpower               = 1953 
   dissent                = 15 
   transports             = 300 
   escorts                = 20 
    
  diplomacy =
  { relation = { tag = AFG value = 1 }
    relation = { tag = BRA value = -50 }
    relation = { tag = BUL value = -200 }
    relation = { tag = CHI value = 25 }
    relation = { tag = SLO value = -150 }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = -100 }
    relation = { tag = U01 value = 100 }
    relation = { tag = GER value = -200 }
    relation =
    { tag        = MON
      value      = 150
      guaranteed = { day = 8 month = april year = 1940 }
      access     = yes
    }
    relation = { tag = PER value = -20 }
    relation = { tag = ROM value = -200 }
    relation =
    { tag        = SIK
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = SPA value = -100 }
    relation = { tag = TAN value = 200 access = yes }
    relation = { tag = TUR value = 70 }
    relation = { tag = URU value = -100 }
    relation = { tag = USA value = 175 }
  }

   SpyInfo                = {  country = "SOV" NumberOfSpies = 10  } 
    
   nationalprovinces      = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 
                              1153 1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 
                              568 615 625 564 621 588 584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 
                              1101 1118 502 501 1151 1130 1137 598 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 632 592 687 689 688 
                              542  686 681 543  547  538  539  537  536  534  535  706 702 704 703 709 708 710 701 696 695 694  691  692  
                              697  698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640  670 667 675 674 672 
                              664 671 673 684 663  693  618  655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  
                              554  569  572  570  585  574  540  541  559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  
                              620  626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  
                              580  652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648  1097 1098 1105 1104 1099 1103 
                              1106 1109 1108 1107 567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185 506 
                              1100 711 712 713 1149 1141 499 593 1542 
               714 576 555 705 
         1126 1127 1128 1069 1070 1161 1170 1171 
         259 260 262 263 264 265 266 267 268 269 270 271 272 273 274 275
         517 519 531 532 530
         300 302 303 304 305 306
                             } 
   ownedprovinces         = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 1153 
                              1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 568 
                              615 625 564 621 588 584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 1101 
                              1118 502 501 1151 1130 1137 598 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 632 592 687 689 688 542  
                              686 681 543  547  538  539  537  536  534  535  706 702 704 703 709 708 710 701 696 695 694  691  692  697  
                              698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640  670 667 675 674 672 664 
                              671 673 684 663  693  618  655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  554  
                              569  572  570  585  574  540  541  559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  620  
                              626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  580  
                              652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648  1097 1098 1105 1104 1099 1103 1106 
                              1109 1108 1107 567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185 506 1100 
                              711 712 713 1149 1141 499 593 
               714 576 555 705 
         1126 1127 1128 1069 1070 1161 1170 1171 
         241 242 244 247 254 245 238 255 257 251 240 248 250 239 249 256 253 259 262 263 260 258 268 269 267 264 266 265 274 270 275 271 272 273
         519 531 532 530 
         300 302 303 304 305 306
                             } 
   controlledprovinces    = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180    1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 1153 
                              1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 568 
                              615 625 564 621 588 584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 1101 
                              1118 502 501 1151 1130 1137 598 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 632 592 687 689 688 542  
                              686 681 543  547  538  539  537  536  534  535  706 702 704 703 709 708 710 701 696 695 694  691  692  697  
                              698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640  670 667 675 674 672 664 
                              671 673 684 663  693  618  655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  554  
                              569  572  570  585  574  540  541  559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  620  
                              626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  580  
                              652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648  1097 1098 1105 1104 1099 1103 1106 
                              1109 1108 1107 567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185 506 1100 
                              711 712 713 1149 1141 499 593 
               714 576 555 705 
         1126 1127 1128 1069 1070 1161 1170 1171 
         241 242 244 247 254 245 238 255 257 251 240 248 250 239 249 256 253 259 262 263 260 258 268 269 267 264 266 265 274 270 275 271 272 273
         519 531 532 530 
         300 302 303 304 305 306
                             }
   claimedprovinces    = { 241 242 244 247 254 245 238 255 257 251 240 248 250 239 249 258 256 253 } 
   # Rocket Test and Research Facility 
   # Air Doctrines 1904 
   # ################ 
	techapps = {
	#Early Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110
	#Early Mountain Division 
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 
	#SEMI-MOTORIZED CAVALRY 
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
	#Motorised Inf
	1396 1400
	#Paratroopers
	1670
	#Engineers
	1830 1840 1850 1860
	#Interbellum 1930 Supply 
	1910 1920 1930 1940 1950 1960 1970 1980 1990

	#Early Tank 
	7600 7610 2620 2010 2630 2640 2646 2650 2030 2040 2050 2100 2110
	# Medium Tank
	2070 2080 2090
	#Basic Armoured Car  
	2860 2870 2880 2020 2150
	#Early Field Artillery 
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330
	#Self-Propelled Artillery
	2220
	#Anti-tank Artillery
	2400 2410
	#Early Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460
	#Anti-air Brig
	2810 2810 2820 2510 2520
 
	#Improved Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	#Interwar Light Cruiser 
	3110 3120 3130 3140 3150 3160 
	#Improved Heavy Cruiser 
	3210 3220 3230 3240 3250 3260 12020
	#Great War Battlecruiser  
	3310 3320 3330 3340
	#Early Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470 3480
	#Short Range Submarine 
	3610 3620 3630 3640 3650 3660
	#Seaplane carrier
	12100
	#Torpedo & ASW 18
	3720 3730 3736 3740 3750 3760 3900 3910
	#Troopships
	3810 3820 3830
	
	#CAS
	4400 4170 4280
	#Inteceptor  
	4500 4510 4520 4530 4540 4550 4010 4020 4030
	#Tactical Bomber 
	4600 4610 4620 4630 4120 4130 4140
	#Multirole fighter
	4300 4310 4320 4330 4340 4040
	#Escort Fighter
	4050 4080
	#ww1 strategic bomber
	4800 4810 4820 4220 4230
	#ww1 navalbomber
	4700 4710 4190
	# Transports
	4290 4250
	#SEAPLANES
	4740 4750 4760 4770 4780 4790 4850
	
	#Modern Agriculture  
	5700 5710 5010 5020 5020 
	#Computers & cryptografi
	5310 54010 54020 54030 5320 5316 5326 5327 5350
	#manufactoring
	5810 5820 5830 5050 5060 5070 5130
	#Construction Engineering 
	5800 5080 5090 5100
	#Radar
	5410 5416
	#Basic Oil Refining 
	5190 5200
	#Medicine
	5600 5610 5620 5630
	#Exp. Rocket
	5560
	# Assembly Line
	5140 5160 5180
	# Specialised Equipment
	5920

	#Great War Hospital System 
	14000 14010 14020 14030
	# Great War Land Doctrines (central powers)
	6500 6510 6530 6550 6590 6600 6620 6650 6670 6680 6690 6700 6710 6910
	#Land Doctrines
	6570 6300 6900 6310 6320 6330

	# Naval Doctrines 
	# Theory
	8070 8010 8020 8030 8040 8050 8060 8070 8080
	# Amphib
	82300
	# Logistics
	82500
	# Naval Interdiction
	8500 8510 8550 8560 8600 8610
	# Indirect Approach
	81300 81310 81320 81330 81340 81350 81360
	# Naval Supremacy
	8100 8110 8120 8150 8160 8200 8210

	#Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 9050 9060 9070 9090 9100 9110 9120 9140 9150 9190 9200
 	} 
	
inventions = { 3000027 }
   blueprints             = {   } 
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 1 
     political_left    = 10 
     freedom           = 1 
     free_market       = 1 
     professional_army = 6 
     defense_lobby     = 6 
     interventionism   = 4 
    } 
	peacetime_ic_mod       = 0.7
	wartime_ic_mod       = 0.75
   headofstate            = {  type = 9 id = 30002  } # Stalin 
   headofgovernment       = {  type = 9 id = 30105  } # Stalin - since 6 May 1941 
   foreignminister        = {  type = 9 id = 30021  } 
   armamentminister       = {  type = 9 id = 30004  } 
   ministerofsecurity     = {  type = 9 id = 30028  } 
   ministerofintelligence = {  type = 9 id = 30035  } 
   chiefofstaff           = {  type = 9 id = 30040  } 
   chiefofarmy            = {  type = 9 id = 30046  } 
   chiefofnavy            = {  type = 9 id = 30049  } 
   chiefofair             = {  type = 9 id = 30053  }
   dormant_ministers      = {  30003 30005 30007 30009 30006 30010 30026 30027 30032 30033 30048 30053  }
   dormant_leaders        = {  30050 30040 30042 30044 30085 30095 30097 30101 30108 30111 30127 30131 30135 30152 30156 30170 30175 30192 30194 30207
                               30217 30220 30229 30232 30243 30255 30267 30272 30315 30316 30338 30339 30403 30409 30416 30454 30472 30477 30484 30487
                               30498 30523 30543 30547 30550 30570 30571 30572 30602 30618 30654 30664 30673 30678 30701 30715 30716 30717 30718 30719
                               30721 30722 30723 30650 30437 30050 30512 30007 30374 30238 30276 30681 30353 30687 30407 30697 30499 30004 30008 30028
                               30057 30059 30063 30081 30084 30090 30098 30100 30107 30120 30136 30172 30174 30186 30190 30191 30198 30199 30214 30215
                               30226 30242 30258 30263 30269 30275 30277 30296 30302 30324 30326 30345 30381 30391 30399 30401 30411 30419 30442 30445
                               30447 30491 30494 30509 30521 30548 30552 30576 30614 30658 30660 30720 30473 30778 30076 30216 30744 30266 30322 30463
                               30479 30538 30789 30313 30765 30767 30515 30776 30528 30758 30373
                            }
#1941

   landunit = 
   {  id       = {  type = 10848 id =  1 } 
     name     = "Raboche-Krest'yanskaya Krasnaya Armyia" 
     location = 572 #Moscow 
     Division = 
     {  id       = {  type = 10848 id = 2  } 
       name     = "Generalnyi Shtab RKKA" 
       strength = 100
       type     = HQ
	   model    = 3
	   extra    = artillery
	   brigade_model    = 9	
	   } 
 } 
   landunit = 
   {  id       = {  type = 10848 id =  3 } 
     name     = "Leningradskyi Voennyi Okrug" 
     location = 553 #Leningrad 
     Division = 
     {  id       = {  type = 10848 id = 4  } 
       name     = "Leningradskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 2
	   }
     Division = 
     {  id       = {  type = 10848 id = 5  } 
       name     = "177-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 6  } 
       name     = "191-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 7  } 
       name     = "8-ya Minskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  14 } 
     name     = "1-i Mekhanizirovannyi Korpus" 
     location = 549
      Division = 
     {  id       = {  type = 10848 id = 1400  } 
       name     = "1-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1401  } 
       name     = "3-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1402  } 
       name     = "163-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  11 } 
     name     = "23-ya Armiya" 
     location = 531
     Division = 
     {  id       = {  type = 10848 id = 12  } 
       name     = "142-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 13  } 
       name     = "115-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  37 } 
     name     = "50-i Strelkovyi Korpus" 
     location = 531
     Division = 
     {  id       = {  type = 10848 id = 38  } 
       name     = "43-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 39  } 
       name     = "70-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 40  } 
       name     = "123-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1403 } 
     name     = "10-i Mekhanizirovannyi Korpus" 
     location = 531
      Division = 
     {  id       = {  type = 10848 id = 1404  } 
       name     = "21-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1405  } 
       name     = "24-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1406  } 
       name     = "198-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  15 } 
     name     = "7-ya Armiya" 
     location = 532
     Division = 
     {  id       = {  type = 10848 id = 16  } 
       name     = "54-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 17  } 
       name     = "71-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 18  } 
       name     = "168-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 19  } 
       name     = "237-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  21 } 
     name     = "14-ya Armiya" 
     location = 535
     Division = 
     {  id       = {  type = 10848 id = 22  } 
       name     = "14-ya Krivorozhskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 23  } 
       name     = "52-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  24 } 
     name     = "42-i Strelkovyi Korpus" 
     location = 519
     Division = 
     {  id       = {  type = 10848 id = 25  } 
       name     = "122-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 26  } 
       name     = "104-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1407 } 
     name     = "Pribaltyiskyi Osobyi Voennyi Okrug" 
     location = 264 
     Division = 
     {  id       = {  type = 10848 id = 1408  } 
       name     = "Pribaltyiskyi Osobyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 2
	   }
     Division = 
     {  id       = {  type = 10848 id = 1409  } 
       name     = "22-ya Strelkovaya Divizyia NKVD" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = police
	   brigade_model = 1
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  45 } 
     name     = "8-ya Armiya" 
     location = 263
     Division = 
     {  id       = {  type = 10848 id = 46  } 
       name     = "10-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 47  } 
       name     = "48-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 48  } 
       name     = "90-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  49 } 
     name     = "8-ya Armiya" 
     location = 259
     Division = 
     {  id       = {  type = 10848 id = 51  } 
       name     = "11-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 50  } 
       name     = "125-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1410 } 
     name     = "12-i Mekhanizirovannyi Korpus" 
     location = 269
      Division = 
     {  id       = {  type = 10848 id = 1411  } 
       name     = "23-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
       extra    = armored_car
       brigade_model = 3
      }
      Division = 
     {  id       = {  type = 10848 id = 1412  } 
       name     = "28-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1413  } 
       name     = "202-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  53 } 
     name     = "11-ya Armiya" 
     location = 255
     Division = 
     {  id       = {  type = 10848 id = 54  } 
       name     = "5-ya Vitebskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 55  } 
       name     = "33-ya Belorusskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 56  } 
       name     = "188-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1000 } 
     name     = "11-ya Armiya" 
     location = 254
     Division = 
     {  id       = {  type = 10848 id = 57  } 
       name     = "126-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 58  } 
       name     = "128-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 59  } 
       name     = "23-ya Har'kovskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  60 } 
     name     = "29-i Strelkovyi Korpus" 
     location = 254
     Division = 
     {  id       = {  type = 10848 id = 61  } 
       name     = "179-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 62  } 
       name     = "184-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 9
	   extra    = artillery
	   brigade_model = 8
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1414 } 
     name     = "3-i Mekhanizirovannyi Korpus" 
     location = 262
      Division = 
     {  id       = {  type = 10848 id = 1415  } 
       name     = "2-ya Tankovaya Divizyia" 
       strength = 65 
       type     = armor
	   model    = 1 
       extra    = heavy_armor
       brigade_model = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1416  } 
       name     = "5-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1417  } 
       name     = "84-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  64 } 
     name     = "27-ya Armiya" 
     location = 263
     Division = 
     {  id       = {  type = 10848 id = 68  } 
       name     = "16-ya Ul'yanovskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 69  } 
       name     = "67-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1418 } 
     name     = "22-i Strelkovyi Korpus" 
     location = 270
     Division = 
     {  id       = {  type = 10848 id = 65  } 
       name     = "180-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 67  } 
       name     = "182-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1419 } 
     name     = "24-i Strelkovyi Korpus" 
     location = 264
     Division = 
     {  id       = {  type = 10848 id = 66  } 
       name     = "181-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 70  } 
       name     = "183-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  72 } 
     name     = "Zapadnyi Osobyi Voennyi Okrug" 
     location = 599
     Division = 
     {  id       = {  type = 10848 id = 73  } 
       name     = "Zapadnyi Osobyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  74 } 
     name     = "47-i Strelkovyi Korpus" 
     location = 253
     Division = 
     {  id       = {  type = 10848 id = 75  } 
       name     = "143-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 76  } 
       name     = "121-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 77  } 
       name     = "55-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1420 } 
     name     = "17-i Mekhanizirovannyi Korpus" 
     location = 258
      Division = 
     {  id       = {  type = 10848 id = 1421  } 
       name     = "27-ya Tankovaya Divizyia" 
       strength = 10 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1422  } 
       name     = "36-ya Tankovaya Divizyia" 
       strength = 10 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1423  } 
       name     = "209-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1424 } 
     name     = "20-i Mekhanizirovannyi Korpus" 
     location = 256
      Division = 
     {  id       = {  type = 10848 id = 1425  } 
       name     = "26-ya Tankovaya Divizyia" 
       strength = 10 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1426  } 
       name     = "38-ya Tankovaya Divizyia" 
       strength = 10 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1427  } 
       name     = "210-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  82 } 
     name     = "3-ya Armiya" 
     location = 250
     Division = 
     {  id       = {  type = 10848 id = 83  } 
       name     = "27-ya Omskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 84  } 
       name     = "56-ya Moskovskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 85  } 
       name     = "85-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  86 } 
     name     = "21-i Strelkovyi Korpus" 
     location = 254
     Division = 
     {  id       = {  type = 10848 id = 87  } 
       name     = "24-ya Samaro-Ul'yanovsk Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 88  } 
       name     = "17-ya Gor'kovskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 89  } 
       name     = "50-ya Tamanskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 90  } 
       name     = "37-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1428 } 
     name     = "11-i Mekhanizirovannyi Korpus" 
     location = 251
      Division = 
     {  id       = {  type = 10848 id = 1429  } 
       name     = "29-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
       extra    = heavy_armor
       brigade_model = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1430  } 
       name     = "33-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1431  } 
       name     = "204-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  92 } 
     name     = "4-ya Armiya" 
     location = 247
     Division = 
     {  id       = {  type = 10848 id = 93  } 
       name     = "6-ya Orlovskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 94  } 
       name     = "42-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 95  } 
       name     = "49-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 96  } 
       name     = "75-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1432 } 
     name     = "14-i Mekhanizirovannyi Korpus" 
     location = 247
      Division = 
     {  id       = {  type = 10848 id = 1433  } 
       name     = "22-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
       extra    = armored_car
       brigade_model = 3
      }
      Division = 
     {  id       = {  type = 10848 id = 1434  } 
       name     = "30-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1435  } 
       name     = "205-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  98 } 
     name     = "10-ya Armiya" 
     location = 250
     Division = 
     {  id       = {  type = 10848 id = 99  } 
       name     = "155-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 100  } 
       name     = "2-ya Belorusskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 9
      }
 }	
   landunit = 
   {  id       = {  type = 10848 id =  1436 } 
     name     = "6-i Mekhanizirovannyi Korpus" 
     location = 253
      Division = 
     {  id       = {  type = 10848 id = 1437  } 
       name     = "4-ya Tankovaya Divizyia" 
       strength = 65 
       type     = armor
	   model    = 1 
       extra    = heavy_armor
       brigade_model = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1438  } 
       name     = "7-ya Tankovaya Divizyia" 
       strength = 65 
       type     = armor
	   model    = 1 
       extra    = heavy_armor
       brigade_model = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1439  } 
       name     = "29-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1
       extra    = armored_car
       brigade_model = 3 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  102 } 
     name     = "6-i Kavaleriiski Korpus" 
     location = 245
      Division = 
     {  id       = {  type = 10848 id = 103  } 
       name     = "6-ya Changarskaya Kavaleriiskaya Divizyia" 
       strength = 65 
       type     = cavalry
	   model    = 10
	extra = light_armor_brigade
	brigade_model = 3
      }
      Division = 
     {  id       = {  type = 10848 id = 104  } 
       name     = "36-ya Kavaleriiskaya Divizyia" 
       strength = 65 
       type     = cavalry
	   model    = 10
	extra = light_armor_brigade
	brigade_model = 3
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  105 } 
     name     = "5-i Strelkovyi Korpus" 
     location = 250
     Division = 
     {  id       = {  type = 10848 id = 106  } 
       name     = "86-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 107  } 
       name     = "13-ya Dagestanskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 108  } 
       name     = "113-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
	   extra    = artillery
	   brigade_model = 8
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1440 } 
     name     = "13-i Mekhanizirovannyi Korpus" 
     location = 266
      Division = 
     {  id       = {  type = 10848 id = 1441  } 
       name     = "25-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1442  } 
       name     = "31-ya Tankovaya Divizyia" 
       strength = 10 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1443  } 
       name     = "208-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  110 } 
     name     = "13-ya Armiya" 
     location = 599
     Division = 
     {  id       = {  type = 10848 id = 111  } 
       name     = "161-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 112  } 
       name     = "100-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1444 } 
     name     = "44-i Strelkovyi Korpus" 
     location = 600
     Division = 
     {  id       = {  type = 10848 id = 113  } 
       name     = "64-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 114  } 
       name     = "108-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  115 } 
     name     = "Kievskyi Osobyi Voennyi Okrug" 
     location = 617
     Division = 
     {  id       = {  type = 10848 id = 116  } 
       name     = "Kievskyi Osobyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  117 } 
     name     = "31-i Strelkovyi Korpus" 
     location = 240
     Division = 
     {  id       = {  type = 10848 id = 118  } 
       name     = "193-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 119  } 
       name     = "195-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 120  } 
       name     = "200-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1445 } 
     name     = "9-i Mekhanizirovannyi Korpus" 
     location = 617
      Division = 
     {  id       = {  type = 10848 id = 1446  } 
       name     = "20-ya Tankovaya Divizyia" 
       strength = 50 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1447  } 
       name     = "35-ya Tankovaya Divizyia" 
       strength = 60 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1448  } 
       name     = "131-ya Motostrelkovaya Divizyia" 
       strength = 60 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  122 } 
     name     = "36-i Strelkovyi Korpus" 
     location = 241
     Division = 
     {  id       = {  type = 10848 id = 123  } 
       name     = "140-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 124  } 
       name     = "146-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 125  } 
       name     = "228-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1449 } 
     name     = "15-i Mekhanizirovannyi Korpus" 
     location = 240
      Division = 
     {  id       = {  type = 10848 id = 1450  } 
       name     = "10-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1 
       extra    = heavy_armor
       brigade_model = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1451  } 
       name     = "37-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
       extra    = tank_destroyer
       brigade_model = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1452  } 
       name     = "212-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  127 } 
     name     = "49-i Strelkovyi Korpus" 
     location = 303
     Division = 
     {  id       = {  type = 10848 id = 128  } 
       name     = "199-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 129  } 
       name     = "197-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 130  } 
       name     = "190-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1453 } 
     name     = "19-i Mekhanizirovannyi Korpus" 
     location = 240
      Division = 
     {  id       = {  type = 10848 id = 1454  } 
       name     = "40-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1455  } 
       name     = "43-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1456  } 
       name     = "213-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  132 } 
     name     = "55-i Strelkovyi Korpus" 
     location = 620
     Division = 
     {  id       = {  type = 10848 id = 133  } 
       name     = "189-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 134  } 
       name     = "169-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 135  } 
       name     = "130-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1457 } 
     name     = "24-i Mekhanizirovannyi Korpus" 
     location = 611
      Division = 
     {  id       = {  type = 10848 id = 1458  } 
       name     = "45-ya Tankovaya Divizyia" 
       strength = 30 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1459  } 
       name     = "49-ya Tankovaya Divizyia" 
       strength = 25 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1460  } 
       name     = "216-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  137 } 
     name     = "5-ya Armiya" 
     location = 245
     Division = 
     {  id       = {  type = 10848 id = 138  } 
       name     = "45-ya Volynskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 139  } 
       name     = "87-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 140  } 
       name     = "62-ya Turkestanskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 141  } 
       name     = "124-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 142  } 
       name     = "135-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1461 } 
     name     = "22-i Mekhanizirovannyi Korpus" 
     location = 245
      Division = 
     {  id       = {  type = 10848 id = 1462  } 
       name     = "19-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1463  } 
       name     = "41-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1464  } 
       name     = "215-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  146 } 
     name     = "6-ya Armiya" 
     location = 239
     Division = 
     {  id       = {  type = 10848 id = 147  } 
       name     = "41-ya Volynskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 148  } 
       name     = "97-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 149  } 
       name     = "159-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1465 } 
     name     = "4-i Mekhanizirovannyi Korpus" 
     location = 245
      Division = 
     {  id       = {  type = 10848 id = 1466  } 
       name     = "8-ya Tankovaya Divizyia" 
       strength = 65 
       type     = armor
	   model    = 1 
       extra    = heavy_armor
       brigade_model = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1467  } 
       name     = "32-ya Tankovaya Divizyia" 
       strength = 65 
       type     = armor
	   model    = 1 
       extra    = heavy_armor
       brigade_model = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1468  } 
       name     = "81-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  152 } 
     name     = "37-i Strelkovyi Korpus" 
     location = 617
     Division = 
     {  id       = {  type = 10848 id = 153  } 
       name     = "80-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 154  } 
       name     = "139-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 155  } 
       name     = "141-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  156  } 
     name     = "5-i Kavaleriiski Korpus" 
     location = 606
      Division = 
     {  id       = {  type = 10848 id = 157  } 
       name     = "3-ya Besarabskaya Kavaleriiskaya Divizyia" 
       strength = 60 
       type     = cavalry
	   model    = 10
	extra = light_armor_brigade
	brigade_model = 3
      } 
      Division = 
     {  id       = {  type = 10848 id = 158  } 
       name     = "14-ya Maykopskaya Kavaleriiskaya Divizyia" 
       strength = 60 
       type     = cavalry
	   model    = 10
	extra = light_armor_brigade
	brigade_model = 3
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1469 } 
     name     = "16-i Mekhanizirovannyi Korpus" 
     location = 619
      Division = 
     {  id       = {  type = 10848 id = 1470  } 
       name     = "15-ya Tankovaya Divizyia" 
       strength = 30 
       type     = armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1471  } 
       name     = "39-ya Tankovaya Divizyia" 
       strength = 5 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1472  } 
       name     = "240-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  160 } 
     name     = "12-ya Armiya" 
     location = 238
     Division = 
     {  id       = {  type = 10848 id = 161  } 
       name     = "44-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 164  } 
       name     = "58-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 162  } 
       name     = "192-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  165 } 
     name     = "17-i Strelkovyi Korpus" 
     location = 300
     Division = 
     {  id       = {  type = 10848 id = 166  } 
       name     = "60-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 1660  } 
       name     = "69-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 1661  } 
       name     = "164-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  169 } 
     name     = "26-ya Armiya" 
     location = 239
     Division = 
     {  id       = {  type = 10848 id = 170  } 
       name     = "99-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 171  } 
       name     = "173-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1473 } 
     name     = "8-i Mekhanizirovannyi Korpus" 
     location = 238
      Division = 
     {  id       = {  type = 10848 id = 1474  } 
       name     = "12-ya Tankovaya Divizyia" 
       strength = 30 
       type     = armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1475  } 
       name     = "34-ya Tankovaya Divizyia" 
       strength = 5 
       type     = light_armor
	   model    = 1
       extra    = heavy_armor
       brigade_model = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1476  } 
       name     = "7-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  173 } 
     name     = "Odesskyi Osobyi Voennyi Okrug" 
     location = 626
     Division = 
     {  id       = {  type = 10848 id = 174  } 
       name     = "Odesskyi Osobyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 175  } 
       name     = "47-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  176 } 
     name     = "7-i Strelkovyi Korpus" 
     location = 627
     Division = 
     {  id       = {  type = 10848 id = 177  } 
       name     = "116-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 178  } 
       name     = "196-ya Dnepropetrovsk Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 179  } 
       name     = "206-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  180 } 
     name     = "9-i Strelkovyi Korpus" 
     location = 641
     Division = 
     {  id       = {  type = 10848 id = 181  } 
       name     = "156-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 182  } 
       name     = "106-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 183  } 
       name     = "32-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  184 } 
     name     = "9-ya Armiya" 
     location = 302
     Division = 
     {  id       = {  type = 10848 id = 185  } 
       name     = "25-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 186  } 
       name     = "51-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1477 } 
     name     = "18-i Mekhanizirovannyi Korpus" 
     location = 620
      Division = 
     {  id       = {  type = 10848 id = 1478  } 
       name     = "44-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1479  } 
       name     = "47-ya Tankovaya Divizyia" 
       strength = 60 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1480  } 
       name     = "218-ya Motostrelkovaya Divizyia" 
       strength = 40 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  188 } 
     name     = "35-i Strelkovyi Korpus" 
     location = 305
     Division = 
     {  id       = {  type = 10848 id = 189  } 
       name     = "176-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 190  } 
       name     = "95-ya Moldavskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1880 } 
     name     = "48-i Strelkovyi Korpus" 
     location = 306
     Division = 
     {  id       = {  type = 10848 id = 1890  } 
       name     = "74-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 1900  } 
       name     = "30-ya Irkutskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1481 } 
     name     = "2-i Mekhanizirovannyi Korpus" 
     location = 304
      Division = 
     {  id       = {  type = 10848 id = 1482  } 
       name     = "11-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0
       extra    = tank_destroyer
       brigade_model = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1483  } 
       name     = "16-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1484  } 
       name     = "15-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  191 } 
     name     = "Zakavkazskyi Voennyi Okrug" 
     location = 709
     Division = 
     {  id       = {  type = 10848 id = 192  } 
       name     = "Zakavkazskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 193  } 
       name     = "63-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 194  } 
       name     = "76-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 195  } 
       name     = "77-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 196  } 
       name     = "4-ya Smolenskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 197  } 
       name     = "20-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 198  } 
       name     = "136-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 199  } 
       name     = "138-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 200  } 
       name     = "47-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 201  } 
       name     = "17-ya Gor'kovskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 202  } 
       name     = "24-ya Kavaleriiskaya Divizyia" 
       strength = 60 
       type     = cavalry
	   model    = 10
	extra = light_armor_brigade
	brigade_model = 3
      }
     Division = 
     {  id       = {  type = 10848 id = 203  } 
       name     = "31-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 204  } 
       name     = "9-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1485 } 
     name     = "28-i Mekhanizirovannyi Korpus" 
     location = 713
      Division = 
     {  id       = {  type = 10848 id = 1486  } 
       name     = "6-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1487  } 
       name     = "54-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1488  } 
       name     = "236-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  205 } 
     name     = "Arhangelskyi Voennyi Okrug" 
     location = 542
     Division = 
     {  id       = {  type = 10848 id = 206  } 
       name     = "Arhangelskyi Voennyi Okrug" 
       strength = 70 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 207  } 
       name     = "88-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 9
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 208  } 
       name     = "111-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  209 } 
     name     = "Moskovskyi Voennyi Okrug" 
     location = 572
     Division = 
     {  id       = {  type = 10848 id = 210  } 
       name     = "Moskovskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 1
	   }
     Division = 
     {  id       = {  type = 10848 id = 211  } 
       name     = "118-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 212  } 
       name     = "235-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  2090 } 
     name     = "Harkovskyi Voennyi Okrug" 
     location = 636
     Division = 
     {  id       = {  type = 10848 id = 2100  } 
       name     = "Harkovskyi Voennyi Okrug" 
       strength = 70 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 1
	   }
     Division = 
     {  id       = {  type = 10848 id = 1489  } 
       name     = "2-i Vozdushno-Desantnye Korpus" 
       strength = 50 
       type     = paratrooper 
	   model    = 0
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1490 } 
     name     = "3-i Vozdushno-Desantnye Korpus" 
     location = 626
     Division = 
     {  id       = {  type = 10848 id = 1491  } 
       name     = "3-i Vozdushno-Desantnye Korpus" 
       strength = 50 
       type     = paratrooper 
	   model    = 0
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1492 } 
     name     = "4-i Vozdushno-Desantnye Korpus" 
     location = 248
     Division = 
     {  id       = {  type = 10848 id = 1493  } 
       name     = "4-i Vozdushno-Desantnye Korpus" 
       strength = 50 
       type     = paratrooper 
	   model    = 0
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1494 } 
     name     = "5-i Vozdushno-Desantnye Korpus" 
     location = 550
     Division = 
     {  id       = {  type = 10848 id = 1495  } 
       name     = "5-i Vozdushno-Desantnye Korpus" 
       strength = 50 
       type     = paratrooper 
	   model    = 0
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1496 } 
     name     = "1-i Vozdushno-Desantnye Korpus" 
     location = 619
     Division = 
     {  id       = {  type = 10848 id = 1497  } 
       name     = "1-i Vozdushno-Desantnye Korpus" 
       strength = 50 
       type     = paratrooper 
	   model    = 0
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  213 } 
     name     = "Severokavkazskyi Voennyi Okrug" 
     location = 691
     Division = 
     {  id       = {  type = 10848 id = 214  } 
       name     = "Severokavkazskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 215  } 
       name     = "175-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 2160  } 
       name     = "165-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 216  } 
       name     = "157-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 217  } 
       name     = "28-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1498 } 
     name     = "26-i Mekhanizirovannyi Korpus" 
     location = 644
      Division = 
     {  id       = {  type = 10848 id = 1499  } 
       name     = "52-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1500  } 
       name     = "56-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1501  } 
       name     = "203-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  219 } 
     name     = "Orlovskyi Voennyi Okrug" 
     location = 581
     Division = 
     {  id       = {  type = 10848 id = 220  } 
       name     = "Orlovskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 1
	   }
     Division = 
     {  id       = {  type = 10848 id = 221  } 
       name     = "19-ya Voronezhskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 222  } 
       name     = "89-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 224  } 
       name     = "120-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 225  } 
       name     = "145-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 227  } 
       name     = "149-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 223  } 
       name     = "217-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 226  } 
       name     = "222-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1502 } 
     name     = "23-i Mekhanizirovannyi Korpus" 
     location = 629
      Division = 
     {  id       = {  type = 10848 id = 1503  } 
       name     = "48-ya Tankovaya Divizyia" 
       strength = 50 
       type     = light_armor
	   model    = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1504  } 
       name     = "51-ya Tankovaya Divizyia" 
       strength = 50 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1505  } 
       name     = "220-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  2190 } 
     name     = "Privolzhskyi Voennyi Okrug" 
     location = 663
     Division = 
     {  id       = {  type = 10848 id = 2200  } 
       name     = "Privolzhskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 1
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  229 } 
     name     = "Sredneaziatskyi Voennyi Okrug" 
     location = 1103
     Division = 
     {  id       = {  type = 10848 id = 230  } 
       name     = "Sredneaziatskyi Voennyi Okrug" 
       strength = 70 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 232  } 
       name     = "238-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  233 } 
     name     = "58-i Strelkovyi Korpus" 
     location = 1105
     Division = 
     {  id       = {  type = 10848 id = 231  } 
       name     = "68-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 234  } 
       name     = "83-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 235  } 
       name     = "194-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
  Division = #SAVO
     {  id       = {  type = 10848 id = 236  } 
       name     = "18-ya Turkmenskaya Kavaleriiskaya Divizyia" 
       strength = 60 
       type     = cavalry
	   model    = 9
     }
  Division = #SAVO
     {  id       = {  type = 10848 id = 237  } 
       name     = "20-ya Tadzhikskaya Kavaleriiskaya Divizyia" 
       strength = 60 
       type     = cavalry
	   model    = 9
     }
  Division = #SAVO
     {  id       = {  type = 10848 id = 238  } 
       name     = "21-ya Kavaleriiskaya Divizyia" 
       strength = 60 
       type     = cavalry
	   model    = 9
     }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1506 } 
     name     = "27-i Mekhanizirovannyi Korpus" 
     location = 1103
      Division = 
     {  id       = {  type = 10848 id = 1507  } 
       name     = "9-ya Tankovaya Divizyia" 
       strength = 40 
       type     = light_armor
	   model    = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1508  } 
       name     = "53-ya Tankovaya Divizyia" 
       strength = 40 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1509  } 
       name     = "221-ya Motostrelkovaya Divizyia" 
       strength = 50 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  242 } 
     name     = "Zabaikalskyi Voennyi Okrug" 
     location = 1162
     Division = 
     {  id       = {  type = 10848 id = 243  } 
       name     = "Zabaikalskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 244  } 
       name     = "93-ya Vostochno-Sibir. Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  245 } 
     name     = "Zabaikalskyi Voennyi Okrug" 
     location = 1169
     Division = 
     {  id       = {  type = 10848 id = 246  } 
       name     = "114-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  239 } 
     name     = "12-i Strelkovyi Korpus" 
     location = 1167
     Division = 
     {  id       = {  type = 10848 id = 240  } 
       name     = "65-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 241  } 
       name     = "94-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      } 
 }
   landunit = 
   {  id       = {  type = 10848 id =  1510 } 
     name     = "17-ya Armiya" 
     location = 1162
      Division = 
     {  id       = {  type = 10848 id = 1511  } 
       name     = "57-ya Tankovaya Divizyia" 
       strength = 20 
       type     = light_armor
	   model    = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1512  } 
       name     = "61-ya Tankovaya Divizyia" 
       strength = 20 
       type     = light_armor
	   model    = 0 
      }
     Division = 
     {  id       = {  type = 10848 id = 1513  } 
       name     = "36-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 1514  } 
       name     = "57-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      } 
     Division = 
     {  id       = {  type = 10848 id = 1515  } 
       name     = "82-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      } 
 }

   landunit = 
   {  id       = {  type = 10848 id =  247 } 
     name     = "20-i Strelkovyi Korpus" 
     location = 612 
     Division = 
     {  id       = {  type = 10848 id = 248  } 
       name     = "137-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 249  } 
       name     = "160-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1516 } 
     name     = "45-i Strelkovyi Korpus" 
     location = 572
     Division = 
     {  id       = {  type = 10848 id = 250  } 
       name     = "187-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 251  } 
       name     = "227-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 252  } 
       name     = "232-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1517 } 
     name     = "67-i Strelkovyi Korpus" 
     location = 558
     Division = 
     {  id       = {  type = 10848 id = 253  } 
       name     = "102-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 254  } 
       name     = "132-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 255  } 
       name     = "151-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1518 } 
     name     = "21-i Mekhanizirovannyi Korpus" 
     location = 584
      Division = 
     {  id       = {  type = 10848 id = 1519  } 
       name     = "42-ya Tankovaya Divizyia" 
       strength = 20 
       type     = light_armor
	   model    = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1520  } 
       name     = "46-ya Tankovaya Divizyia" 
       strength = 20 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1521  } 
       name     = "185-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  256 } 
     name     = "16-ya Armiya" 
     location = 612 
     Division = 
     {  id       = {  type = 10848 id = 257  } 
       name     = "46-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 258  } 
       name     = "152-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1522 } 
     name     = "5-i Mekhanizirovannyi Korpus" 
     location = 612
      Division = 
     {  id       = {  type = 10848 id = 1523  } 
       name     = "13-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 2
      }
      Division = 
     {  id       = {  type = 10848 id = 1524  } 
       name     = "17-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1
       extra    = tank_destroyer
       brigade_model = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1525  } 
       name     = "109-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  259 } 
     name     = "19-ya Armiya" 
     location = 606 
     Division = 
     {  id       = {  type = 10848 id = 260  } 
       name     = "38-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 261  } 
       name     = "127-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 262  } 
       name     = "134-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 263  } 
       name     = "162-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1526 } 
     name     = "34-i Strelkovyi Korpus" 
     location = 608
     Division = 
     {  id       = {  type = 10848 id = 264  } 
       name     = "129-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 265  } 
       name     = "158-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 266  } 
       name     = "171-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  267 } 
     name     = "20-ya Armiya" 
     location = 565 
     Division = 
     {  id       = {  type = 10848 id = 268  } 
       name     = "18-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 272  } 
       name     = "73-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 273  } 
       name     = "229-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 274  } 
       name     = "233-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1527 } 
     name     = "61-i Strelkovyi Korpus" 
     location = 607
     Division = 
     {  id       = {  type = 10848 id = 269  } 
       name     = "110-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 270  } 
       name     = "114-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 271  } 
       name     = "172-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1528 } 
     name     = "7-i Mekhanizirovannyi Korpus" 
     location = 569
      Division = 
     {  id       = {  type = 10848 id = 1529  } 
       name     = "14-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1530  } 
       name     = "18-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1 
       extra    = tank_destroyer
       brigade_model = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1531  } 
       name     = "1-ya Motorizovannaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1 
       extra    = armored_car
       brigade_model = 3 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  275 } 
     name     = "21-ya Armiya" 
     location = 605 
     Division = 
     {  id       = {  type = 10848 id = 276  } 
       name     = "53-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 277  } 
       name     = "148-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 278  } 
       name     = "167-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 279  } 
       name     = "61-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 280  } 
       name     = "117-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 281  } 
       name     = "154-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1532 } 
     name     = "25-i Mekhanizirovannyi Korpus" 
     location = 607
      Division = 
     {  id       = {  type = 10848 id = 1533  } 
       name     = "50-ya Tankovaya Divizyia" 
       strength = 40 
       type     = light_armor
	   model    = 1
       extra    = tank_destroyer
       brigade_model = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1534  } 
       name     = "55-ya Tankovaya Divizyia" 
       strength = 5 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1535  } 
       name     = "219-ya Motostrelkovaya Divizyia" 
       strength = 40 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  282 } 
     name     = "22-ya Armiya" 
     location = 573 
     Division = 
     {  id       = {  type = 10848 id = 283  } 
       name     = "98-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 284  } 
       name     = "112-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 285  } 
       name     = "153-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1536 } 
     name     = "62-i Strelkovyi Korpus" 
     location = 590 
     Division = 
     {  id       = {  type = 10848 id = 286  } 
       name     = "186-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 287  } 
       name     = "170-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 288  } 
       name     = "174-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  289 } 
     name     = "24-ya Armiya" 
     location = 572 
     Division = 
     {  id       = {  type = 10848 id = 290  } 
       name     = "91-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 291  } 
       name     = "119-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 292  } 
       name     = "166-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 293  } 
       name     = "178-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 294  } 
       name     = "107-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 295  } 
       name     = "133-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1537 } 
     name     = "Uralskyi Voennyi Okrug" 
     location = 1151
     Division = 
     {  id       = {  type = 10848 id = 1538  } 
       name     = "Uralskyi Voennyi Okrug" 
       strength = 60 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1539 } 
     name     = "Sibirskyi Voennyi Okrug" 
     location = 1142
     Division = 
     {  id       = {  type = 10848 id = 1540  } 
       name     = "Sibirskyi Voennyi Okrug" 
       strength = 60 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  296 } 
     name     = "Dalnevostochnyi Front" 
     location = 1191
     Division = 
     {  id       = {  type = 10848 id = 297  } 
       name     = "Dalnevostochnyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 298  } 
       name     = "35-ya Sibirskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 299  } 
       name     = "66-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 300  } 
       name     = "78-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  301 } 
     name     = "Dalnevostochnyi Front" 
     location = 1191
     Division = 
     {  id       = {  type = 10848 id = 302  } 
       name     = "79-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 303  } 
       name     = "101-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  304 } 
     name     = "1-ya Armiya" 
     location = 1196
     Division = 
     {  id       = {  type = 10848 id = 305  } 
       name     = "26-ya Zlatoustovskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 306  } 
       name     = "21-ya Permskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 307  } 
       name     = "22-ya Krasnodarskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 308  } 
       name     = "39-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 309  } 
       name     = "59-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 9
	   extra    = artillery
	   brigade_model = 8
      }
      Division = 
     {  id       = {  type = 10848 id = 312  } 
       name     = "8-ya Dalnevostochnaya Kavaleriiskaya Divizyia" 
       strength = 60 
       type     = cavalry
	   model    = 10
	extra = light_armor_brigade
	brigade_model = 3
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1541 } 
     name     = "30-i Mekhanizirovannyi Korpus" 
     location = 1196
      Division = 
     {  id       = {  type = 10848 id = 1542  } 
       name     = "58-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1543  } 
       name     = "69-ya Tankovaya Divizyia" 
       strength = 65 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1544  } 
       name     = "239-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1
       extra    = anti_tank
       brigade_model = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  313 } 
     name     = "2-ya Armiya" 
     location = 1175
     Division = 
     {  id       = {  type = 10848 id = 314  } 
       name     = "12-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 315  } 
       name     = "3-ya Tihookeanskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
 }
   landunit = 
   {  id       = {  type = 10848 id = 1545  } 
     name     = "18-i Sibirskyi Korpus" 
     location = 1168
      Division = 
     {  id       = {  type = 10848 id = 1546  } 
       name     = "59-ya Tankovaya Divizyia" 
       strength = 40 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1547  } 
       name     = "69-ya Motostrelkovaya Divizyia" 
       strength = 80 
       type     = motorized
	   model    = 1
       extra    = anti_tank
       brigade_model = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  316 } 
     name     = "15-ya Armiya" 
     location = 1183
     Division = 
     {  id       = {  type = 10848 id = 317  } 
       name     = "34-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  318 } 
     name     = "25-ya Armiya" 
     location = 1190
     Division = 
     {  id       = {  type = 10848 id = 319  } 
       name     = "92-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 10
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 320  } 
       name     = "32-ya Saratovskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 321  } 
       name     = "40-ya Bogucharskaya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 322  } 
       name     = "105-ya Strelkovaya Divizyia" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }

# Air OOB
#MVO
airunit = { 
	id = { type = 10848 id = 7004 } 
	name = "Dal'nii Vostok Vozdushnogo Komandovaniya" 
	location = 1191 # Vladivostok 
	base = 1191 # Vladivostok 

	division = { 
	id = { type = 10848 id = 7005 } 
		name = "29.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7006 } 
		name = "79.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7007 } 
		name = "31.TBABR" 
		strength = 50 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7008 } 
		name = "32.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7001 } 
		name = "34.LSHABR" 
		strength = 80 
		type = cas 
		model = 1 
			}
	division = { 
	id = { type = 10848 id = 7002 } 
		name = "69.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			} 
	division = { 
	id = { type = 10848 id = 7003 } 
		name = "70.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	}
airunit = { 
	id = { type = 10848 id = 7016 } 
	name = "Leningradskaya Vozdushnogo Komandovaniya" 
	location = 553 # Leningrad
	base = 553 # Leningrad 

	division = { 
	id = { type = 10848 id = 7017 } 
		name = "1.LBABR" 
		strength = 80 
		type = multi_role 
		model = 4 
			}
	division = { 
	id = { type = 10848 id = 7018 } 
		name = "2.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7019 } 
		name = "4.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7020 } 
		name = "5.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7010 } 
		name = "23.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7011 } 
		name = "24.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7012 } 
		name = "26.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7013 } 
		name = "40.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7014 } 
		name = "41.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7015 } 
		name = "3.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	}
airunit = { 
	id = { type = 10848 id = 7026 } 
	name = "Pribaltii'skii Front Vozdushnogo Komandovaniya" 
	location = 264 # Riga
	base = 264 # Riga 

	division = { 
	id = { type = 10848 id = 7027 } 
		name = "6.LBABR" 
		strength = 80 
		type = multi_role 
		model = 4 
			}
	division = { 
	id = { type = 10848 id = 7028 } 
		name = "7.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7029 } 
		name = "8.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7030 } 
		name = "39.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7022 } 
		name = "12.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7023 } 
		name = "13.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7024 } 
		name = "57.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7025 } 
		name = "62.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	}
airunit = { 
	id = { type = 10848 id = 7037 } 
	name = "Zapadnyi Front Vozdushnogo Komandovaniya" 
	location = 597 # Luban
	base = 597 # Luban 

	division = { 
	id = { type = 10848 id = 7038 } 
		name = "9.LBABR" 
		strength = 80 
		type = multi_role 
		model = 4 
			}
	division = { 
	id = { type = 10848 id = 7039 } 
		name = "10.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7040 } 
		name = "11.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7041 } 
		name = "25.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7032 } 
		name = "28.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7033 } 
		name = "31.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7034 } 
		name = "29.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	division = { 
	id = { type = 10848 id = 7035 } 
		name = "30.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	division = { 
	id = { type = 10848 id = 7036 } 
		name = "42.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	}
airunit = { 
	id = { type = 10848 id = 7048 } 
	name = "Yugo-Zapadnogo Fronta Vozdushnogo Komandovaniya" 
	location = 240 # Tarnopol
	base = 240 # Tarnopol

	division = { 
	id = { type = 10848 id = 7049 } 
		name = "14.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7050 } 
		name = "15.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7051 } 
		name = "16.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7052 } 
		name = "17.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7043 } 
		name = "19.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7044 } 
		name = "32.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7045 } 
		name = "33.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7046 } 
		name = "37.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7047 } 
		name = "34.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	}
airunit = { 
	id = { type = 10848 id = 7058 } 
	name = "Yuzhnyi Front Vozdushnogo Komandovaniya" 
	location = 626 # Odessa 
	base = 626 # Odessa 

	division = { 
	id = { type = 10848 id = 7059 } 
		name = "20.LBABR" 
		strength = 80 
		type = multi_role 
		model = 4 
			}
	division = { 
	id = { type = 10848 id = 7060 } 
		name = "21.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7061 } 
		name = "22.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7062 } 
		name = "27.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7054 } 
		name = "18.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7055 } 
		name = "45.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7056 } 
		name = "35.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	division = { 
	id = { type = 10848 id = 7057 } 
		name = "38.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	}
airunit = { 
	id = { type = 10848 id = 7068 } 
	name = "Moskva Vozdushnogo Komandovaniya" 
	location = 572 # Moscow 
	base = 572 # Moscow 

	division = { 
	id = { type = 10848 id = 7069 } 
		name = "36.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7070 } 
		name = "43.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7071 } 
		name = "46./48.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 1
			}
	division = { 
	id = { type = 10848 id = 7072 } 
		name = "49./50.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 1
			}
	division = { 
	id = { type = 10848 id = 7064 } 
		name = "44.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7065 } 
		name = "47.LSHABR" 
		strength = 80 
		type = cas 
		model = 1 
			}
	division = { 
	id = { type = 10848 id = 7066 } 
		name = "55.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7067 } 
		name = "52.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	}

# Naval OOB

	navalunit = { # Dushenov K.I.
		id = { type = 10848 id = 5400 } 
		name = "Severnaya Voennaya Flotiliya" 
		location = 535 
		base = 535 
		division = { 
			id = { type = 10848 id = 5401 } 
			name = "1. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 6009 } 
			name = "2. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5402 } 
			name = "1. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 6008 } 
			name = "2. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5153 } 
			name = "3. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		} 	
	navalunit = { # Galler L.M.
		id = { type = 10848 id = 5100 } 
		name = "Krasnoznamenny Baltijsky Flot" 
		location = 553 
		base = 553 
		division = { 
			id = { type = 10848 id = 5101 } 
			name = "Marat" 
			type = battleship 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 5102 } 
			name = "Oktyabrskaya Revolutsiya" 
			type = battleship 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 6000 } 
			name = "Kirov" 
			type = heavy_cruiser
			model = 5 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 8501 } 
			name = "Maxim Gorky" 
			type = heavy_cruiser
			model = 5 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5103 } 
			name = "3. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5104 } 
			name = "4. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5206 } 
			name = "5. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5500 } 
			name = "10. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5501 } 
			name = "11. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5154 } 
			name = "4. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6003 } 
			name = "5. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5161 } 
			name = "6. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5162 } 
			name = "7. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5163 } 
			name = "8. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5171 } 
			name = "9. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5301 } 
			name = "10. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		}  						
	navalunit = { # Kozhanov I.K.
		id = { type = 10848 id = 5200 } 
		name = "Chernomorskiy Flot" 
		location = 641 
		base = 641 
		division = { 
			id = { type = 10848 id = 5201 } 
			name = "Parizhskaya Kommuna" 
			type = battleship 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 5202 } 
			name = "Krasnyi Kavkaz" 
			type = heavy_cruiser 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5203 } 
			name = "Krasnyi Krym" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5204 } 
			name = "Komintern" 
			type = light_cruiser 
			model = 0 
			} 
		division = { 
			id = { type = 10848 id = 5205 } 
			name = "Chervona Ukraina" 
			type = light_cruiser 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 8500 } 
			name = "Voroshilov" 
			type = heavy_cruiser
			model = 5 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 8502 } 
			name = "Molotov" 
			type = heavy_cruiser
			model = 5 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5207 } 
			name = "6. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5502 } 
			name = "7. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5503 } 
			name = "12. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5504 } 
			name = "13. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5302 } 
			name = "11. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 6011 } 
			name = "12. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5172 } 
			name = "13. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5173 } 
			name = "14. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 6012 } 
			name = "15. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		} 
	navalunit = { # Viktorov M.V.
		id = { type = 10848 id = 5515 } 
		name = "Tikhookeanskiy Flot" 
		location = 1191 
		base = 1191 
		division = { 
			id = { type = 10848 id = 6001 } 
			name = "8. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6015 } 
			name = "9. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6013 } 
			name = "16. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6014 } 
			name = "17. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5551 } 
			name = "18. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5552 } 
			name = "19. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5351 } 
			name = "20. Divizion Podlodok" 
			type = submarine 
			model = 1 
			} 
		division = { 
			id = { type = 10848 id = 5352 } 
			name = "21. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5353 } 
			name = "22. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}
		division = { 
			id = { type = 10848 id = 6006 } 
			name = "23. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6007 } 
			name = "24. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6018 } 
			name = "25. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6019 } 
			name = "26. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6010 } 
			name = "27. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}  
		division = { 
			id = { type = 10848 id = 5514 } 
			name = "1. Transportnaya Flotiliya" 
			type = transport 
			model = 2 
			} 
		} 	
	
	# Starting Build Queue 
	division_development = {
		name  = "Kaganovich"
		type  = heavy_cruiser
		model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8503 }
		date  = { year = 1942 month = december day = 31 }
	}
	division_development = {
		name  = "Kalinin"
		type  = heavy_cruiser
		model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8504 }
		date  = { year = 1944 month = december day = 6 }
	}
	division_development = {
		name  = "Chapayev"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8505 }
		date  = { year = 1943 month = march day = 8 }
	}
	division_development = {
		name  = "Zheleznyakov"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8506 }
		date  = { year = 1943 month = march day = 30 }
	}
	division_development = {
		name  = "Kuybyshev"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8507 }
		date  = { year = 1943 month = february day = 28 }
	}
	division_development = {
		name  = "Chkalov"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8508 }
		date  = { year = 1943 month = february day = 28 }
	}
	division_development = {
		name  = "Frunze"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8509 }
		date  = { year = 1943 month = february day = 26 }
	}
	division_development = {
		name  = "Ordzhinikidze"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8510 }
		date  = { year = 1943 month = august day = 24 }
	}
	division_development = {
		name  = "Sverdlov"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8511 }
		date  = { year = 1943 month = october day = 3 }
	}
	division_development = {
		name  = "Kronshtadt"
		type  = battlecruiser
		model = 3
		cost  = 0.1
		id    = { type = 10848 id = 8512 }
		date  = { year = 1945 month = may day = 6 }
	}
	division_development = {
		name  = "Sevastopol"
		type  = battlecruiser
		model = 3
		cost  = 0.1
		id    = { type = 10848 id = 8513 }
		date  = { year = 1945 month = april day = 21 }
	}
	division_development = {
		name  = "Sovyetskiy Soyuz"
		type  = battleship
		model = 8
		cost  = 0.1
		id    = { type = 10848 id = 8514 }
		date  = { year = 1945 month = august day = 11 }
	}
	division_development = {
		name  = "Sovyetskaya Ukraina"
		type  = battleship
		model = 8
		cost  = 0.1
		id    = { type = 10848 id = 8515 }
		date  = { year = 1945 month = october day = 12 }
	}
	division_development = {
		name  = "Sovyetskaya Rossiya"
		type  = battleship
		model = 8
		cost  = 0.1
		id    = { type = 10848 id = 8516 }
		date  = { year = 1946 month = september day = 3 }
	}

 }	
