 
 ############################## 
 # Country definition for ENG # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = ENG 
 
	ai = "eng_1941.ai"
   capital                = 29 
   belligerence           = 5 
   
   manpower               = 485
   energy                 = 8040
   metal                  = 4020
   rare_materials         = 2010
   oil                    = 1000 
   supplies               = 1000 
   money                  = 100 
   transports             = 1550 
   escorts                = 60 
     research_mod = 0.75
  diplomacy =
  { relation = { tag = AFG value = -75 }
    relation = { tag = ARG value = 75 }
    relation = { tag = AST value = 200 access = yes }
    relation = { tag = BEL value = 200 }
    relation = { tag = BHU value = 200 access = yes }
    relation = { tag = BUL value = -200 }
    relation = { tag = CAN value = 200 access = yes }
    relation = { tag = CHI value = 100 }
    relation = { tag = SLO value = -200 }
    relation = { tag = ETH value = 50 }
    relation = { tag = FIN value = 85 }
    relation = { tag = U01 value = 200 }
    relation = { tag = GER value = -200 }
    relation = { tag = GUA value = 50 }
    relation = { tag = HOL value = 200 }
    relation = { tag = HON value = 50 }
    relation = { tag = HUN value = -200 }
    relation = { tag = IRE value = 50 }
    relation = { tag = IRQ value = 100 }
    relation = { tag = ITA value = -200 }
    relation = { tag = MEX value = 50 }
    relation = { tag = NEP value = 200 access = yes }
    relation = { tag = NZL value = 200 access = yes }
    relation = { tag = OMN value = 150 access = yes }
    relation = { tag = PER value = 25 }
    relation =
    { tag        = POR
      value      = 100
      guaranteed = { day = 22 month = may year = 1939 }
    }
    relation = { tag = ROM value = -200 }
    relation = { tag = SAF value = 200 access = yes }
    relation =
    { tag        = SAU
      value      = 100
      guaranteed = { day = 11 month = february year = 1940 }
    }
    relation =
    { tag        = SCH
      value      = 50
      guaranteed = { day = 19 month = april year = 1939 }
    }
    relation = { tag = SIA value = 70 }
    relation = { tag = SOV value = 150 }
    relation = { tag = SPA value = -65 }
    relation = { tag = SWE value = 80 }
    relation =
    { tag        = TUR
      value      = 75
      guaranteed = { day = 17 month = may year = 1938 }
    }
    relation = { tag = USA value = 150 }
    relation = { tag = VEN value = -10 }
    relation =
    { tag        = YEM
      value      = 150
      access     = yes
      guaranteed = { day = 11 month = february year = 1940 }
    }
    relation = { tag = NIC value = 200 }
    relation = { tag = U05 value = 125  }
    relation = { tag = U02 value = 200 access = yes }
  } 
   SpyInfo                = {  country = "ENG" NumberOfSpies = 12  } 
    
   # GREAT BRITAIN 
   nationalprovinces      = {  29 9 5 4 6 7 12 11 10 36 35 13 14 15 18 17 16 24 25 28  
        19 26 27 20 23 22 21 8 }
   # GREAT BRITAIN 
   ownedprovinces         = {  4 5 6 7 11 10 13 15 17 18 24 22 28 25 29 26 27 19 20 36 35 429 348 1011 1010 1024 387 388 1773 1760 1772 2136 2138 2137 1774 1753 1754 1755 1771 1038 2086 1757 1770 1763 1764 1769 1758 2045 1998 1997 1782 1766 1759 900 874 979 964 937 952 955 956 939 929 940 941 930 931 803 804 813 814 805 832 811 812 843 841 842 848 844 807 810 806 808 809 932 859 860 871 869 870 866 867 933 861 863 864 997 849 850 851 938 993 896 23 16 9 12 1371 1435 1436 1437 1438 1432 21 1039 1510 1511 1433 1434 1509 1678 1679 1680 1728 1687 1729 1588 1590 1593 1624 1625 1626 1589 1591 1592 1682   1749 1750 1746 1022 1172 1008 1009 1025 1026 1053 1051 840 998 1611 877 1041 1013 1023  1612 1613 1614 14 8 845  852 
        839 865 862 936 934 935 954 953 868 1783 1 2 3 790 780 785 799 784 783 778 789 792 788 786 791 796 800 801 1004 1005 1006 1007 793 794 797 795 798 802 781 782 779 815 816 817 834 835 836 837 838 1036 1033 1034 1035 1037 1028 1032 1031 1030 1027 1029 820 819 821 822 823 818 829 825 830 826 831 828 827 824                          } 
   # GREAT BRITAIN 
   controlledprovinces    = {  4 5 6 7 11 10 13 15 17 18 24 22 28 25 29 26 27 19 20 36 35 429 348 1011 1010 1024 387 388 1773 1760 1772 2136 2138 2137 1774 1753 1754 1755 1771 1038 2086 1757 1770 1763 1764 1769 1758 2045 1998 1997 1782 1766 1759 900 874 979 964 937 952 955 956 939 929 940 941 930 931 803 804 813 814 805 832 811 812 843 841 842 848 844 807 810 806 808 809 932 859 860 871 869 870 866 867 933 861 863 864 997 849 850 851 938 993 896 23 16 9 12 1371 1435 1436 1437 1438 1432 21 1039 1510 1511 1433 1434 1509 1678 1679 1680 1728 1687 1729 1588 1590 1593 1624 1625 1626 1589 1591 1592 1682   1749 1750 1746 1022 1172 1008 1009 1025 1026 1053 1051 840 998 1611 877 1041 1013 1023  1612 1613 1614 14 8 845  852 
        839 865 862 936 934 935 954 953 868 1783 1 2 3 790 780 785 799 784 783 778 789 792 788 786 791 796 800 801 1004 1005 1006 1007 793 794 797 795 798 802 781 782 779 815 816 817 834 835 836 837 838 1036 1033 1034 1035 1037 1028 1032 1031 1030 1027 1029 820 819 821 822 823 818 829 825 830 826 831 828 827 824 765                          } 
   claimedprovinces = { 
                        348 429 387 388 900 #Gibraltar + Malta + Cyprus + Suez
						1371 #Hong Kong
                        2136 2138 2137 #Newfoundland
						1008 1009 1010 1011 1172 1013 1022 1023 1024 1025 1026 #Palestine + Transjordan
						1038 1039 1041 1051 1053 #Kuwait, UAE, Oman, Yemen
						1432 1433 1434 1435 1436 1437 1438 1624 1625 1626 #Malaysia
						2045 2086 1998 1997 #Falkland Islands + Belize + Guyana
						896 993 1753 1754 1755 1757 1758 1759 1760 1763 1764 1766 1769 1770 1771 1772 1773 1774 1782 #Atlantic Ocean Islands
						929 930 931 932 933 934 935 936 937 938 939 940 941 952 953 954 955 956 964 979 #West African possessions
						803 804 805 806 807 808 809 810 811 812 813 814 832 
						815 816 817 839 841 842 843 844 845 848 849 850 851 852   859 860 861 862 863 864 865 866 867 868 869 870 871 874 877 #East African possessions
						840 997 998 1509 1510 1511 1611 1612 1613 1614 #Indian Ocean Islands
						1588 1589 1590 1591 1592 1593 1678 1679 1680 1682 1687 1728 1729 1746 1749 1750 #Pacific Ocean Islands
						790 780 785 799 784 783 778 789 792 788 786 791 796 800 801 1004 1005 1006 1007 793 794 797 795 798 802 781 782 779 # Egypt
                        } 
						
# Commonwealth Tech '41 
# UK 1941 techs 
# ###################### 
techapps               = { 
# Infantry Division  
1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110
# Cavalry
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
# Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240 1250
# Marine Division
1560 1570 1580 1590 1600
# Airborne Division
1670 1680
# Motorised Inf
1396 1400
# Engineers
1830 1840 1850 1860 1870
# Supply/Logisitics/Repair
1910 1920 1930 1940 1950 1960 1970 1980 1990 199100 199130

# Armoured Car 
2860 2870 2880 2020 2150
# Armor 
7600 7610 2620 2010 2630 2640 2646 2650 2030 2040 2050 2070 2080 2100 2110
# Field Artillery 
2290 2300 2310 2900 2910 2920 2930 2940 2320 2330
# Static Anti-Air Artillery 
2800 2450 21180 21190 21200 2460 2470
# Anti-Air Artillery Brigade 
2810 2820 2510 2520
# Anti-tank Artillery
2400 2410
# Tank Destroyer
2170

# Submarine 
3610 3620 3630 3640 3650 3660 3670
# Destroyer 
3010 3020 3030 3040 3050 3060 3070 12000
# Light Cruiser 
3110 3120 3130 3140 3150 3160 12010
# Heavy Cruiser 
3210 3220 3230 3240 3250 3260
# Battlecruiser
3310 3320 3330 3340
# Battleship 
3410 3420 3430 3440 3450 3456 3460 3470 3480
# Light Carrier 
12100 12110 12120 12130 12140
# Fleet Carrier 
3510 3520 3530 3540 3550
# Torpedo & ASW 18
3720 3730 3736 3740 3750 3760 3900 3910
# Troopships
3810 3820 3830 3840

# Interceptors
4500 4510 4520 4530 4540 4550 4010 4020 4030 4060
# Tactical Bombers
4600 4610 4620 4630 4120 4130 4140 4150
# Close Air Support
4400 4170 4280
# Escort Fighters
4050 4080
# Multirole fighter
4300 4310 4320 4330 4340 4040
# Transports
4290 4250 4260
# Naval bomber
4700 4710 4190 4200
# CAG 37
4900 4910 4920 4930 4940
# Strategic Bomber 
4800 4810 4820 4220 4230
# Seaplanes
4740 4750 4760 4770 4780 4790 4850

#Agriculture
5700 5710 5010 5020 5030
#Manufacturing
5810 5820 5050 5830 5060 5070 5130
#Improved Construction Engineering 
5800 5080 5090 5100
#Basic Oil Refining
5190 5200 5210
#Computers
5310 54010 54020 54030 5320 5330
#Cryptography
5316 5326 5327 5350 5360
#Basic Decimetric Radar Warning Sites 
5410 5416 5417 5420 5426
#Faculty of Atomic Research 
5470
#Exp. Rocket
5560
#Medicine
5600 5610 5620 5630 5640
#Assembly Line
5140 5160 5180

#Great War Hospital System 
14000 14010 14020 14030

# WWI Land Doctrines - Entente line: eng fra ita usa bel hol jap 
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
# WWII Land Doctrines
6560 6030 6120 6110 6420

# Naval Doctrines
# 
# Theories
8010 8020 8030 8040 8050 8060 8070 8080
# Amphib
82300 82310
# Logistic Support
82500 82510
# Naval Interdiction
8500 8510 8520 8550 8560 8600 8610
# Engagement Tactics
8900 8910 8920 8930 8940 8950 8960 8970 8980
# Naval Supremacy
8100 8110 8120 8150 8160 8200 8210 8220
# Carrier Doctrine
81650 
# Carrier - Scouting Focus Line
81850 81860 81870 81880 81890
# Carrier - Strike Line
81700 81710 81720 81730 81740

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 9050 9060 9090 9140 9150 9160 9070 9080 9100 9110 9120 9130 9190 9200 9210 9230 9240 9250

} 
inventions = { 3000027 }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 8 
     political_left    = 2 
     freedom           = 8 
     free_market       = 8 
     professional_army = 7 
     defense_lobby     = 5 
     interventionism   = 6 
    }
   headofstate            = {  type = 9 id = 10014  } 
   headofgovernment       = {  type = 9 id = 10018  } 
   foreignminister        = {  type = 9 id = 10003  } 
   armamentminister       = {  type = 9 id = 10039  } 
   ministerofsecurity     = {  type = 9 id = 10064  } 
   ministerofintelligence = {  type = 9 id = 10078  } 
   chiefofstaff           = {  type = 9 id = 10094  } 
   chiefofarmy            = {  type = 9 id = 10104  } 
   chiefofnavy            = {  type = 9 id = 10112  } 
   chiefofair             = {  type = 9 id = 10117  }
   dormant_ministers      = {  10001 10011 10002 10004 10005 10058 10006 10007 10008 10101 10102 10009 10109 10010 10017 10022 10091 10103 10105 10119 10059 10131 10141 10142
                            }
  
   # ## United Kingdom Land OOB ### 
   landunit = 
   {  name     = "Aldershot Command" 
     location = 27 
     id       = {  type = 12700 id = 1  } 
     Division = 
     {  id       = {  type = 12700 id = 63  } 
       name     = "British Army HQ" 
       type     = hq 
       model    = 3 
       strength = 100
      }
     Division = 
     {  id            = {  type = 12700 id = 2  } 
       name 	= "1st Infantry Division" 
       type 	= infantry
	   model 	= 10
       strength = 100
	   extra 	= light_armor_brigade
	   brigade_model = 3
      } 
     Division = 
     {  id       = {  type = 12700 id = 3  } 
       name     = "2nd Infantry Division" 
       type     = infantry
		model   = 10	   
       strength = 100
	   extra    = light_armor_brigade
	   brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 12700 id = 1941  } 
       name     = "Guards Armoured Division" 
       type     = armor 
	   model    = 0
       strength = 60
      }   
    } 
   landunit = 
   {  name     = "Northern Command" 
     location = 18 
     id       = {  type = 12700 id = 4  } 
     Division = 
     {  id       = {  type = 12700 id = 5  } 
       name     = "5th Infantry Division" 
       type     = infantry 
	   model    = 10
       strength = 100
      }
     Division = 
     {  id       = {  type = 12700 id = 1504  } 
       name     = "46th (West Riding) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }   
    } 
   landunit = 
   {  name     = "Iceland Occupation Force" 
     location = 1 
     id       = {  type = 12700 id = 2900  } 
     Division = 
     {  id       = {  type = 12700 id = 1501  } 
       name     = "49th (West Riding) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      } 
    } 
   landunit = 
   {  name     = "Southern Command" 
     location = 26 
     id       = {  type = 12700 id = 6  } 
     Division = 
     {  id       = {  type = 12700 id = 7  } 
       name     = "3rd Infantry Division" 
       type     = infantry 
       strength = 100
	   model    = 10
	   extra    = artillery 
       brigade_model = 4
      } 
     Division = 
     {  id       = {  type = 12700 id = 5050  } 
       name     = "1st Armoured Div. (Royal Hussars)" 
       type     = light_armor 
	   model    = 2
       strength = 50
      }   
     Division = 
     {  id       = {  type = 12700 id = 1920  } 
       name     = "6th Armoured Division" 
       type     = armor 
	   model    = 0
       strength = 45
      } 
     Division = 
     {  id       = {  type = 12700 id = 505  } 
       name     = "43rd (Wessex) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }    
     Division = 
     {  id       = {  type = 12700 id = 507  } 
       name     = "45th (Wessex) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }
     Division = 
     {  id       = {  type = 12700 id = 506  } 
       name     = "48th (South Midland) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }
     Division = 
     {  id       = {  type = 12700 id = 508  } 
       name     = "61st (South Midland) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
    } 
   landunit = 
   {  name     = "Scottish Command" 
     location = 12 
     id       = {  type = 12700 id = 509  } 
     Division = 
     {  id       = {  type = 12700 id = 513  } 
       name     = "15th (Scottish) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 512  } 
       name     = "51st (Highland) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 511  } 
       name     = "52nd (Lowland) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
    } 
   landunit = 
   {  name     = "Western Command" 
     location = 17 
     id       = {  type = 12700 id = 514  } 
     Division = 
     {  id       = {  type = 12700 id = 515  } 
       name     = "42nd (East Lancashire) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 517  } 
       name     = "55th (West Lancashire) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 518  } 
       name     = "38th (Welsh) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 519  } 
       name     = "59th (Staffordshire) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
    } 
   landunit = 
   {  name     = "53rd Division" 
     location = 36 
     id       = {  type = 12700 id = 1921  } 
     Division = 
     {  id       = {  type = 12700 id = 516  } 
       name     = "53rd (Welsh) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
    } 
   landunit = 
   {  name     = "Eastern Command" 
     location = 25 
     id       = {  type = 12700 id = 521  } 
     Division = 
     {  id       = {  type = 12700 id = 522  } 
       name     = "4th Infantry Division" 
       type     = infantry 
       strength = 100
	   model    = 10
	   extra    = anti_air
       brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 12700 id = 523  } 
       name     = "44th (Home Counties) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 524  } 
       name     = "54th (East Anglian) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 526  } 
       name     = "18th Division" 
       type     = infantry 
	   model    = 5
       strength = 80
      }  
    } 
   landunit = 
   {  name     = "London District" 
     location = 29 
     id       = {  type = 12700 id = 527  } 
     Division = 
     {  id       = {  type = 12700 id = 528  } 
       name     = "47th (London) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 529  } 
       name     = "56th (London) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
    } 
   landunit = 
   {  name     = "Norfolk County Division" 
     location = 25 
     id       = {  type = 12700 id = 1902  } 
     Division = 
     {  id            = {  type = 12700 id = 1903  } 
       name 	= "Norfolk County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Devon and Cornwall County Division" 
     location = 23 
     id       = {  type = 12700 id = 1904  } 
     Division = 
     {  id            = {  type = 12700 id = 1905  } 
       name 	= "Devon and Cornwall County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Dorset County Division" 
     location = 20 
     id       = {  type = 12700 id = 1906  } 
     Division = 
     {  id            = {  type = 12700 id = 1907  } 
       name 	= "Dorset County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Durham and North Riding County Division" 
     location = 13 
     id       = {  type = 12700 id = 1908  } 
     Division = 
     {  id            = {  type = 12700 id = 1909  } 
       name 	= "Durham and North Riding County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Essex County Division" 
     location = 29 
     id       = {  type = 12700 id = 1910  } 
     Division = 
     {  id            = {  type = 12700 id = 1911  } 
       name 	= "Essex County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Hampshire County Division" 
     location = 27 
     id       = {  type = 12700 id = 1912  } 
     Division = 
     {  id            = {  type = 12700 id = 1913  } 
       name 	= "Hampshire County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Lincolnshire County Division" 
     location = 16 
     id       = {  type = 12700 id = 1914  } 
     Division = 
     {  id            = {  type = 12700 id = 1915  } 
       name 	= "Lincolnshire County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Northumberland County Division" 
     location = 13 
     id       = {  type = 12700 id = 1916  } 
     Division = 
     {  id            = {  type = 12700 id = 1917  } 
       name 	= "Northumberland County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Yorkshire County Division" 
     location = 15 
     id       = {  type = 12700 id = 1918  } 
     Division = 
     {  id            = {  type = 12700 id = 1919  } 
       name 	= "Yorkshire County Division" 
       type 	= garrison
       model 	= 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "XIII Corps" 
     location = 781 
     id       = {  type = 12700 id = 1000  } 
     Division = 
     {  id       = {  type = 12700 id = 1502  } 
       name     = "50th (Northumbrian) Division" 
       type     = infantry 
	   model    = 9
       strength = 80
      }  
     Division = 
     {  id       = {  type = 12700 id = 1900  } 
       name     = "7th Armoured Division" 
       type     = light_armor 
	   model    = 2
       strength = 45
      } 
    } 
   landunit = 
   {  name     = "China Command" 
     location = 1371 
     id       = {  type = 12700 id = 8  } 
     Division = 
     {  id       = {  type = 12700 id = 9  } 
       name     = "Hong Kong Defence Force" 
       type     = garrison 
	   model    = 5
       strength = 75
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Malaya Command" 
     location = 1432 
     id       = {  type = 12700 id = 10  } 
     Division = 
     {  id       = {  type = 12700 id = 11  } 
       name     = "Singapore Fortress" 
       type     = garrison
	   model    = 5
	   extra    = engineer
       brigade_model = 3
       strength = 35
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Royal West African Frontier Force" 
     location = 929 
     id       = {  type = 12700 id = 282  } 
     Division = 
     {  id       = {  type = 12700 id = 283  } 
       name     = "The Nigeria Regiment" 
       type     = militia 
	   model    = 5
       strength = 70
      } 
    } 
   landunit = 
   {  name     = "British Troops on Gibraltar" 
     location = 348 
     id       = {  type = 12700 id = 12  } 
     Division = 
     {  id       = {  type = 12700 id = 13  } 
       name     = "Gibraltar Defence Force" 
       type     = garrison 
	   model    = 5
       strength = 25
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Ceylon Command" 
     location = 1511 
     id       = {  type = 12700 id = 14  } 
     Division = 
     {  id       = {  type = 12700 id = 15  } 
       name     = "Ceylon Defence Force" 
       type     = militia 
	   model    = 5
       strength = 80
      } 
    } 
   landunit = 
   {  name     = "Malta Command" 
     location = 429 
     id       = {  type = 12700 id = 16  } 
     Division = 
     {  id       = {  type = 12700 id = 17  } 
       name     = "Malta Defence Force" 
       type     = garrison 
	   model    = 5
       strength = 35
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Western Desert Command" 
     location = 789 
     id       = {  type = 12700 id = 18  } 
     Division = 
     {  id       = {  type = 12700 id = 1922  } 
       name     = "8th Armoured Division" 
       type     = light_armor 
	   model    = 2
       strength = 45
      } 
    }
   landunit = 
   {  name     = "Gentforce" 
     location = 1016 
     id       = {  type = 12700 id = 1901  } 
     Division = 
     {  id       = {  type = 12700 id = 5052  } 
       name     = "1st Cavalry Division" 
       type     = cavalry
	   model    = 10
       strength = 70
      } 
     Division = 
     {  id       = {  type = 12700 id = 19  } 
       name     = "6th Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 60
      } 
    }
   landunit = 
   {  name     = "Mobile Defense Corps" 
     location = 27 
     id       = {  type = 12700 id = 1923  } 
     Division = 
     {  id       = {  type = 12700 id = 1924  } 
       name     = "9th Armoured Division" 
       type     = armor 
	   model    = 0
       strength = 45
      } 
     Division = 
     {  id       = {  type = 12700 id = 1925  } 
       name     = "11th Armoured Division" 
       type     = light_armor 
	   model    = 2
       strength = 45
      } 
    }
   landunit = 
   {  name     = "British Forces in Palestine and Transjordan" 
     location = 1172 
     id       = {  type = 12700 id = 530  } 
     Division = 
     {  id       = {  type = 12700 id = 531  } 
       name     = "8th Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 20
      }
    }
   landunit = 
   {  name     = "African Corps" 
     location = 825 
     id       = {  type = 12700 id = 1926  } 
     Division = 
     {  id       = {  type = 12700 id = 1927  } 
       name     = "11th (African) Division" 
       type     = infantry 
	   model    = 9
       strength = 65
      } 
     Division = 
     {  id       = {  type = 12700 id = 1928  } 
       name     = "12th (African) Division" 
       type     = infantry 
	   model    = 9
       strength = 65
      } 
    }
   landunit = 
   {  name     = "Tobruk Garrison" 
     location = 765 
     id       = {  type = 12700 id = 1929  } 
     Division = 
     {  id       = {  type = 12700 id = 1930  } 
       name     = "Tobruk Garrison" 
       type     = garrison 
	   model    = 5
       strength = 65
      } 
    }
 landunit = 
   {  name     = "Gold Coast Defence Force" 
     location = 956 
     id       = {  type = 12700 id = 43  } 
     Division = 
     {  id       = {  type = 12700 id = 44  } 
       name     = "The Gold Coast Regiment" 
       type     = militia 
	   model    = 5
       strength = 30
      } 
    } 
   landunit = 
   {  name     = "British troops in the Sudan" 
     location = 810 
     id       = {  type = 12700 id = 45  } 
     Division = 
     {  id       = {  type = 12700 id = 46  } 
       name     = "Sudan Defence Force" 
       type     = militia 
	   model    = 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Southern Rhodesia Defence Force" 
     location = 867 
     id       = {  type = 12700 id = 47  } 
     Division = 
     {  id       = {  type = 12700 id = 48  } 
       name     = "Southern Rhodesia Defence Force" 
       type     = militia 
	   model    = 5
       strength = 30
      } 
    } 
   landunit = 
   {  name     = "East Africa Force" 
     location = 841 
     id       = {  type = 12700 id = 55  } 
     Division = 
     {  id       = {  type = 12700 id = 56  } 
       name     = "King's African Rifles" 
       type     = militia 
	   model    = 5
       strength = 70
      } 
    }
   # ################# 
   # Royal Navy # 
   # ################# 

	# HOME FLEET
	navalunit = { 
		id = { type = 12700 id = 84 } 
		name = "Home Fleet" 
		location = 5 
		base = 5  
		division = { 
			id = { type = 12700 id = 89 } 
			name = "HMS Resolution" 
			type = battleship 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 86 } 
			name = "HMS Rodney" 
			type = battleship 
			model = 6 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}  
		division = { 
			id = { type = 12700 id = 8600 } 
			name = "HMS King George V" 
			type = battleship 
			model = 7 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}  
		division = { 
			id = { type = 12700 id = 94 } 
			name = "HMS Repulse" 
			type = battlecruiser 
			model = 1 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 2360 } 
			name = "HMS Victorious" 
			type = carrier 
                        model = 3
			extra1 = cag 
			brigade_model1 = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 208 } 
			name = "HMS Berwick" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}
		division = { 
			id = { type = 12700 id = 210 } 
			name = "HMS Cumberland" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}   
		division = { 
			id = { type = 12700 id = 212 } 
			name = "HMS Kent" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 188 } 
			name = "HMS Norfolk" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}
		division = { 
			id = { type = 12700 id = 211 } 
			name = "HMS Suffolk" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 9600 } 
			name = "HMS Kenya" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			}  
		division = { 
			id = { type = 12700 id = 9601 } 
			name = "HMS Nigeria" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			}  
		division = { 
			id = { type = 12700 id = 98 } 
			name = "HMS Dunedin" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 1815 } 
			name = "Destroyer Division 11" 
			type = destroyer 
			model = 5 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 139 } 
			name = "Destroyer Division 11" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 141 } 
			name = "Destroyer Division 12" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 142 } 
			name = "Destroyer Division 13" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 144 } 
			name = "Destroyer Division 14" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 145 } 
			name = "Destroyer Division 15" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 146 } 
			name = "Destroyer Division 16" 
			type = destroyer 
			model = 6 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2227 } 
			name = "Destroyer Division 37" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2228 } 
			name = "Destroyer Division 38" 
			type = destroyer
			model = 4 			
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 176 } 
			name = "2nd Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 110 } 
			name = "6th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 116 } 
			name = "6th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 117 } 
			name = "7th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 122 } 
			name = "8th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			}  
		division = { 
			id = { type = 12700 id = 119 } 
			name = "9th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		}
	navalunit = { 
		id = { type = 12700 id = 202 } 
		name = "Reserve Fleet" 
		location = 5 
		base = 5  
		division = { 
			id = { type = 12700 id = 2361 } 
			name = "HMS Formidable" 
			type = carrier 
                        model = 3
			extra1 = cag 
			brigade_model1 = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2362 } 
			name = "HMS Illustrious" 
			type = carrier 
                        model = 3
			extra1 = cag 
			brigade_model1 = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 93 } 
			name = "HMS Furious" 
			type = carrier 
			extra1 = cag 
			brigade_model1 = 4 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 2020 } 
			name = "HMS Albatross" 
			type = escort_carrier 
			model = 0 
			}
		division = { 
			id = { type = 12700 id = 8601 } 
			name = "HMS Prince of Wales" 
			type = battleship 
			model = 7 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}  
		division = { 
			id = { type = 12700 id = 152 } 
			name = "HMS Warspite" 
			type = battleship 
			model = 4 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 85 } 
			name = "HMS Nelson" 
			type = battleship 
			model = 6 
			experience = 20
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}
		division = { 
			id = { type = 12700 id = 205 } 
			name = "HMS Frobisher" 
			type = heavy_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 207 } 
			name = "HMS Hawkins" 
			type = heavy_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 157 } 
			name = "HMS London" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 158 } 
			name = "HMS Shropshire" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 159 } 
			name = "HMS Sussex" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 196 } 
			name = "HMS Capetown" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}  
		division = { 
			id = { type = 12700 id = 215 } 
			name = "HMS Caradoc" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 162 } 
			name = "HMS Coventry" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			extra1 = naval_anti_air_s
			} 
		division = { 
			id = { type = 12700 id = 164 } 
			name = "HMS Delhi" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 167 } 
			name = "HMS Arethusa" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 100 } 
			name = "HMS Orion" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 1670 } 
			name = "HMS Phoebe" 
			type = light_cruiser 
			model = 6 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 2166 } 
			name = "HMS Belfast" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2161 } 
			name = "HMS Liverpool" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2162 } 
			name = "HMS Manchester" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 232 } 
			name = "HMS Newcastle" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 136 } 
			name = "Destroyer Division 9" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 138 } 
			name = "Destroyer Division 10" 
			type = destroyer 
			model = 6 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 1830 } 
			name = "Destroyer Division 29" 
			type = destroyer 
			model = 6 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 1831 } 
			name = "Destroyer Division 30" 
			type = destroyer 
			model = 6 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 224 } 
			name = "Destroyer Division 31" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 225 } 
			name = "Destroyer Division 32" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2224 } 
			name = "Destroyer Division 36" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 109 } 
			name = "5th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 120 } 
			name = "10th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 121 } 
			name = "11th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2503 } 
			name = "12th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 124 } 
			name = "13th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 1812 } 
			name = "30th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		} 
	# WESTERN APPROACHES COMMAND
	navalunit = { 
		id = { type = 12700 id = 2021 } 
		name = "Western Approaches Command" 
		location = 23 
		base = 23 
 		division = { 
			id = { type = 12700 id = 160 } 
			name = "HMS Exeter" 
			type = heavy_cruiser 
			model = 4 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}
		division = { 
			id = { type = 12700 id = 218 } 
			name = "HMS Cardiff" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 96 } 
			name = "HMS Cairo" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}  
		division = { 
			id = { type = 12700 id = 220 } 
			name = "HMS Curacao" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			extra1 = naval_anti_air_s
			}
		division = { 
			id = { type = 12700 id = 2200 } 
			name = "HMS Dido" 
			type = light_cruiser 
			model = 6 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 172 } 
			name = "Destroyer Division 21" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 226 } 
			name = "Destroyer Division 33" 
			type = destroyer 
			model = 6 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 227 } 
			name = "Destroyer Division 34" 
			type = destroyer 
			model = 6 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2223 } 
			name = "Destroyer Division 35" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 113 } 
			name = "1st Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 114 } 
			name = "2nd Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2500 } 
			name = "3rd Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		} 
	# MURMANSK CONVOY COMMAND
	navalunit = { 
		id = { type = 12700 id = 2022 } 
		name = "Murmansk Convoy Command" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 2164 } 
			name = "HMS Edinburgh" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 234 } 
			name = "HMS Sheffield" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 171 } 
			name = "Destroyer Division 20" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 128 } 
			name = "18th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 129 } 
			name = "19th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		} 
	# MEDITERRANEAN FLEET
	navalunit = { 
		id = { type = 12700 id = 147 } 
		name = "Mediterranean Fleet" 
		location = 789 
		base = 789
		division = { 
			id = { type = 12700 id = 148 } 
			name = "HMS Queen Elizabeth" 
			type = battleship 
			model = 4 
			experience = 20 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = naval_torpedoes_l
			brigade_model3 = 4
			}
		division = { 
			id = { type = 12700 id = 150 } 
			name = "HMS Valiant" 
			type = battleship 
			model = 4 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}
		division = { 
			id = { type = 12700 id = 149 } 
			name = "HMS Barham" 
			type = battleship 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 195 } 
			name = "HMS Eagle" 
			type = escort_carrier 
			model = 1 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 1807 } 
			name = "HMS Erebus" 
			type = heavy_cruiser # Erebus-class monitor
			model = 2 
			experience = 20 
			extra1 = naval_fire_controll_l
			brigade_model1 = 0
			} 
		division = { 
			id = { type = 12700 id = 2201 } 
			name = "HMS Naiad" 
			type = light_cruiser 
			model = 6 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 184 } 
			name = "HMS Carlisle" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 101 } 
			name = "Destroyer Division 1" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 102 } 
			name = "Destroyer Division 2" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 103 } 
			name = "Destroyer Division 3" 
			type = destroyer 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 95 } 
			name = "Destroyer Division 4" 
			type = destroyer 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 131 } 
			name = "Destroyer Division 5" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 132 } 
			name = "Destroyer Division 6" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 133 } 
			name = "Destroyer Division 7" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 135 } 
			name = "Destroyer Division 8" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 125 } 
			name = "14th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			}  
		division = { 
			id = { type = 12700 id = 2504 } 
			name = "15th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2505 } 
			name = "16th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 127 } 
			name = "17th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		} 
	# FORCE K
	navalunit = { 
		id = { type = 12700 id = 1470 } 
		name = "Force K" 
		location = 25 
		base = 25
		division = { 
			id = { type = 12700 id = 97 } 
			name = "HMS Galatea" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 233 } 
			name = "HMS Penelope" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 179 } 
			name = "HMS Ajax" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 99 } 
			name = "HMS Neptune" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 229 } 
			name = "HMS Aurora" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 193 } 
			name = "Destroyer Division 28" 
			type = destroyer 
			model = 6 
			experience = 20 
			}
		} 
	# FORCE H
	navalunit = { 
		id = { type = 12700 id = 1471 } 
		name = "Force H" 
		location = 348 
		base = 348
		division = { 
			id = { type = 12700 id = 151 } 
			name = "HMS Malaya" 
			type = battleship 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 92 } 
			name = "HMS Renown" 
			type = battlecruiser 
			model = 1 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 105 } 
			name = "HMS Argus" 
			type = escort_carrier 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 236 } 
			name = "HMS Ark Royal" 
			type = carrier 
                        model = 2
			extra1 = cag 
			brigade_model1 = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2202 } 
			name = "HMS Hermione" 
			type = light_cruiser 
			model = 6 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 222 } 
			name = "HMS Dauntless" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 173 } 
			name = "Destroyer Division 22" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 180 } 
			name = "Destroyer Division 23" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		} 
	# SOUTH ATLANTIC SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1472 } 
		name = "South Atlantic Squadron" 
		location = 880 
		base = 880
		division = { 
			id = { type = 12700 id = 165 } 
			name = "HMS Despatch" 
			type = light_cruiser 
			model = 2
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 189 } 
			name = "HMS Diomede" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}  
		division = { 
			id = { type = 12700 id = 206 } 
			name = "HMS Dorsetshire" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			}
		division = { 
			id = { type = 12700 id = 156 } 
			name = "HMS Devonshire" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 230 } 
			name = "HMS Birmingham" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 181 } 
			name = "24th Destroyer Flotilla" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 111 } 
			name = "7th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			}  
		} 
	# INDIAN OCEAN SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1473 } 
		name = "Indian Ocean Squadron" 
		location = 1611 
		base = 1611
		division = { 
			id = { type = 12700 id = 87 } 
			name = "HMS Royal Sovereign" 
			type = battleship 
			model = 3 
			experience = 20 
			}   
		division = { 
			id = { type = 12700 id = 153 } 
			name = "HMS Revenge" 
			type = battleship 
			model = 3 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 203 } 
			name = "HMS Hermes" 
			type = escort_carrier 
			model = 2 
			experience = 20 
			}  
		division = { 
			id = { type = 12700 id = 191 } 
			name = "HMS Enterprise" 
			type = light_cruiser 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 217 } 
			name = "HMS Colombo" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 209 } 
			name = "HMS Cornwall" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 185 } 
			name = "Destroyer Division 25" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		} 
	# EAST INDIES STATION
	navalunit = { 
		id = { type = 12700 id = 1474 } 
		name = "East Indies Station" 
		location = 1511 
		base = 1511
		division = { 
			id = { type = 12700 id = 90 } 
			name = "HMS Ramillies" 
			type = battleship 
			model = 3 
			experience = 20 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 2168 } 
			name = "HMS Mauritius" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 190 } 
			name = "HMS Emerald" 
			type = light_cruiser 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 213 } 
			name = "HMS Caledon" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 219 } 
			name = "HMS Ceres" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 231 } 
			name = "HMS Glasgow" 
			type = light_cruiser 
			model = 5 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 186 } 
			name = "Destroyer Division 26" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2516 } 
			name = "29th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		} 
	# CHINA STATION
	navalunit = { 
		id = { type = 12700 id = 194 } 
		name = "China Station" 
		location = 1371 
		base = 1371
		division = { 
			id = { type = 12700 id = 166 } 
			name = "HMS Durban" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 221 } 
			name = "HMS Danae" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 178 } 
			name = "HMS Dragon" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 192 } 
			name = "Destroyer Flotilla 27" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 1809 } 
			name = "Destroyer Division 41" 
			type = destroyer 
			model = 6 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 1810 } 
			name = "Destroyer Division 42" 
			type = destroyer 
			model = 6 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 108 } 
			name = "4th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2506 } 
			name = "20th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2508 } 
			name = "21st Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2509 } 
			name = "22nd Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2510 } 
			name = "23rd Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2511 } 
			name = "24th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2512 } 
			name = "25th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2513 } 
			name = "26th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2514 } 
			name = "27th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2515 } 
			name = "28th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		} 
	# ROYAL NAVY AUXILIARY
	navalunit = { 
		id = { type = 12700 id = 1813 } 
		name = "Royal Navy Auxiliary" 
		location = 5 
		base = 5  
		division = { 
			id = { type = 12700 id = 2518 } 
			name = "31st Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2519 } 
			name = "32nd Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2520 } 
			name = "33rd Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2521 } 
			name = "34th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2522 } 
			name = "35th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2507 } 
			name = "36th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			}
		division = { 
			id = { type = 12700 id = 2523 } 
			name = "37th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2524 } 
			name = "38th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2525 } 
			name = "39th Transport Flotilla" 
			type = transport 
			model = 2 
			experience = 20 
			} 
		}         
	# 1ST SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 174 } 
		name = "1st Submarine Squadron" 
		location = 789 
		base = 789 
		division = { 
			id = { type = 12700 id = 175 } 
			name = "1st Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 107 } 
			name = "3rd Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		} 
	# 3RD SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 199 } 
		name = "3rd Submarine Squadron" 
		location = 1371 
		base = 1371 
		division = { 
			id = { type = 12700 id = 200 } 
			name = "8th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 201 } 
			name = "9th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 20 
			} 
		} 
	# 4TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1990 } 
		name = "4th Submarine Squadron" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 228 } 
			name = "10th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2280 } 
			name = "11th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 20 
			} 
		} 
	# 5TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1991 } 
		name = "5th Submarine Squadron" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 2281 } 
			name = "12th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 20 
			} 
		} 
	# POLISH NAVY
	navalunit = { 
		id = { type = 12700 id = 970 } 
		name = "Polish Navy" 
		location = 12 
		base = 12 
     		division = {
			id = {  type = 18600 id = 54 } 
       			name = "1 Flotylla Niszczycieli" 
      			type = destroyer 
       			model = 3
       			strength = 40 
      			} 
		}
   # ################# 
   # Royal Airforce # 
   # ################# 
   airunit = 
   {  location = 25 
     base     = 25 
     id       = {  type = 12700 id = 65  } 
     name     = "RAF Bomber Command" 
     Division = 
     {  id       = {  type = 12700 id = 66  } 
       name     = "No.2 RAF Strategic Group" 
       type     = strategic_bomber 
       model    = 4
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 68  } 
       name     = "No.3 RAF Strategic Group" 
       type     = strategic_bomber 
       model    = 4
       strength = 100
      }
     Division = 
     {  id       = {  type = 12700 id = 69  } 
       name     = "No.4 RAF Strategic Group" 
       type     = strategic_bomber 
       model    = 4
       strength = 100
      } 
    } 
   airunit = 
   {  location = 26 
     base     = 26 
     id       = {  type = 12700 id = 70  } 
     name     = "No.5 RAF Tactical Group" 
     Division = 
     {  id       = {  type = 12700 id = 71  } 
       name     = "No.5 RAF Tactical Group" 
       type     = tactical_bomber 
       model    = 7 
       strength = 100
      } 
    } 
   airunit = 
   {  location = 26 
     base     = 26 
     id       = {  type = 12700 id = 72  } 
     name     = "RAF Fighter Command" 
     Division = 
     {  id       = {  type = 12700 id = 73  } 
       name     = "1/No.11 RAF Interceptor Group" 
       type     = interceptor 
       model    = 9
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7300  } 
       name     = "2/No.11 RAF Interceptor Group" 
       type     = interceptor 
       model    = 9
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7301  } 
       name     = "1/No.12 RAF Interceptor Group" 
       type     = interceptor 
       model    = 8
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7302  } 
       name     = "2/No.12 RAF Interceptor Group" 
       type     = interceptor 
       model    = 8
       strength = 100
      } 
    } 
   airunit = 
   {  location = 25 
     base     = 25 
     id       = {  type = 12700 id = 7200  } 
     name     = "No.13 RAF Interceptor Group" 
     Division = 
     {  id       = {  type = 12700 id = 7303  } 
       name     = "1/No.13 RAF Interceptor Group" 
       type     = interceptor 
       model    = 9
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7304  } 
       name     = "2/No.13 RAF Interceptor Group" 
       type     = interceptor 
       model    = 9
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7305  } 
       name     = "1/No.14 RAF Interceptor Group" 
       type     = interceptor 
       model    = 8
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7306  } 
       name     = "2/No.14 RAF Interceptor Group" 
       type     = interceptor 
       model    = 8
       strength = 100
      } 
    } 
   airunit = 
   {  location = 789 
     base     = 789 
     id       = {  type = 12700 id = 78  } 
     name     = "Middle East Air Command" 
     Division = 
     {  id       = {  type = 12700 id = 7307  } 
       name     = "1/No.15 RAF Interceptor Group" 
       type     = interceptor 
       model    = 8
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7308  } 
       name     = "2/No.15 RAF Interceptor Group" 
       type     = interceptor 
       model    = 8
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7309  } 
       name     = "5/No.15 RAF Interceptor Group" 
       type     = interceptor 
       model    = 8
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 79  } 
       name     = "1/Middle East Group" 
       type     = tactical_bomber 
       model    = 6 
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7900  } 
       name     = "2/Middle East Group" 
       type     = tactical_bomber 
       model    = 6 
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7901  } 
       name     = "4/Middle East Group" 
       type     = naval_bomber 
       model    = 2 
       strength = 80
      } 
    }
   airunit = 
   {  location = 348 
     base     = 348 
     id       = {  type = 12700 id = 7800  } 
     name     = "Gibraltar Air Command" 
     Division = 
     {  id       = {  type = 12700 id = 7902  } 
       name     = "1/Gibraltar Group" 
       type     = interceptor 
       model    = 9
       strength = 100
      } 
     Division = 
     {  id       = {  type = 12700 id = 7903  } 
       name     = "2/Gibraltar Group" 
       type     = naval_bomber 
       model    = 2 
       strength = 80
      } 
    }
   airunit = 
   {  location = 1517 
     base     = 1517 
     id       = {  type = 12700 id = 67  } 
     name     = "India Air Command" 
     Division = 
     {  id       = {  type = 12700 id = 64  } 
       name     = "Indian Group" 
       type     = tactical_bomber 
       model    = 6 
       strength = 100
      } 
    } 
   airunit = 
   {  location = 1432 
     base     = 1432 
     id       = {  type = 12700 id = 82  } 
     name     = "Far East Air Command" 
     Division = 
     {  id       = {  type = 12700 id = 83  } 
       name     = "1/Far East Group" 
       type     = tactical_bomber
       model    = 6
       strength = 85
      } 
     Division = 
     {  id       = {  type = 12700 id = 7904  } 
       name     = "2/Far East Group" 
       type     = interceptor 
       model    = 8
       strength = 85
      } 
    } 
   # Warships Under Construction# 
   division_development = 
   {  name  = "HMS Duke of York" 
     type  = battleship 
     model = 7
     cost  = 0.1
     id    = {  type = 12700 id = 240  } 
     date  = {  year = 1941 month = november day = 4  } 
      extra = naval_torpedoes_l  
      brigade_model = 4  
    }
   division_development = 
   {  name  = "HMS Anson" 
     type  = battleship 
     model = 7
     cost  = 0.1
     id    = {  type = 12700 id = 241  } 
     date  = {  year = 1942 month = june day = 22  } 
      extra = naval_torpedoes_l  
      brigade_model = 4  
    }
   division_development = 
   {  name  = "HMS Howe" 
     type  = battleship 
     model = 7
     cost  = 0.1
     id    = {  type = 12700 id = 242  } 
     date  = {  year = 1942 month = august day = 29  } 
      extra = naval_torpedoes_l  
      brigade_model = 4  
    }
   division_development = 
   {  name  = "HMS Roberts" 
     type  = heavy_cruiser 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 3900  } 
     date  = {  year = 1941 month = october day = 27  } 
      extra = naval_fire_controll_l  
      brigade_model = 0  
    }
   division_development = 
   {  name  = "HMS Abercrombie" 
     type  = heavy_cruiser 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 3901  } 
     date  = {  year = 1943 month = may day = 5  } 
      extra = naval_fire_controll_l  
      brigade_model = 0  
    }
   division_development = 
   {  name  = "HMS Unicorn" 
     type  = escort_carrier 
     model = 3
     cost  = 0.1
     id    = {  type = 12700 id = 243  } 
     date  = {  year = 1943 month = march day = 12  } 
    }
   division_development = 
   {  name  = "HMS Indomitable" 
     type  = carrier 
     model = 3
     cost  = 0.1
     id    = {  type = 12700 id = 244  } 
     date  = {  year = 1941 month = october day = 10  } 
      extra = cag 
      brigade_model = 4  
    }
   division_development = 
   {  name  = "HMS Implacable" 
     type  = carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 245  } 
     date  = {  year = 1944 month = august day = 28  } 
      extra = cag 
      brigade_model = 4  
    }
   division_development = 
   {  name  = "HMS Indefatigable" 
     type  = carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 246  } 
     date  = {  year = 1944 month = may day = 3  } 
      extra = cag 
      brigade_model = 4  
    }
   division_development = 
   {  name  = "HMS Euryalus" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 261  } 
     date  = {  year = 1941 month = june day = 30  } 
    }
   division_development = 
   {  name  = "HMS Sirius" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 262  } 
     date  = {  year = 1942 month = may day = 6  } 
    }
   division_development = 
   {  name  = "HMS Charybdis" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 263  } 
     date  = {  year = 1941 month = december day = 3  } 
    }
   division_development = 
   {  name  = "HMS Cleopatra" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 264  } 
     date  = {  year = 1941 month = december day = 5  } 
    }
   division_development = 
   {  name  = "HMS Scylla" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 265  } 
     date  = {  year = 1942 month = june day = 12  } 
    }
   division_development = 
   {  name  = "HMS Argonaut" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 266  } 
     date  = {  year = 1942 month = august day = 8  } 
    }
   division_development = 
   {  name  = "HMS Bellona" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 267  } 
     date  = {  year = 1943 month = october day = 23  } 
    }
   division_development = 
   {  name  = "HMS Black Prince" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 268  } 
     date  = {  year = 1943 month = november day = 30  } 
    }
   division_development = 
   {  name  = "HMS Diadem" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 269  } 
     date  = {  year = 1944 month = january day = 6  } 
    }
   division_development = 
   {  name  = "HMS Royalist" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 270  } 
     date  = {  year = 1943 month = september day = 10  } 
    }
   division_development = 
   {  name  = "HMS Spartan" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 271  } 
     date  = {  year = 1943 month = january day = 10  } 
    }
   division_development = 
   {  name  = "HMS Bermuda" 
     type  = light_cruiser 
     model = 5
     cost  = 0.1
     id    = {  type = 12700 id = 272  } 
     date  = {  year = 1942 month = august day = 21  } 
    }
   division_development = 
   {  name  = "HMS Gambia" 
     type  = light_cruiser 
     model = 5
     cost  = 0.1
     id    = {  type = 12700 id = 273  } 
     date  = {  year = 1942 month = february day = 21  } 
    }
   division_development = 
   {  name  = "HMS Jamaica" 
     type  = light_cruiser 
     model = 5
     cost  = 0.1
     id    = {  type = 12700 id = 274  } 
     date  = {  year = 1942 month = june day = 29  } 
    }
   division_development = 
   {  name  = "HMS Trinidad" 
     type  = light_cruiser 
     model = 5
     cost  = 0.1
     id    = {  type = 12700 id = 277  } 
     date  = {  year = 1941 month = october day = 14  } 
    }
   division_development = 
   {  name  = "HMS Ceylon" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 278  } 
     date  = {  year = 1943 month = july day = 13  } 
    }
   division_development = 
   {  name  = "HMS Newfoundland" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 279  } 
     date  = {  year = 1943 month = january day = 21  } 
    }
   division_development = 
   {  name  = "HMS Uganda" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 2800  } 
     date  = {  year = 1943 month = january day = 3  } 
    }

  } 
 
