   
   ##############################   
   # Country definition for USA #   
   ##############################   
      
   #####################   
   # Country main data #   
   #####################   
      
   country =   
   {  tag                    = USA   
     # Resource Reserves   
energy                 = 30060
metal                  = 15030
rare_materials         = 7515  
     oil                    = 5000   
     supplies               = 5000   
     money                  = 100   
     manpower               = 102   
     transports             = 1900   
     escorts                = 14   
     dissent = 15
     research_mod = 0.75
     
     capital                = 1809   

  diplomacy =
  { relation =
    { tag        = ARG
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = AST value = 150 }
    relation = { tag = BEL value = 75 }
    relation =
    { tag        = BOL
      value      = 85
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = BRA
      value      = 120
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = CAN value = 200 }
    relation = { tag = CHI value = 100 }
    relation =
    { tag        = CHL
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = COL
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = COS
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = CUB
      value      = 200
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = DOM
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = ECU
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = 90 }
    relation = { tag = U01 value = 65 }
    relation = { tag = GER value = -125 }
    relation =
    { tag        = GUA
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = HAI
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = HOL value = 70 }
    relation =
    { tag        = HON
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = IRE value = 75 }
    relation = { tag = IRQ value = 120 }
    relation = { tag = JAP value = -125 }
    relation = { tag = LIB value = 200 access = yes }
    relation = { tag = MAN value = -200 }
    relation = { tag = MEN value = -200 }
    relation =
    { tag        = MEX
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = NEP value = 100 }
    relation =
    { tag        = NIC
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = NZL value = 125 }
    relation = { tag = OMN value = 100 }
    relation =
    { tag        = PAN
      value      = 175
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = PAR
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = PHI value = 200 access = yes }
    relation =
    { tag        = PRU
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = SAF value = 125 }
    relation =
    { tag        = SAL
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = SOV value = 175 }
    relation = { tag = SWE value = 75 }
    relation =
    { tag        = URU
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = VEN
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = YEM value = 100 }
    relation = { tag = U05 value = 70  }  
  }   
     SpyInfo                = {  country = "USA" NumberOfSpies = 11  }   
        
     nationalprovinces      = {  1809 1953 1949 1948 1952 1951 1950 1947 1956 1954 1955 1960 1958 1963 1961   
      1962 1964 1813 1812 1814 1818 1815 1816 1817 1808 1807 1801 1797 1791 1795 1793    
      1792 1805 1803 1804 1790 1787 1788 1784 1785 1789 1796 1826 1806   
      1810 1811 1820 1819 1942 1943 1940 1939 1936 1937 1944 1931 1825 1821 1842 1845 1802   
      1957 1828 1934 1930 1929 1932 1918 1915 1925 1836 1833 1830 1829 1832 1839   
      1838 1841 1843 1834 1837 2140 2145 2144 2146 2151 1846 1850 1855 1856 1858 1857 1859   
      1860 1914 1913 1919 1910 1911 1924 1928 1926 1920 1921 1922   
      1905 1906 1904 1900 1901 1902 1898 1896 1907 1908 1897 1909  
     1868 1866 1862 1869 1865 1871 1873 1875 1876 1874  
      1877 1878 1882 1879 1880 1895 1893 1892 1899 1886 1887 1883  
     1888 1889 1884 2141  2142 2147 2143 2139  2174
     1923  
     1831 1847 1935 1945 1885 1872 1863 2150 1864 1778     
    # Panamacanal to prevent transfer to allies  
    889   
    1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
                              }  
    ownedprovinces         = {  1953  1949  1948  1952  1951  1950  1947  1956  1954    1955  1960  1958  1963    1961  1962  1964  1813  1812    1814  1818 1815 1816 1817  1809   
                               1808  1807  1801  1797  1791  1795  1793    1792  1805  1803  1804    1790    1787  1788  1784  1785    1789  1796  1826  1806   
                               1810  1811  1820  1819  1942  1943  1940   1939 1936 1937  1944  1931  1825  1821  1842  1845  1802  1957  1828  1934  1930  1929 1932  1918  1915     
                               1925    1836  1833  1830  1829  1832  1839  1838  1841  1843  1834  1837   2145 2144 2146 2151  1846  1850        1855  1856  1858  1857  1859   
                               1860    1914  1913    1919  1910  1911    1924  1928  1926  1920   1921  1922   1905  1906  1904  1900    1901   
                               1902  1898  1896  1907  1908  1897  1909  1868  1866      1862        1869    1865    1871    1873 1875 1876  1874     
                               1877  1878  1882    1879  1880    1895  1893    1892  1899  1886  1887  1883  1888  1889  1884  2141   2140  2142 2147 2143  2139     
                                         1923      1765  889  1736  1737  1735    1739  1734  1738  1673 1683   
                 1747  
               1733 1751 1745  
               1778 1831  
               1872 1863 2150 1864 1847 1935 1945 1885  2174
         1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
                              }  
    controlledprovinces    = {  1953  1949  1948  1952  1951  1950  1947  1956  1954   1955  1960  1958  1963    1961  1962  1964  1813  1812    1814  1818 1815 1816 1817  1809   
                               1808  1807  1801  1797  1791  1795  1793    1792  1805  1803  1804   1790    1787  1788  1784  1785    1789  1796  1826  1806   
                               1810  1811  1820  1819  1942  1943  1940    1939 1936 1937  1944  1931  1825  1821  1842  1845  1802  1957  1828  1934  1930  1929 1932  1918  1915     
                               1925    1836  1833  1830  1829  1832  1839  1838  1841  1843  1834  1837   2145 2144 2146 2151  1846  1850        1855  1856  1858  1857  1859   
                               1860    1914  1913    1919  1910  1911    1924  1928  1926  1920    1921  1922   1905  1906  1904  1900    1901   
                               1902  1898  1896  1907  1908  1897  1909  1868  1866      1862        1869    1865    1871    1873 1875 1876  1874    
                               1877  1878  1882    1879  1880    1895  1893    1892  1899  1886  1887  1883  1888  1889  1884  2141    2140  2142 2147 2143  2139     
                                         1923      1765  889  1736  1737  1735    1739  1734  1738  1673 1683  1747  
                1733 1751 1745  2174
               1778 1831  
               1872 1863 2150 1864 1847 1935 1945 1885  
         1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
                }  
	# USA 1941 techs  
	# ######################  
	techapps = {  
	# Manufacturing
	5810 5820 5050 5830 5060 5070 5130
	# Construction Engineering 
	5800 5080 5090 5100
	# Computers and cryptography
	5310 54010 54020 54030 5320 5330 5316 5326 5327 5350 5360
	# Agriculture 
	5700 5710 5010 5020 5030
	# Refining
	5190 5200 5210 5220
	# Atomic Research 
	5470 5480 5490
	# Medicine
	5600 5610 5620 5630 5640
	# Exp. Rocket
	5560
	# Radar
	5410 5416 5417 5420
	# Assembly Line
	5140 5160 5180
	
	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110
	# Cavalry Division  
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380
	# Supply / Logs
	1910 1920 1930 1940 1950 1960 1970 1980 1990 199130
	# Marines
	1560 1570 1580 1590 1600
	# Mountain
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250
	# Motorized
	1396
	# Airborne
	1670
	# Engineers
	1830 1840 1850 1860 1870

	# Tank 
	7600 7610 2620 2010 2630 2640 2640 2646 2650 2030 2040 2050 2070
	# Armoured Cars 
	2860 2870 2880 2020 2150
	# Field Artillery 
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330
	# Anti-Tank Artillery
	2400
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460 2470
	# Anti-Air Artillery Brigade 
	2810 2820 2510 2520
	# Tank Destroyer
	2170

	# Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	# Light Cruiser 
	3110 3120 3130 3140 3150 3160 12010
	# Heavy Cruiser 
	3210 3220 3230 3240 3250 3260 12020
	# Battlecruiser
	3310 3320 3330 3340 3350
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470 3480
	# Fleet Carrier 
	3510 3520 3530 3540 3550
	# Light Carrier 
	12100 12110 12120 12130 12140
	# Submarine 
	3610 3620 3630 3640 3650 3660 3670
	# Troopships
	3810 3820 3830 3840
	#Torpedo & ASW 18
	3720 3730 3736 3740 3750 3760 3900 3910
	
	# Interceptor  
	4500 4510 4520 4530 4540 4550 4010 4020	4030 4060
	# Multi-role fighter
	4300 4310 4320 4330 4340 4040 4070
	# Close Air Support
	4400 4170
	# Escort Fighter
	4050
	# Tactical Bomber 
	4600 4610 4620 4630 4120 4130 4140 4150
	# Air Transport 
	4290 4250	
	# Strategic Bomber 
	4800 4810 4820 4220 4230
	# Naval bomber
	4700 4710 4190 4200
	# Seaplanes
	4740 4750 4760 4770 4780 4790 4850 
	# CAG
	4900 4910 4920 4930 4940
	
	# Hospital System 
	14000 14010 14020 14030
	# WWI Land Doctrines - Entente: eng fra ita usa bel hol jap 
	6500 6510  6530 6540 6580 6600 6610 6620 6630 6640 6650 6660 6670 6910
	# WWII Land Doctrines - Firepower Focus
	6010 6020 6040 6050 6060 6070

	# Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9140 9040 9050 9060 9070 9080 9090 9100 9110 9120 9130 9140 9150 9190 9210
	9220 9230 9240 9250 9350

	# Naval Doctrines -
	# Engagement Theories
	8010 8020 8030 8040 8050 8060 8070 8080
	# Naval Supremacy
	8100 8110 8120 8150 8160 8200 8210 8170
	# Naval Interdiction
	8500 8510 8550 8520 8560 8600 8610
	# Engagement Tactics - Fleet-in-Being colum
	8900 8910 8920 8930 8940 8950 8960 8970
	# Subsidiary Carrier Role
	81650
	# Carrier - Scouting Focus
	81850 81860 81870 81880
	# Carrier - Aerial Supremacy
	81700
	# Logistic Support
	82500 82510
	# Amphibious Warfare
	82300 82310
	} 

blueprints = { 81880 81890 }

inventions = { 3000027 }
    policy =  
    {  date              = {  year = 1942 month = january day = 0  }  
     democratic        = 9 
      political_left    = 6  
      freedom           = 10  
      free_market       = 10  
      professional_army = 2  
      defense_lobby     = 3  
      interventionism   = 4  
     }  
	 peacetime_ic_mod       = 0.5
	 wartime_ic_mod       = 0.8
    headofstate            = {  type = 9 id = 240001  }  
    headofgovernment       = {  type = 9 id = 240232  }
    foreignminister        = {  type = 9 id = 240003  }  
    armamentminister       = {  type = 9 id = 240004  }  
    ministerofsecurity     = {  type = 9 id = 240005  }  
    ministerofintelligence = {  type = 9 id = 240098  }  
    chiefofstaff           = {  type = 9 id = 240104  }  
    chiefofarmy            = {  type = 9 id = 240109  }  
    chiefofnavy            = {  type = 9 id = 240126  }  
    chiefofair             = {  type = 9 id = 240129  }
    dormant_ministers      = {  240052 240006 240135 240009 240125 240121 240010 240080 240007 240008 240020 240086  } 

    landunit =  
    {  location = 1734  
      name     = "Pacific HQ"  
      id       = {  type = 14800 id = 1005  }  
     Division = 
     {  id       = {  type = 13500 id = 1006  } 
       name     = "Pacific HQ" 
       type     = hq 
       model    = 3 
       strength = 100 
      } 
    }
    landunit =  
    {  location = 1889  
      name     = "CONUS HQ"  
      id       = {  type = 14800 id = 1007  }  
     Division = 
     {  id       = {  type = 13500 id = 1008  } 
       name     = "CONUS HQ" 
       type     = hq 
       model    = 3 
       strength = 100 
      } 
    }
    landunit =  
    {  location = 1808  
      name     = "US I Corps"  
      id       = {  type = 14800 id = 601  } 
      Division =  
      {  id   = {  type = 14800 id = 1104  }  
        name = "8th 'Pathfinder' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }   
      Division =  
      {  id   = {  type = 14800 id = 1004  }  
        name = "30th 'Old Hickory' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
     }
    landunit =  
    {  location = 1830  
      name     = "US II Corps"  
      id       = {  type = 14800 id = 1009  }
      Division =  
      {  id   = {  type = 14800 id = 611  }  
        name = "28th 'Keystone' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }  
      Division =  
      {  id   = {  type = 14800 id = 612  }  
        name = "29th 'Blue and Gray' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 607  }  
        name = "44th Infantry Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 606  }  
        name = "21st Cavalry Division"  
		strength = 25		
        type = infantry  
		model    = 10
       }    
      Division =  
      {  id   = {  type = 14800 id = 608  }  
        name = "78th 'Lightning' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
     }
    landunit =  
    {  location = 1887  
      name     = "US VI Corps"  
      id       = {  type = 14800 id = 1010  }
      Division =  
      {  id   = {  type = 14800 id = 605  }  
        name = "1st 'Big Red One' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }
      Division =  
      {  id   = {  type = 14800 id = 602  }  
        name = "26th 'Yankee' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 621  }  
        name = "94th 'Pilgrim' Division"
		strength = 15		
        type = infantry  
		model    = 9
       }
     }
    landunit =  
    {  location = 1963  
      name     = "US VII Corps"  
      id       = {  type = 14800 id = 1011  }
      Division =  
      {  id   = {  type = 14800 id = 1012  }  
        name = "27th 'New York Division'"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 1013  }  
        name = "33rd 'Golden Cross' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 625  }  
        name = "35th 'Santa Fe' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 623  }  
        name = "24th Cavalry Division"  
		strength = 25		
        type = infantry  
		model    = 10
       }
     }
    landunit =  
    {  location = 1928  
      name     = "US IV Corps"  
      id       = {  type = 14800 id = 1014  }
      Division =  
      {  id   = {  type = 14800 id = 615  }  
        name = "31st 'Dixie' Division"
		strength = 25		
        type = infantry  
		model    = 10
       } 
      Division =  
      {  id   = {  type = 14800 id = 603  }  
        name = "43rd 'Winged Victory' Division"
		strength = 25		
        type = infantry  
		model    = 10
       } 
      Division =  
      {  id   = {  type = 14800 id = 628  }  
        name = "1st Cavalry 'The 1st Team' Div."  
		strength = 100
        type = cavalry  
		model    = 10
	extra = armored_car
		brigade_model = 3
       }
      Division =  
      {  id   = {  type = 14800 id = 614  }  
        name = "23rd Cavalry Division"  
		strength = 25
        type = cavalry  
		model    = 10
       } 
     }
    landunit =  
    {  location = 1877  
      name     = "US V Corps"  
      id       = {  type = 14800 id = 1015  }
      Division =  
      {  id   = {  type = 14800 id = 1016  }  
        name = "32nd 'Red Arrow' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 624  }  
        name = "34th 'Red Bull' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 618  }  
        name = "37th 'Buckeye' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 1017  }  
        name = "38th 'Cyclone' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 617  }  
        name = "22nd Cavalry Division"  
		strength = 25
        type = cavalry  
		model    = 10
       }    
      Division =  
      {  id   = {  type = 14800 id = 619  }  
        name = "100th 'Century' Division"
		strength = 15		
        type = infantry  
		model    = 10
       }  
     }
    landunit =  
    {  location = 1797  
      name     = "US VIII Corps"  
      id       = {  type = 14800 id = 626  }  
      Division =  
      {  id   = {  type = 14800 id = 627  }  
        name = "2nd 'Indianhead' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }
      Division =  
      {  id   = {  type = 14800 id = 1105  }  
        name = "9th 'Old Reliables' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }
      Division =  
      {  id   = {  type = 14800 id = 1018  }  
        name = "36th 'Texas' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }   
      Division =  
      {  id   = {  type = 14800 id = 629  }  
        name = "45th 'Thunderbird' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 630  }  
        name = "95th 'Victory' Division"
		strength = 15		
        type = infantry  
		model    = 9
       }
     }
    landunit =  
    {  location = 1878  
      name     = "US III Corps"  
      id       = {  type = 14800 id = 1019  }
      Division =  
      {  id   = {  type = 14800 id = 1103  }  
        name = "7th 'Bayonet' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 633  }  
        name = "40th 'Sunshine' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }   
     } 
    landunit =  
    {  location = 1952  
      name     = "US IX Corps"  
      id       = {  type = 14800 id = 631  }  
      Division =  
      {  id   = {  type = 14800 id = 632  }  
        name = "3rd 'Rock of the Marne' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }    
      Division =  
      {  id   = {  type = 14800 id = 634  }  
        name = "41st 'Sunsetters' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 635  }  
        name = "91st 'Wild West' Division"
		strength = 15		
        type = infantry  
		model    = 9
       }  
      Division =  
      {  id   = {  type = 14800 id = 636  }  
        name = "104th 'Timberwolf' Division"
		strength = 15		
        type = infantry  
		model    = 9
       } 
     }
    landunit =  
    {  location = 1736  
      name     = "Hawaiian Corps"  
      id       = {  type = 14800 id = 1020  }
      Division =  
      {  id   = {  type = 14800 id = 1021  }  
        name = "24th 'Victory' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
     }  
    landunit =  
    {  location = 1945  
      name     = "5th Infantry Division"  
      id       = {  type = 14800 id = 1000  }  
      Division =  
      {  id   = {  type = 14800 id = 1001  }  
        name = "5th 'Red Devils' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }    
     }
    landunit =  
    {  location = 1891  
      name     = "6th Infantry Division"  
      id       = {  type = 14800 id = 1002  }  
      Division =  
      {  id   = {  type = 14800 id = 1003  }  
        name = "6th 'Sightseeing Sixth' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }    
     }
    landunit =  
    {  location = 1909  
      name     = "US I Armored Corps"  
      id       = {  type = 14800 id = 1100  }  
      Division =  
      {  id   = {  type = 14800 id = 1101  }  
        name = "4th 'Iron Horse' Division" 
		strength = 100
		type = infantry  
		model    = 10
		extra = artillery
		brigade_model = 6
       }    
      Division =  
      {  id   = {  type = 14800 id = 1113  }  
        name = "2nd Armored 'Hell on Wheels' Div." 
		strength = 60
		type = armor  
		model    = 0
       }
     }  
    landunit =  
    {  location = 1819  
      name     = "1st Armored Division"  
      id       = {  type = 14800 id = 1107  }    
      Division =  
      {  id   = {  type = 14800 id = 1108  }  
        name = "1st Armored 'Old Ironsides' Div." 
		strength = 60
		type = armor  
		model    = 0
       }
     }    
    landunit =  
    {  location = 1795  
      name     = "4th Armored Division"  
      id       = {  type = 14800 id = 1109  }    
      Division =  
      {  id   = {  type = 14800 id = 1110  }  
        name = "4th Armored 'Breakthrough' Div." 
		strength = 60
		type = armor  
		model    = 0
       }
     }   
    landunit =  
    {  location = 1932  
      name     = "3rd Armored Division"  
      id       = {  type = 14800 id = 1111  }    
      Division =  
      {  id   = {  type = 14800 id = 1112  }  
        name = "3rd Armored 'Spearhead' Div." 
		strength = 60
		type = armor  
		model    = 0
       }
     }   
    landunit =  
    {  location = 1808  
      name     = "U.S. Army General Staff"  
      id       = {  type = 14800 id = 609  }  
     Division = 
     {  id       = {  type = 13500 id = 610  } 
       name     = "U.S. Army General Staff" 
       type     = hq 
       model    = 3 
       strength = 100 
      }   
     }     
    landunit =  
    {  location = 1812  
      name     = "1st Marine Division"  
      id       = {  type = 14800 id = 6370  }  
      Division =  
      {  id   = {  type = 14800 id = 6380  }  
        name = "1st US Marine 'The Old Breed' Div." 
		strength = 60
		type = marine
		model    = 4
       }  
     }         
    landunit =  
    {  location = 1886  
      name     = "2nd Marine Division"  
      id       = {  type = 14800 id = 6371  }  
      Division =  
      {  id   = {  type = 14800 id = 6381  }  
        name = "2nd US Marine 'Follow Me' Division" 
		strength = 60
		type = marine
		model    = 4
       }  
     }     
    landunit =  
    {  location = 1874  
      name     = "4th Marine Regiment"  
      id       = {  type = 14800 id = 637  }  
      Division =  
      {  id   = {  type = 14800 id = 638  }  
        name = "4th Marine Regiment" 
		strength = 35
		type = marine
		model    = 4
       }  
     }  
    landunit =  
    {  location = 1814  
      name     = "5th Marine Regiment"  
      id       = {  type = 14800 id = 639  }  
      Division =  
      {  id   = {  type = 14800 id = 640  }  
        name = "5th Marine Regiment" 
		strength = 35
		type = marine
		model    = 4
       }  
     }  
    landunit =  
    {  location = 1886  
      name     = "6th Marine Regiment"  
      id       = {  type = 14800 id = 641  }  
      Division =  
      {  id   = {  type = 14800 id = 642  }  
        name = "6th Marine Regiment" 
		strength = 35
		type = marine
		model    = 4
       }  
     }  
    landunit =  
    {  location = 1734  
      name     = "Hawaiian Department"  
      id       = {  type = 14800 id = 643  }  
      Division =  
      {  id     = {  type = 14800 id = 644  }  
        name   = "Hawaiian Division"  
        type   = infantry  
		model    = 10
        strength = 100 
	extra = engineer
		brigade_model = 3
       }  
     }  
    landunit =  
    {  location = 1565  
      name     = "Philippine Department"  
      id       = {  type = 14800 id = 645  }  
      Division =  
      {  id     = {  type = 14800 id = 646  }  
        name   = "Philippine Division"  
        type   = infantry  
		model    = 10
        strength = 100 
	extra = engineer
		brigade_model = 3
       }  
     }  
    landunit =  
    {  id       = {  type = 14800 id = 647  }  
      name     = "Panama Canal Department"  
      location = 889  
      Division =  
      {  id     = {  type = 14800 id = 648  }  
        name   = "Panama Canal Garrison"  
		strength = 100
        type   = garrison  
        model  = 5
        locked = yes  
       }  
     }  

    # US ASIATIC FLEET-MANILA, PHILLIPINES 
    navalunit =  
    {  name     = "Asiatic Fleet"  
      id       = {  type = 14800 id = 4000  }  
      location = 1565  
      base     = 1565 
      Division =  
      {  id       = {  type = 14800 id = 93  }  
        name     = "USS Houston"  
        strength = 100  
        type     = heavy_cruiser  
        model    = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id       = {  type = 14800 id = 90  }  
        name     = "USS Marblehead"  
        strength = 100  
        type     = light_cruiser  
        model    = 3  
       }  
     }
    # Destroyer Flotilla 29
    navalunit =  
    {  name     = "USN Destroyer Flotilla 29"  
      id       = {  type = 14800 id = 4001  }  
      location = 1565  
      base     = 1565 
      Division =  
      {  id    = {  type = 14800 id = 2294  }  
        name  = "Destroyer Division 57"  
        type  = destroyer  
        model = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 179  }  
        name  = "Destroyer Division 58"  
        type  = destroyer  
        model = 4  
       }  
      Division =  
      {  id    = {  type = 14800 id = 180  }  
        name  = "Destroyer Division 59"  
        type  = destroyer  
        model = 4  
       }   
     }
    # Submarine Squadron 20
    navalunit =  
    {  name     = "USN Submarine Squadron 20"  
      id       = {  type = 14800 id = 4005  }  
      location = 1565  
      base     = 1565 
      Division =  
      {  id    = {  type = 14800 id = 4006  }  
        name  = "Submarine Division 21"  
        type  = submarine  
        model = 4 # Salmon-class
       } 
      Division =  
      {  id    = {  type = 14800 id = 4007  }  
        name  = "Submarine Division 22"  
        type  = submarine  
        model = 5 # Sargo-class  
       } 
      Division =  
      {  id    = {  type = 14800 id = 4008  }  
        name  = "Submarine Division 201"  
        type  = submarine  
        model = 2 # S-class  
       } 
      Division =  
      {  id    = {  type = 14800 id = 4224  }  
        name  = "Submarine Division 202"  
        type  = submarine  
        model = 5 # Sargo-class  
       } 
      Division =  
      {  id    = {  type = 14800 id = 4225  }  
        name  = "Submarine Division 203"  
        type  = submarine  
        model = 4 # Porpoise-class
       } 
     }
    # USS Heron
    navalunit =  
    {  name     = "USS Heron"  
      id       = {  type = 14800 id = 2102  }  
      location = 1565  
      base     = 1565  
      Division =  
      {  id   = {  type = 14800 id = 2103  }  
        name  = "USS Heron"  
        type  = escort_carrier  
        model = 0    
       }
     } 
    # USS Langley
    navalunit =  
    {  name     = "USS Langley"  
      id       = {  type = 14800 id = 4226  }  
      location = 1565  
      base     = 1565  
      Division =  
      {  id   = {  type = 14800 id = 162  }  
        name = "USS Langley"  
        type = escort_carrier  
		model = 0
       } 
     }  
    # US PACIFIC FLEET-PEARL HARBOR, HAWAII  
    # Battleship Division 1  
    navalunit =  
    {  name     = "USN Battleship Division 1"  
      id       = {  type = 14800 id = 26  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 28  }  
        name  = "USS Nevada"  
        type  = battleship  
        model = 4
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 29  }  
        name  = "USS Arizona"  
        type  = battleship  
        model = 4
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 30  }  
        name  = "USS Pennsylvania"  
        type  = battleship
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
     }
    # Battleship Division 2  
    navalunit =  
    {  name     = "USN Battleship Division 2"  
      id       = {  type = 14800 id = 2600  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 33  }  
        name  = "USS Oklahoma"  
        type  = battleship  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 34  }  
		name  = "USS Tennessee"  
		type  = battleship  
		model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 35  }  
        name  = "USS California"  
        type  = battleship  
        model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 4	
       }
     }
    # Battleship Division 4  
    navalunit =  
    {  name     = "USN Battleship Division 4"  
      id       = {  type = 14800 id = 31  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 37  }  
        name  = "USS Colorado"  
        type  = battleship  
        model = 6  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 39  }  
        name  = "USS Maryland"  
        type  = battleship  
        model = 6
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }     
      Division =  
      {  id    = {  type = 14800 id = 38  }  
        name  = "USS West Virginia"  
        type  = battleship  
        model = 6
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
     }
    # Carrier Division 1
    navalunit =  
    {  name     = "USN Carrier Division 1"  
      id       = {  type = 14800 id = 2004  }  
      location = 1734  
      base     = 1734  
      Division =  
      {  id            = {  type = 14800 id = 27  }  
        name          = "USS Lexington"  
        type          = carrier  
        model         = 0  
        extra         = CAG  
        brigade_model = 4  
       } 
      Division =  
      {  id            = {  type = 14800 id = 32  }  
        name          = "USS Saratoga"  
        type          = carrier  
        model         = 0  
        extra         = CAG  
        brigade_model = 4  
       }
     }
    # Carrier Division 2
    navalunit =  
    {  name     = "USN Carrier Division 2"  
      id       = {  type = 14800 id = 2601  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id            = {  type = 14800 id = 501  }  
        name          = "USS Enterprise"  
        type          = carrier  
        model         = 2  
        extra         = CAG  
        brigade_model = 4  
       }
      Division =  
      {  id   = {  type = 14800 id = 2104  }  
        name  = "USS Wright"  
        type  = escort_carrier  
        model = 0    
       }
      Division =  
      {  id   = {  type = 14800 id = 4030  }  
        name  = "USS Curtiss"  
        type  = escort_carrier  
        model = 0    
       }
     }  
    # USS Albemarle
    navalunit =  
    {  name     = "USS Albemarle"  
      id       = {  type = 14800 id = 4031  }  
      location = 2326  
      base     = 1812  
      Division =  
      {  id   = {  type = 14800 id = 4032  }  
        name  = "USS Albemarle"  
        type  = escort_carrier  
        model = 0    
       }
     } 
    # Cruiser Division 3
    navalunit =  
    {  name     = "USN Cruiser Division 3"  
      id       = {  type = 14800 id = 4011  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 41  }  
        name  = "USS Richmond"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 42  }  
        name  = "USS Trenton"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 43  }  
        name  = "USS Concord"  
        type  = light_cruiser  
        model = 3  
       }
     }  
    # Cruiser Division 9
    navalunit =  
    {  name     = "USN Cruiser Division 9"  
      id       = {  type = 14800 id = 4010  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 510  }  
        name  = "USS Honolulu"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 2043  }  
        name  = "USS Helena"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 508  }  
        name  = "USS Phoenix"  
        type  = light_cruiser  
        model = 5  
       }  
      Division =  
      {  id    = {  type = 14800 id = 509  }  
        name  = "USS Boise"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 2042  }  
        name  = "USS St. Louis"  
        type  = light_cruiser  
        model = 5  
       }
     }  
    # Cruiser Division 4
    navalunit =  
    {  name     = "USN Cruiser Division 4"  
      id       = {  type = 14800 id = 4009  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 47  }  
        name  = "USS Pensacola"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 48  }  
        name  = "USS Salt Lake City"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
      Division =  
      {  id    = {  type = 14800 id = 49  }  
		name  = "USS Chicago"  
		type  = heavy_cruiser  
		model = 3 
		extra1 = naval_torpedoes_l
		brigade_model1 = 4			
       }  
      Division =  
      {  id    = {  type = 14800 id = 50  }  
        name  = "USS Indianapolis"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       } 
     } 
    # Cruiser Division 5
    navalunit =  
    {  name     = "USN Cruiser Division 5"  
      id       = {  type = 14800 id = 4200  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 52  }  
        name  = "USS Northampton"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
      Division =  
      {  id    = {  type = 14800 id = 53  }  
        name  = "USS Chester"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 54  }  
        name  = "USS Louisville"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 55  }  
        name  = "USS Portland"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       } 
     }  
    # Cruiser Division 6
    navalunit =  
    {  name     = "USN Cruiser Division 6"  
      id       = {  type = 14800 id = 4201  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 57  }  
        name  = "USS New Orleans"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 58  }  
        name  = "USS Astoria"  
        type  = heavy_cruiser  
        model = 4  
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		
       }  
      Division =  
      {  id    = {  type = 14800 id = 59  }  
        name  = "USS Minneapolis"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
      Division =  
      {  id    = {  type = 14800 id = 60  }  
		name  = "USS San Francisco"  
		type  = heavy_cruiser  
		model = 4  
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		
       }  
     }  
    # Destroyer Flotilla 2
    navalunit =  
    {  name     = "USN Destroyer Flotilla 2"  
      id       = {  type = 14800 id = 4012  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 45  }  
        name  = "USS Detroit"  
        type  = light_cruiser  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 2317  }  
        name  = "Destroyer Division 7"  
        type  = destroyer  
        model = 3  
       } 
      Division =  
      {  id    = {  type = 14800 id = 2318  }  
        name  = "Destroyer Division 8"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2291  }  
        name  = "Destroyer Division 11"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2292  }  
        name  = "Destroyer Division 12"  
        type  = destroyer  
        model = 3  
       } 
      Division =  
      {  id    = {  type = 14800 id = 4013  }  
        name  = "Destroyer Division 50"  
        type  = destroyer  
        model = 3  
       } 
     }  
    # Destroyer Flotilla 1
    navalunit =  
    {  name     = "USN Destroyer Flotilla 1"  
      id       = {  type = 14800 id = 4014  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 44  }  
        name  = "USS Raleigh"  
        type  = light_cruiser  
        model = 3  
       } 
      Division =  
      {  id    = {  type = 14800 id = 62  }  
        name  = "Destroyer Division 1"  
        type  = destroyer  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 63  }  
        name  = "Destroyer Division 2"  
        type  = destroyer  
        model = 5  
       }    
      Division =  
      {  id    = {  type = 14800 id = 2315  }  
        name  = "Destroyer Division 5"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2316  }  
        name  = "Destroyer Division 6"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2319  }  
        name  = "Destroyer Division 9"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2320  }  
        name  = "Destroyer Division 10"  
        type  = destroyer  
        model = 3  
       }  
     }  
    # Submarine Squadron 4
    navalunit =  
    {  name     = "USN Submarine Squadron 4"  
      id       = {  type = 14800 id = 4202  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 4203  }  
        name  = "Submarine Division 41"  
        type  = submarine  
        model = 2 # S-class
       }  
      Division =  
      {  id    = {  type = 14800 id = 4204  }  
        name  = "Submarine Division 42"  
        type  = submarine  
        model = 3 # Barracuda-class
       }  
      Division =  
      {  id    = {  type = 14800 id = 4205  }  
        name  = "Submarine Division 43"  
        type  = submarine  
        model = 4 # Porpoise-class 
       }  
     }  
    # Submarine Squadron 6
    navalunit =  
    {  name     = "USN Submarine Squadron 6"  
      id       = {  type = 14800 id = 4206  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 4207  }  
        name  = "Submarine Division 61"  
        type  = submarine  
        model = 5 # Tambor-class
       }  
      Division =  
      {  id    = {  type = 14800 id = 4208  }  
        name  = "Submarine Division 62"  
        type  = submarine  
        model = 5 # Tambor-class  
       }  
     }  
    # US ATLANTIC FLEET-NORFOLK, VIRGINIA
    # Battleship Division 3
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 98  }  
      name     = "USN Battleship Division 3"  
      Division =  
      {  id    = {  type = 14800 id = 99  }  
        name  = "USS New Mexico"  
        type  = battleship  
        model = 4  
       }  
      Division =  
      {  id    = {  type = 14800 id = 100  }  
        name  = "USS Mississippi"  
        type  = battleship  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 101  }  
		name  = "USS Idaho"  
		type  = battleship  
		model = 4  
		extra1 = naval_torpedoes_l
		brigade_model1 = 4	
       } 
     } 
    # Battleship Division 5
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 4209  }  
      name     = "USN Battleship Division 5"  
      Division =  
      {  id    = {  type = 14800 id = 103  }  
        name  = "USS Arkansas"  
        type  = battleship  
        model = 2 
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 104  }  
        name  = "USS New York"  
        type  = battleship  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 105  }  
		name  = "USS Texas"  
		type  = battleship  
		model = 3
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		
       } 
     } 
    # USS North Carolina
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 4210  }  
      name     = "USS North Carolina"  
      Division =  
      {  id    = {  type = 14800 id = 4023  }  
        name  = "USS North Carolina"  
        type  = battleship  
        model = 7  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
     } 
    # USS Washington
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 4211  }  
      name     = "USS Washington"  
      Division =  
      {  id    = {  type = 14800 id = 4024  }  
        name  = "USS Washington"  
        type  = battleship  
        model = 7  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
     }
    # Carrier Division 3
    navalunit =  
    {  name     = "USN Carrier Division 3"  
      id       = {  type = 14800 id = 2114  }  
      location = 1812  
      base     = 1812  
      Division =  
      {  id            = {  type = 14800 id = 115  }  
        name          = "USS Ranger"  
        type          = carrier  
        model         = 1  
        extra         = cag  
        brigade_model = 4  
       } 
      Division =  
      {  id            = {  type = 14800 id = 500  }  
        name          = "USS Yorktown"  
        type          = carrier  
        model         = 2  
        extra         = cag  
        brigade_model = 4  
       }
      Division =  
      {  id            = {  type = 14800 id = 2041  }  
        name          = "USS Wasp"  
        type          = carrier  
        model         = 2  
        extra         = CAG  
        brigade_model = 4  
       }
      Division =  
      {  id   = {  type = 14800 id = 2101  }  
        name  = "USS Patoka"  
        type  = escort_carrier  
        model = 0    
       }
     }   
    # Cruiser Division 2
    navalunit =  
    {  name     = "USN Cruiser Division 2"  
      id       = {  type = 14800 id = 2013  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 107  }  
        name  = "USS Omaha"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 108  }  
        name  = "USS Milwaukee"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 109  }  
        name  = "USS Cincinnati"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 110  }  
        name  = "USS Memphis"  
        type  = light_cruiser  
        model = 3  
       }
     }   
    # Cruiser Division 7
    navalunit =  
    {  name     = "USN Cruiser Division 7"  
      id       = {  type = 14800 id = 4212  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 112  }  
        name  = "USS Augusta"  
        type  = heavy_cruiser  
        model = 3  
		extra1 = naval_torpedoes_l
		brigade_model1 = 4			
       }  
      Division =  
      {  id    = {  type = 14800 id = 113  }  
        name  = "USS Tuscaloosa"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       } 
      Division =  
      {  id    = {  type = 14800 id = 502  }  
        name  = "USS Quincy"  
        type  = heavy_cruiser  
        model = 4
		extra1 = naval_torpedoes_l
		brigade_model1 = 4			
       }
      Division =  
      {  id    = {  type = 14800 id = 512  }  
        name  = "USS Wichita"  
        type  = heavy_cruiser  
        model = 5 
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       } 
      Division =  
      {  id    = {  type = 14800 id = 2007  }  
        name  = "USS Vincennes"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
     } 
    # Cruiser Division 8
    navalunit =  
    {  name     = "USN Cruiser Division 8"  
      id       = {  type = 14800 id = 40  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 504  }  
        name  = "USS Brooklyn"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 505  }  
        name  = "USS Philadelphia"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 506  }  
        name  = "USS Savannah"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 511  }  
        name  = "USS Nashville"  
        type  = light_cruiser  
        model = 5  
       }
     } 
    # Destroyer Flotilla 3
    navalunit =  
    {  name     = "USN Destroyer Flotilla 3"  
      id       = {  type = 14800 id = 4025  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 82  }  
        name  = "Destroyer Division 13"  
        type  = destroyer  
        model = 5  
       }   
      Division =  
      {  id    = {  type = 14800 id = 83  }  
        name  = "Destroyer Division 14"  
        type  = destroyer  
        model = 3
       } 
      Division =  
      {  id    = {  type = 14800 id = 96  }  
        name  = "Destroyer Division 17"  
        type  = destroyer  
        model = 3 
       }  
      Division =  
      {  id    = {  type = 14800 id = 116  }  
        name  = "Destroyer Division 18"  
        type  = destroyer  
        model = 5  
       } 
      Division =  
      {  id    = {  type = 14800 id = 119  }  
        name  = "Destroyer Division 21"  
        type  = destroyer  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 120  }  
        name  = "Destroyer Division 22"  
        type  = destroyer  
        model = 3  
       }  
     } 
    # Destroyer Flotilla 4
    navalunit =  
    {  name     = "USN Destroyer Flotilla 4"  
      id       = {  type = 14800 id = 4027  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 64  }  
        name  = "Destroyer Division 3"  
        type  = destroyer  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 2023  }  
        name  = "Destroyer Division 4"  
        type  = destroyer  
        model = 5  
       } 
      Division =  
      {  id    = {  type = 14800 id = 84  }  
        name  = "Destroyer Division 15"  
        type  = destroyer  
        model = 3  
       } 
      Division =  
      {  id    = {  type = 14800 id = 91  }  
        name  = "Destroyer Division 16"  
        type  = destroyer  
        model = 3  
       }    
      Division =  
      {  id    = {  type = 14800 id = 117  }  
        name  = "Destroyer Division 19"  
        type  = destroyer  
        model = 3
       }
      Division =  
      {  id    = {  type = 14800 id = 118  }  
        name  = "Destroyer Division 20"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 121  }  
        name  = "Destroyer Division 23"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 172  }  
        name  = "Destroyer Division 24"  
        type  = destroyer  
        model = 3  
       }  
     } 
    # Destroyer Flotilla 8
    navalunit =  
    {  name     = "USN Destroyer Flotilla 8"  
      id       = {  type = 14800 id = 4028  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 173  }  
        name  = "Destroyer Division 25"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 174  }  
        name  = "Destroyer Division 26"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 175  }  
        name  = "Destroyer Division 27"  
        type  = destroyer  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 2293  }  
        name  = "Destroyer Division 28"  
        type  = destroyer  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 2025  }  
        name  = "Destroyer Division 29"  
        type  = destroyer  
        model = 5  
       } 
     } 
    # Submarine Squadron 1
    navalunit =  
    {  name     = "USN Submarine Squadron 1"  
      id       = {  type = 14800 id = 4213  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 97  }  
        name  = "Submarine Division 11"  
        type  = submarine  
        model = 1 # O-class  
       }
      Division =  
      {  id    = {  type = 14800 id = 123  }  
        name  = "Submarine Division 12"  
        type  = submarine  
        model = 1 # R-class  
       }  
     } 
    # Submarine Squadron 3
    navalunit =  
    {  name     = "USN Submarine Squadron 3"  
      id       = {  type = 14800 id = 4214  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 4215  }  
        name  = "Submarine Division 31"  
        type  = submarine  
        model = 2 # S-class  
       }
      Division =  
      {  id    = {  type = 14800 id = 4216  }  
        name  = "Submarine Division 32"  
        type  = submarine  
        model = 3 # Barracuda-class  
       }  
     } 
    # Submarine Squadron 5
    navalunit =  
    {  name     = "USN Submarine Squadron 5"  
      id       = {  type = 14800 id = 4217  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 4218  }  
        name  = "Submarine Division 51"  
        type  = submarine  
        model = 2 # S-class  
       }
      Division =  
      {  id    = {  type = 14800 id = 4219  }  
        name  = "Submarine Division 52"  
        type  = submarine  
        model = 2 # S-class  
       }  
      Division =  
      {  id    = {  type = 14800 id = 4220  }  
        name  = "Submarine Division 53"  
        type  = submarine  
        model = 2 # S-class  
       }  
     } 
    # Submarine Squadron 7
    navalunit =  
    {  name     = "USN Submarine Squadron 7"  
      id       = {  type = 14800 id = 4221  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 4222  }  
        name  = "Submarine Division 71"  
        type  = submarine  
        model = 1 # R-class  
       }
      Division =  
      {  id    = {  type = 14800 id = 4223  }  
        name  = "Submarine Division 72"  
        type  = submarine  
        model = 2 # S-class  
       }  
     } 
    # OTHER
    # Training Squadron
    navalunit =  
    {  name     = "Training Squadron"  
      id       = {  type = 14800 id = 4227  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 4228  }  
        name  = "Destroyer Division 31"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 4229  }  
        name  = "Destroyer Division 32"  
        type  = destroyer  
        model = 3  
       }  
     } 
    # Fleet Train, Atlantic
    navalunit =  
    {  name     = "Fleet Train, Atlantic"  
      id       = {  type = 14800 id = 102  }  
      location = 1812  
      base     = 1812  

      Division =  
      {  id   = {  type = 14800 id = 4230  }  
        name = "Transport Division 1"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 153  }  
        name = "Transport Division 3"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 154  }  
        name = "Transport Division 5"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 156  }  
        name = "Transport Division 7"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 150  }  
        name = "Transport Division 9"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 151  }  
        name = "Transport Division 11"  
        type = transport  
		model = 2
       }  
     }  
    # Fleet Train, Pacific
    navalunit =  
    {  name     = "Fleet Train, Pacific"  
      id       = {  type = 14800 id = 111  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id   = {  type = 14800 id = 152  }  
        name = "Transport Division 2"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 143  }  
        name = "Transport Division 4"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 144  }  
        name = "Transport Division 6"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 145  }  
        name = "Transport Division 8"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id   = {  type = 14800 id = 134  }  
        name = "Transport Division 10"  
        type = transport
		model = 2
       }  
     }  
    # 1st Naval District
    navalunit =  
    {  location = 1789  
      base     = 1789  
      id       = {  type = 14800 id = 92  }  
      name     = "1st Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 135  }  
        name = "Transport Division 15"  
        type = transport  
		model = 2
       }  
     }  
    # 3rd Naval District
    navalunit =  
    {  location = 1795  
      base     = 1795  
      id       = {  type = 14800 id = 95  }  
      name     = "3rd Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 136  }  
        name = "Transport Division 17"  
        type = transport  
		model = 2
       }  
     }  
    # 4th Naval District
    navalunit =  
    {  location = 1805
      base     = 1809
      id       = {  type = 14800 id = 2322  }  
      name     = "4th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 137  }  
        name = "Transport Division 19"  
        type = transport  
		model = 2
       }  
     }  
    # 5th Naval District
    navalunit =  
    {  location = 1812
      base     = 1812
      id       = {  type = 14800 id = 706  }  
      name     = "5th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 707  }  
        name = "Transport Division 21"  
        type = transport  
		model = 2
       }  
     }  
    # 6th Naval District
    navalunit =  
    {  location = 1960
      base     = 1812
      id       = {  type = 14800 id = 708  }  
      name     = "6th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 709  }  
        name = "Transport Division 23"  
        type = transport  
		model = 2
       }  
     }  
    # 7th Naval District
    navalunit =  
    {  location = 1952
      base     = 1953
      id       = {  type = 14800 id = 710  }  
      name     = "7th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 711  }  
        name = "Transport Division 25"  
        type = transport  
		model = 2
       }  
     }  
    # 8th Naval District
    navalunit =  
    {  location = 1931
      base     = 1922
      id       = {  type = 14800 id = 712  }  
      name     = "8th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 713  }  
        name = "Transport Division 27"  
        type = transport  
		model = 2
       }  
     }  
    # 10th Naval District
    navalunit =  
    {  location = 1765
      base     = 1778
      id       = {  type = 14800 id = 714  }  
      name     = "10th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 715  }  
        name = "Transport Division 29"  
        type = transport  
		model = 2
       }  
     }  
    # 11th Naval District
    navalunit =  
    {  location = 1886  
      base     = 1886  
      id       = {  type = 14800 id = 4231  }  
      name     = "11th Naval District"  
      Division =  
      {  id    = {  type = 14800 id = 4232  }  
        name  = "Transport Division 16"  
        type  = transport
        model = 2  
       }  
      Division =  
      {  id    = {  type = 14800 id = 4233  }  
        name  = "Destroyer Division 33"  
        type  = destroyer  
        model = 3 
       }  
     }  
    # 12th Naval District
    navalunit =  
    {  location = 1889  
      base     = 1889  
      id       = {  type = 14800 id = 4234  }  
      name     = "12th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 159  }  
        name = "Transport Division 18"  
        type = transport  
		model = 2
       }  
      Division =  
      {  id    = {  type = 14800 id = 4235  }  
        name  = "Destroyer Division 30"  
        type  = destroyer  
        model = 3
       }
     }  
    # 13th Naval District
    navalunit =  
    {  location = 1874  
      base     = 1874  
      id       = {  type = 14800 id = 106  }  
      name     = "13th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 140  }  
        name = "Transport Division 20"  
        type = transport  
		model = 2
       }  
     }  
    # 14th Naval District
    navalunit =  
    {  location = 1734  
      base     = 1734  
      id       = {  type = 14800 id = 4236  }  
      name     = "14th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 138  }  
        name = "Transport Division 22"  
        type = transport  
		model = 2
       }  
     }  
    # 15th Naval District
    navalunit =  
    {  location = 889  
      base     = 889  
      id       = {  type = 14800 id = 114  }  
      name     = "15th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 141  }  
        name = "Transport Division 24"  
        type = transport  
		model = 2
       }  
     }  
    # 16th Naval District
    navalunit =  
    {  location = 1565  
      base     = 1565
      id       = {  type = 14800 id = 133  }  
      name     = "16th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 139  }  
        name = "Transport Division 26"  
        type = transport  
		model = 2
       }  
     }  

  airunit =
  { id       = { type = 14800 id = 5000 }
    name     = "First Air Force"
    location = 1789
    base     = 1789
    division =
    { id       = { type = 14800 id = 5001 }
      name     = "1st USAAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 4
    }
    division =
    { id       = { type = 14800 id = 5002 }
      name     = "6th USAAF Interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5019 }
      name     = "20th USAAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
  }
  airunit =
  { id       = { type = 14800 id = 5003 }
    name     = "Second Air Force"
    location = 1789
    base     = 1789
    division =
    { id       = { type = 14800 id = 5004 }
      name     = "2nd USAAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 4
    }
    division =
    { id       = { type = 14800 id = 5005 }
      name     = "7th USAAF Interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5006 }
      name     = "12th USAAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 6
    }
  }
  airunit =
  { id       = { type = 14800 id = 5007 }
    name     = "Third Air Force"
    location = 1812
    base     = 1812
    division =
    { id       = { type = 14800 id = 5008 }
      name     = "13th USAAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 4
    }
    division =
    { id       = { type = 14800 id = 5009 }
      name     = "9th USAAF Interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5020 }
      name     = "47th USAAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 6
    }
  }
  airunit =
  { id       = { type = 14800 id = 5010 }
    name     = "Fourth Air Force"
    location = 1565
    base     = 1565
    division =
    { id       = { type = 14800 id = 5011 }
      name     = "4th USAAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 4
    }
    division =
    { id       = { type = 14800 id = 5012 }
      name     = "10th USAAF Interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 8
    }
    division =
    { id       = { type = 14800 id = 5021 }
      name     = "57th USAAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 6
    }
  }
  airunit =
  { id       = { type = 14800 id = 5022 }
    name     = "14th USAAF Tactical Bomb. Wing"
    location = 1795
    base     = 1795
    division =
    { id       = { type = 14800 id = 5023 }
      name     = "14th USAAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
  }
  airunit =
  { id       = { type = 14800 id = 5013 }
    name     = "Hawaiian Air Department"
    location = 1734
    base     = 1734
    division =
    { id       = { type = 14800 id = 5014 }
      name     = "18th USAAF Bombardment Wing"
      strength = 40
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5015 }
      name     = "14th USAAF Pursuit Wing"
      strength = 80
      type     = multi_role
      model    = 6
    }
  }
  airunit =
  { id       = { type = 14800 id = 5016 }
    name     = "Transport Command"
    location = 1832
    base     = 1832
    division =
    { id       = { type = 14800 id = 5018 }
      name     = "50th USAAF Troop Carrier Wing"
      strength = 100
      type     = transport_plane
      model    = 1
    }
  }

   division_development =    
   {  name  = "USS Hornet"  
      type  = carrier  
      model = 2  
      cost  = 0.5  
      id    = {  type = 14800 id = 3000  }  
      date  = {  year = 1941 month = october day = 20  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS Essex"  
      type  = carrier  
      model = 4  
      cost  = 0.5  
      id    = {  type = 14800 id = 3009  }  
      date  = {  year = 1942 month = december day = 30  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS South Dakota"  
      type  = battleship  
      model = 7  
      cost  = 0.5  
      id    = {  type = 14800 id = 3001  }  
      date  = {  year = 1942 month = march day = 20  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }
   division_development =    
   {  name  = "USS Indiana"  
      type  = battleship  
      model = 7  
      cost  = 0.5  
      id    = {  type = 14800 id = 3002  }  
      date  = {  year = 1942 month = april day = 30  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     } 
   division_development =    
   {  name  = "USS Massachusetts"  
      type  = battleship  
      model = 7  
      cost  = 0.5  
      id    = {  type = 14800 id = 3003  }  
      date  = {  year = 1942 month = may day = 12  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }
   division_development =    
   {  name  = "USS Alabama"  
      type  = battleship  
      model = 7  
      cost  = 0.5  
      id    = {  type = 14800 id = 3004  }  
      date  = {  year = 1942 month = august day = 16  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS Iowa"  
      type  = battleship  
      model = 8  
      cost  = 0.5  
      id    = {  type = 14800 id = 3005  }  
      date  = {  year = 1943 month = february day = 22  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS New Jersey"  
      type  = battleship  
      model = 8  
      cost  = 0.5  
      id    = {  type = 14800 id = 3006  }  
      date  = {  year = 1943 month = may day = 23  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS Missouri"  
      type  = battleship  
      model = 8  
      cost  = 0.5  
      id    = {  type = 14800 id = 3007  }  
      date  = {  year = 1944 month = june day = 11  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS Wisconsin"  
      type  = battleship  
      model = 8  
      cost  = 0.5  
      id    = {  type = 14800 id = 3008  }  
      date  = {  year = 1944 month = april day = 16  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS Atlanta"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 3010  }  
      date  = {  year = 1941 month = december day = 24  }    
     }  
   division_development =    
   {  name  = "USS San Diego"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 3011  }  
      date  = {  year = 1942 month = january day = 10  }    
     }        
   division_development =    
   {  name  = "USS Juneau"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 3016  }  
      date  = {  year = 1942 month = february day = 14  }    
     }      
   division_development =    
   {  name  = "USS San Juan"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 3017  }  
      date  = {  year = 1942 month = february day = 28  }    
     }      
   division_development =    
   {  name  = "USS Cleveland"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3018  }  
      date  = {  year = 1942 month = june day = 15  }    
     }      
   division_development =    
   {  name  = "USS Columbia"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3019  }  
      date  = {  year = 1942 month = july day = 29  }    
     }      
   division_development =    
   {  name  = "USS Montpelier"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3020  }  
      date  = {  year = 1942 month = september day = 9  }    
     }      
   division_development =    
   {  name  = "USS Denver"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3021  }  
      date  = {  year = 1942 month = october day = 15  }    
     }      
   division_development =    
   {  name  = "USS Santa Fe"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3022  }  
      date  = {  year = 1942 month = november day = 24  }    
     }      
   division_development =    
   {  name  = "USS Amsterdam"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3023  }  
      date  = {  year = 1943 month = january day = 14  }    
     }      
   division_development =    
   {  name  = "USS Tallahassee"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3024  }  
      date  = {  year = 1943 month = february day = 25  }    
     }      
   division_development =    
   {  name  = "USS Birmingham"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3025  }  
      date  = {  year = 1943 month = january day = 29  }    
     }      
   division_development =    
   {  name  = "USS Mobile"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3026  }  
      date  = {  year = 1943 month = march day = 24  }    
     }      
   division_development =    
   {  name  = "USS Baltimore"  
      type  = heavy_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3027  }  
      date  = {  year = 1943 month = april day = 15  }    
     }      
   division_development =    
   {  name  = "USS Pocomoke"  
      type  = escort_carrier  
      model = 0  
      cost  = 0.3  
      id    = {  type = 14800 id = 3012  }  
      date  = {  year = 1941 month = july day = 18  }    
     }  
   division_development =    
   {  name  = "USS Chandeleur"  
      type  = escort_carrier  
      model = 0  
      cost  = 0.3  
      id    = {  type = 14800 id = 3014  }  
      date  = {  year = 1942 month = november day = 19  }    
     }  
   division_development =    
   {  name  = "USS Tangier"  
      type  = escort_carrier  
      model = 0  
      cost  = 0.3  
      id    = {  type = 14800 id = 3015  }  
      date  = {  year = 1941 month = august day = 25  }    
     }  
   division_development =    
   {  name  = "5th Armored 'Victory' Div."  
      type  = armor  
      model = 1  
      cost  = 0.1  
      id    = {  type = 14800 id = 3013  }  
      date  = {  year = 1941 month = october day = 10  }    
     }  
   division_development =    
   {  name  = "25th 'Tropic Lightning' Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3029  }  
      date  = {  year = 1941 month = october day = 1  }    
     }  
   }  
  
