 
 ############################## 
 # Country definition for BEL # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = BEL 
 
	ai = "bel_1940.ai"
   capital                = 116 
   manpower               = 1 
   # Resource Reserves 
energy                 = 2040
metal                  = 1020
rare_materials         = 510
   oil                    = 500 
   supplies               = 500 
   money                  = 20 
   transports             = 100 
   escorts                = 20 
   diplomacy = 
   {  relation = {  tag = AST value = 75  } 
     relation = {  tag = CAN value = 150  } 
     relation = {  tag = DEN value = 100  } 
     relation = {  tag = ENG value = 150  } 
     relation = {  tag = FIN value = 100  } 
     relation = {  tag = FRA value = 120  } 
     relation = {  tag = GER value = -200  } 
     relation = {  tag = HOL value = 150  } 
     relation = {  tag = IRE value = 75  } 
     relation = {  tag = ITA value = -5  } 
     relation = {  tag = JAP value = -25  } 
     relation = {  tag = LUX value = 200  } 
     relation = {  tag = NOR value = 100  } 
     relation = {  tag = NZL value = 20  } 
     relation = {  tag = POR value = -20  } 
     relation = {  tag = SAF value = 35  } 
     relation = {  tag = SWE value = 100  } 
     relation = {  tag = U05 value = 150  }
     relation = {  tag = USA value = 75  } 
    } 
   SpyInfo                = {  country = "BEL" NumberOfSpies = 6  } 
   nationalprovinces      = {  114 115 116 112 113 108 117 111 110 } 
   ownedprovinces         = {  114 115 116 112 113 108 117 111 894 901 904 903 905 906 902 898 897 899 846 847 110  } 
   controlledprovinces    = {  114 115 116 112 113 108 117 111 894 901 904 903 905 906 902 898 897 899 846 847 110  } 
   claimedprovinces       = {  894 901 904 903 905 906 902 898 897 899 846 847 } #Belgian Congo
   
	# Western Minor Tech '40
	# Group C 1940 techs 
	# ###################### 
	techapps               = { 
	# Infantry Division  
	1010  1020 1030 1040 1050 1060 1070 1080 1090 1100
	# Mountain Division 
	1160  1170 1180 1190 1200 1210 1220 1230 1240 1250
	# Motorised Inf
	1396
	# Supply/Logistics
	1910 1920 1930 1940 1950 1960 1970 1980 1990
	# Cavalry Division  
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380
	# Engineers
	1830 1840 1850 1860

	# Armoured Car  
	2860 2870 2880 2020 2150
	# Tanks
	7600 7610 2620 2010 2630 2640 2646 2650
	# Field Artillery 
	2290 2300 2310 2900 2910 2920 2930 2940
	# Anti-tank Artillery
	2400
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460
	# Anti-Air Artillery Brigade 
	2810 2820 2510 2520

	# Destroyers 
	3010
	# Torpedo & ASW 18
	3720 3730 3900
	# Troopships
	3810 3820
	
	# Interceptors
	4500 4510 4520 4530 4540 4550 4010 4020
	# Tactical Bomber 
	4600 4610 4620 4630 4120 4130
	
	# Computers & cryptography
	5310 54010 54020 54030 5316 5326 5327 5350
	# Oil
	5190
	# Medicine
	5600 5610 5620 5630 5640
	# Agriculture 
	5700 5710 5010 5020
	# Manufacturing
	5810 5820 5050 5830 5060
	# Construction Engineering 
	5800 5080 5090
	
	# Hospital System 
	14000 14010 14020 14030
	# Great War Land Doctrines
	6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
	# Defensive Focus Grand Battleplan Path (FRA / UK)
	6560 6030 6110
	#Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 
	9040 9090
	# Naval Doctrines
	8010 8020 8040 8050 
	}
	
inventions = { 3000027 } 
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 9 
     political_left    = 3 
     free_market       = 9 
     freedom           = 10 
     professional_army = 6 
     defense_lobby     = 4 
     interventionism   = 3 
    } 
   headofstate            = {  type = 9 id = 70087  } 
   headofgovernment       = {  type = 9 id = 70017  } 
   foreignminister        = {  type = 9 id = 70027  } 
   armamentminister       = {  type = 9 id = 70038  } 
   ministerofsecurity     = {  type = 9 id = 70053  } 
   ministerofintelligence = {  type = 9 id = 70063  } 
   chiefofstaff           = {  type = 9 id = 70074  } 
   chiefofarmy            = {  type = 9 id = 70081  } 
   chiefofnavy            = {  type = 9 id = 70009  } 
   chiefofair             = {  type = 9 id = 70085  } 
   dormant_ministers      = {  70002 70003 70007 70025 70033 70050 70089 70092 70097 70098 70099 70100  }
   landunit = 
   { id       = {  type = 11500 id = 1  } 
     location = 116 
     name     = "Ière Corps" 
     division = 
     { id    = {  type = 11500 id = 2  } 
       name  = "1ère Division d'Infanterie" 
       strength = 50 
       type  = infantry 
       model = 8
       extra = artillery 
       brigade_model = 5
      }
     division = 
     { id    = {  type = 11500 id = 3  } 
       name  = "4ème Division d'Infanterie" 
       strength = 50 
       type  = infantry 
       model = 8
       extra = engineer 
       brigade_model = 3
      }
     Division = 
     {  id    = {  type = 11500 id = 4  } 
       name  = "7ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
    } 
   landunit = 
   {  id       = {  type = 11500 id = 5  } 
     location = 112 
     name     = "IIème Corps" 
     Division = 
     {  id    = {  type = 11500 id = 6  } 
       name  = "6ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      }
     Division = 
     {  id    = {  type = 11500 id = 7  } 
       name  = "11ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      }
     Division = 
     {  id    = {  type = 11500 id = 8  } 
       name  = "14ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      }
    } 
   landunit = 
   {  id       = {  type = 11500 id = 9  } 
     location = 116 
     name     = "IIIème Corps" 
     Division = 
     {  id    = {  type = 11500 id = 10  } 
       name  = "2ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
     Division = 
     {  id    = {  type = 11500 id = 11  } 
       name  = "3ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
     Division = 
     {  id    = {  type = 11500 id = 12  } 
       name  = "1ère Chasseurs à Pied" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
    } 
   landunit = 
   {  id       = {  type = 11500 id = 13  } 
     location = 117 
     name     = "IVème Armée"  
     Division = 
     {  id    = {  type = 11500 id = 14  } 
       name  = "9ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
     Division = 
     {  id    = {  type = 11500 id = 15  } 
       name  = "15ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
     Division = 
     {  id    = {  type = 11500 id = 16  } 
       name  = "18ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
    } 
   landunit = 
   {  id       = {  type = 11500 id = 17  } 
     location = 111 
     name     = "Vème Corps" 
     Division = 
     {  id    = {  type = 11500 id = 18  } 
       name  = "12ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
     Division = 
     {  id    = {  type = 11500 id = 19  } 
       name  = "13ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
     Division = 
     {  id    = {  type = 11500 id = 20  } 
       name  = "17ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
    } 
   landunit = 
   {  id       = {  type = 11500 id = 21  } 
     location = 108 
     name     = "VIème Korps" 
     Division = 
     {  id    = {  type = 11500 id = 22  } 
       name  = "5ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
     Division = 
     {  id    = {  type = 11500 id = 23  } 
       name  = "10ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
     Division = 
     {  id    = {  type = 11500 id = 24  } 
       name  = "16ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
    } 
   landunit = 
   {  id       = {  type = 11500 id = 25  } 
     location = 114 
     name     = "VIIème Armée" 
     Division = 
     {  id    = {  type = 11500 id = 26  } 
       name  = "1ère Chasseurs Ardennais" 
	   strength = 50 
       type  = bergsjaeger
       model = 6 
       extra = artillery 
	   brigade_model = 5
      } 
     Division = 
     {  id    = {  type = 11500 id = 27  } 
       name  = "8ème Division d'Infanterie" 
	   strength = 50 
       type  = infantry 
       model = 8
      } 
    } 
   landunit = 
   {  id       = {  type = 11500 id = 28  } 
     location = 116 
     name     = "Armée de Lancers" 
     Division = 
     {  id    = {  type = 11500 id = 29  } 
       name  = "1ère Division de Guides" 
	   strength = 50 
       type  = cavalry 
       model = 8 
      } 
     Division = 
     {  id    = {  type = 11500 id = 30  } 
       name  = "2de Gidsen" 
	   strength = 50 
       type  = cavalry 
       model = 8 
      } 
    } 
   landunit = 
   {  id       = {  type = 11500 id = 31  } 
     location = 894 
     name     = "Garde Royale Coloniale" 
     Division = 
     {  id    = {  type = 11500 id = 32  } 
       name  = "1ère Garde Coloniale" 
	   strength = 25 
       type  = infantry 
       model = 6
      } 
    } 
	navalunit = { 
		id = { type = 11500 id = 33 } 
		name = "1ste Transportatie Smaldeel" 
		location = 114 
		base = 114 
		division = { 
			id = { type = 11500 id = 34 } 
			name = "1ère Transporte Naval" 
			type = transport model = 1 
			} 
		division = { 
			id = { type = 11500 id = 36 } 
			name = "2de Smaldeel" 
			type = transport model = 1 
			} 
		division = { 
			id = { type = 11500 id = 2322 } 
			name = "1ère Flottille de Contre-Torpilleur" 
			type = destroyer 
			} 
		division = { 
			id = { type = 11500 id = 2323 } 
			name = "2de Flotielje Torpedoboten" 
			type = destroyer 
			} 
		} 
  } 