 
 ############################## 
 # Country definition for LIT # 
 ############################## 
   
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = LIT 
   capital                = 258 
   manpower               = 0 
   # Resource Reserves 
energy                 = 480
metal                  = 240
rare_materials         = 120
   transports = 100
   oil                    = 500 
   supplies               = 500 
   money                  = 10 
      
   diplomacy = 
   {  relation = {  tag = ENG value = 65  } 
     relation = 
     {  tag        = EST 
       value      = 40 
       guaranteed = {  day = 12 month = september year = 1934  } 
      } 
     relation = {  tag = FIN value = 80  } 
     relation = {  tag = CZE value = 65  }
     relation = {  tag = USA value = 65  }
     relation = {  tag = SWE value = 75  }
     relation = {  tag = DEN value = 75  }
     relation = {  tag = FRA value = 65  } 
     relation = {  tag = GER value = 10  } 
     relation = 
     {  tag        = LAT 
       value      = 40 
       guaranteed = {  day = 12 month = september year = 1934  } 
      }  
     relation = {  tag = SOV value = 75  } 
    } 
   SpyInfo                = {  country = "LIT" NumberOfSpies = 3  } 
   nationalprovinces      = {  259 262 263 255 260 261 258 252 } 
   ownedprovinces         = {  259 262 263 260 258 } 
   controlledprovinces    = {  259 262 263 260 258 } 
   # Eastern Minor Tech '36 
   # Group D 1936 techs 
   # ###################### 
   # GW fighter 
   techapps               = {  
#Interwar Fighter  
4500 4510 4520 4530 4540 4550 4010
#Basic Armoured Car  
2860 2870 2880 2020
#Great War Heavy Field Artillery 
2290 2300 2310 2900
#SW Tank 
7600 7610
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 1070 1080
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340
#Early Mountain Division 
1160  1170 1180 1190 1200 1210
#Engineers
1830 1840 1850 
#Early Static Anti-Air Artillery 
2800 2450 21180
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Medicine
5600 5610
#Scientific Management
5810
#Troopships
3810
#Modern Agriculture  
5700 5710 5010
#Improved Construction Engineering 
5800 5080 

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
# Land Doctrine WW1 - Entente Line (default)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
} 
inventions = { 3000027 }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 4 
     political_left    = 2 
     freedom           = 5 
     free_market       = 5 
     professional_army = 5 
     defense_lobby     = 5 
     interventionism   = 5 
    } 
	peacetime_ic_mod       = 0.6
   headofstate            = {  type = 9 id = 140001  } 
   headofgovernment       = {  type = 9 id = 140025  } 
   foreignminister        = {  type = 9 id = 140037  } 
   armamentminister       = {  type = 9 id = 140052  } 
   ministerofsecurity     = {  type = 9 id = 140066  } 
   ministerofintelligence = {  type = 9 id = 140082  } 
   chiefofstaff           = {  type = 9 id = 140094  } 
   chiefofarmy            = {  type = 9 id = 140102  } 
   chiefofnavy            = {  type = 9 id = 140009  } 
   chiefofair             = {  type = 9 id = 140010  } 
   # Firepower 
   # ########################################### 
   # ###Lithuanian Army######################### 
   # ########################################### 
   landunit = 
   {  id       = {  type = 26500 id = 1  } 
     location = 262 
     name     = "Lietuvos kariuomene" 
     Division = 
     {  id       = {  type = 26500 id = 2  } 
       name     = "I Pestininku divizija" 
       type     = infantry 
	   model = 7
       strength = 70 
      } 
     Division = 
     {  id       = {  type = 26500 id = 3  } 
       name     = "II Pestininku Divizija" 
       type     = infantry 
	   model = 7
       extra    = artillery 
	   brigade_model = 6
       strength = 70 
      } 
     Division = 
     {  id       = {  type = 26500 id = 4  } 
       name     = "III Pestininku Divizija" 
       type     = infantry 
       strength = 70
	   model = 7
      } 
     Division = 
     {  id       = {  type = 26500 id = 9  } 
       name     = "Sauliu sajunga" 
       type     = militia 
	   model = 4
       strength = 100 
      } 
    }  

landunit = 
   {  id       = {  type = 26500 id = 10  } 
     location = 259 
     name     = "Mobilizacinis rezervas" 
     Division = 
     {  id       = {  type = 26500 id = 11  } 
       name     = "IV Pestininku divizija" 
       type     = infantry 
	   model = 7
       strength = 5 
      } 
Division = 
     {  id       = {  type = 26500 id = 12  } 
       name     = "V Pestininku divizija" 
       type     = infantry 
	   model = 7
       strength = 5 
      } 
    }  

airunit = 
   {  id       = {  type = 26500 id = 5  } 
     location = 262 
     base     = 262 
     name     = "Lietuvos Karines oro pajegos" 
     Division = 
     {  id       = {  type = 26500 id = 6  } 
       name     = "I Naikintuvu Aviacijos Grupe" 
       type     = interceptor 
       model    = 6
       strength = 45 
      } 
    }
  } 
 
