 
 ############################## 
 # Country definition for SPA # 
 ############################## 
   
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = SPA
    regular_id             = SPR
   intrinsic_gov_type     = fascist 
   
   ai = "spa_1940.ai"
   manpower               = 250 
   # Resource Reserves 
energy                 = 2280
metal                  = 1140
rare_materials         = 570
   oil                    = 500 
   supplies               = 500 
   money                  = 20 
   dissent                = 30 
   capital                = 460 
   belligerence           = 5
   transports             = 80 
   escorts                = 27 
   # Gibralter claim 
   diplomacy = 
   {  relation = {  tag = ENG value = -65  } 
     relation = {  tag = FIN value = 35  } 
     relation = {  tag = FRA value = -65  } 
     relation = {  tag = GER value = 50  } 
     relation = {  tag = IRE value = 50  } 
     relation = {  tag = ITA value = 50  } 
     relation = {  tag = POR value = -50  } 
     relation = {  tag = SOV value = -10  } 
    } 
   SpyInfo                = {  country = "SPA" NumberOfSpies = 7  } 
   # Spanish Guinea 
   nationalprovinces      = {  444 451 441 453 466 456 460 457 458 472 474 471 470 467 463 468 464 461  
                              348 440 438 436 442 443 475 437 439 452 447 990 991 469 
            455 448 449  446 462 445 459 473 465 454     450                         } 
   ownedprovinces         = {  441  444  451  466  453  460  458  472  474  471  470  467  463  468  464  457  461  456  442  443  436  438  440  475  
                              437  439  452  447  990  991   469   715      987  988  913 
               446 
               449 448 455 454 465 473 
               462 459 445 450 
               989   716 916    
                             } 
   # Spanish Guinea 
   controlledprovinces    = {  441  444  451  466  453  460  458  472  474  471  470  467  463  468  464  457  461  456  442  443  436  438  440  475  
                              437  439  452  447  990  991      715      987  988  913 
               446 469 450 
               449 448 455 454 465 473 
               462 459 445  
               989   716 916   
                             }
	claimedprovinces = {
		715 716 987 988 989 913 916
	}
   # Semi-Major Tech '36 
   # Group C 1936 techs 
   # ###################### 
   techapps               = { 
#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Interwar Bomber 
4600 4610 4620 4630 4120
#Basic Armoured Car  
2860 2870 2880 2020
#Tankette 
7600 7610 2620 2010 2630 2640
#Early Anti-Tank Artillery 
#2400
#Great War Heavy Field Artillery 
2290 2300 2310 
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Early Bomber 
4600 4610 4620 4630 4120 4130
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Naval Infantry
#1560 1570 1580
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#Engineers
1830 1840 1850 1860
#Early Battleship 
3410 3420 3430 3440 3450 3456 3460 3470
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250
#Short Range Submarine 
3610 3620 3630
#Interwar Light Cruiser 
3110 3120 3130 3140
#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Modern Agriculture  
5700 5710 5010
#Computers & cryptografi
5310 54010 54020 54030 5316 5326
#Manufactoring
5810 5820 5050 5830
#Improved Construction Engineering 
5800 5080 5090 
#Basic Oil Refining 
##5190 
#Multirole fighter
4300 4310 4320 4330
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810
#Medicine
5600 5610 5620 
#Improved Great War Hospital System
14000 14010

# WWI Land Doctrines - Entente line: eng fra ita usa bel hol jap
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910 #Landdoctrine ww2 - none?
#Naval Doctrines
8010 8020 8040 8050 
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
} 
inventions = { 3000027 }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 3 
     political_left    = 4 
     freedom           = 4 
     free_market       = 4 
     professional_army = 4 
     defense_lobby     = 5 
     interventionism   = 3 
    }
   headofstate            = {  type = 9 id = 35011  } 
   headofgovernment       = {  type = 9 id = 35016  } 
   foreignminister        = {  type = 9 id = 35023  } 
   armamentminister       = {  type = 9 id = 35052  } 
   ministerofsecurity     = {  type = 9 id = 35078  } 
   ministerofintelligence = {  type = 9 id = 35101  } 
   chiefofstaff           = {  type = 9 id = 35117  } 
   chiefofarmy            = {  type = 9 id = 35136  } 
   chiefofnavy            = {  type = 9 id = 35147  } 
   chiefofair             = {  type = 9 id = 35160  }
   dormant_ministers      = {  35001 35003 35008 35009 35010 35014 35015 35020 35048 35058 35064 35096 35121 35122 35131 35137 35144 35146 35159 35180  } 
   dormant_leaders        = {  35014 35015 35017 35028 35056 35067 35076 35093 35094 35095  }
   # Spanish Troops
   landunit = 
   {  id       = {  type = 25000 id = 5  } 
     location = 472 
     name     = "Región de Guadarrama" 
     Division = 
     {  id   = {  type = 25000 id = 1000  } 
       name = "11a División de Infantería" 
       type = infantry 
	   model      = 9
       extra = artillery
       brigade_model = 3
       strength = 70
      }
     Division = 
     {  id   = {  type = 25000 id = 1001  } 
       name = "12a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1002  } 
       name = "13a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1003  } 
     location = 466 
     name     = "Región de Andalucía" 
     Division = 
     {  id   = {  type = 25000 id = 1004  } 
       name = "21a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1005  } 
       name = "22a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1006  } 
       name = "23a División de Infantería" 
       type = infantry 
	   model      = 9
       extra = artillery
       brigade_model = 3
       strength = 70
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1007  } 
     location = 463 
     name     = "Región del Túria" 
     Division = 
     {  id   = {  type = 25000 id = 1008  } 
       name = "31a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1009  } 
       name = "32a División de Infantería" 
       type = infantry 
	   model      = 9
       extra = artillery
       brigade_model = 3
       strength = 70
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1010  } 
     location = 442 
     name     = "Región de Urgel" 
     Division = 
     {  id   = {  type = 25000 id = 1011  } 
       name = "41a División de Infantería" 
       type = infantry 
	   model      = 9
       strength = 70
      }
     Division = 
     {  id   = {  type = 25000 id = 1012  } 
       name = "42a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1013  } 
       name = "43a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1014  } 
     location = 436 
     name     = "Región de Aragón" 
     Division = 
     {  id   = {  type = 25000 id = 1015  } 
       name = "51a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1016  } 
       name = "52a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1017  } 
     location = 446 
     name     = "Región de Navarra" 
     Division = 
     {  id   = {  type = 25000 id = 1018  } 
       name = "61a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1019  } 
       name = "62a División de Infantería" 
       type = infantry 
	   model      = 7
       strength = 60
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1020  } 
     location = 460 
     name     = "Región de Castilla" 
     Division = 
     {  id   = {  type = 25000 id = 1021  } 
       name = "71a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1022  } 
       name = "72a División de Infantería" 
       type = infantry 
	   model      = 7
       strength = 60
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1023  } 
     location = 441 
     name     = "Región de Galicia" 
     Division = 
     {  id   = {  type = 25000 id = 1024  } 
       name = "81a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1025  } 
       name = "82a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1026  } 
     location = 715 
     name     = "Región de Marruecos" 
     Division = 
     {  id   = {  type = 25000 id = 1027  } 
       name = "91a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1028  } 
       name = "92a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1029  } 
       name = "93a División de Infantería" 
       type = infantry 
	   model      = 8
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1030  } 
       name = "Tercios de la Legión" 
       type = infantry 
	   model      = 7
       extra = artillery
       brigade_model = 3
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1031  } 
       name = "Fuerzas Indígenas" 
       type = infantry 
	   model      = 7
       strength = 50
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 1032  } 
     location = 447 
     name     = "Región del Maestrazgo" 
     Division = 
     {  id   = {  type = 25000 id = 1033  } 
       name = "101a División de Infantería" 
       type = infantry 
	   model      = 7
       strength = 60
      }
     Division = 
     {  id   = {  type = 25000 id = 1034  } 
       name = "102a División de Infantería" 
       type = infantry 
	   model      = 7
       strength = 60
      }
    }
   landunit = 
   {  id       = {  type = 25000 id = 19  } 
     location = 475 
     name     = "Comandancia de Baleares" 
     Division = 
     {  id       = {  type = 25000 id = 20  } 
       name     = "Comandancia de Baleares" 
       type     = infantry 
	   model      = 7
       strength = 30 
      } 
    } 
   landunit = 
   {  id       = {  type = 25000 id = 21  } 
     location = 990 
     name     = "Comandancia de Canarias" 
     Division = 
     {  id       = {  type = 25000 id = 22  } 
       name     = "Comandancia de Canarias" 
       type     = infantry 
	   model      = 7
       strength = 30 
      } 
    } 
   landunit = 
   {  id       = {  type = 25000 id = 1035  } 
     location = 460 
     name     = "Región del Maestrazgo" 
     Division = 
     {  id   = {  type = 25000 id = 1036  } 
       name = "1a División de Caballería" 
       type = cavalry 
	   model      = 9
      }
     Division = 
     {  id   = {  type = 25000 id = 1037  } 
       name = "1a División Blindada 'Brunete'" 
       type = armor 
	   model      = 0
      }
    }

   # Some naval units were clearly outdated or in bad fighting shape. Strength has been reduced in those cases. 
	navalunit = { 
		id = { type = 25000 id = 30 } 
		name = "Armada Colonial" 
		location = 988 
		base = 988 
		division = { 
			id = { type = 25000 id = 31 } 
			name = "ARNE Navarra" 
			type = light_cruiser 
			model = 3 
			strength = 60 
			} 
		division = { 
			id = { type = 25000 id = 32 } 
			name = "1a Flotilla de Destructores" 
			type = destroyer 
			model = 2 
			} 
		} 
	navalunit = { 
		id = { type = 25000 id = 33 } 
		name = "Grupo Méndez Núñez" 
		location = 988 
		base = 988 
		division = { 
			id = { type = 25000 id = 34 } 
			name = "ARNE Méndez Núñez" 
			type = light_cruiser 
			model = 3 
			} 
		} 
	navalunit = { 
		id = { type = 25000 id = 35 } 
		name = "Escuadrón de Batalla" 
		location = 436 
		base = 436 
		division = { 
			id = { type = 25000 id = 38 } 
			name = "ARNE Miguel de Cervantes" 
			type = light_cruiser 
			model = 3 
			}
		division = { 
			id = { type = 25000 id = 39 } 
			name = "ARNE Almirante Cervera" 
			type = light_cruiser 
			model = 3 
			}
		division = { 
			id = { type = 25000 id = 42 } 
			name = "Flotilla Villalpando" 
			type = transport model = 1 
			} 
		division = { 
			id = { type = 25000 id = 43 } 
			name = "Flotilla Benavende" 
			type = transport model = 1 
			} 
		division = { 
			id = { type = 25000 id = 40 } 
			name = "2a Flotilla de Destructores" 
			type = destroyer 
			} 
		division = { 
			id = { type = 25000 id = 41 } 
			name = "3a Flotilla de Destructores" 
			type = destroyer 
			} 
		} 
	navalunit = { 
		id = { type = 25000 id = 44 } 
		name = "Base Naval Cádiz" 
		location = 473 
		base = 473 
		division = { 
			id = { type = 25000 id = 45 } 
			name = "5a Flotilla de Destructores" 
			type = destroyer 
			model = 1 
			} 
		division = { 
			id = { type = 25000 id = 47 } 
			name = "Flotilla Sanabria" 
			type = transport model = 1 
			} 
		division = { 
			id = { type = 25000 id = 48 } 
			name = "Flotilla Peña Mira" 
			type = transport model = 1 
			} 
		division = { 
			id = { type = 25000 id = 2314 } 
			name = "4a Flotilla de Destructores" 
			type = destroyer 
			} 
		} 
	navalunit = { 
		id = { type = 25000 id = 49 } 
		name = "1a Flotilla de Submarinos" 
		location = 475 
		base = 475 
		division = { 
			id = { type = 25000 id = 50 } 
			name = "1a Flotilla de Submarinos" 
			type = submarine 
			model = 2 
			}  
		}     
	navalunit = { 
		id = { type = 25000 id = 1946 } 
		name = "Base Naval Ferrol" 
		location = 441 
		base = 441   
		division = { 
			id = { type = 25000 id = 54 } 
			name = "ARNE Galicia" 
			type = light_cruiser 
			model = 3 
			}
		division = { 
			id = { type = 25000 id = 500 } 
			name = "ARNE Canarias" 
			type = heavy_cruiser 
			model = 4 
			}
		division = { 
			id = { type = 25000 id = 501 } 
			name = "Flotilla Alcafices" 
			type = transport model = 1 
			}
		division = { 
			id = { type = 25000 id = 502 } 
			name = "Flotilla Valderas" 
			type = transport model = 1 
			}  
		}
   airunit = 
   {  location = 441 
     base     = 441 
     id       = {  type = 25000 id = 100  } 
     name     = "Región Pirineos" 
     Division = 
     {  id       = {  type = 25000 id = 101  } 
       name     = "FAN 1-G-20 de Bombardeo" 
       strength = 100 
       type     = tactical_bomber
		model    = 5  
      } 
     Division = 
     {  id       = {  type = 25000 id = 102  } 
       name     = "FAN 1-G-5 de Caza" 
       strength = 30 
       type     = interceptor 
	   model    = 7
      } 
    }
   airunit = 
   {  location = 474 
     base     = 474 
     id       = {  type = 25000 id = 103  } 
     name     = "Región Estrecho" 
     Division = 
     {  id       = {  type = 25000 id = 104  } 
       name     = "FAN 2-G-20 de Bombardeo" 
       strength = 50 
       type     = tactical_bomber
		model    = 5  
      } 
     Division = 
     {  id       = {  type = 25000 id = 105  } 
       name     = "FAN 2-G-5 de Caza" 
       strength = 100 
       type     = interceptor 
	   model    = 7
      } 
    }
   airunit = 
   {  location = 436 
     base     = 436 
     id       = {  type = 25000 id = 106  } 
     name     = "Región Este" 
     Division = 
     {  id       = {  type = 25000 id = 107  } 
       name     = "FAN 3-G-20 de Bombardeo" 
       strength = 50 
       type     = tactical_bomber
		model    = 5  
      } 
     Division = 
     {  id       = {  type = 25000 id = 108  } 
       name     = "FAN 3-G-5 de Caza" 
       strength = 75 
       type     = interceptor 
	   model    = 7
      } 
    }
   airunit = 
   {  location = 988 
     base     = 988 
     id       = {  type = 25000 id = 109  } 
     name     = "Fuerzas Aéreas Africanas" 
     Division = 
     {  id       = {  type = 25000 id = 110  } 
       name     = "FAN 1-G-10 de Cooperación" 
       strength = 30 
       type     = cas
		model    = 1  
      } 
     Division = 
     {  id       = {  type = 25000 id = 111  } 
       name     = "FAN 4-G-5 de Caza" 
       strength = 30 
       type     = interceptor 
	   model    = 7
      } 
    }
   airunit = 
   {  location = 460 
     base     = 460 
     id       = {  type = 25000 id = 112  } 
     name     = "Región Central" 
     Division = 
     {  id       = {  type = 25000 id = 113  } 
       name     = "FAN 1-G-40 Estratégico" 
       strength = 50 
       type     = strategic_bomber
		model    = 2  
      } 
     Division = 
     {  id       = {  type = 25000 id = 114  } 
       name     = "FAN 5-G-5 de Caza" 
       strength = 100 
       type     = interceptor 
	   model    = 7
      } 
    }
   airunit = 
   {  location = 990 
     base     = 990 
     id       = {  type = 25000 id = 115  } 
     name     = "Región Canarias"  
     Division = 
     {  id       = {  type = 25000 id = 116  } 
       name     = "FAN 6-G-5 de Caza" 
       strength = 30 
       type     = interceptor 
	   model    = 7
      } 
    }
   airunit = 
   {  location = 441 
     base     = 441 
     id       = {  type = 25000 id = 117  } 
     name     = "Región Atlántica" 
     Division = 
     {  id       = {  type = 25000 id = 118  } 
       name     = "FAN 2-G-40 Estratégico" 
       strength = 30 
       type     = strategic_bomber
		model    = 2  
      } 
     Division = 
     {  id       = {  type = 25000 id = 119  } 
       name     = "FAN 7-G-5 de Caza" 
       strength = 50 
       type     = interceptor 
	   model    = 7
      } 
    } 
  } 
 
