 
 ############################## 
 # Country definition for the British Raj # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = U02  
   regular_id             = IND 
   puppet                 = ENG 
   capital                = 1459 
   manpower               = 508 
   dissent = 9
   
   
   relative_manpower = 0.6000 
   # Resource Reserves 
energy                 = 5520
metal                  = 2760
rare_materials         = 1380
   oil                    = 500 
   supplies               = 500 
   money                  = 70 
   transports             = 200 
   escorts                = 20 
  
   
   diplomacy = 
   {   
  relation = {  tag = ENG value = 50 access = yes  }  
    } 
   nationalprovinces      = {
  #Malaysia                 
  1439 1445 1442 1450 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1413 1418 1443 1421 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529    } 
   ownedprovinces         = {   
  #Malaysia                 
  1439 1445 1442 1450 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1413 1418 1443 1421 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529 
   } 
   controlledprovinces    = {    
  #Malaysia                 
  1439 1445 1442 1450 1443 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529 
   } 
  
   SpyInfo                = {  country = "U02" NumberOfSpies = 3  } 
  
   techapps               = {  
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060    
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240   
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980   
#1930 Cavalry Division 
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
#Motorised Inf
1396
#Basic Armoured Car 
2860 2870 2880 2020   
#Great War Heavy Field Artillery 
2290 2300 2310 
#SW Tank 
7600 7610 2620 2010 
#Engineers
1830 1840 1850 1860
#Early Static Anti-Air Artillery 
2800 2450
#Great War Destroyer
3010 3020 3030 3040
#Interwar Light Cruiser 
3110 3120 3130 3140
#Early Heavy Cruiser 
3210 3220 3230
#Interwar Fighter 
4500 4510 4520 4530 4540 4550 4010
#Interwar Bomber 
4600 4610 4620 4630 4120
#Computers & cryptografi
5310 54010 54020 54030 5316 5326
#Manufactoring
5810 5820 5050 5830
#Improved Construction Engineering 
5800 5080 5090 
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810
#Medicine
5600


#Naval Doctrines
8010 8020 8050
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
# Defensive Focus Grand Battleplan Path (FRA / UK)
6560
} 
inventions = { 3000027 }
  policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 5 
     political_left    = 3 
     freedom           = 3 
     free_market       = 5 
     professional_army = 2 # no conscription 
     defense_lobby     = 3 
     interventionism   = 3 
    } 
   peacetime_ic_mod = 0.6
   wartime_ic_mod = 0.7
   headofstate            = {  type = 9 id = 825001  } 
   headofgovernment       = {  type = 9 id = 825002  } 
   foreignminister        = {  type = 9 id = 825003  } 
   armamentminister       = {  type = 9 id = 825004  } 
   ministerofsecurity     = {  type = 9 id = 825005  } 
   ministerofintelligence = {  type = 9 id = 825006  } 
   chiefofstaff           = {  type = 9 id = 825007  } 
   chiefofarmy            = {  type = 9 id = 825008  } 
   chiefofnavy            = {  type = 9 id = 825009  } 
   chiefofair             = {  type = 9 id = 825010  } 
  
   landunit = 
   {  name     = "Delhi District" 
     location = 1459 
     id       = {  type = 12700 id = 21  } 
     Division = 
     {  id       = {  type = 12700 id = 22  } 
       name     = "Delhi Contingent" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
 Division = 
     {  id       = {  type = 12700 id = 500  } 
       name     = "Delhi Cavalry" 
       type     = cavalry 
	   model    = 9
       strength = 80 
       }   	  
	  
	  
    } 
   landunit = 
   {  name     = "Sind District" 
     location = 1533 
     id       = {  type = 12700 id = 27  } 
     Division = 
     {  id       = {  type = 12700 id = 28  } 
       name     = "The Sind Rifles" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Bikaner District" 
     location = 1527 
     id       = {  type = 12700 id = 29  } 
     Division = 
     {  id       = {  type = 12700 id = 30  } 
       name     = "Punjab Rifles" 
       type     = infantry 
	   model    = 9
       extra    = engineer 
	   brigade_model = 3
       strength = 100 
        
      } 
	Division = 
     {  id       = {  type = 12700 id = 503  } 
       name     = "Punjab Cavalry" 
       type     = cavalry 
	   model    = 9
       strength = 80 
       } 
    } 
   landunit = 
   {  name     = "Vishkahapatnam District" 
     location = 1477 
     id       = {  type = 12700 id = 31  } 
     Division = 
     {  id       = {  type = 12700 id = 32  } 
       name     = "The Madras Guards" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
	Division = 
     {  id       = {  type = 12700 id = 504 } 
       name     = "Madras Cavalry" 
       type     = cavalry
	model    = 9	   
       strength = 80 
       } 	  
    } 
   landunit = 
   {  name     = "Bombay District" 
     location = 1517 
     id       = {  type = 12700 id = 33  } 
     Division = 
     {  id       = {  type = 12700 id = 34  } 
       name     = "Central India Railway Regiment" 
       type     = infantry
		model    = 9	   
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Mangalore District" 
     location = 1503 
     id       = {  type = 12700 id = 35  } 
     Division = 
     {  id       = {  type = 12700 id = 36  } 
       name     = "Poona Rifles" 
       type     = infantry 
	   model    = 9
       extra    = artillery 
	   brigade_model = 5
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Madras District" 
     location = 1494 
     id       = {  type = 12700 id = 37  } 
     Division = 
     {  id       = {  type = 12700 id = 38  } 
       name     = "Southern Mahratta Railway Rifles" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Conchin District" 
     location = 1495 
     id       = {  type = 12700 id = 39  } 
     Division = 
     {  id       = {  type = 12700 id = 40  } 
       name     = "Coorg and Mysore Company" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "Madurai District" 
     location = 1504 
     id       = {  type = 12700 id = 41  } 
     Division = 
     {  id       = {  type = 12700 id = 42  } 
       name     = "South Indian Railway Battalion" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    } 
   landunit = 
   {  name     = "4th Indian Division" 
     location = 761 
     id       = {  type = 12700 id = 6043  } 
     Division = 
     {  id       = {  type = 12700 id = 6044  } 
       name     = "4th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }  
   landunit = 
   {  name     = "XV Indian Corps" 
     location = 1442 
     id       = {  type = 12700 id = 6045  } 
     Division = 
     {  id       = {  type = 12700 id = 6046  } 
       name     = "5th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
     Division = 
     {  id       = {  type = 12700 id = 6070  } 
       name     = "23rd Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "British X Army" 
     location = 1034 
     id       = {  type = 12700 id = 6047  } 
     Division = 
     {  id       = {  type = 12700 id = 6048  } 
       name     = "6th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
     Division = 
     {  id       = {  type = 12700 id = 6065  } 
       name     = "31st Indian Armoured Division" 
       type     = light_armor
	   model    = 1
       strength = 40 
        
      } 
    }
   landunit = 
   {  name     = "7th Indian Division" 
     location = 1447 
     id       = {  type = 12700 id = 6049  } 
     Division = 
     {  id       = {  type = 12700 id = 6050  } 
       name     = "7th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "XXI Indian Corps" 
     location = 1029 
     id       = {  type = 12700 id = 6051  } 
     Division = 
     {  id       = {  type = 12700 id = 6052  } 
       name     = "8th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
     Division = 
     {  id       = {  type = 12700 id = 6057  } 
       name     = "10th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "14th Indian Division" 
     location = 1450 
     id       = {  type = 12700 id = 6058  } 
     Division = 
     {  id       = {  type = 12700 id = 6059  } 
       name     = "14th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "17th Indian Division" 
     location = 1440 
     id       = {  type = 12700 id = 6060  } 
     Division = 
     {  id       = {  type = 12700 id = 6061  } 
       name     = "17th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "19th Indian Division" 
     location = 1491 
     id       = {  type = 12700 id = 6062  } 
     Division = 
     {  id       = {  type = 12700 id = 6063  } 
       name     = "19th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "Indian Armoured Corps" 
     location = 1459 
     id       = {  type = 12700 id = 6064  } 
     Division = 
     {  id       = {  type = 12700 id = 6066  } 
       name     = "33rd Indian Armoured Division" 
       type     = light_armor
	   model    = 1
       strength = 40 
        
      } 
     Division = 
     {  id       = {  type = 12700 id = 6081  } 
       name     = "43rd Indian Armoured Division" 
       type     = light_armor
	   model    = 1
       strength = 40 
        
      } 
    }
   landunit = 
   {  name     = "20th Indian Division" 
     location = 1462 
     id       = {  type = 12700 id = 6067  } 
     Division = 
     {  id       = {  type = 12700 id = 6068  } 
       name     = "20th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "25th Indian Division" 
     location = 1502 
     id       = {  type = 12700 id = 6071  } 
     Division = 
     {  id       = {  type = 12700 id = 6072  } 
       name     = "25th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
        
      } 
    }
   landunit = 
   {  name     = "26th Indian Division" 
     location = 1444 
     id       = {  type = 12700 id = 6073  } 
     Division = 
     {  id       = {  type = 12700 id = 6074  } 
       name     = "26th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
       extra    = artillery 
	   brigade_model = 5
        
      } 
    }
   landunit = 
   {  name     = "34th Indian Division" 
     location = 1511 
     id       = {  type = 12700 id = 6075  } 
     Division = 
     {  id       = {  type = 12700 id = 6076  } 
       name     = "34th Indian Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
       extra    = artillery 
	   brigade_model = 5
        
      } 
    }
   landunit = 
   {  name     = "1st Burma Division" 
     location = 1414 
     id       = {  type = 12700 id = 6077  } 
     Division = 
     {  id       = {  type = 12700 id = 6078  } 
       name     = "1st Burma Infantry Division" 
       type     = infantry 
	   model    = 9
       strength = 80
        
      } 
    }
   landunit = 
   {  name     = "3rd Indian Division" 
     location = 1464 
     id       = {  type = 12700 id = 6079  } 
     Division = 
     {  id       = {  type = 12700 id = 6080  } 
       name     = "3rd Indian (Chindits) Division" 
       type     = infantry 
	   model    = 9
       strength = 100 
       extra    = artillery 
	   brigade_model = 5
        
      } 
    }

	navalunit = { 
		id = { type = 12700 id = 288 } 
		name = "Royal Indian Navy" 
		location = 1517 
		base = 1517 
		division = { 
			id = { type = 12700 id = 284 } 
			name = "HMIS 2nd Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 286 } 
			name = "HMIS 4th Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 2318 } 
			name = "2nd DD. Division" 
			type = destroyer 
			} 
		division = { 
			id = { type = 12700 id = 2319 } 
			name = "3rd DD. Division" 
			type = destroyer 
			} 
		}  
	navalunit = { 
		id = { type = 12700 id = 2332 } 
		name = "1st Squadron" 
		location = 1517 
		base = 1517 
		division = { 
			id = { type = 12700 id = 289 } 
			name = "HMIS 1st Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 285 } 
			name = "HMIS 3rd Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 287 } 
			name = "HMIS Destroyer Flotilla" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 12700 id = 2317 } 
			name = "1st DD. Division" 
			type = destroyer 
			} 
		} 
   airunit = 
   {  location = 1517 
     base     = 1517 
     id       = {  type = 12700 id = 80  } 
     name     = "Royal Indian Air Force" 
     Division = 
     {  id       = {  type = 12700 id = 81  } 
       name     = "Indian Group" 
       type     = tactical_bomber 
       model    = 4
       strength = 100 
      } 
    }

   division_development = 
   {  name  = "36th Indian Infantry Division" 
     type  = infantry 
     model = 9
     cost  = 0.1
     id    = {  type = 12700 id = 7000  } 
     date  = {  year = 1942 month = december day = 15  }   
    }
  }