    ##############################
    # Country definition for ITA #
    ##############################
     
    #####################
    # Country main data #
    #####################
     
    country =
    {  tag                    = ITA
       manpower               = 460
       # Resource Reserves
       energy                 = 3600
       metal                  = 1800
       rare_materials         = 1000
       oil                    = 3000
       supplies               = 2000
       money                  = 100
       belligerence           = 20
       capital                = 419
       transports             = 130
       escorts                = 35
   #ground_def_eff         = 0.600 
 
  diplomacy =
  { relation = { tag = AFG value = 50 }
    relation = { tag = ARG value = 30 }
    relation = { tag = AST value = -200 }
    relation = { tag = BEL value = -200 }
    relation = { tag = BHU value = -200 }
    relation = { tag = BUL value = 150 }
    relation = { tag = CAN value = -200 }
    relation = { tag = CHI value = 25 }
    relation = { tag = CHL value = 30 }
    relation =
    { tag        = CRO
      value      = 200
      access     = yes
      guaranteed = { day = 1 month = may year = 1941 }
    }
    relation = { tag = SLO value = 120 }
    relation = { tag = ENG value = -200 }
    relation = { tag = ETH value = -200 }
    relation = { tag = FIN value = 100 }
    relation = { tag = U01 value = -200 }
    relation =
    { tag        = GER
      value      = 200
      guaranteed = { day = 27 month = september year = 1940 }
    }
    relation = { tag = HOL value = -200 }
    relation =
    { tag        = HUN
      value      = 200
      guaranteed = { day = 20 month = november year = 1940 }
    }
    relation = { tag = IRQ value = -200 }
    relation =
    { tag        = JAP
      value      = 125
      guaranteed = { day = 27 month = september year = 1940 }
    }
    relation =
    { tag        = MTN
      value      = 200
      access     = yes
      guaranteed = { day = 1 month = may year = 1941 }
    }
    relation = { tag = NEP value = -200 }
    relation = { tag = NIC value = -200 }
    relation = { tag = NZL value = -200 }
    relation = { tag = OMN value = -200 }
    relation = { tag = POR value = 65 }
    relation =
    { tag        = ROM
      value      = 150
      guaranteed = { day = 20 month = november year = 1940 }
    }
    relation = { tag = SAF value = -200 }
    relation = { tag = SAU value = -25 }
    relation = { tag = SCH value = -25 }
    relation =
    { tag        = SPA
      value      = 50
      guaranteed = { day = 18 month = november year = 1940 }
    }
    relation = { tag = TUR value = 1 }
    relation = { tag = FRA value = 50 }
    relation = { tag = YEM value = -200 }
  }
       SpyInfo                = {  country = "ITA" NumberOfSpies = 9  }
       # Somaliland
       nationalprovinces      = {  430 431 425 422 424 421 420 416 423 415 414 419 410 412 411 393 408 396 398 407 401 400 434 350 343   
            403 406 402 413 417 435 432 405 404 390 94 399 371 429 378 379 87 394 395 418 426 427 428 433 91 }
            #367 90 371 429 378 379 #added
            #389 335 361 329 359 334 362 360 87 2509#removed
       
       ownedprovinces         = { 430  431  425 422 424 421 420 416 423 415 414 419 410 412 411 393 408 396 398 407 401 400 434 378 
                                  379 754 752 750 757 756 762 761 768 760 766 765 771 769 770 773 755 751 774
                                  776 777 758 759 763 775 764 767 772 403 406 394 395 418 426 427 428 433   
	                          402 413 417 435 432 405 404 753 399
                                  359 362 361 360 334 329 349 350 343 367 368 369 371 372 373 374 375 376 380 381
                                  86  87  90  91  92  93  94 }

       controlledprovinces    = {  430  431  425  422  424  421  420  416  423  415  414  419  410  412  411  393  408  396  398  407  401  400  434  378 
                                  379  754  752  750  757  756  755  751  774
                                  776 777 758 759
             403 406  394 395 418 426 427 428 433 402 413 417 435 432 405 404 753 399
             359 362 361 360 334 329 349 350 343 367 368 369 371 372 373 374 375 376 380 381
             86  87  90  91  92  93  94  741 742 744 745 747 748 }
		claimedprovinces =  {   740 741 742 744 745 746 747 748 749 #Tunisia
                                750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 #Libya
                                359 362 361 360 334 329 #Albania
								349 #Ljubljana
                                367 368 369 371 372 373 374 375 376 380 381 # Greece
							} 

	# ITA 1942.11 techs
	# ######################
	techapps = {  
	
	# Manufacturing
	5810 5820 5050 5830 5060 5070 5130
	# Construction Engineering 
	5800 5080 5090 5100
	# Agriculture 
	5700 5710 5010 5020 5030
	# Computers
	5310 54010 54020 54030 5320
	# Cryptography
	5316 5326 5327 5350 5360
	# Radar
	5410
	# Oil Refining
	5190
	# Atomic Research
	5470 
	# Medicine
	5600 5610 5620 5630 5640
	# Exp. Rocket
	5560
	
	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110
	# Mountain Division
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260
	# Cavalry
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
	# Motorized Infantry
	1396 1400
	# Naval Infantry
	1560 1570 1580
	# Paratroopers
	1670
	# Engineers
	1830 1840 1850 1860 1870
	# Supply 
	1910 1920 1930 1940 1950 1960 1970 1980 1990 199130

	# Tanks 
	7600 7610 2620 2010 2630 2640 2646 2650 2030 2040 2050 2070
	# Armored Car 
	2860 2870 2880 2020 2150 
	# Artillery
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330
	# Anti-Tank Artillery
	2400 2410
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460 2470
	# Anti-Air Artillery
	2810 2820 2510 2520

	# Hospital System 
	14000 14010 14020 14030
	# Great War Land Doctrines (entente)
	6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
	# WWII Land Doctrines
	6560 6030 6120 6110 6130
	# Armored Division Formation
	6900

	# Light Cruiser 
	3110 3120 3130 3140 3150 3160 12010
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470
	# Battlecruiser  
	3310 3320 3330
	# Heavy Cruiser 
	3210 3220 3230 3240 3250 3260
	# Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	# Submarine 
	3610 3620 3630 3640 3650 3660 3670
	# Light carrier 
	12100 12110
	# Carrier
	3510 3520 3530
	# Torpedo & ASW
	3720 3730 3736 3740 3750 3900
	# Troopships
	3810 3820

	# Naval Doctrines
	# Engagement Theories
	8010 8020 8030 8040 8050 8060 8070 8080
	# Amphibious Warfare
	82300
	# Logistic Support
	82500
	# Naval Interdiction
	8500 8510 8520 8550
	# Trade Interdiction Submarine
	8600 8610
	# Engagement Tactics - Fleet-in-Being column
	8900 8910 8920 8930 8940 8950 8960 8970
	# Naval Supremacy
	8100 8110 8120 8150 8160 8170 8200 8210
	# Carrier
	81650

	# Interceptor Fighter  
	4500 4510 4520 4530 4540 4550 4010 4020 4030 4060
	# Multirole fighter
	4300 4310 4320 4330 4340 4040
	# Escort fighter
	4050
	# Close Air Support
    4400 4170
	# Tactical Bomber 
	4600 4610 4620 4630 4120 4130 4140 4150
	# Strategic Bomber
	4800 4810 4820
	# Naval Bomber
	4700 4710 4190
	# Seaplanes
	4740 4750 4760 4770 4780 4790 4850 4860
	# CAG
	4900 4910 4920
	# Air Transport 
	4290 4250 4260

	# Air Doctrines
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 
	9040 9050 9060 9070 9090 9100 9110 9120 9130 9140 9190 9200 9210 9220 9230 9240
	}

	inventions = { 3000027 }
       policy =
       {  date              = {  year = 0 month = january day = 0  }
         democratic        = 2
         political_left    = 3
         freedom           = 3 #former value was 4
         free_market       = 7
         professional_army = 6
         defense_lobby     = 7
         interventionism   = 8 #former value was 6
        }
       headofstate            = {  type = 9 id = 25001  }
       headofgovernment       = {  type = 9 id = 25002  }
       foreignminister        = {  type = 9 id = 25003  }
       armamentminister       = {  type = 9 id = 25047  }
       ministerofsecurity     = {  type = 9 id = 25005  }
       ministerofintelligence = {  type = 9 id = 25086  }
       chiefofstaff           = {  type = 9 id = 25097  }
       chiefofarmy            = {  type = 9 id = 25110  }
       chiefofnavy            = {  type = 9 id = 25117  }
       chiefofair             = {  type = 9 id = 25126  }
       dormant_ministers      = {  25008  }
       dormant_ministers      = {  25016 25195  }
       # ######################
       # ITA 1942 LAND OOB

       # SUPREME COMMAND
       landunit =
       {  id       = {  type = 23500 id = 1  }
         location = 419
         name     = "Superesercito"
         division =
         { id       = {  type = 23500 id = 2  }
           name     = "Q.G. Forze Armate"
           type     = hq
           model    = 2
           strength = 50
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6  }
         location = 378
         name     = "Guarnigione di Leros"
         Division =
         {  id       = {  type = 23500 id = 25  }
           name     = "Guarnigione di Leros"
           type     = garrison
           model    = 4
           strength = 30  #the garrison was 5500 soldiers strong
          }
        }
       # ARMY GROUP WEST
       landunit =
       {  id       = {  type = 23500 id = 6924  }
         location = 407
         name     = "Gruppo d'Armate Ovest"
         division =
         { id       = {  type = 23500 id = 6925  }
           name     = "Gruppo d'Armate Ovest"
           type     = hq
           model    = 2
           strength = 35
          }
        }
       # 4th Army
       landunit =
       {  id       = {  type = 23500 id = 6930  }
         location = 90
         name     = "IV Armata"
         division =
         { id       = {  type = 23500 id = 8  }
           name     = "5a Divisione Alpina 'Pusteria'"
           type     = bergsjaeger
           model    = 10
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6927  }
           name     = "104a Divisione 'Mantova'"
           type     = motorized
           model    = 1
           strength = 10
          }
         division =
         { id       = {  type = 23500 id = 6928  }
           name     = "105a Divisione 'Rovigo'"
           type     = motorized
           model    = 1
           strength = 10
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 60  }
         location = 86
         name     = "XV Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 62  }
           name     = "10a Divisione 'Piave'"
           type     = motorized
           model    = 1
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 11  }
           name     = "7a Divisione 'Lupi di Toscana'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 27  }
           name     = "58a Divisione 'Legnano'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6922  }
         location = 94
         name     = "IX Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 100  }
           name     = "20a Divisione 'Friuli'"
           type     = infantry
           model    = 10
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 23  }
           name     = "44a Divisione 'Cremona'"
           type     = infantry
           model    = 10
           strength = 80
           extra    = anti_tank
           brigade_model = 1
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 12  }
         location = 430
         name     = "II Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 13  }
           name     = "4a Divisione 'Livorno'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6921  }
         location = 419
         name     = "IX Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 103  }
           name     = "21a Divisione 'Granatieri di Sardegna'"
           type     = infantry
           model    = 10
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 95  }
           name     = "47a Divisione 'Bari'"
           type     = infantry
           model    = 10
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 76  }
         location = 433
         name     = "XII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 77  }
           name     = "28a Divisione 'Aosta'"
           type     = infantry
           model    = 10
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 78  }
           name     = "54a Divisione 'Napoli'"
           type     = infantry
           model    = 10
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 20  }
         location = 434
         name     = "XIII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 80  }
           name     = "30a Divisione 'Sabauda'"
           type     = infantry
           model    = 10
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 81  }
           name     = "31a Divisione 'Calabria'"
           type     = infantry
           model    = 10
           strength = 60
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 4500  }
         location = 430
         name     = "VI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 37  }
           name     = "26a Divisione 'Assietta'"
           type     = infantry
           model    = 10
           strength = 80
           extra    = artillery
           brigade_model = 8
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 52  }
         location = 398
         name     = "XXII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 6929  }
           name     = "103a Divisione 'Piacenza'"
           type     = motorized
           model    = 1
           strength = 10
          }
         division =
         { id       = {  type = 23500 id = 54  }
           name     = "2a Divisione 'Emanuele Filiberto'"
           type     = cavalry
           model    = 10
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 96  }
           name     = "48a Divisione 'Taro'"
           type     = infantry
           model    = 10
           strength = 70
          }
        }
       # ARMY GROUP EAST
       landunit =
       {  id       = {  type = 23500 id = 38  }
         location = 400
         name     = "Gruppo d'Armate Est"
         division =
         { id       = {  type = 23500 id = 39  }
           name     = "Gruppo d'Armate Est"
           type     = hq
           model    = 2
           strength = 35
          }
        }
       # SUPREME COMMAND "SLOVENIA"
       # 2nd Army
       landunit =
       {  id       = {  type = 23500 id = 6943  }
         location = 349
         name     = "II Armata"
         division =
         { id       = {  type = 23500 id = 44  }
           name     = "14a Divisione 'Isonzo'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 6914  }
           name     = "153a Divisione 'Macerata'"
           type     = garrison
           model    = 4
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6904  }
         location = 350
         name     = "V Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 43  }
           name     = "13a Divisione 'Re'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 49  }
           name     = "57a Divisione 'Lombardia'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 53  }
           name     = "1a Divisione 'Eugenio di Savoia'"
           type     = cavalry
           model    = 11
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 45  }
         location = 350
         name     = "VI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 70  }
           name     = "18a Divisione 'Messina'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 67  }
           name     = "32a Divisione 'Marche'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 6912  }
           name     = "154a Divisione 'Murge'"
           type     = garrison
           model    = 4
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6913  }
           name     = "155a Divisione 'Emilia'"
           type     = garrison
           model    = 4
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6915  }
         location = 343
         name     = "XVIII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 46  }
           name     = "12a Divisione 'Sassari'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 47  }
           name     = "15a Divisione 'Bergamo'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 6916  }
           name     = "158a Divisione 'Zara'"
           type     = garrison
           model    = 4
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 69  }
         location = 350
         name     = "XVII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 7  }
           name     = "22a Divisione 'Cacciatori delle Alpi'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       # ALBANIA ARMY COMMAND
       # 9th Army
       landunit =
       {  id       = {  type = 23500 id = 6962  }
         location = 359
         name     = "IX Armata"
         division =
         { id       = {  type = 23500 id = 73  }
           name     = "49a Divisione 'Parma'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 85  }
           name     = "23a Divisione 'Ferrara'"
           type     = infantry
           model    = 10
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 86  }
           name     = "53a Divisione 'Arezzo'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       # MONTENEGRO ARMY COMMAND
       landunit =
       {  id       = {  type = 23500 id = 82  }
         location = 332
         name     = "Comando Truppe d'Montenegro"
         division =
         { id       = {  type = 23500 id = 84  }
           name     = "19a Divisione 'Venezia'"
           type     = infantry
           model    = 10
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 68  }
           name     = "38a Divisione 'Puglie'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 101  }
           name     = "41a Divisione 'Firenze'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 30  }
           name     = "1a Divisione Alpina 'Taurinese'"
           type     = bergsjaeger
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 6917  }
           name     = "6a Divisione Alpina 'Alpi Graje'"
           type     = bergsjaeger
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 6918  }
           name     = "151a Divisione 'Perugia'"
           type     = garrison
           model    = 4
           strength = 70
          }
        }
       # SUPREME COMMAND "GREECE"
       # 11th Army
       landunit =
       {  id       = {  type = 23500 id = 123  }
         location = 375
         name     = "XI Armata"
         division =
         { id       = {  type = 23500 id = 26  }
           name     = "11a Divisione 'Brennero'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 33  }
           name     = "24a Divisione 'Pinerolo'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 15  }
           name     = "36a Divisione 'Forlì'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 93  }
         location = 376
         name     = "VIII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 94  }
           name     = "29a Divisione 'Piemonte'"
           type     = infantry
           model    = 10
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 34  }
           name     = "59a Divisione 'Cagliari'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 690  }
         location = 367
         name     = "XXVI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 22  }
           name     = "37a Divisione 'Modena'"
           type     = infantry
           model    = 10
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 71  }
           name     = "56a Divisione 'Casale'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6903  }
         location = 371
         name     = "XXVI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 14  }
           name     = "33a Divisione 'Acqui'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6905  }
         location = 381
         name     = "XXVI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 19  }
           name     = "6a Divisione 'Cuneo'"
           type     = infantry
           model    = 10
           strength = 80
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 105  }
         location = 379
         name     = "Comando Truppe delle Isole Italiane dell'Egeo"
         division =
         { id       = {  type = 23500 id = 106  }
           name     = "50a Divisione 'Regina'"
           type     = infantry
           model    = 10
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6901  }
         location = 380
         name     = "FF.AA. Isole Italiane dell'Egeo"
         division =
         { id       = {  type = 23500 id = 104  }
           name     = "51a Divisione 'Siena'"
           type     = infantry
           model    = 10
           strength = 70
           extra    = artillery
           brigade_model = 7
          }
        }
       # AFRICAN SUPREME COMMAND
       landunit =
       {  id       = {  type = 23500 id = 107  }
         location = 750
         name     = "Comando Superiore FF.AA. Africa"
         division =
         { id       = {  type = 23500 id = 108  }
           name     = "Comando Superiore FF.AA. Africa"
           type     = hq
           model    = 2
           strength = 50
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 113  }
         location = 754
         name     = "X Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 6919  }
           name     = "185a Divisione 'Folgore'"
           type     = paratrooper
           model    = 1
           strength = 20
          }
         division =
         { id       = {  type = 23500 id = 6934  }
           name     = "136a Divisione 'Giovani Fascisti'"
           type     = infantry
           model    = 10
           strength = 30
          }
          dig_in = 20.000
        }
       landunit =
       {  id       = {  type = 23500 id = 118  }
         location = 759
         name     = "XX Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 57  }
           name     = "101a Divisione 'Trieste'"
           type     = motorized
           model    = 1
           strength = 10
          }
         division =
         { id       = {  type = 23500 id = 90  }
           name     = "133a Divisione 'Littorio'"
           type     = light_armor
           model    = 1
           strength = 15
          }
          dig_in = 20.000
        }
       landunit =
       {  id       = {  type = 23500 id = 6920  }
         location = 745
         name     = "IX Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 9  }
           name     = "16a Divisione 'Pistoia'"
           type     = motorized
           model    = 1
           strength = 70
          }
          dig_in = 20.000
        }
       landunit =
       {  id       = {  type = 23500 id = 111  }
         location = 750
         name     = "60a Divisione"
         division =
         { id       = {  type = 23500 id = 112  }
           name     = "60a Divisione 'Sabratha'"
           type     = infantry
           model    = 10
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6935  }
         location = 744
         name     = "80a Divisione"
         division =
         { id       = {  type = 23500 id = 6936  }
           name     = "80a Divisione 'La Spezia'"
           type     = paratrooper
           model    = 1
           strength = 50
          }
          dig_in = 20.000
        }
       landunit =
       {  id       = {  type = 23500 id = 31  }
         location = 748
         name     = "I Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 32  }
           name     = "1a Divisione 'Superga'"
           type     = infantry
           model    = 10
           strength = 80
          }
          dig_in = 20.000
        }
       landunit =
       {  id       = {  type = 23500 id = 6933  }
         location = 747
         name     = "I Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 88  }
           name     = "131a Divisione 'Centauro'"
           type     = light_armor
           model    = 1
           strength = 70
           extra    = armored_car
           brigade_model = 3
          }
          dig_in = 20.000
        }
    # GARRISONS
       landunit =
       {  id       = {  type = 23500 id = 6937 }
         location = 422
         name     = "152a Divisione"
         division =
         { id       = {  type = 23500 id = 6938  }
           name     = "152a Divisione 'Piceno'"
           type     = garrison
           model    = 4
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6939 }
         location = 427
         name     = "157a Divisione"
         division =
         { id       = {  type = 23500 id = 6940  }
           name     = "157a Divisione 'Novara'"
           type     = garrison
           model    = 4
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6941 }
         location = 405
         name     = "159a Divisione"
         division =
         { id       = {  type = 23500 id = 6942  }
           name     = "159a Divisione 'Veneto'"
           type     = garrison
           model    = 4
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6907  }
         location = 636
         name     = "Befehlshaber Heeresgruppe B"
         division =
         { id       = {  type = 23500 id = 6908  }
           name     = "156a Divisione 'Vicenza'"
           type     = garrison
           model    = 4
           strength = 70
          }
        }
       # 8th Army
       landunit =
       {  id       = {  type = 23500 id = 6909  }
         location = 649
         name     = "VIII Armata"
         division =
         { id       = {  type = 23500 id = 28  }
           name     = "2a Divisione Alpina 'Tridentina'"
           type     = bergsjaeger
           model    = 10
           strength = 30
          }
         division =
         { id       = {  type = 23500 id = 87  }
           name     = "3a Divisione Alpina 'Julia'"
           type     = bergsjaeger
           model    = 10
           strength = 20
          }
         division =
         { id       = {  type = 23500 id = 16  }
           name     = "4a Divisione Alpina 'Cuneense'"
           type     = bergsjaeger
           model    = 10
           strength = 30
          }
          dig_in = 20.000
        }
       landunit =
       {  id       = {  type = 23500 id = 17  }
         location = 649
         name     = "II Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 18  }
           name     = "3a Divisione 'Ravenna'"
           type     = infantry
           model    = 10
           strength = 30
          }
         division =
         { id       = {  type = 23500 id = 21  }
           name     = "5a Divisione 'Cosseria'"
           type     = infantry
           model    = 10
           strength = 25
          }
          dig_in = 20.000
        }
       landunit =
       {  id       = {  type = 23500 id = 6911  }
         location = 649
         name     = "XXXV Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 61  }
           name     = "9a Divisione 'Pasubio'"
           type     = motorized
           model    = 0
           strength = 15
          }
          dig_in = 20.000
        }
       landunit =
       {  id       = {  type = 23500 id = 6900  }
         location = 649
         name     = "XXIX. Armeekorps"
         division =
         { id       = {  type = 23500 id = 36  }
           name     = "2nd Divisione 'Sforzesca'"
           type     = infantry
           model    = 9
           strength = 35
          }
         division =
         { id       = {  type = 23500 id = 55  }
           name     = "3a Divisione 'Principe Amedeo'"
           type     = cavalry
           model    = 10
           strength = 10
           extra    = artillery
           brigade_model = 5
          }
         division =
         { id       = {  type = 23500 id = 63  }
           name     = "52a Divisione 'Torino'"
           type     = motorized
           model    = 0
           strength = 15
           extra    = armored_car
           brigade_model = 3
          }
          dig_in = 20.000
        }

    ####################################################################
      
	# ROYAL ITALIAN NAVY
	navalunit = { 
		id = { type = 23500 id = 2000 } 
		name = "Regia Marina" 
		location = 422 
		base = 422 
		division = { 
			id = { type = 23500 id = 263 } 
			name = "RN Taranto" 
			type = light_cruiser 
			model = 1 
			} 
		division = { 
			id = { type = 23500 id = 264 } 
			name = "RN Bari" 
			type = light_cruiser 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 265 } 
			name = "II Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 233 } 
			name = "III Squadriglia Cacciatorpediere" 
			type = destroyer 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 216 } 
			name = "IV Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 4 
			}
		division = { 
			id = { type = 23500 id = 234 } 
			name = "V Squadriglia Cacciatorpediere" 
			type = destroyer 
			model = 4 
			}  
		division = { 
			id = { type = 23500 id = 282 } 
			name = "Squadrone Giorgio Orsini" 
			type = transport 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 2830 } 
			name = "Squadrone Porto di Roma" 
			type = transport 
			model = 2 
			} 
		} 
	# 1ST FLEET
	navalunit = { 
		id = { type = 23500 id = 200 } 
		name = "Prima Squadra" 
		location = 422 
		base = 422 
		division = { 
			id = { type = 23500 id = 2001 } 
			name = "RN Giulio Cesare" 
			type = battleship 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 2002 } 
			name = "RN Andrea Doria" 
			type = battleship 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 401 } 
			name = "RN Caio Duilio" 
			type = battleship 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 2320 } 
			name = "RN Vittorio Veneto" 
			type = battleship 
			model = 7 
			}
		division = { 
			id = { type = 23500 id = 2329 } 
			name = "RN Littorio" 
			type = battleship 
			model = 7 
			}
		division = { 
			id = { type = 23500 id = 403 } 
			name = "RN Roma" 
			type = battleship 
			model = 7 
			}
		division = { 
			id = { type = 23500 id = 205 } 
			name = "RN Giuseppe Miraglia" 
			type = escort_carrier 
			} 
		division = { 
			id = { type = 23500 id = 267 } 
			name = "RN Gorizia" 
			type = heavy_cruiser 
			model = 4 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 23500 id = 204 } 
			name = "RN Luigi Cadorna" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 2040 } 
			name = "RN Duca degli Abruzzi" 
			type = light_cruiser 
			model = 4 
			}
		division = { 
			id = { type = 23500 id = 2041 } 
			name = "RN Giuseppe Garibaldi" 
			type = light_cruiser 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 404 } 
			name = "RN Attilio Regolo" 
			type = light_cruiser 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 270 } 
			name = "VII Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 206 } 
			name = "VIII Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 6 
			}
		division = { 
			id = { type = 23500 id = 2060 } 
			name = "IX Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 6 
			}
		division = { 
			id = { type = 23500 id = 269 } 
			name = "XIV Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 294 } 
			name = "XV Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 293 } 
			name = "XVI Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 2720 } 
			name = "Squadrone Aspromonte" 
			type = transport 
			model = 2 
			}
		division = { 
			id = { type = 23500 id = 2721 } 
			name = "Squadrone Maria" 
			type = transport 
			model = 2 
			}
		}
	# 2TH FLEET
	navalunit = { 
		id = { type = 23500 id = 207 } 
		name = "Seconda Squadra" 
		location = 396 
		base = 396 
		division = { 
			id = { type = 23500 id = 210 } 
			name = "RN Bolzano" 
			type = heavy_cruiser 
			model = 3 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 23500 id = 211 } 
			name = "RN Trieste" 
			type = heavy_cruiser 
			model = 3 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 23500 id = 212 } 
			name = "RN Duca d'Aosta" 
			type = light_cruiser 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 213 } 
			name = "RN Muzio Attendolo" 
			type = light_cruiser 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 214 } 
			name = "RN Raimondo Montecuccoli" 
			type = light_cruiser 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 2140 } 
			name = "RN Eugenio di Savoia" 
			type = light_cruiser 
			model = 4 
			}
		division = { 
			id = { type = 23500 id = 296 } 
			name = "X Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 222 } 
			name = "XI Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 23500 id = 228 } 
			name = "XII Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 2220 } 
			name = "XIII Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 23500 id = 272 } 
			name = "Squadrone Sagittario" 
			type = transport 
			model = 2 
			}
		} 
	# AEGEAN SEA NAVAL COMMAND
	navalunit = { 
		id = { type = 23500 id = 218 } 
		name = "Comando Navale Mar Egeo" 
		location = 378 
		base = 378 
		division = { 
			id = { type = 23500 id = 219 } 
			name = "LI Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 220 } 
			name = "LII Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		}
	# LIBYA MARITIME COMMAND
	navalunit = { 
		id = { type = 23500 id = 223 } 
		name = "Comando Navale Libia" 
		location = 750 
		base = 750  
		division = { 
			id = { type = 23500 id = 227 } 
			name = "I Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			}  
		} 
	# SUBMARINE FLEET
	# 1st Submarine Group
	navalunit = { 
		id = { type = 23500 id = 238 } 
		name = "I Gruppo Sommergibili" 
		location = 422 
		base = 422 
		division = { 
			id = { type = 23500 id = 239 } 
			name = "XI Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 240 } 
			name = "XII Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 241 } 
			name = "XIII Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 242 } 
			name = "XIV Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 243 } 
			name = "XV Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 2900 } 
			name = "XVI Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 244 } 
			name = "XVII Squadriglia Sommergibili" 
			type = submarine 
			model = 3 
			} 
		}
	# 2nd Submarine Group
	navalunit = { 
		id = { type = 23500 id = 245 } 
		name = "II Gruppo Sommergibili" 
		location = 421 
		base = 421 
		division = { 
			id = { type = 23500 id = 249 } 
			name = "XXI Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 250 } 
			name = "XXII Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			} 
		}  
	# 3rd Submarine Group
	navalunit = { 
		id = { type = 23500 id = 2380 } 
		name = "III Gruppo Sommergibili" 
		location = 396 
		base = 396 
		division = { 
			id = { type = 23500 id = 2390 } 
			name = "XXXI Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			}  
		division = { 
			id = { type = 23500 id = 253 } 
			name = "XXXIII Squadriglia Sommergibili" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 251 } 
			name = "XXXIV Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 252 } 
			name = "XXXV Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 2420 } 
			name = "XXXVII Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			}  
		}
	# 4th Submarine Group
	navalunit = { 
		id = { type = 23500 id = 254 } 
		name = "IV Gruppo Sommergibili" 
		location = 434 
		base = 434 
		division = { 
			id = { type = 23500 id = 255 } 
			name = "XL Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 230 } 
			name = "XLI Squadra Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 231 } 
			name = "XLII Squadra Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 256 } 
			name = "XLIII Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			}
		division = { 
			id = { type = 23500 id = 290 } 
			name = "XLIV Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 289 } 
			name = "XLV Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 288 } 
			name = "XLVI Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 257 } 
			name = "XLVII Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 287 } 
			name = "XLVIII Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 258 } 
			name = "XLIX Squadriglia Sommergibili" 
			type = submarine 
			model = 3 
			} 
		}
	navalunit = { 
		id = { type = 23500 id = 271 } 
		name = "I Squadra di Marina Trasporti" 
		location = 419 
		base = 421  
		division = { 
			id = { type = 23500 id = 273 } 
			name = "Squadrone Aventino" 
			type = transport 
			model = 2 
			}  
		division = { 
			id = { type = 23500 id = 292 } 
			name = "VI Squadriglia Torpediniere" 
			type = destroyer 
			model = 3 
			}
		} 
	navalunit = { 
		id = { type = 23500 id = 276 } 
		name = "II Squadra di Marina Trasporti" 
		location = 421 
		base = 421 
		division = { 
			id = { type = 23500 id = 277 } 
			name = "Squadrone Vallelunga" 
			type = transport 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 278 } 
			name = "Squadrone Asmara" 
			type = transport 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 283 } 
			name = "Squadrone Tarquinia" 
			type = transport 
			model = 2 
			} 
		}         



    ####################################################################
    
  airunit =
  { location = 422
    base     = 422
    id       = { type = 23500 id = 307 }
    name     = "2a Comando Caccia 'Borea'"
    division =
    { id       = { type = 23500 id = 308 }
      name     = "2a Divisione Caccia 'Borea'"
      strength = 65
      type     = interceptor
      model    = 8
    }
  }
  airunit =
  { location = 422
    base     = 422
    id       = { type = 23500 id = 3000 }
    name     = "2nd Squadra Aerea"
    division =
    { id       = { type = 23500 id = 3010 }
      name     = "6a Divisione Caccia"
      strength = 65
      type     = interceptor
      model    = 8
    }
  }
  airunit =
  { location = 422
    base     = 422
    id       = { type = 23500 id = 312 }
    name     = "3a Comando Aerosiluranti 'Centauro'"
    division =
    { id       = { type = 23500 id = 3130 }
      name     = "11a Divisione Bombardieri"
      strength = 65
      type     = naval_bomber
      model    = 2
    }
  }
  airunit =
  { location = 430
    base     = 430
    id       = { type = 23500 id = 3120 }
    name     = "11a Comando Aerosiluranti 'Nibbio'"
    division =
    { id       = { type = 23500 id = 3131 }
      name     = "30a Divisione Bombardieri"
      strength = 65
      type     = naval_bomber
      model    = 3
    }
  }
  airunit =
  { location = 430
    base     = 430
    id       = { type = 23500 id = 315 }
    name     = "1a Comando Caccia 'Aquila'"
    division =
    { id       = { type = 23500 id = 316 }
      name     = "1a Divisione Caccia 'Aquila'"
      strength = 65
      type     = interceptor
      model    = 8
    }
  }
  airunit =
  { location = 430
    base     = 430
    id       = { type = 23500 id = 317 }
    name     = "3rd Squadra Aerea"
    division =
    { id       = { type = 23500 id = 318 }
      name     = "7a Divisione Caccia"
      strength = 65
      type     = interceptor
      model    = 9
    }
  }
  airunit =
  { location = 434
    base     = 434
    id       = { type = 23500 id = 319 }
    name     = "5a Comando Aerosiluranti 'Eolo'"
    division =
    { id       = { type = 23500 id = 3140 }
      name     = "9a Divisione Bombardieri"
      strength = 65
      type     = naval_bomber
      model    = 3
    }
  }
  airunit =
  { location = 434
    base     = 434
    id       = { type = 23500 id = 3190 }
    name     = "8a Comando Caccia 'Astore'"
    division =
    { id       = { type = 23500 id = 333 }
      name     = "8a Divisione Caccia 'Astore'"
      strength = 65
      type     = interceptor
      model    = 8
    }
  }
  airunit =
  { location = 419
    base     = 419
    id       = { type = 23500 id = 323 }
    name     = "4th Squadra Aerea"
    division =
    { id       = { type = 23500 id = 324 }
      name     = "35a Divisione Bombardieri"
      strength = 65
      type     = tactical_bomber
      model    = 6
    }
    division =
    { id       = { type = 23500 id = 325 }
      name     = "39a Divisione Trasporti"
      strength = 65
      type     = transport_plane
      model    = 0
    }
  }
  airunit =
  { location = 430
    base     = 430
    id       = { type = 23500 id = 3260 }
    name     = "Aeronautica Sardegna"
    division =
    { id       = { type = 23500 id = 335 }
      name     = "10a Divisione Bombardieri 'Marte'"
      strength = 65
      type     = naval_bomber
      model    = 3
    }
    division =
    { id       = { type = 23500 id = 309 }
      name     = "3a Divisione Caccia"
      strength = 65
      type     = interceptor
      model    = 8
    }
  }
  airunit =
  { location = 750
    base     = 750
    id       = { type = 23500 id = 332 }
    name     = "Aeronautica Libia Ovest"
    division =
    { id       = { type = 23500 id = 322 }
      name     = "2a Divisione Caccia"
      strength = 65
      type     = interceptor
      model    = 8
    }
    division =
    { id       = { type = 23500 id = 334 }
      name     = "15a Divisione Bombardieri"
      strength = 65
      type     = naval_bomber
      model    = 2
    }
  }
  airunit =
  { location = 750
    base     = 750
    id       = { type = 23500 id = 336 }
    name     = "Aeronautica Libia Est"
    division =
    { id       = { type = 23500 id = 311 }
      name     = "14a Divisione Caccia 'Rex'"
      strength = 65
      type     = interceptor
      model    = 8
    }
    division =
    { id       = { type = 23500 id = 338 }
      name     = "13a Divisione Bombardieri 'Pegaso'"
      strength = 65
      type     = tactical_bomber
      model    = 6
    }
  }
	
	division_development = {
		id    = { type = 23500 id = 402 }
		name  = "RN Impero"
		type  = battleship
		model = 7
		cost  = 0.2
		date  = { year = 1945 month = april day = 9 } # 18 months from 09.09.1943
	}
	division_development = {
		id    = { type = 23500 id = 419 }
		name  = "RN Conte di Cavour"
		type  = battleship
		model = 5
		cost  = 0.2
		date  = { year = 1944 month = january day = 1 } # this date is random, since the ship was captured incomplete by the Germans in 10.09.1943
		extra = naval_anti_air_l
	}
	division_development = {
		id    = { type = 23500 id = 420 }
		name  = "RN Aquila"
		type  = carrier
		model = 2
		cost  = 0.3
		date  = { year = 1944 month = january day = 21 }
		extra = cag
		brigade_model = 3
	}
	division_development = {
		id    = { type = 23500 id = 421 }
		name  = "RN Sparviero"
		type  = escort_carrier
		model = 1
		cost  = 0.3
		date  = { year = 1945 month = may day = 1 }
		extra = cag
		brigade_model = 3
	}
	division_development = {
		id    = { type = 23500 id = 405 }
		name  = "RN Caio Mario"
		type  = light_cruiser
		model = 5
		date  = { year = 1944 month = january day = 24 }
	}
	division_development = {
		id    = { type = 23500 id = 408 }
		name  = "RN Cornelio Silla"
		type  = light_cruiser
		model = 5
		date  = { year = 1944 month = february day = 7 }
	}
	division_development = {
		id    = { type = 23500 id = 409 }
		name  = "RN Giulio Germanico"
		type  = light_cruiser
		model = 5
		date  = { year = 1943 month = november day = 1 } # almost complete by 09.1943
	}
	division_development = {
		id    = { type = 23500 id = 410 }
		name  = "RN Ottaviano Augusto"
		type  = light_cruiser
		model = 5
		date  = { year = 1944 month = january day = 19 }
	}
	division_development = {
		id    = { type = 23500 id = 412 }
		name  = "RN Pompeo Magno"
		type  = light_cruiser
		model = 5
		date  = { year = 1943 month = june day = 24 }
	}
	division_development = {
		id    = { type = 23500 id = 413 }
		name  = "RN Scipione Africano"
		type  = light_cruiser
		model = 5
		date  = { year = 1943 month = april day = 23 }
	}
	division_development = {
		id    = { type = 23500 id = 414 }
		name  = "RN Ulpio Traiano"
		type  = light_cruiser
		model = 5
		date  = { year = 1944 month = january day = 19 }
	}
	division_development = {
		id    = { type = 23500 id = 416 }
		name  = "RN Etna"
		type  = light_cruiser
		model = 6
		date  = { year = 1944 month = may day = 28 }
	}
	division_development = {
		id    = { type = 23500 id = 417 }
		name  = "RN Vesuvio"
		type  = light_cruiser
		model = 6
		date  = { year = 1944 month = august day = 1 }
	}
	division_development = {
		id    = { type = 23500 id = 422 }
		name  = "La Galissonnière"
		type  = light_cruiser
		model = 4
		date  = { year = 1943 month = march day = 3 } # scuttled at Toulon; raised by Italy in 03.03.1943
	}
	division_development = {
		id    = { type = 23500 id = 418 }
		name  = "184a Divisione 'Nembo'"
		type  = paratrooper
		model = 1
		cost  = 0.1
		date  = { year = 1942 month = december day = 1 }
	}
}
