 
 ############################## 
 # Country definition for SOV # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = SOV 
   regular_id             = RUS 
   intrinsic_gov_type     = leninist 
   ai                     = "SOV_1942.ai"
   ground_def_eff         = 1.400
   capital                = 572 
   # Resource Reserves 
	energy                 = 12000
	metal                  = 6000
	rare_materials         = 3000
	oil                    = 2000 
	supplies               = 2000 
	money                  = 100 
	belligerence           = 30
	manpower               = 1953 
	dissent                = 15 
	transports             = 300 
	escorts                = 20 
    
  diplomacy =
  { relation = { tag = AFG value = 1 }
    relation = { tag = BRA value = -50 }
    relation = { tag = BUL value = -200 }
    relation = { tag = CHI value = 25 }
    relation = { tag = SLO value = -150 }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = -100 }
    relation = { tag = U01 value = 100 }
    relation = { tag = GER value = -200 }
    relation =
    { tag        = MON
      value      = 150
      guaranteed = { day = 8 month = april year = 1940 }
      access     = yes
    }
    relation = { tag = PER value = -20 }
    relation = { tag = ROM value = -200 }
    relation =
    { tag        = SIK
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = SPA value = -100 }
    relation = { tag = TAN value = 200 access = yes }
    relation = { tag = TUR value = 70 }
    relation = { tag = URU value = -100 }
    relation = { tag = USA value = 175 }
  }

   SpyInfo                = {  country = "SOV" NumberOfSpies = 10  } 
    
   nationalprovinces      = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 
                              1153 1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 
                              568 615 625 564 621 588 584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 
                              1101 1118 502 501 1151 1130 1137 598 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 632 592 687 689 688 
                              542  686 681 543  547  538  539  537  536  534  535  706 702 704 703 709 708 710 701 696 695 694  691  692  
                              697  698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640  670 667 675 674 672 
                              664 671 673 684 663  693  618  655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  
                              554  569  572  570  585  574  540  541  559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  
                              620  626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  
                              580  652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648  1097 1098 1105 1104 1099 1103 
                              1106 1109 1108 1107 567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185 506 
                              1100 711 712 713 1149 1141 499 593 1542 
               714 576 555 705 
         1126 1127 1128 1069 1070 1161 1170 1171 
         259 260 262 263 264 265 266 267 268 269 270 271 272 273 274 275
         517 519 531 532 530
         300 302 303 304 305 306
                             } 
   ownedprovinces         = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 1153 
                              1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 568 
                              615 625 564 621 588 584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 1101 
                              1118 502 501 1151 1130 1137 598 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 632 592 687 689 688 542  
                              686 681 543  547  538  539  537  536  534  535  706 702 704 703 709 708 710 701 696 695 694  691  692  697  
                              698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640  670 667 675 674 672 664 
                              671 673 684 663  693  618  655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  554  
                              569  572  570  585  574  540  541  559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  620  
                              626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  580  
                              652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648  1097 1098 1105 1104 1099 1103 1106 
                              1109 1108 1107 567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185 506 1100 
                              711 712 713 1149 1141 499 593 
               714 576 555 705 
         1126 1127 1128 1069 1070 1161 1170 1171 
         241 242 244 247 254 245 238 255 257 251 240 248 250 239 249 256 253 259 262 263 260 258 268 269 267 264 266 265 274 270 275 271 272 273
         1083 1081 1080 1082 1092
                             } 
   controlledprovinces    = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180    1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 1153 
                              1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 568 
                              584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 1101 
                              1118 502 501 1151 1130 1137 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 687 689 688 542  
                              686 681 543  547  537  536  534  535  706 702 704 709 708 710 695  
                              700 659  662 661 660 666 1134 665 669 658 668  670 667 675 674 672 664 
                              671 673 684  655  651  650  656  578  683  682  679  571  680  678  677  676  548  556  554  
                              569  572  570  541  559  557  553  
                              582  579  657  654  580  
                              652  653  1097 1098 1105 1104 1099 1103 1106 
                              1109 1108 1107 567  573  589  575  577  562  558  563  707  1185 506 1100 
                              711 712 713 1149 1141 499 
               714 576 555 705 703
         1126 1127 1128 1069 1070 1161 1170 1171 
         1083 1081 1080 1082 1092
                             }
   claimedprovinces    = { 241 242 244 247 254 245 238 255 257 251 240 248 250 239 249 258 256 253 } 

   # 
   # Soviet Techs 1942.11
   # ################ 
	techapps = {

	# Manufacturing
	5810 5820 5830 5050 5060 5070 5130
	# Assembly Line
	5140 5160 5180
	# Construction Engineering 
	5800 5080 5090 5100
	# Computers & cryptografi
	5310 54010 54020 54030 5320 5316 5326 5327 5350 5360
	# Agriculture  
	5700 5710 5010 5020 5020 5030
	# Radar
	5410 5416 5417
	# Oil Refining 
	5190 5200
	# Atomics
	5470 5480
	# Medicine
	5600 5610 5620 5630
	# Rocket
	5560
	# Specialised Equipment
	5920
	
	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120
	# Mountain Division 
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260 1270
	# Paratroopers
	1670
	# Motorized Inf
	1396 1400 1410
	# Cavalry
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
	# Mechanized Inf
	1470
	# Engineers
	1830 1840 1850 1860 1870
	# Supply 
	1910 1920 1930 1940 1950 1960 1970 1980 1990 199130

	# Early/Light Tank 
	7600 7610 2620 2010 2630 2640 2646 2650 2030 2040 2050 2100 2110
	# Medium Tank
	2070 2080 2090
	# Armoured Car  
	2860 2870 2880 2020 2150
	# Field Artillery 
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330
	# Self-Propelled Artillery
	2220 2230
	# Self-Propelled Rocket
	2980
	# Anti-tank Artillery
	2400 2410
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460
	# Anti-air Brig
	2810 2810 2820 2510 2520
 
 	# Hospital System 
	14000 14010 14020 14030
	# Great War Land Doctrines (central powers)
	6500 6510 6530 6550 6590 6600 6620 6650 6670 6680 6690 6700 6710 6910
	# Land Doctrines
	6570 6300 6900 6310 6320 6330

	# Light Cruiser 
	3110 3120 3130 3140 3150 3160 
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470 3480
	# Battlecruiser  
	3310 3320 3330 3340
	# Heavy Cruiser 
	3210 3220 3230 3240 3250 3260 12020
	# Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	# Submarine 
	3610 3620 3630 3640 3650 3660 3670
	# Light Carrier
	12100 12110 12120 12130
	# Fleet Carrier
	3510
	# Torpedo & ASW 18
	3720 3730 3736 3740 3750 3760 3900 3910
	# Troopships
	3810 3820 3830

	# Naval Doctrines 
	# Theory
	8070 8010 8020 8030 8040 8050 8060 8070 8080
	# Amphib
	82300
	# Logistics
	82500
	# Naval Interdiction
	8500 8510 8550 8560 8600 8610 8520
	# Indirect Approach
	81300 81310 81320 81330 81340 81350 81360
	# Naval Supremacy
	8100 8110 8120 8150 8160 8200 8210 8170

	# CAS
	4400 4170 4280
	# Inteceptor  
	4500 4510 4520 4530 4540 4550 4010 4020 4030
	# Tactical Bomber 
	4600 4610 4620 4630 4120 4130 4140
	# Multirole fighter
	4300 4310 4320 4330 4340 4040
	# Escort Fighter
	4050 4080
	# Strategic bomber
	4800 4810 4820 4220 4230
	# Navalbomber
	4700 4710 4190
	# Transports
	4290 4250
	# Seaplanes
	4740 4750 4760 4770 4780 4790 4850
	
	# Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 
	9010 9040 9050 9060 9070 9080 9090 9100 9110 9120 9130 9140 9150 9160 9170 9180 9190 9200 9210 9220 9230 9240
 	} 
	
inventions = { 3000027 }
   blueprints             = {   } 
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 1 
     political_left    = 10 
     freedom           = 1 
     free_market       = 1 
     professional_army = 6 
     defense_lobby     = 6 
     interventionism   = 4 
    } 
	peacetime_ic_mod       = 0.7
   headofstate            = {  type = 9 id = 30002  } # Stalin 
   headofgovernment       = {  type = 9 id = 30105  } # Stalin - since 6 May 1941 
   foreignminister        = {  type = 9 id = 30021  } 
   armamentminister       = {  type = 9 id = 30004  } 
   ministerofsecurity     = {  type = 9 id = 30028  } 
   ministerofintelligence = {  type = 9 id = 30035  } 
   chiefofstaff           = {  type = 9 id = 30040  } 
   chiefofarmy            = {  type = 9 id = 30046  } 
   chiefofnavy            = {  type = 9 id = 30049  } 
   chiefofair             = {  type = 9 id = 30053  }
   dormant_ministers      = {  30003 30005 30007 30009 30006 30010 30026 30027 30032 30033 30048 30053  }
   dormant_leaders        = {  30050 30040 30042 30044 30085 30095 30097 30101 30108 30111 30127 30131 30135 30152 30156 30170 30175 30192 30194 30207
                               30217 30220 30229 30232 30243 30255 30267 30272 30315 30316 30338 30339 30403 30409 30416 30454 30472 30477 30484 30487
                               30498 30523 30543 30547 30550 30570 30571 30572 30602 30618 30654 30664 30673 30678 30701 30715 30716 30717 30718 30719
                               30721 30722 30723 30650 30437 30050 30512 30007 30374 30238 30276 30681 30353 30687 30407 30697 30499 30004 30008 30028
                               30057 30059 30063 30081 30084 30090 30098 30100 30107 30120 30136 30172 30174 30186 30190 30191 30198 30199 30214 30215
                               30226 30242 30258 30263 30269 30275 30277 30296 30302 30324 30326 30345 30381 30391 30399 30401 30411 30419 30442 30445
                               30447 30491 30494 30509 30521 30548 30552 30576 30614 30658 30660 30720 30473 30778 30076 30216 30744 30266 30322 30463
                               30479 30538 30789 30313 30765 30767 30515 30776 30528 30758 30373 30564
                            }
#1942

   landunit = 
   {  id       = {  type = 10848 id =  1 } 
     name     = "Raboche-Krest'yanskaya Krasnaya Armyia" 
     location = 572 #Moscow 
     Division = 
     {  id       = {  type = 10848 id = 2  } 
       name     = "Generalnyi Shtab RKKA" 
       strength = 100
       type     = HQ
	   model    = 3
	   extra    = artillery
	   brigade_model    = 10	
	   experience = 30
	   } 
      Division = 
     {  id       = {  type = 10848 id = 1519  } 
       name     = "11-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1594  } 
       name     = "11-ya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1520  } 
       name     = "12-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1595  } 
       name     = "21-ya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1596  } 
       name     = "55-ya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1597  } 
       name     = "112-ya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1591  } 
       name     = "32-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 1521  } 
       name     = "63-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 1592  } 
       name     = "5-i Mekhanizirovannyi Korpus" 
       strength = 80 
       type     = mechanized
	   model    = 0 
	   extra    = armored_car
	   brigade_model = 4
      }
 } 
   landunit = 
   {  id       = {  type = 10848 id =  3 } 
     name     = "Karelskyi Front" 
     location = 535 
     Division = 
     {  id       = {  type = 10848 id = 4  } 
       name     = "Karelskyi Front" 
       strength = 60 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
	   }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  5 } 
     name     = "14-ya Armiya" 
     location = 535
     Division = 
     {  id       = {  type = 10848 id = 6  } 
       name     = "10-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 35
      }
     Division = 
     {  id       = {  type = 10848 id = 7  } 
       name     = "14-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  8 } 
     name     = "19-ya Armiya" 
     location = 536
     Division = 
     {  id       = {  type = 10848 id = 9  } 
       name     = "104-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 10  } 
       name     = "122-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  184 } 
     name     = "26-ya Armiya" 
     location = 537
     Division = 
     {  id       = {  type = 10848 id = 185  } 
       name     = "27-ya Omskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 9
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 186  } 
       name     = "54-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  12 } 
     name     = "32-ya Armiya" 
     location = 541
     Division = 
     {  id       = {  type = 10848 id = 13  } 
       name     = "37-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 14  } 
       name     = "289-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 15  } 
       name     = "313-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 16  } 
       name     = "367-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  17 } 
     name     = "Leningradskyi Front" 
     location = 553 
     Division = 
     {  id       = {  type = 10848 id = 18  } 
       name     = "Leningradskyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
	   }
     Division = 
     {  id       = {  type = 10848 id = 19  } 
       name     = "63-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 20  } 
       name     = "86-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 21  } 
       name     = "123-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 22  } 
       name     = "268-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  23 } 
     name     = "23-ya Armiya" 
     location = 553
     Division = 
     {  id       = {  type = 10848 id = 24  } 
       name     = "10-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 9
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 25  } 
       name     = "92-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 26  } 
       name     = "291-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  27 } 
     name     = "42-ya Armiya" 
     location = 553
     Division = 
     {  id       = {  type = 10848 id = 28  } 
       name     = "85-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 29  } 
       name     = "109-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 30  } 
       name     = "125-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  31 } 
     name     = "55-ya Armiya" 
     location = 553 
     Division = 
     {  id       = {  type = 10848 id = 32  } 
       name     = "45-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 33  } 
       name     = "43-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 34  } 
       name     = "56-ya Moskovskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 35  } 
       name     = "72-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  36 } 
     name     = "67-ya Armiya" 
     location = 553 
     Division = 
     {  id       = {  type = 10848 id = 37  } 
       name     = "13-ya Dagestanskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 38  } 
       name     = "46-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 39  } 
       name     = "90-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 40  } 
       name     = "142-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 41  } 
       name     = "189-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 42  } 
       name     = "224-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  43 } 
     name     = "Volhovskyi Front" 
     location = 556 
     Division = 
     {  id       = {  type = 10848 id = 44  } 
       name     = "Volhovskyi Front" 
       strength = 70 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
	   }
     Division = 
     {  id       = {  type = 10848 id = 45  } 
       name     = "64-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 189  } 
       name     = "128-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 46  } 
       name     = "165-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 47  } 
       name     = "372-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 48  } 
       name     = "374-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  49 } 
     name     = "2-ya Udarnaya Armiya" 
     location = 562 
     Division = 
     {  id       = {  type = 10848 id = 50  } 
       name     = "11-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 51  } 
       name     = "18-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 52  } 
       name     = "71-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 53  } 
       name     = "80-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 55  } 
       name     = "147-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 56  } 
       name     = "191-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 57  } 
       name     = "239-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 1700  } 
       name     = "256-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 58  } 
       name     = "314-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 59  } 
       name     = "364-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 60  } 
       name     = "376-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 61  } 
       name     = "379-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  62 } 
     name     = "4-ya Armiya" 
     location = 558 
     Division = 
     {  id       = {  type = 10848 id = 63  } 
       name     = "44-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 64  } 
       name     = "288-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 1701  } 
       name     = "310-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  65 } 
     name     = "8-ya Armiya" 
     location = 577 
     Division = 
     {  id       = {  type = 10848 id = 66  } 
       name     = "265-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 67  } 
       name     = "286-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  68 } 
     name     = "52-ya Armiya" 
     location = 559 
     Division = 
     {  id       = {  type = 10848 id = 69  } 
       name     = "65-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 70  } 
       name     = "225-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  71 } 
     name     = "54-ya Armiya" 
     location = 557 
     Division = 
     {  id       = {  type = 10848 id = 72  } 
       name     = "115-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 73  } 
       name     = "177-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 74  } 
       name     = "198-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 75  } 
       name     = "281-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 76  } 
       name     = "285-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 77  } 
       name     = "294-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 78  } 
       name     = "311-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  79 } 
     name     = "59-ya Armiya" 
     location = 559 
     Division = 
     {  id       = {  type = 10848 id = 80  } 
       name     = "2-ya Belorusskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 81  } 
       name     = "377-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 82  } 
       name     = "378-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 83  } 
       name     = "382-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  84 } 
     name     = "Severo-Zapadnyi Front" 
     location = 558 
     Division = 
     {  id       = {  type = 10848 id = 85  } 
       name     = "Severo-Zapadnyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
	   }
      Division = 
     {  id       = {  type = 10848 id = 1498  } 
       name     = "3-i Mekhanizirovannyi Korpus" 
       strength = 80 
       type     = mechanized
	   model    = 0 
	   extra = artillery
	   brigade_model = 9
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  86 } 
     name     = "1-ya Udarnaya Armiya" 
     location = 571 
     Division = 
     {  id       = {  type = 10848 id = 87  } 
       name     = "7-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 88  } 
       name     = "23-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 89  } 
       name     = "53-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 90  } 
       name     = "129-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 91  } 
       name     = "380-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 92  } 
       name     = "391-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 93  } 
       name     = "397-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  94 } 
     name     = "11-ya Armiya" 
     location = 558 
     Division = 
     {  id       = {  type = 10848 id = 95  } 
       name     = "26-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 97  } 
       name     = "163-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 96  } 
       name     = "202-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 98  } 
       name     = "282-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 99  } 
       name     = "28-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 100  } 
       name     = "43-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 101  } 
       name     = "55-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 102  } 
       name     = "188-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 103  } 
       name     = "254-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 104  } 
       name     = "370-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  105 } 
     name     = "27-ya Armiya" 
     location = 558 
     Division = 
     {  id       = {  type = 10848 id = 106  } 
       name     = "170-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 107  } 
       name     = "253-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  108 } 
     name     = "34-ya Armiya" 
     location = 577 
     Division = 
     {  id       = {  type = 10848 id = 109  } 
       name     = "171-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 110  } 
       name     = "182-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 111  } 
       name     = "200-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 112  } 
       name     = "245-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  113 } 
     name     = "53-ya Armiya" 
     location = 559 
     Division = 
     {  id       = {  type = 10848 id = 114  } 
       name     = "166-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 116  } 
       name     = "235-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 117  } 
       name     = "241-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 118  } 
       name     = "250-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 119  } 
       name     = "348-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  120 } 
     name     = "Kalininskyi Front" 
     location = 569 
     Division = 
     {  id       = {  type = 10848 id = 121  } 
       name     = "Kalininsknyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
	   }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  122 } 
     name     = "3-ya Udarnaya Armiya" 
     location = 573 
     Division = 
     {  id       = {  type = 10848 id = 123  } 
       name     = "8-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 124  } 
       name     = "9-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 125  } 
       name     = "21-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 126  } 
       name     = "28-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 127  } 
       name     = "32-ya Saratovskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 128  } 
       name     = "33-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 129  } 
       name     = "46-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 130  } 
       name     = "117-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 131  } 
       name     = "150-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 132  } 
       name     = "257-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 133  } 
       name     = "357-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 134  } 
       name     = "360-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 135  } 
       name     = "381-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  136 } 
     name     = "4-ya Udarnaya Armiya" 
     location = 577 
     Division = 
     {  id       = {  type = 10848 id = 137  } 
       name     = "47-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 138  } 
       name     = "332-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 139  } 
       name     = "334-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 140  } 
       name     = "358-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  141 } 
     name     = "22-ya Armiya" 
     location = 589 
     Division = 
     {  id       = {  type = 10848 id = 142  } 
       name     = "155-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 143  } 
       name     = "362-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 144  } 
       name     = "3-ya Motostrelkovaya Divizyia" 
       strength = 100 
       type     = motorized 
	   model    = 1
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 145  } 
       name     = "185-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  146 } 
     name     = "39-ya Armiya" 
     location = 575 
     Division = 
     {  id       = {  type = 10848 id = 147  } 
       name     = "135-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 148  } 
       name     = "158-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 149  } 
       name     = "178-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 150  } 
       name     = "186-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 151  } 
       name     = "373-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  152 } 
     name     = "41-ya Armiya" 
     location = 572 
     Division = 
     {  id       = {  type = 10848 id = 153  } 
       name     = "74-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 154  } 
       name     = "75-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 155  } 
       name     = "78-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 156  } 
       name     = "91-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 157  } 
       name     = "93-ya Vostochno-Sibir. Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 158  } 
       name     = "17-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 159  } 
       name     = "134-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 160  } 
       name     = "262-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 161  } 
       name     = "1-ya Motostrelkovaya Divizyia" 
       strength = 100 
       type     = motorized 
	   model    = 1
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  162 } 
     name     = "43-ya Armiya" 
     location = 589 
     Division = 
     {  id       = {  type = 10848 id = 163  } 
       name     = "145-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 164  } 
       name     = "179-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 165  } 
       name     = "234-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 166  } 
       name     = "306-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  167 } 
     name     = "Zapadnyi Front" 
     location = 579 
     Division = 
     {  id       = {  type = 10848 id = 168  } 
       name     = "Zapadnyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
	   }
     Division = 
     {  id       = {  type = 10848 id = 169  } 
       name     = "1-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 170  } 
       name     = "16-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 1702  } 
       name     = "19-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 171  } 
       name     = "20-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 173  } 
       name     = "113-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 174  } 
       name     = "139-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 175  } 
       name     = "194-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 176  } 
       name     = "246-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 177  } 
       name     = "247-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 178  } 
       name     = "326-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 179  } 
       name     = "354-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 180  } 
       name     = "375-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 181  } 
       name     = "5-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 2 
      }
      Division = 
     {  id       = {  type = 10848 id = 182  } 
       name     = "6-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 2 
      }
      Division = 
     {  id       = {  type = 10848 id = 183  } 
       name     = "9-i Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 477  } 
       name     = "1-i Mekhanizirovannyi Korpus" 
       strength = 60 
       type     = mechanized
	   model    = 0 
	   extra    = armored_car
	   brigade_model = 4
      }
      Division = 
     {  id       = {  type = 10848 id = 1439  } 
       name     = "1-i Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 1 
	   extra = heavy_armor
	   brigade_model = 2
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  190 } 
     name     = "5-ya Armiya" 
     location = 576 
     Division = 
     {  id       = {  type = 10848 id = 191  } 
       name     = "29-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 192  } 
       name     = "108-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 193  } 
       name     = "144-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 194  } 
       name     = "352-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  195 } 
     name     = "10-ya Armiya" 
     location = 584 
     Division = 
     {  id       = {  type = 10848 id = 196  } 
       name     = "31-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 197  } 
       name     = "290-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 198  } 
       name     = "323-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 199  } 
       name     = "330-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 200  } 
       name     = "385-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  201 } 
     name     = "16-ya Armiya" 
     location = 567 
     Division = 
     {  id       = {  type = 10848 id = 202  } 
       name     = "11-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 203  } 
       name     = "97-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 204  } 
       name     = "217-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 205  } 
       name     = "324-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  1703 } 
     name     = "20-ya Armiya" 
     location = 576 
     Division = 
     {  id       = {  type = 10848 id = 1704  } 
       name     = "26-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 1705  } 
       name     = "30-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 1706  } 
       name     = "42-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 1707  } 
       name     = "251-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 1708  } 
       name     = "331-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 1709  } 
       name     = "336-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 1710  } 
       name     = "415-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  206 } 
     name     = "29-ya Armiya" 
     location = 568 
     Division = 
     {  id       = {  type = 10848 id = 207  } 
       name     = "82-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 208  } 
       name     = "312-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  209 } 
     name     = "30-ya Armiya" 
     location = 567 
     Division = 
     {  id       = {  type = 10848 id = 210  } 
       name     = "215-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 211  } 
       name     = "220-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 212  } 
       name     = "274-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 213  } 
       name     = "359-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 214  } 
       name     = "369-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  215 } 
     name     = "31-ya Armiya" 
     location = 568 
     Division = 
     {  id       = {  type = 10848 id = 216  } 
       name     = "88-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 217  } 
       name     = "118-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 218  } 
       name     = "133-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 219  } 
       name     = "371-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  220 } 
     name     = "33-ya Armiya" 
     location = 576 
     Division = 
     {  id       = {  type = 10848 id = 383  } 
       name     = "5-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 221  } 
       name     = "17-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 222  } 
       name     = "50-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 223  } 
       name     = "53-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 224  } 
       name     = "110-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 225  } 
       name     = "160-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 226  } 
       name     = "222-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  227 } 
     name     = "49-ya Armiya" 
     location = 584 
     Division = 
     {  id       = {  type = 10848 id = 228  } 
       name     = "18-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 229  } 
       name     = "42-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 230  } 
       name     = "164-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  231 } 
     name     = "50-ya Armiya" 
     location = 583 
     Division = 
     {  id       = {  type = 10848 id = 232  } 
       name     = "58-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 233  } 
       name     = "69-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 234  } 
       name     = "146-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 235  } 
       name     = "325-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 236  } 
       name     = "344-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 237  } 
       name     = "413-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  238 } 
     name     = "61-ya Armiya" 
     location = 583 
     Division = 
     {  id       = {  type = 10848 id = 239  } 
       name     = "12-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  240 } 
     name     = "Voronezhskyi Front" 
     location = 652 
     Division = 
     {  id       = {  type = 10848 id = 241  } 
       name     = "Voronezhskyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
	   }
     Division = 
     {  id       = {  type = 10848 id = 242  } 
       name     = "137-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 270  } 
       name     = "4-i Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 1 
	   extra = heavy_armor
	   brigade_model = 2
      }
      Division = 
     {  id       = {  type = 10848 id = 243  } 
       name     = "11-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 1 
	   extra = tank_destroyer
	   brigade_model = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 244  } 
       name     = "19-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1459  } 
       name     = "3-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1460  } 
       name     = "4-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1461  } 
       name     = "20-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  245 } 
     name     = "3-ya Armiya" 
     location = 582 
     Division = 
     {  id       = {  type = 10848 id = 246  } 
       name     = "5-ya Vitebskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 247  } 
       name     = "60-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 248  } 
       name     = "269-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 249  } 
       name     = "283-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 250  } 
       name     = "287-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 251  } 
       name     = "20-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 1 
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  252 } 
     name     = "13-ya Armiya" 
     location = 580 
     Division = 
     {  id       = {  type = 10848 id = 253  } 
       name     = "8-ya Minskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 254  } 
       name     = "15-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 255  } 
       name     = "81-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 256  } 
       name     = "132-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 257  } 
       name     = "148-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 258  } 
       name     = "211-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 259  } 
       name     = "280-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 260  } 
       name     = "307-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  261 } 
     name     = "48-ya Armiya" 
     location = 580 
     Division = 
     {  id       = {  type = 10848 id = 262  } 
       name     = "41-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 263  } 
       name     = "73-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 264  } 
       name     = "143-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 265  } 
       name     = "399-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  266 } 
     name     = "2-ya Tankovaya Armiya" 
     location = 582 
     Division = 
     {  id       = {  type = 10848 id = 267  } 
       name     = "6-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 268  } 
       name     = "16-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 269  } 
       name     = "16-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 1 
      }
     Division = 
     {  id       = {  type = 10848 id = 272  } 
       name     = "161-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 273  } 
       name     = "180-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 274  } 
       name     = "218-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 275  } 
       name     = "270-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  276 } 
     name     = "38-ya Armiya" 
     location = 654 
     Division = 
     {  id       = {  type = 10848 id = 277  } 
       name     = "167-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 278  } 
       name     = "206-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 279  } 
       name     = "232-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 280  } 
       name     = "237-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 281  } 
       name     = "240-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  286 } 
     name     = "40-ya Armiya" 
     location = 653 
     Division = 
     {  id       = {  type = 10848 id = 287  } 
       name     = "25-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 288  } 
       name     = "100-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 289  } 
       name     = "107-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 290  } 
       name     = "183-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 291  } 
       name     = "303-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 292  } 
       name     = "305-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 293  } 
       name     = "309-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 294  } 
       name     = "340-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  282 } 
     name     = "60-ya Armiya" 
     location = 654 
     Division = 
     {  id       = {  type = 10848 id = 283  } 
       name     = "121-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 284  } 
       name     = "141-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 285  } 
       name     = "322-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  295 } 
     name     = "3-ya Tankovaya Armiya" 
     location = 653 
     Division = 
     {  id       = {  type = 10848 id = 296  } 
       name     = "48-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 297  } 
       name     = "62-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 298  } 
       name     = "111-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 299  } 
       name     = "184-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 300  } 
       name     = "12-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 2 
	   extra = heavy_armor
	   brigade_model = 2
      }
      Division = 
     {  id       = {  type = 10848 id = 301  } 
       name     = "15-i Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 1 
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  302 } 
     name     = "Yugo-Zapadnyi Front" 
     location = 669 
     Division = 
     {  id       = {  type = 10848 id = 303  } 
       name     = "Yugo-Zapadnyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
	   }
      Division = 
     {  id       = {  type = 10848 id = 1711  } 
       name     = "1-i Gvardyeiskaya Tankovaya Korpus" 
       strength = 90 
       type     = armor
	   model    = 1 
	   extra = heavy_armor
	   brigade_model = 2
      }
      Division = 
     {  id       = {  type = 10848 id = 304  } 
       name     = "3-i Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 305  } 
       name     = "10-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 1 
	   extra = heavy_armor
	   brigade_model = 2
      }
      Division = 
     {  id       = {  type = 10848 id = 306  } 
       name     = "18-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 1 
	   extra = tank_destroyer
	   brigade_model = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 307  } 
       name     = "25-i Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 2 
      }
      Division = 
     {  id       = {  type = 10848 id = 1543  } 
       name     = "1-i Gvardyeiskaya Mekhanizirovannyi Korpus" 
       strength = 80 
       type     = mechanized
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1542  } 
       name     = "6-i Mekhanizirovannyi Korpus" 
       strength = 80 
       type     = mechanized
	   model    = 0 
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  308 } 
     name     = "1-ya Gvardyeiskaya Armiya" 
     location = 655 
     Division = 
     {  id       = {  type = 10848 id = 309  } 
       name     = "35-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 310  } 
       name     = "38-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 311  } 
       name     = "41-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 312  } 
       name     = "44-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 313  } 
       name     = "57-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 314  } 
       name     = "58-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 315  } 
       name     = "68-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 316  } 
       name     = "195-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 317  } 
       name     = "244-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  318 } 
     name     = "3-ya Gvardyeiskaya Armiya" 
     location = 659 
     Division = 
     {  id       = {  type = 10848 id = 320  } 
       name     = "50-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 321  } 
       name     = "59-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 322  } 
       name     = "60-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 323  } 
       name     = "61-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 325  } 
       name     = "203-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 326  } 
       name     = "243-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 327  } 
       name     = "266-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 328  } 
       name     = "279-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
      Division = 
     {  id       = {  type = 10848 id = 1712  } 
       name     = "2-i Gvardyeiskaya Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 2 
	   extra = heavy_armor
	   brigade_model = 2
       offensive = { year = 1943 month = february day = 15 }
      }
      Division = 
     {  id       = {  type = 10848 id = 330  } 
       name     = "2-i Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 1 
	   extra = heavy_armor
	   brigade_model = 2
       offensive = { year = 1943 month = february day = 15 }
      }
      Division = 
     {  id       = {  type = 10848 id = 331  } 
       name     = "23-i Tankovaya Korpus" 
       strength = 80 
       type     = light_armor
	   model    = 2 
	   extra = armored_car
	   brigade_model = 4
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  332 } 
     name     = "6-ya Armiya" 
     location = 655 
     Division = 
     {  id       = {  type = 10848 id = 333  } 
       name     = "6-ya Orlovskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 334  } 
       name     = "172-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 335  } 
       name     = "267-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 336  } 
       name     = "350-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 485  } 
       name     = "1-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 11
	extra = armored_car
	brigade_model = 4
      }
      Division = 
     {  id       = {  type = 10848 id = 486  } 
       name     = "2-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 487  } 
       name     = "7-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 60 
       type     = cavalry
	   model    = 11
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  337 } 
     name     = "5-ya Tankovaya Armiya" 
     location = 662 
     Division = 
     {  id       = {  type = 10848 id = 1713  } 
       name     = "47-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 1714  } 
       name     = "54-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 338  } 
       name     = "321-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 339  } 
       name     = "333-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 340  } 
       name     = "346-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 341  } 
       name     = "5-ya Motostrelkovaya Divizyia" 
       strength = 100 
       type     = motorized 
	   model    = 1
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  342 } 
     name     = "Donskyi Front" 
     location = 659 
     Division = 
     {  id       = {  type = 10848 id = 343  } 
       name     = "Donskyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  344 } 
     name     = "21-ya Armiya" 
     location = 659 
     Division = 
     {  id       = {  type = 10848 id = 1715  } 
       name     = "51-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 1716  } 
       name     = "52-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 1717  } 
       name     = "66-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 345  } 
       name     = "96-ya Vinnickaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 346  } 
       name     = "120-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 347  } 
       name     = "173-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 348  } 
       name     = "252-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 349  } 
       name     = "298-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  350 } 
     name     = "62-ya Armiya" 
     location = 660 
     Division = 
     {  id       = {  type = 10848 id = 1718  } 
       name     = "13-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 172  } 
       name     = "19-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 351  } 
       name     = "45-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 352  } 
       name     = "95-ya Moldavskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 353  } 
       name     = "138-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 354  } 
       name     = "284-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  355 } 
     name     = "64-ya Armiya" 
     location = 662 
     Division = 
     {  id       = {  type = 10848 id = 1719  } 
       name     = "15-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 1720  } 
       name     = "36-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 356  } 
       name     = "29-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 357  } 
       name     = "38-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 358  } 
       name     = "204-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 359  } 
       name     = "422-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  360 } 
     name     = "65-ya Armiya" 
     location = 661 
     Division = 
     {  id       = {  type = 10848 id = 1721  } 
       name     = "27-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 1722  } 
       name     = "67-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 361  } 
       name     = "23-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 362  } 
       name     = "24-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 363  } 
       name     = "214-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 364  } 
       name     = "233-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 365  } 
       name     = "260-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  366 } 
     name     = "66-ya Armiya" 
     location = 660 
     Division = 
     {  id       = {  type = 10848 id = 367  } 
       name     = "84-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 368  } 
       name     = "99-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 369  } 
       name     = "116-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 370  } 
       name     = "226-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 1723  } 
       name     = "243-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 372  } 
       name     = "273-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 373  } 
       name     = "299-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  374 } 
     name     = "Stalingradskyi Front" 
     location = 662 
     Division = 
     {  id       = {  type = 10848 id = 375  } 
       name     = "Stalingradskyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
      Division = 
     {  id       = {  type = 10848 id = 1589  } 
       name     = "5-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
       offensive = { year = 1943 month = february day = 15 }
      }
      Division = 
     {  id       = {  type = 10848 id = 1590  } 
       name     = "6-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  376 } 
     name     = "5-ya Udarnaya Armiya" 
     location = 1113 
     Division = 
     {  id       = {  type = 10848 id = 377  } 
       name     = "4-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 378  } 
       name     = "40-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 379  } 
       name     = "258-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 380  } 
       name     = "315-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 1567  } 
       name     = "9-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1568  } 
       name     = "10-ya Gvardyeiskaya Kavaleriiskaya Divizyia" 
       strength = 80 
       type     = cavalry
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 1569  } 
       name     = "30-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 1570  } 
       name     = "4-i Mekhanizirovannyi Korpus" 
       strength = 60 
       type     = mechanized
	   model    = 0 
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  381 } 
     name     = "2-ya Gvardyeiskaya Armiya" 
     location = 1113 
     Division = 
     {  id       = {  type = 10848 id = 382  } 
       name     = "2-ya Gvardyeiskaya Motostrelkovaya Divizyia" 
       strength = 100 
       type     = motorized 
	   model    = 1
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 1725  } 
       name     = "5-ya Gvardyeiskaya Motostrelkovaya Divizyia" 
       strength = 100 
       type     = motorized 
	   model    = 1
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
      Division = 
     {  id       = {  type = 10848 id = 1726  } 
       name     = "3-i Gvardyeiskaya Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 1 
	   extra = heavy_armor
	   brigade_model = 0
      }
     Division = 
     {  id       = {  type = 10848 id = 384  } 
       name     = "3-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 385  } 
       name     = "24-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 386  } 
       name     = "33-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 387  } 
       name     = "49-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 388  } 
       name     = "98-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 1724  } 
       name     = "300-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 389  } 
       name     = "387-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 1561  } 
       name     = "2-i Gvardyeiskaya Mekhanizirovannyi Korpus" 
       strength = 80 
       type     = mechanized
	   model    = 0 
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  390 } 
     name     = "28-ya Armiya" 
     location = 699 
     Division = 
     {  id       = {  type = 10848 id = 391  } 
       name     = "34-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 392  } 
       name     = "248-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  393 } 
     name     = "51-ya Armiya" 
     location = 662 
     Division = 
     {  id       = {  type = 10848 id = 394  } 
       name     = "3-ya Gvardyeiskaya Motostrelkovaya Divizyia" 
       strength = 100 
       type     = motorized 
	   model    = 1
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 395  } 
       name     = "4-ya Gvardyeiskaya Motostrelkovaya Divizyia" 
       strength = 100 
       type     = motorized 
	   model    = 1
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 396  } 
       name     = "87-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 397  } 
       name     = "126-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 398  } 
       name     = "302-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  483 } 
     name     = "57-ya Armiya" 
     location = 662 
     Division = 
     {  id       = {  type = 10848 id = 319  } 
       name     = "14-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
     Division = 
     {  id       = {  type = 10848 id = 484  } 
       name     = "52-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
       offensive = { year = 1943 month = february day = 15 }
      }
      Division = 
     {  id       = {  type = 10848 id = 488  } 
       name     = "22-i Tankovaya Korpus" 
       strength = 80 
       type     = armor
	   model    = 2 
	   extra = heavy_armor
	   brigade_model = 2
       offensive = { year = 1943 month = february day = 15 }
      }
   dig_in = 20.000
 }

   landunit = 
   {  id       = {  type = 10848 id =  399 } 
     name     = "Zakavkazskyi Front" 
     location = 709 
     Division = 
     {  id       = {  type = 10848 id = 400  } 
       name     = "Zakavkazskyi Front" 
       strength = 70 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 4
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 1583  } 
       name     = "1-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 1584  } 
       name     = "23-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 1585  } 
       name     = "39-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  401 } 
     name     = "44-ya Armiya" 
     location = 700 
     Division = 
     {  id       = {  type = 10848 id = 402  } 
       name     = "151-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 403  } 
       name     = "271-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 404  } 
       name     = "320-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 405  } 
       name     = "347-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 406  } 
       name     = "416-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  407 } 
     name     = "9-ya Armiya" 
     location = 702 
     Division = 
     {  id       = {  type = 10848 id = 408  } 
       name     = "7-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 409  } 
       name     = "10-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 410  } 
       name     = "89-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  411 } 
     name     = "37-ya Armiya" 
     location = 703 
     Division = 
     {  id       = {  type = 10848 id = 412  } 
       name     = "2-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
	   extra    = artillery
	   brigade_model = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 413  } 
       name     = "223-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 414  } 
       name     = "295-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 415  } 
       name     = "389-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 416  } 
       name     = "409-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 417  } 
       name     = "414-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  418 } 
     name     = "58-ya Armiya" 
     location = 699 
     Division = 
     {  id       = {  type = 10848 id = 419  } 
       name     = "77-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 420  } 
       name     = "276-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 421  } 
       name     = "317-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 422  } 
       name     = "351-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 423  } 
       name     = "417-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  424 } 
     name     = "18-ya Armiya" 
     location = 708 
     Division = 
     {  id       = {  type = 10848 id = 425  } 
       name     = "236-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 426  } 
       name     = "353-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 427  } 
       name     = "395-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  428 } 
     name     = "46-ya Armiya" 
     location = 708 
     Division = 
     {  id       = {  type = 10848 id = 429  } 
       name     = "31-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  430 } 
     name     = "47-ya Armiya" 
     location = 695 
     Division = 
     {  id       = {  type = 10848 id = 431  } 
       name     = "176-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 432  } 
       name     = "216-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 433  } 
       name     = "318-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 434  } 
       name     = "337-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 435  } 
       name     = "339-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 436  } 
       name     = "383-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
      Division = 
     {  id       = {  type = 10848 id = 1524  } 
       name     = "3-i Gvardyeiskaya Mekhanizirovannyi Korpus" 
       strength = 80 
       type     = mechanized
	   model    = 0 
	   extra    = tank_destroyer
	   brigade_model = 0
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  437 } 
     name     = "56-ya Armiya" 
     location = 710 
     Division = 
     {  id       = {  type = 10848 id = 438  } 
       name     = "32-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 439  } 
       name     = "55-ya Gvardyeiskaya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 440  } 
       name     = "61-ya Strelkovaya Divizyia" 
       strength = 100 
       type     = infantry 
	   model    = 11
	   experience = 30
      }
     Division = 
     {  id       = {  type = 10848 id = 441  } 
       name     = "394-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
	   experience = 30
      }
   dig_in = 20.000
 }
   landunit = 
   {  id       = {  type = 10848 id =  442 } 
     name     = "Zabaikalskyi Front" 
     location = 1162
     Division = 
     {  id       = {  type = 10848 id = 443  } 
       name     = "Zabaikalskyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 2
	   }
     Division = 
     {  id       = {  type = 10848 id = 444  } 
       name     = "103-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 1625  } 
       name     = "59-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  445 } 
     name     = "17-ya Armiya" 
     location = 1168
     Division = 
     {  id       = {  type = 10848 id = 446  } 
       name     = "36-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 447  } 
       name     = "57-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  448 } 
     name     = "36-ya Armiya" 
     location = 1169
     Division = 
     {  id       = {  type = 10848 id = 449  } 
       name     = "94-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 450  } 
       name     = "209-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 451  } 
       name     = "210-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  452 } 
     name     = "Dalnevostochnyi Front" 
     location = 1191
     Division = 
     {  id       = {  type = 10848 id = 453  } 
       name     = "Dalnevostochnyi Front" 
       strength = 80 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 2
	   }
      Division = 
     {  id       = {  type = 10848 id = 1593  } 
       name     = "8-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  454 } 
     name     = "1-ya Krasnaya Znameni Armiya" 
     location = 1190
     Division = 
     {  id       = {  type = 10848 id = 457  } 
       name     = "22-ya Krasnodarskaya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 460  } 
       name     = "39-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 458  } 
       name     = "59-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 455  } 
       name     = "187-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 1621  } 
       name     = "67-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
      Division = 
     {  id       = {  type = 10848 id = 1622  } 
       name     = "84-ya Kavaleriiskaya Divizyia" 
       strength = 70 
       type     = cavalry
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  461 } 
     name     = "2-ya Krasnaya Znameni Armiya" 
     location = 1196
     Division = 
     {  id       = {  type = 10848 id = 462  } 
       name     = "3-ya Tihookeanskaya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 463  } 
       name     = "12-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  464 } 
     name     = "15-ya Armiya" 
     location = 1175
     Division = 
     {  id       = {  type = 10848 id = 465  } 
       name     = "34-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  466 } 
     name     = "25-ya Armiya" 
     location = 1170
     Division = 
     {  id       = {  type = 10848 id = 467  } 
       name     = "40-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 468  } 
       name     = "105-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 469  } 
       name     = "190-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  470 } 
     name     = "35-ya Armiya" 
     location = 1190
     Division = 
     {  id       = {  type = 10848 id = 471  } 
       name     = "35-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
     Division = 
     {  id       = {  type = 10848 id = 472  } 
       name     = "66-ya Strelkovaya Divizyia" 
       strength = 90 
       type     = infantry 
	   model    = 10
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  479 } 
     name     = "Uralskyi Voennyi Okrug" 
     location = 1151
     Division = 
     {  id       = {  type = 10848 id = 480  } 
       name     = "Uralskyi Voennyi Okrug" 
       strength = 60 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 2
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  481 } 
     name     = "Sibirskyi Voennyi Okrug" 
     location = 1142
     Division = 
     {  id       = {  type = 10848 id = 482  } 
       name     = "Sibirskyi Voennyi Okrug" 
       strength = 60 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 2
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1400 } 
     name     = "4-i Vozdushno-Desantnye Korpus" 
     location = 575
     Division = 
     {  id       = {  type = 10848 id = 1401  } 
       name     = "4-i Vozdushno-Desantnye Korpus" 
       strength = 70 
       type     = paratrooper 
	   model    = 1
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1402 } 
     name     = "8-i Vozdushno-Desantnye Korpus" 
     location = 571
     Division = 
     {  id       = {  type = 10848 id = 1403  } 
       name     = "8-i Vozdushno-Desantnye Korpus" 
       strength = 70 
       type     = paratrooper 
	   model    = 1
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1404 } 
     name     = "1-i Vozdushno-Desantnye Korpus" 
     location = 572
     Division = 
     {  id       = {  type = 10848 id = 1405  } 
       name     = "1-i Vozdushno-Desantnye Korpus" 
       strength = 70 
       type     = paratrooper 
	   model    = 1
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1406 } 
     name     = "6-i Vozdushno-Desantnye Korpus" 
     location = 577
     Division = 
     {  id       = {  type = 10848 id = 1407  } 
       name     = "6-i Vozdushno-Desantnye Korpus" 
       strength = 70 
       type     = paratrooper 
	   model    = 1
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1631 } 
     name     = "Arhangelskyi Voennyi Okrug" 
     location = 542
     Division = 
     {  id       = {  type = 10848 id = 1632  } 
       name     = "Arhangelskyi Voennyi Okrug" 
       strength = 70 
       type     = HQ
	   model    = 3
	   extra    = anti_air
	   brigade_model = 0
	   }
 }

# Air OOB
#MVO
airunit = { 
	id = { type = 10848 id = 7004 } 
	name = "Dal'nii Vostok Vozdushnogo Komandovaniya" 
	location = 1191 # Vladivostok 
	base = 1191 # Vladivostok 

	division = { 
	id = { type = 10848 id = 7005 } 
		name = "29.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7006 } 
		name = "79.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7007 } 
		name = "31.TBABR" 
		strength = 50 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7008 } 
		name = "32.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7001 } 
		name = "34.LSHABR" 
		strength = 80 
		type = cas 
		model = 2 
			}
	division = { 
	id = { type = 10848 id = 7002 } 
		name = "69.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			} 
	division = { 
	id = { type = 10848 id = 7003 } 
		name = "70.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	}
airunit = { 
	id = { type = 10848 id = 7016 } 
	name = "Leningradskaya Vozdushnogo Komandovaniya" 
	location = 553 # Leningrad
	base = 553 # Leningrad 

	division = { 
	id = { type = 10848 id = 7017 } 
		name = "1.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7018 } 
		name = "2.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7019 } 
		name = "4.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7020 } 
		name = "5.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7010 } 
		name = "23.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7011 } 
		name = "24.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7012 } 
		name = "26.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7013 } 
		name = "40.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7014 } 
		name = "41.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7015 } 
		name = "3.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	}
airunit = { 
	id = { type = 10848 id = 7037 } 
	name = "Zapadnyi Front Vozdushnogo Komandovaniya" 
	location = 572 # Moskva
	base = 572 # Moskva 

	division = { 
	id = { type = 10848 id = 7038 } 
		name = "9.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7039 } 
		name = "10.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7040 } 
		name = "11.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7041 } 
		name = "25.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7032 } 
		name = "28.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7033 } 
		name = "31.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7034 } 
		name = "29.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 3 
			}
	division = { 
	id = { type = 10848 id = 7035 } 
		name = "30.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 3 
			}
	division = { 
	id = { type = 10848 id = 7036 } 
		name = "42.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 3 
			}
	}
airunit = { 
	id = { type = 10848 id = 7048 } 
	name = "Yugo-Zapadnogo Fronta Vozdushnogo Komandovaniya" 
	location = 654 # Voronezh
	base = 654 # Voronezh

	division = { 
	id = { type = 10848 id = 7049 } 
		name = "14.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5  
			}
	division = { 
	id = { type = 10848 id = 7050 } 
		name = "15.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7051 } 
		name = "16.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7052 } 
		name = "17.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7043 } 
		name = "19.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7044 } 
		name = "32.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7045 } 
		name = "33.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7046 } 
		name = "37.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7047 } 
		name = "34.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 3 
			}
	}
airunit = { 
	id = { type = 10848 id = 7058 } 
	name = "Yuzhnyi Front Vozdushnogo Komandovaniya" 
	location = 653 # Pavlosk 
	base = 653 # Pavlosk 

	division = { 
	id = { type = 10848 id = 7059 } 
		name = "20.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7060 } 
		name = "21.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7061 } 
		name = "22.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7062 } 
		name = "27.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7054 } 
		name = "18.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7055 } 
		name = "45.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7056 } 
		name = "35.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 3 
			}
	division = { 
	id = { type = 10848 id = 7057 } 
		name = "38.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 4 
			}
	}
airunit = { 
	id = { type = 10848 id = 7068 } 
	name = "Moskva Vozdushnogo Komandovaniya" 
	location = 572 # Moscow 
	base = 572 # Moscow 

	division = { 
	id = { type = 10848 id = 7069 } 
		name = "36.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7070 } 
		name = "43.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7071 } 
		name = "46./48.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 1
			}
	division = { 
	id = { type = 10848 id = 7072 } 
		name = "49./50.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 1
			}
	division = { 
	id = { type = 10848 id = 7064 } 
		name = "44.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7065 } 
		name = "47.LSHABR" 
		strength = 80 
		type = cas 
		model = 2 
			}
	division = { 
	id = { type = 10848 id = 7066 } 
		name = "55.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7067 } 
		name = "52.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 7 
			}
	}


# Naval OOB

	navalunit = { # Dushenov K.I.
		id = { type = 10848 id = 5400 } 
		name = "Severnaya Voennaya Flotiliya" 
		location = 535 
		base = 535 
		division = { 
			id = { type = 10848 id = 5401 } 
			name = "1 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 6009 } 
			name = "2 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5402 } 
			name = "1. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 6008 } 
			name = "2. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5153 } 
			name = "3. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		} 	
	navalunit = { # Galler L.M.
		id = { type = 10848 id = 5100 } 
		name = "Krasnoznamenny Baltijsky Flot" 
		location = 553 
		base = 553 
		division = { 
			id = { type = 10848 id = 5101 } 
			name = "Marat" 
			type = battleship 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 5102 } 
			name = "Oktyabrskaya Revolutsiya" 
			type = battleship 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 6000 } 
			name = "Kirov" 
			type = heavy_cruiser
			model = 5 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 8501 } 
			name = "Maxim Gorky" 
			type = heavy_cruiser
			model = 5 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5103 } 
			name = "3 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5104 } 
			name = "4 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5206 } 
			name = "5 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5500 } 
			name = "10 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5501 } 
			name = "11 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5154 } 
			name = "4. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6003 } 
			name = "5. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5161 } 
			name = "6. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5162 } 
			name = "7. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5163 } 
			name = "8. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5171 } 
			name = "9. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5301 } 
			name = "10. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		}  						
	navalunit = { # Kozhanov I.K.
		id = { type = 10848 id = 5200 } 
		name = "Chernomorskiy Flot" 
		location = 708 
		base = 708 
		division = { 
			id = { type = 10848 id = 5201 } 
			name = "Parizhskaya Kommuna" 
			type = battleship 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 5202 } 
			name = "Krasnyi Kavkaz" 
			type = heavy_cruiser 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5203 } 
			name = "Krasnyi Krym" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5204 } 
			name = "Komintern" 
			type = light_cruiser 
			model = 0 
			} 
		division = { 
			id = { type = 10848 id = 5205 } 
			name = "Chervona Ukraina" 
			type = light_cruiser 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 8500 } 
			name = "Voroshilov" 
			type = heavy_cruiser
			model = 5 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 8502 } 
			name = "Molotov" 
			type = heavy_cruiser
			model = 5 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5207 } 
			name = "6 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5502 } 
			name = "7 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5503 } 
			name = "12 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5504 } 
			name = "13 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5302 } 
			name = "11. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 6011 } 
			name = "12. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5172 } 
			name = "13. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5173 } 
			name = "14. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 6012 } 
			name = "15. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		} 
	navalunit = { # Viktorov M.V.
		id = { type = 10848 id = 5515 } 
		name = "Tikhookeanskiy Flot" 
		location = 1191 
		base = 1191 
		division = { 
			id = { type = 10848 id = 6001 } 
			name = "8 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6015 } 
			name = "9 Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6013 } 
			name = "16. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6014 } 
			name = "17. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5551 } 
			name = "18. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5552 } 
			name = "19. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5351 } 
			name = "20. Divizion Podlodok" 
			type = submarine 
			model = 1 
			} 
		division = { 
			id = { type = 10848 id = 5352 } 
			name = "21. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5353 } 
			name = "22. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}
		division = { 
			id = { type = 10848 id = 6006 } 
			name = "23. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6007 } 
			name = "24. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6018 } 
			name = "25. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6019 } 
			name = "26. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6010 } 
			name = "27. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}  
		division = { 
			id = { type = 10848 id = 5514 } 
			name = "1. Transportnaya Flotiliya" 
			type = transport 
			model = 2 
			} 
		} 	
	
	# Starting Build Queue 
	division_development = {
		name  = "Kaganovich"
		type  = heavy_cruiser
		model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8503 }
		date  = { year = 1942 month = december day = 31 }
	}
	division_development = {
		name  = "Kalinin"
		type  = heavy_cruiser
		model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8504 }
		date  = { year = 1944 month = december day = 6 }
	}
	division_development = {
		name  = "Chapayev"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8505 }
		date  = { year = 1943 month = march day = 8 }
	}
	division_development = {
		name  = "Zheleznyakov"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8506 }
		date  = { year = 1943 month = march day = 30 }
	}
	division_development = {
		name  = "Kuybyshev"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8507 }
		date  = { year = 1943 month = february day = 28 }
	}
	division_development = {
		name  = "Chkalov"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8508 }
		date  = { year = 1943 month = february day = 28 }
	}
	division_development = {
		name  = "Frunze"
		type  = heavy_cruiser
		model = 6
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8509 }
		date  = { year = 1943 month = february day = 26 }
	}
	division_development = {
		name  = "2-ya Gvardyeiskaya Vozdushno-Desantnye Div."
		type  = paratrooper
		model = 1
		cost  = 0.1
		id    = { type = 10848 id = 8510 }
		date  = { year = 1942 month = december day = 1 }
	}
	division_development = {
		name  = "5-ya Gvardyeiskaya Vozdushno-Desantnye Div."
		type  = paratrooper
		model = 1
		cost  = 0.1
		id    = { type = 10848 id = 8511 }
		date  = { year = 1942 month = december day = 1 }
	}
	division_development = {
		name  = "7-ya Gvardyeiskaya Vozdushno-Desantnye Div."
		type  = paratrooper
		model = 1
		cost  = 0.1
		id    = { type = 10848 id = 8512 }
		date  = { year = 1942 month = december day = 1 }
	}
	division_development = {
		name  = "8-ya Gvardyeiskaya Vozdushno-Desantnye Div."
		type  = paratrooper
		model = 1
		cost  = 0.1
		id    = { type = 10848 id = 8513 }
		date  = { year = 1942 month = december day = 1 }
	}
	division_development = {
		name  = "10-ya Gvardyeiskaya Vozdushno-Desantnye Div."
		type  = paratrooper
		model = 1
		cost  = 0.1
		id    = { type = 10848 id = 8514 }
		date  = { year = 1942 month = december day = 1 }
	}

 }	
