   
   ##############################   
   # Country definition for USA #   
   ##############################   
      
   #####################   
   # Country main data #   
   #####################   
      
   country =   
   {  tag                    = USA   
     # Resource Reserves   
energy                 = 30060
metal                  = 15030
rare_materials         = 7515  
     oil                    = 5000   
     supplies               = 5000   
     money                  = 100   
     manpower               = 102   
     transports             = 1900   
     escorts                = 14   
     dissent = 15
     research_mod = 0.75
     
     capital                = 1809   

  diplomacy =
  { relation =
    { tag        = ARG
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = AST value = 150 }
    relation = { tag = BEL value = 75 }
    relation =
    { tag        = BOL
      value      = 85
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = BRA
      value      = 120
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = CAN value = 200 }
    relation = { tag = CHI value = 100 }
    relation =
    { tag        = CHL
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = COL
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = COS
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = CUB
      value      = 200
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = DOM
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = ECU
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = 90 }
    relation = { tag = U01 value = 65 }
    relation = { tag = GER value = -125 }
    relation =
    { tag        = GUA
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = HAI
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = HOL value = 70 }
    relation =
    { tag        = HON
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = IRE value = 75 }
    relation = { tag = IRQ value = 120 }
    relation = { tag = JAP value = -125 }
    relation = { tag = LIB value = 200 access = yes }
    relation = { tag = MAN value = -200 }
    relation = { tag = MEN value = -200 }
    relation =
    { tag        = MEX
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = NEP value = 100 }
    relation =
    { tag        = NIC
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = NZL value = 125 }
    relation = { tag = OMN value = 100 }
    relation =
    { tag        = PAN
      value      = 175
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = PAR
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = PHI value = 200 access = yes }
    relation =
    { tag        = PRU
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = SAF value = 125 }
    relation =
    { tag        = SAL
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = SOV value = 175 }
    relation = { tag = SWE value = 75 }
    relation =
    { tag        = URU
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = VEN
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = YEM value = 100 }
    relation = { tag = U05 value = 70  }  
  }   
     SpyInfo                = {  country = "USA" NumberOfSpies = 11  }   
        
     nationalprovinces      = {  1809 1953 1949 1948 1952 1951 1950 1947 1956 1954 1955 1960 1958 1963 1961   
      1962 1964 1813 1812 1814 1818 1815 1816 1817 1808 1807 1801 1797 1791 1795 1793    
      1792 1805 1803 1804 1790 1787 1788 1784 1785 1789 1796 1826 1806   
      1810 1811 1820 1819 1942 1943 1940 1939 1936 1937 1944 1931 1825 1821 1842 1845 1802   
      1957 1828 1934 1930 1929 1932 1918 1915 1925 1836 1833 1830 1829 1832 1839   
      1838 1841 1843 1834 1837 2140 2145 2144 2146 2151 1846 1850 1855 1856 1858 1857 1859   
      1860 1914 1913 1919 1910 1911 1924 1928 1926 1920 1921 1922   
      1905 1906 1904 1900 1901 1902 1898 1896 1907 1908 1897 1909  
     1868 1866 1862 1869 1865 1871 1873 1875 1876 1874  
      1877 1878 1882 1879 1880 1895 1893 1892 1899 1886 1887 1883  
     1888 1889 1884 2141  2142 2147 2143 2139  2174
     1923  
     1831 1847 1935 1945 1885 1872 1863 2150 1864 1778     
    # Panamacanal to prevent transfer to allies  
    889   
    1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
                              }  
    ownedprovinces         = {  1953  1949  1948  1952  1951  1950  1947  1956  1954    1955  1960  1958  1963    1961  1962  1964  1813  1812    1814  1818 1815 1816 1817  1809   
                               1808  1807  1801  1797  1791  1795  1793    1792  1805  1803  1804    1790    1787  1788  1784  1785    1789  1796  1826  1806   
                               1810  1811  1820  1819  1942  1943  1940   1939 1936 1937  1944  1931  1825  1821  1842  1845  1802  1957  1828  1934  1930  1929 1932  1918  1915     
                               1925    1836  1833  1830  1829  1832  1839  1838  1841  1843  1834  1837   2145 2144 2146 2151  1846  1850        1855  1856  1858  1857  1859   
                               1860    1914  1913    1919  1910  1911    1924  1928  1926  1920   1921  1922   1905  1906  1904  1900    1901   
                               1902  1898  1896  1907  1908  1897  1909  1868  1866      1862        1869    1865    1871    1873 1875 1876  1874     
                               1877  1878  1882    1879  1880    1895  1893    1892  1899  1886  1887  1883  1888  1889  1884  2141   2140  2142 2147 2143  2139     
                                         1923      1765  889  1736  1737  1735    1739  1734  1738  1673 1683   
                 1747  
               1733 1751 1745  
               1778 1831  
               1872 1863 2150 1864 1847 1935 1945 1885  2174
         1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938 
  1783 1    3
  740  741  742  744  745  746  747  748  749  717  718  719  720  721  722  723  724  725  726  727  728  729  730  731  732  733  734  735  736  737  738  739  743
  1593 1590 1591 1592 1588 1589 1678 1679 1680 1682
  1750 1687 1586 1585 1584 1583 1582 1581
  1724 1725 1726 1727 1602 1234 1603 1605 1587 1604 1606 1607 1610 1608 1609
                              }  
    controlledprovinces    = {  1953  1949  1948  1952  1951  1950  1947  1956  1954   1955  1960  1958  1963    1961  1962  1964  1813  1812    1814  1818 1815 1816 1817  1809   
                               1808  1807  1801  1797  1791  1795  1793    1792  1805  1803  1804   1790    1787  1788  1784  1785    1789  1796  1826  1806   
                               1810  1811  1820  1819  1942  1943  1940    1939 1936 1937  1944  1931  1825  1821  1842  1845  1802  1957  1828  1934  1930  1929 1932  1918  1915     
                               1925    1836  1833  1830  1829  1832  1839  1838  1841  1843  1834  1837   2145 2144 2146 2151  1846  1850        1855  1856  1858  1857  1859   
                               1860    1914  1913    1919  1910  1911    1924  1928  1926  1920    1921  1922   1905  1906  1904  1900    1901   
                               1902  1898  1896  1907  1908  1897  1909  1868  1866      1862        1869    1865    1871    1873 1875 1876  1874    
                               1877  1878  1882    1879  1880    1895  1893    1892  1899  1886  1887  1883  1888  1889  1884  2141    2140  2142 2147 2143  2139     
                                         1923      1765  889  1736  1737  1735    1739  1734  1738  1747  
                1733 1751 1745
               1778 1831  
               1872 1863 2150 1864 1847 1935 1945 1885  
         1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
  1783 1    3
  740  746  749  717  718  719  720  721  722  723  724  725  726  727  728  729  730  731  732  733  734  735  736  737  738  739  743
  1590 1591 1592
  1750 1687 1586 1585 1584 1583 1582 1581
  1604 1606 1607 1608 1609
                }
				
	# USA 1942.11 techs  
	# ######################  
	techapps = {  
	
	# Manufacturing
	5810 5820 5050 5830 5060 5070 5130
	# Assembly Line
	5140 5160 5180 5150
	# Construction Engineering 
	5800 5080 5090 5100
	# Computers and cryptography
	5310 54010 54020 54030 5320 5330 5316 5326 5327 5350 5360 5370 5380
	# Agriculture 
	5700 5710 5010 5020 5030
	# Radar
	5410 5416 5417 5420 5426
	# Refining
	5190 5200 5210 5220
	# Atomic Research 
	5470 5480 5490
	# Medicine
	5600 5610 5620 5630 5640
	# Exp. Rocket
	5560
	
	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120
	# Mountain
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260
	# Marines
	1560 1570 1580 1590 1600
	# Airborne
	1670
	# Motorized
	1396 1400
	# Cavalry Division  
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
	# Engineers
	1830 1840 1850 1860 1870
	# Supply / Logs
	1910 1920 1930 1940 1950 1960 1970 1980 1990 199130

	# Tank 
	7600 7610 2620 2010 2630 2640 2640 2646 2650 2030 2040 2050 2070 2080
	# Armoured Cars 
	2860 2870 2880 2020 2150
	# Field Artillery 
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330
	# Anti-Tank Artillery
	2400
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460 2470
	# Anti-Air Artillery Brigade 
	2810 2820 2510 2520
	# Tank Destroyer
	2170
	# SP Art
	2230

	# Hospital System 
	14000 14010 14020 14030
	# WWI Land Doctrines - Entente: eng fra ita usa bel hol jap 
	6500 6510  6530 6540 6580 6600 6610 6620 6630 6640 6650 6660 6670 6910
	# WWII Land Doctrines - Firepower Focus
	6010 6020 6040 6050 6060 6070 6900

	# Light Cruiser 
	3110 3120 3130 3140 3150 3160 12010
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470 3480
	# Battlecruiser
	3310 3320 3330 3340 3350
	# Heavy Cruiser 
	3210 3220 3230 3240 3250 3260 12020
	# Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	# Submarine 
	3610 3620 3630 3640 3650 3660 3670
	# Light Carrier 
	12100 12110 12120 12130 12140
	# Fleet Carrier 
	3510 3520 3530 3540 3550
	# Troopships
	3810 3820 3830 3840
	#Torpedo & ASW 18
	3720 3730 3736 3740 3750 3760 3900 3910

	# Naval Doctrines -
	# Engagement Theories
	8010 8020 8030 8040 8050 8060 8070 8080
	# Naval Supremacy
	8100 8110 8120 8150 8160 8200 8210 8170
	# Naval Interdiction
	8500 8510 8550 8520 8560 8600 8610
	# Engagement Tactics - Fleet-in-Being colum
	8900 8910 8920 8930 8940 8950 8960 8970 8980
	# Subsidiary Carrier Role
	81650
	# Carrier - Scouting Focus
	81850 81860 81870 81880 81890
	# Carrier - Aerial Supremacy
	81700 81710 81720 81730 81740
	# Logistic Support
	82500 82510
	# Amphibious Warfare
	82300 82310 82320
	
	# Interceptor  
	4500 4510 4520 4530 4540 4550 4010 4020	4030 4060 4090
	# Multi-role fighter
	4300 4310 4320 4330 4340 4040 4070 4100
	# Close Air Support
	4400 4170 4280
	# Escort Fighter
	4050 4080
	# Tactical Bomber 
	4600 4610 4620 4630 4120 4130 4140 4150 4160
	# Air Transport 
	4290 4250 4260 4270
	# Strategic Bomber 
	4800 4810 4820 4220 4230 4240
	# Naval bomber
	4700 4710 4190 4200
	# Seaplanes
	4740 4750 4760 4770 4780 4790 4850 
	# CAG
	4900 4910 4920 4930 4940
	
	# Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9140 9040 9050 9060 9070 
	9080 9090 9100 9110 9120 9130 9140 9150 9160 9170 9180 9190 9200 9210 9220 9230 9240 9250 9350 9260

	} 

blueprints = { 81880 81890 }

inventions = { 3000027 }
    policy =  
    {  date              = {  year = 1942 month = january day = 0  }  
     democratic        = 9 
      political_left    = 6  
      freedom           = 10  
      free_market       = 10  
      professional_army = 2  
      defense_lobby     = 3  
      interventionism   = 4  
     }  
	 peacetime_ic_mod       = 0.5
	 wartime_ic_mod       = 0.8
    headofstate            = {  type = 9 id = 240001  }  
    headofgovernment       = {  type = 9 id = 240232  }
    foreignminister        = {  type = 9 id = 240003  }  
    armamentminister       = {  type = 9 id = 240004  }  
    ministerofsecurity     = {  type = 9 id = 240005  }  
    ministerofintelligence = {  type = 9 id = 240098  }  
    chiefofstaff           = {  type = 9 id = 240104  }  
    chiefofarmy            = {  type = 9 id = 240109  }  
    chiefofnavy            = {  type = 9 id = 240126  }  
    chiefofair             = {  type = 9 id = 240129  }
    dormant_ministers      = {  240052 240006 240135 240009 240125 240121 240010 240080 240007 240008 240020 240086  } 

    landunit =  
    {  location = 1734  
      name     = "Pacific HQ"  
      id       = {  type = 14800 id = 1005  }  
     Division = 
     {  id       = {  type = 13500 id = 1006  } 
       name     = "Pacific HQ" 
       type     = hq 
       model    = 3 
       strength = 100 
      } 
    }
    landunit =  
    {  location = 1586  
      name     = "South-East Pacific HQ"  
      id       = {  type = 14800 id = 6128  }  
     Division = 
     {  id       = {  type = 13500 id = 6129  } 
       name     = "South-East Pacific HQ" 
       type     = hq 
       model    = 3 
       strength = 100 
      } 
    }
    landunit =  
    {  location = 1889  
      name     = "CONUS HQ"  
      id       = {  type = 14800 id = 1007  }  
     Division = 
     {  id       = {  type = 13500 id = 1008  } 
       name     = "CONUS HQ" 
       type     = hq 
       model    = 3 
       strength = 100 
      } 
    }
    landunit =  
    {  location = 740  
      name     = "Center Task Force"  
      id       = {  type = 14800 id = 6050  } 
      Division =  
      {  id   = {  type = 14800 id = 605  }  
        name = "1st 'Big Red One' Division" 
		strength = 100
		type = motorized  
		model    = 2
		extra = anti_air
		brigade_model = 3
       }
    }
    landunit =  
    {  location = 743  
      name     = "Western Task Force"  
      id       = {  type = 14800 id = 6320  } 
      Division =  
      {  id   = {  type = 14800 id = 632  }  
        name = "3rd 'Rock of the Marne' Division" 
		strength = 100
		type = motorized  
		model    = 2
		extra = anti_tank
		brigade_model = 2
       }    
      Division =  
      {  id   = {  type = 14800 id = 1113  }  
        name = "2nd Armored 'Hell on Wheels' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
    }
    landunit =  
    {  location = 749  
      name     = "1st Armored Division"  
      id       = {  type = 14800 id = 1107  }    
      Division =  
      {  id   = {  type = 14800 id = 1108  }  
        name = "1st Armored 'Old Ironsides' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
     }    
    landunit =  
    {  location = 743  
      name     = "9th Infantry Division"  
      id       = {  type = 14800 id = 6321  } 
      Division =  
      {  id   = {  type = 14800 id = 1105  }  
        name = "9th 'Old Reliables' Division" 
		strength = 100
		type = motorized  
		model    = 2
		extra = anti_tank
		brigade_model = 2
       }
    }
    landunit =  
    {  location = 1590  
      name     = "US XIV Corps"  
      id       = {  type = 14800 id = 6322  } 
      Division =  
      {  id   = {  type = 14800 id = 6323  }  
        name = "23rd 'Americal Division'" 
		strength = 70
		type = infantry  
		model    = 11
		extra = artillery
		brigade_model = 8
       }
      Division =  
      {  id   = {  type = 14800 id = 6380  }  
        name = "1st US Marine 'The Old Breed' Div." 
		strength = 60
		type = marine
		model    = 4
       }  
    }
    landunit =  
    {  location = 1734  
      name     = "Hawaiian Department"  
      id       = {  type = 14800 id = 6324  } 
      Division =  
      {  id   = {  type = 14800 id = 6325  }  
        name = "25th 'Tropic Lightning' Division" 
		strength = 50
		type = infantry  
		model    = 11
       }
      Division =  
      {  id   = {  type = 14800 id = 633  }  
        name = "40th 'Sunshine' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }   
    }
    landunit =  
    {  location = 17  
      name     = "29th Infantry Division"  
      id       = {  type = 14800 id = 6326  } 
      Division =  
      {  id   = {  type = 14800 id = 612  }  
        name = "29th 'Blue and Gray' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
    }
    landunit =  
    {  location = 1604  
      name     = "32nd Infantry Division"  
      id       = {  type = 14800 id = 6327  } 
      Division =  
      {  id   = {  type = 14800 id = 1016  }  
        name = "32nd 'Red Arrow' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
    }
    landunit =  
    {  location = 727  
      name     = "Eastern Task Force"  
      id       = {  type = 14800 id = 6328  } 
      Division =  
      {  id   = {  type = 14800 id = 624  }  
        name = "34th 'Red Bull' Division"
		strength = 60		
        type = motorized  
		model    = 1
		extra = artillery
		brigade_model = 8
       }
    }
    landunit =  
    {  location = 1795  
      name     = "36th Infantry Division"  
      id       = {  type = 14800 id = 6329  } 
      Division =  
      {  id   = {  type = 14800 id = 1018  }  
        name = "36th 'Texas' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }   
    }
    landunit =  
    {  location = 1728  
      name     = "37th Infantry Division"  
      id       = {  type = 14800 id = 6051  } 
      Division =  
      {  id   = {  type = 14800 id = 618  }  
        name = "37th 'Buckeye' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
    }
    landunit =  
    {  location = 1700  
      name     = "41st Infantry Division"  
      id       = {  type = 14800 id = 6052  } 
      Division =  
      {  id   = {  type = 14800 id = 634  }  
        name = "41st 'Sunsetters' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
    }
    landunit =  
    {  location = 1586  
      name     = "43rd Infantry Division"  
      id       = {  type = 14800 id = 6053  } 
      Division =  
      {  id   = {  type = 14800 id = 603  }  
        name = "43rd 'Winged Victory' Division"
		strength = 50		
        type = infantry  
		model    = 11
       } 
    }
    landunit =  
    {  location = 1812  
      name     = "76th Infantry Division"  
      id       = {  type = 14800 id = 6054  } 
      Division =  
      {  id   = {  type = 14800 id = 6055  }  
        name = "76th 'Onaway Division'"
		strength = 25		
        type = infantry  
		model    = 10
       } 
      Division =  
      {  id   = {  type = 14800 id = 6056  }  
        name = "77th 'Liberty Division'"
		strength = 25		
        type = infantry  
		model    = 10
       } 
    }
    landunit =  
    {  location = 1962  
      name     = "78th Infantry Division"  
      id       = {  type = 14800 id = 6057  } 
      Division =  
      {  id   = {  type = 14800 id = 608  }  
        name = "78th 'Lightning' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 6080  }  
        name = "79th Infantry Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
    }
    landunit =  
    {  location = 1944  
      name     = "80th Infantry Division"  
      id       = {  type = 14800 id = 6058  } 
      Division =  
      {  id   = {  type = 14800 id = 6081  }  
        name = "80th 'Blue Ridge Division'"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 6082  }  
        name = "81st 'Wildcat' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
    }
    landunit =  
    {  location = 1932  
      name     = "82nd Airborne Division"  
      id       = {  type = 14800 id = 6059  } 
      Division =  
      {  id   = {  type = 14800 id = 6083  }  
        name = "82nd Airborne 'All American' Division"
		strength = 50		
        type = paratrooper  
		model    = 1
       }
    }
    landunit =  
    {  location = 1955  
      name     = "101st Airborne Division"  
      id       = {  type = 14800 id = 6126  } 
      Division =  
      {  id   = {  type = 14800 id = 6127  }  
        name = "101st US Air. 'Screaming Eagles Div.'"
		strength = 50		
        type = paratrooper  
		model    = 1
       }
    }
    landunit =  
    {  location = 1819  
      name     = "83rd Infantry Division"  
      id       = {  type = 14800 id = 6084  } 
      Division =  
      {  id   = {  type = 14800 id = 6085  }  
        name = "83rd 'Thunderbolts' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 6086  }  
        name = "84th 'Railsplitters' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
    }
    landunit =  
    {  location = 1931  
      name     = "85th Infantry Division"  
      id       = {  type = 14800 id = 6087  } 
      Division =  
      {  id   = {  type = 14800 id = 6088  }  
        name = "85th 'Custer Division'"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 6089  }  
        name = "86th 'Blackhawk' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
    }
    landunit =  
    {  location = 1913  
      name     = "88th Infantry Division"  
      id       = {  type = 14800 id = 6100  } 
      Division =  
      {  id   = {  type = 14800 id = 6101  }  
        name = "88th 'Blue Devils' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 6102  }  
        name = "89th 'Midwest Division'"
		strength = 25		
        type = infantry  
		model    = 10
       }
    }
    landunit =  
    {  location = 1901  
      name     = "92nd Infantry Division"  
      id       = {  type = 14800 id = 6103  } 
      Division =  
      {  id   = {  type = 14800 id = 6104  }  
        name = "92nd 'Buffalo Soldiers' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 6105  }  
        name = "93rd Infantry (Colored) Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
    }
    landunit =  
    {  location = 1957  
      name     = "99th Infantry Division"  
      id       = {  type = 14800 id = 6107  } 
      Division =  
      {  id   = {  type = 14800 id = 6108  }  
        name = "99th 'Checkerboard' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 619  }  
        name = "100th 'Century' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }  
    }
    landunit =  
    {  location = 1808  
      name     = "102th Infantry Division"  
      id       = {  type = 14800 id = 6109  } 
      Division =  
      {  id   = {  type = 14800 id = 6110  }  
        name = "102nd 'Ozarks' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 6111  }  
        name = "103rd 'Cactus' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }  
    }

    landunit =  
    {  location = 1808  
      name     = "US I Corps"  
      id       = {  type = 14800 id = 601  } 
      Division =  
      {  id   = {  type = 14800 id = 1104  }  
        name = "8th 'Pathfinder' Division" 
		strength = 100
		type = infantry  
		model    = 11
		extra = artillery
		brigade_model = 7
       }   
      Division =  
      {  id   = {  type = 14800 id = 1004  }  
        name = "30th 'Old Hickory' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
     }
    landunit =  
    {  location = 1830  
      name     = "US II Corps"  
      id       = {  type = 14800 id = 1009  }
      Division =  
      {  id   = {  type = 14800 id = 611  }  
        name = "28th 'Keystone' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }  
     }
    landunit =  
    {  location = 1887  
      name     = "US VI Corps"  
      id       = {  type = 14800 id = 1010  }
      Division =  
      {  id   = {  type = 14800 id = 602  }  
        name = "26th 'Yankee' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
      Division =  
      {  id   = {  type = 14800 id = 621  }  
        name = "94th 'Pilgrim' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
     }
    landunit =  
    {  location = 1963  
      name     = "US VII Corps"  
      id       = {  type = 14800 id = 1011  }
      Division =  
      {  id   = {  type = 14800 id = 1013  }  
        name = "33rd 'Golden Cross' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
      Division =  
      {  id   = {  type = 14800 id = 625  }  
        name = "35th 'Santa Fe' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
     }
    landunit =  
    {  location = 1928  
      name     = "US IV Corps"  
      id       = {  type = 14800 id = 1014  }
      Division =  
      {  id   = {  type = 14800 id = 615  }  
        name = "31st 'Dixie' Division"
		strength = 50		
        type = infantry  
		model    = 11
       } 
      Division =  
      {  id   = {  type = 14800 id = 628  }  
        name = "1st Cavalry 'The 1st Team' Div."  
		strength = 100
        type = cavalry  
		model    = 11
	extra = armored_car
		brigade_model = 3
       }
     }
    landunit =  
    {  location = 1877  
      name     = "US V Corps"  
      id       = {  type = 14800 id = 1015  }
      Division =  
      {  id   = {  type = 14800 id = 1017  }  
        name = "38th 'Cyclone' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
      Division =  
      {  id   = {  type = 14800 id = 607  }  
        name = "44th Infantry Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
     }
    landunit =  
    {  location = 1926  
      name     = "US VIII Corps"  
      id       = {  type = 14800 id = 626  }  
      Division =  
      {  id   = {  type = 14800 id = 627  }  
        name = "2nd 'Indianhead' Division" 
		strength = 100
		type = infantry  
		model    = 11
		extra = artillery
		brigade_model = 7
       }
      Division =  
      {  id   = {  type = 14800 id = 629  }  
        name = "45th 'Thunderbird' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
      Division =  
      {  id   = {  type = 14800 id = 630  }  
        name = "95th 'Victory' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
      Division =  
      {  id   = {  type = 14800 id = 6106  }  
        name = "96th 'Deadeye' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }
     }
    landunit =  
    {  location = 1891  
      name     = "US III Corps"  
      id       = {  type = 14800 id = 1019  }
      Division =  
      {  id   = {  type = 14800 id = 1103  }  
        name = "7th 'Bayonet' Division" 
		strength = 100
		type = motorized  
		model    = 1
		extra = artillery
		brigade_model = 7
       }  
     } 
    landunit =  
    {  location = 1952  
      name     = "US IX Corps"  
      id       = {  type = 14800 id = 631  }  
      Division =  
      {  id   = {  type = 14800 id = 6350  }  
        name = "90th 'Tough Ombres' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }  
      Division =  
      {  id   = {  type = 14800 id = 635  }  
        name = "91st 'Wild West' Division"
		strength = 25		
        type = infantry  
		model    = 10
       }  
      Division =  
      {  id   = {  type = 14800 id = 636  }  
        name = "104th 'Timberwolf' Division"
		strength = 25		
        type = infantry  
		model    = 10
       } 
     }
    landunit =  
    {  location = 1736  
      name     = "Hawaiian Corps"  
      id       = {  type = 14800 id = 1020  }
      Division =  
      {  id   = {  type = 14800 id = 1021  }  
        name = "24th 'Victory' Division"
		strength = 50		
        type = infantry  
		model    = 11
       }
      Division =  
      {  id   = {  type = 14800 id = 1012  }  
        name = "27th 'New York Division'"
		strength = 50		
        type = infantry  
		model    = 11
       }
     }  
    landunit =  
    {  location = 1  
      name     = "5th Infantry Division"  
      id       = {  type = 14800 id = 1000  }  
      Division =  
      {  id   = {  type = 14800 id = 1001  }  
        name = "5th 'Red Devils' Division" 
		strength = 100
		type = infantry  
		model    = 11
		extra = artillery
		brigade_model = 7
       }    
     }
    landunit =  
    {  location = 1891  
      name     = "US XVII Corps"  
      id       = {  type = 14800 id = 1002  }  
      Division =  
      {  id   = {  type = 14800 id = 1003  }  
        name = "6th 'Sightseeing Sixth' Division" 
		strength = 100
		type = infantry  
		model    = 11
		extra = artillery
		brigade_model = 7
       }    
     }
    landunit =  
    {  location = 1959  
      name     = "US I Armored Corps"  
      id       = {  type = 14800 id = 1100  }  
      Division =  
      {  id   = {  type = 14800 id = 1101  }  
        name = "4th 'Iron Horse' Division" 
		strength = 100
		type = infantry  
		model    = 11
		extra = artillery
		brigade_model = 7
       }    
     }  
    landunit =  
    {  location = 1795  
      name     = "4th Armored Division"  
      id       = {  type = 14800 id = 1109  }    
      Division =  
      {  id   = {  type = 14800 id = 1110  }  
        name = "4th Armored 'Breakthrough' Div." 
		strength = 60
		type = armor  
		model    = 0
       }
     }   
    landunit =  
    {  location = 1886  
      name     = "US II Armored Corps"  
      id       = {  type = 14800 id = 1111  }    
      Division =  
      {  id   = {  type = 14800 id = 1112  }  
        name = "3rd Armored 'Spearhead' Div." 
		strength = 60
		type = armor  
		model    = 0
       }
      Division =  
      {  id   = {  type = 14800 id = 6112  }  
        name = "5th Armored 'Victory' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
      Division =  
      {  id   = {  type = 14800 id = 6113  }  
        name = "6th Armored 'Super Sixth' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
     }   
    landunit =  
    {  location = 1932  
      name     = "7th Armored Division"  
      id       = {  type = 14800 id = 6114  }    
      Division =  
      {  id   = {  type = 14800 id = 6115  }  
        name = "7th Armored 'Lucky Seventh' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
      Division =  
      {  id   = {  type = 14800 id = 6116  }  
        name = "8th Armored 'Thundering Herd' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
     }   
    landunit =  
    {  location = 1954  
      name     = "9th Armored Division"  
      id       = {  type = 14800 id = 6117  }    
      Division =  
      {  id   = {  type = 14800 id = 6118  }  
        name = "9th Armored 'Phantom' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
      Division =  
      {  id   = {  type = 14800 id = 6119  }  
        name = "10th Armored 'Tiger' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
      Division =  
      {  id   = {  type = 14800 id = 6120  }  
        name = "11th Armored 'Thunderbolt' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
     }   
    landunit =  
    {  location = 1888  
      name     = "12th Armored Division"  
      id       = {  type = 14800 id = 6121  }    
      Division =  
      {  id   = {  type = 14800 id = 6122  }  
        name = "12th Armored 'Hellcat' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
      Division =  
      {  id   = {  type = 14800 id = 6123  }  
        name = "13th Armored 'Blackcat' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
     }   
    landunit =  
    {  location = 1917  
      name     = "14th Armored Division"  
      id       = {  type = 14800 id = 6124  }    
      Division =  
      {  id   = {  type = 14800 id = 6125  }  
        name = "14th Armored 'Liberator' Div." 
		strength = 60
		type = armor  
		model    = 1
       }
     }   
    landunit =  
    {  location = 1808  
      name     = "U.S. Army General Staff"  
      id       = {  type = 14800 id = 609  }  
     Division = 
     {  id       = {  type = 13500 id = 610  } 
       name     = "U.S. Army General Staff" 
       type     = hq 
       model    = 3 
       strength = 100 
      }   
     }            
    landunit =  
    {  location = 1733  
      name     = "2nd Marine Division"  
      id       = {  type = 14800 id = 6371  }  
      Division =  
      {  id   = {  type = 14800 id = 6381  }  
        name = "2nd US Marine 'Follow Me' Division" 
		strength = 60
		type = marine
		model    = 4
       }  
     }     
    landunit =  
    {  location = 1886  
      name     = "3rd Marine Division"  
      id       = {  type = 14800 id = 6372  }  
      Division =  
      {  id   = {  type = 14800 id = 6382  }  
        name = "3rd US Marine Division" 
		strength = 60
		type = marine
		model    = 4
       }  
     }     
    landunit =  
    {  location = 1874  
      name     = "4th Marine Regiment"  
      id       = {  type = 14800 id = 637  }  
      Division =  
      {  id   = {  type = 14800 id = 638  }  
        name = "4th Marine Regiment" 
		strength = 35
		type = marine
		model    = 4
       }  
     }  
    landunit =  
    {  location = 1814  
      name     = "5th Marine Regiment"  
      id       = {  type = 14800 id = 639  }  
      Division =  
      {  id   = {  type = 14800 id = 640  }  
        name = "5th Marine Regiment" 
		strength = 35
		type = marine
		model    = 4
       }  
     }  
    landunit =  
    {  location = 1886  
      name     = "6th Marine Regiment"  
      id       = {  type = 14800 id = 641  }  
      Division =  
      {  id   = {  type = 14800 id = 642  }  
        name = "6th Marine Regiment" 
		strength = 35
		type = marine
		model    = 4
       }  
     }  
    landunit =  
    {  location = 1734  
      name     = "Hawaiian Department"  
      id       = {  type = 14800 id = 643  }  
      Division =  
      {  id     = {  type = 14800 id = 644  }  
        name   = "Hawaiian Division"  
        type   = infantry  
		model    = 10
        strength = 100 
	extra = engineer
		brigade_model = 3
       }  
     }  
    landunit =  
    {  id       = {  type = 14800 id = 647  }  
      name     = "Panama Canal Department"  
      location = 889  
      Division =  
      {  id     = {  type = 14800 id = 648  }  
        name   = "Panama Canal Garrison"  
		strength = 100
        type   = garrison  
        model  = 5
        locked = yes  
       }  
     }  

    # US NAVY
    # USS Nevada
    navalunit =  
    {  name     = "USS Nevada"  
      id       = {  type = 14800 id = 2800  }  
      location = 1874  
      base     = 1874  
      Division =  
      {  id    = {  type = 14800 id = 28  }  
        name  = "USS Nevada"  
        type  = battleship  
        model = 6 # modernized to resemble South Dakota-class, but still not a South Dakota; uses BB 1922 model
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
     }
    # USS Pennsylvania  
    navalunit =  
    {  name     = "USN Pennsylvania"  
      id       = {  type = 14800 id = 26  }  
      location = 1889  
      base     = 1889 
      Division =  
      {  id    = {  type = 14800 id = 30  }  
        name  = "USS Pennsylvania"  
        type  = battleship
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
     }
    # Fiji Patrol Squadron  
    navalunit =  
    {  name     = "USN Fiji Patrol Squadron"  
      id       = {  type = 14800 id = 31  }  
      location = 2434  
      base     = 1728 
      Division =  
      {  id    = {  type = 14800 id = 37  }  
        name  = "USS Colorado"  
        type  = battleship  
        model = 6  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 39  }  
        name  = "USS Maryland"  
        type  = battleship  
        model = 6
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }     
      Division =  
      {  id    = {  type = 14800 id = 173  }  
        name  = "Destroyer Division 25"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2293  }  
        name  = "Destroyer Division 28"  
        type  = destroyer  
        model = 3  
       }
     }
    # USS Heron
    navalunit =  
    {  name     = "USS Heron"  
      id       = {  type = 14800 id = 2102  }  
      location = 1704  
      base     = 1704  
      Division =  
      {  id   = {  type = 14800 id = 2103  }  
        name  = "USS Heron"  
        type  = escort_carrier  
        model = 0    
       }
     } 
    # USN Task Force 11
    navalunit =  
    {  name     = "USN Task Force 11"  
      id       = {  type = 14800 id = 2004  }  
      location = 1586  
      base     = 1586  
      Division =  
      {  id            = {  type = 14800 id = 32  }  
        name          = "USS Saratoga"  
        type          = carrier  
        model         = 0  
        extra         = CAG  
        brigade_model = 4  
       }
      Division =  
      {  id    = {  type = 14800 id = 60  }  
		name  = "USS San Francisco"  
		type  = heavy_cruiser  
		model = 4  
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		
       }  
      Division =  
      {  id    = {  type = 14800 id = 2319  }  
        name  = "Destroyer Division 9"  
        type  = destroyer  
        model = 3  
       }  
     }
    # USN Task Force 16
    navalunit =  
    {  name     = "USN Task Force 16"  
      id       = {  type = 14800 id = 2601  }  
      location = 2439  
      base     = 1586 
      Division =  
      {  id            = {  type = 14800 id = 501  }  
        name          = "USS Enterprise"  
        type          = carrier  
        model         = 2  
        extra         = CAG  
        brigade_model = 4  
       }
      Division =  
      {  id   = {  type = 14800 id = 2104  }  
        name  = "USS Wright"  
        type  = escort_carrier  
        model = 0    
       }
      Division =  
      {  id   = {  type = 14800 id = 4030  }  
        name  = "USS Curtiss"  
        type  = escort_carrier  
        model = 0    
       }
      Division =  
      {  id    = {  type = 14800 id = 3001  }  
        name  = "USS South Dakota"  
        type  = battleship  
        model = 7
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 52  }  
        name  = "USS Northampton"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
      Division =  
      {  id    = {  type = 14800 id = 55  }  
        name  = "USS Portland"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       } 
      Division =  
      {  id    = {  type = 14800 id = 3011  }  
        name  = "USS San Diego"  
        type  = light_cruiser  
        model = 5  
       } 
      Division =  
      {  id    = {  type = 14800 id = 3017  }  
        name  = "USS San Juan"  
        type  = light_cruiser  
        model = 5  
       } 
      Division =  
      {  id    = {  type = 14800 id = 2316  }  
        name  = "Destroyer Division 6"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2025  }  
        name  = "Destroyer Division 29"  
        type  = destroyer  
        model = 5  
       } 
     }  
    # USN Transport Flotilla 10
    navalunit =  
    {  name     = "USN Transport Flotilla 10"  
      id       = {  type = 14800 id = 2602  }  
      location = 1590  
      base     = 1590 
      Division =  
      {  id    = {  type = 14800 id = 43  }  
        name  = "USS Concord"  
        type  = light_cruiser  
        model = 3  
       }
      Division =  
      {  id   = {  type = 14800 id = 138  }  
        name = "Transport Division 22"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 709  }  
        name = "Transport Division 23"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 141  }  
        name = "Transport Division 24"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 711  }  
        name = "Transport Division 25"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 139  }  
        name = "Transport Division 26"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 713  }  
        name = "Transport Division 27"  
        type = transport  
		model = 3
       }  
     }  
    # USN Task Force 44
    navalunit =  
    {  name     = "USN Task Force 44"  
      id       = {  type = 14800 id = 4010  }  
      location = 2456  
      base     = 1586 
      Division =  
      {  id    = {  type = 14800 id = 4024  }  
        name  = "USS Washington"  
        type  = battleship  
        model = 7  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 47  }  
        name  = "USS Pensacola"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 510  }  
        name  = "USS Honolulu"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 508  }  
        name  = "USS Phoenix"  
        type  = light_cruiser  
        model = 5  
       }  
      Division =  
      {  id    = {  type = 14800 id = 174  }  
        name  = "Destroyer Division 26"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 175  }  
        name  = "Destroyer Division 27"  
        type  = destroyer  
        model = 3  
       }
     }  
    # USN Task Force 64
    navalunit =  
    {  name     = "USN Task Force 64"  
      id       = {  type = 14800 id = 5092  }  
      location = 2456  
      base     = 1586 
      Division =  
      {  id    = {  type = 14800 id = 48  }  
        name  = "USS Salt Lake City"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
      Division =  
      {  id    = {  type = 14800 id = 2043  }  
        name  = "USS Helena"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 121  }  
        name  = "Destroyer Division 23"  
        type  = destroyer  
        model = 3
       }  
     }  
    # USN Task Force 67
    navalunit =  
    {  name     = "USN Task Force 67"  
      id       = {  type = 14800 id = 4200  }  
      location = 2456  
      base     = 1586 
      Division =  
      {  id    = {  type = 14800 id = 3002  }  
        name  = "USS Indiana"  
        type  = battleship  
        model = 7
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 57  }  
        name  = "USS New Orleans"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 59  }  
        name  = "USS Minneapolis"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }
      Division =  
      {  id    = {  type = 14800 id = 54  }  
        name  = "USS Louisville"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 4235  }  
        name  = "Destroyer Division 30"  
        type  = destroyer  
        model = 3
       }
      Division =  
      {  id    = {  type = 14800 id = 4228  }  
        name  = "Destroyer Division 31"  
        type  = destroyer  
        model = 3  
       }  
     }  
    # USN Task Group 8.6
    navalunit =  
    {  name     = "USN Task Group 8.6"  
      id       = {  type = 14800 id = 4009  }  
      location = 2396  
      base     = 2142 
      Division =  
      {  id    = {  type = 14800 id = 50  }  
        name  = "USS Indianapolis"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       } 
      Division =  
      {  id    = {  type = 14800 id = 45  }  
        name  = "USS Detroit"  
        type  = light_cruiser  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 44  }  
        name  = "USS Raleigh"  
        type  = light_cruiser  
        model = 3  
       } 
     } 
    # Submarine Flotilla 2
    navalunit =  
    {  name     = "USN Submarine Flotilla 2"  
      id       = {  type = 14800 id = 4202  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 4203  }  
        name  = "Submarine Division 41"  
        type  = submarine  
        model = 2 # S-class
       }  
      Division =  
      {  id    = {  type = 14800 id = 4204  }  
        name  = "Submarine Division 42"  
        type  = submarine  
        model = 3 # Barracuda-class
       }  
      Division =  
      {  id    = {  type = 14800 id = 4205  }  
        name  = "Submarine Division 43"  
        type  = submarine  
        model = 4 # Porpoise-class 
       }  
      Division =  
      {  id    = {  type = 14800 id = 4207  }  
        name  = "Submarine Division 61"  
        type  = submarine  
        model = 5 # Tambor-class
       }  
      Division =  
      {  id    = {  type = 14800 id = 4208  }  
        name  = "Submarine Division 62"  
        type  = submarine  
        model = 5 # Tambor-class  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2603  }  
        name  = "Submarine Division 73"  
        type  = submarine  
        model = 6  
       }
      Division =  
      {  id    = {  type = 14800 id = 2604  }  
        name  = "Submarine Division 74"  
        type  = submarine  
        model = 6  
       }  
     }  
    # USN Task Force 38
    navalunit =  
    {  name     = "USN Task Force 38"  
      id       = {  type = 14800 id = 4209  }  
      location = 717  
      base     = 717  
      Division =  
      {  id    = {  type = 14800 id = 103  }  
        name  = "USS Arkansas"  
        type  = battleship  
        model = 2 
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 104  }  
        name  = "USS New York"  
        type  = battleship  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 504  }  
        name  = "USS Brooklyn"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 2292  }  
        name  = "Destroyer Division 12"  
        type  = destroyer  
        model = 3  
       } 
      Division =  
      {  id    = {  type = 14800 id = 4013  }  
        name  = "Destroyer Division 50"  
        type  = destroyer  
        model = 3  
       } 
     } 
    # USN Mediterranean Transport Fleet
    navalunit =  
    {  name     = "USS Mediterranean Transport Fleet"  
      id       = {  type = 14800 id = 2605  }  
      location = 717  
      base     = 717  
      Division =  
      {  id    = {  type = 14800 id = 62  }  
        name  = "Destroyer Division 1"  
        type  = destroyer  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 63  }  
        name  = "Destroyer Division 2"  
        type  = destroyer  
        model = 5  
       }    
      Division =  
      {  id    = {  type = 14800 id = 2315  }  
        name  = "Destroyer Division 5"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2317  }  
        name  = "Destroyer Division 7"  
        type  = destroyer  
        model = 3  
       } 
      Division =  
      {  id    = {  type = 14800 id = 2318  }  
        name  = "Destroyer Division 8"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2320  }  
        name  = "Destroyer Division 10"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2291  }  
        name  = "Destroyer Division 11"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id   = {  type = 14800 id = 4230  }  
        name = "Transport Division 1"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 152  }  
        name = "Transport Division 2"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 153  }  
        name = "Transport Division 3"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 143  }  
        name = "Transport Division 4"  
        type = transport  
		model = 3
       }  
     } 
    # USN Texas Group
    navalunit =  
    {  name     = "USN Texas Group"  
      id       = {  type = 14800 id = 2606  }     
      location = 2331 
      prevprov = 2286 
      home = 717 
      base = 728 
      mission = { 
          type = rebase 
          target = 1812 
          percentage = 0.0000 
          night = yes 
          day = yes 
          task = 1 
          location = 1812 
      } 
      date = { 
          year = 1942 
          month = november 
          day = 21 
          hour = 0 
      } 
      movetime = { 
          year = 1942 
          month = november 
          day = 21 
          hour = 22 
      } 
      movement = { 2330 2328 2311 2312 2322 2321 1812 }
      Division =  
      {  id    = {  type = 14800 id = 105  }  
		name  = "USS Texas"  
		type  = battleship  
		model = 3
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		
       } 
      Division =  
      {  id    = {  type = 14800 id = 506  }  
        name  = "USS Savannah"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 505  }  
        name  = "USS Philadelphia"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 119  }  
        name  = "Destroyer Division 21"  
        type  = destroyer  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 120  }  
        name  = "Destroyer Division 22"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id   = {  type = 14800 id = 154  }  
        name = "Transport Division 5"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 144  }  
        name = "Transport Division 6"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 156  }  
        name = "Transport Division 7"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 145  }  
        name = "Transport Division 8"  
        type = transport  
		model = 3
       }  
     } 
    # South Atlantic Force
    navalunit =  
    {  name     = "South Atlantic Force"  
      id       = {  type = 14800 id = 4000  }    
      location = 2273 
      prevprov = 2305 
      home = 2075 
      base = 2075 
      mission = { 
          type = naval_combat_patrol  
          target = 2273 
          percentage = 0.5000 
          night = no 
          day = yes 
          startdate = { year = 1942 month = november day = 21 hour = 2 } 
          enddate = { year = 1942 month = december day = 21 hour = 2 } 
          task = 1 
          location = 2273 
      } 
      date = { 
          year = 1942 
          month = november 
          day = 21 
          hour = 0 
      } 
      Division =  
      {  id   = {  type = 14800 id = 2101  }  
        name  = "USS Patoka"  
        type  = escort_carrier  
        model = 0    
       }
      Division =  
      {  id       = {  type = 14800 id = 90  }  
        name     = "USS Marblehead"  
        strength = 100  
        type     = light_cruiser  
        model    = 3  
       } 
      Division =  
      {  id    = {  type = 14800 id = 107  }  
        name  = "USS Omaha"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 108  }  
        name  = "USS Milwaukee"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 109  }  
        name  = "USS Cincinnati"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 110  }  
        name  = "USS Memphis"  
        type  = light_cruiser  
        model = 3  
       } 
     }
    # USS Trenton
    navalunit =  
    {  name     = "USS Trenton"  
      id       = {  type = 14800 id = 2607  }     
      location = 2296 
      prevprov = 2297 
      home = 2075 
      base = 2075 
      mission = { 
         type = naval_combat_patrol  
         target = 2296 
         percentage = 0.5000 
         night = no 
         day = yes 
         startdate = { year = 1942 month = november day = 21 hour = 2 } 
         enddate = { year = 1942 month = december day = 21 hour = 2 } 
         task = 1 
         location = 2296 
      } 
      Division =  
      {  id    = {  type = 14800 id = 42  }  
        name  = "USS Trenton"  
        type  = light_cruiser  
        model = 3  
       }  
     }
    # USN Task Force 34
    navalunit =  
    {  name     = "USN Task Force 34"  
      id       = {  type = 14800 id = 4212  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id            = {  type = 14800 id = 115  }  
        name          = "USS Ranger"  
        type          = carrier  
        model         = 1  
        extra         = cag  
        brigade_model = 4  
       } 
      Division =  
      {  id    = {  type = 14800 id = 3003  }  
        name  = "USS Massachussetts"  
        type  = battleship  
        model = 7
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 3004  }  
        name  = "USS Alabama"  
        type  = battleship  
        model = 7
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 2023  }  
        name  = "Destroyer Division 4"  
        type  = destroyer  
        model = 5  
       } 
      Division =  
      {  id    = {  type = 14800 id = 84  }  
        name  = "Destroyer Division 15"  
        type  = destroyer  
        model = 3  
       } 
      Division =  
      {  id    = {  type = 14800 id = 91  }  
        name  = "Destroyer Division 16"  
        type  = destroyer  
        model = 3  
       }    
      Division =  
      {  id    = {  type = 14800 id = 117  }  
        name  = "Destroyer Division 19"  
        type  = destroyer  
        model = 3
       }
      Division =  
      {  id    = {  type = 14800 id = 118  }  
        name  = "Destroyer Division 20"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 172  }  
        name  = "Destroyer Division 24"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id   = {  type = 14800 id = 150  }  
        name = "Transport Division 9"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 151  }  
        name = "Transport Division 11"  
        type = transport  
		model = 3
       }  
     } 
    # USN Cruiser Squadron 4
    navalunit =  
    {  name     = "USN Cruiser Squadron 4"  
      id       = {  type = 14800 id = 2608  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 112  }  
        name  = "USS Augusta"  
        type  = heavy_cruiser  
        model = 3  
		extra1 = naval_torpedoes_l
		brigade_model1 = 4			
       }  
      Division =  
      {  id    = {  type = 14800 id = 113  }  
        name  = "USS Tuscaloosa"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       } 
      Division =  
      {  id    = {  type = 14800 id = 512  }  
        name  = "USS Wichita"  
        type  = heavy_cruiser  
        model = 5 
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       } 
      Division =  
      {  id    = {  type = 14800 id = 511  }  
        name  = "USS Nashville"  
        type  = light_cruiser  
        model = 5  
       }
      Division =  
      {  id    = {  type = 14800 id = 3018  }  
        name  = "USS Cleveland"  
        type  = light_cruiser  
        model = 6  
       } 
      Division =  
      {  id    = {  type = 14800 id = 82  }  
        name  = "Destroyer Division 13"  
        type  = destroyer  
        model = 5  
       }   
      Division =  
      {  id    = {  type = 14800 id = 83  }  
        name  = "Destroyer Division 14"  
        type  = destroyer  
        model = 3
       } 
      Division =  
      {  id    = {  type = 14800 id = 96  }  
        name  = "Destroyer Division 17"  
        type  = destroyer  
        model = 3 
       }  
      Division =  
      {  id    = {  type = 14800 id = 116  }  
        name  = "Destroyer Division 18"  
        type  = destroyer  
        model = 5  
       } 
      Division =  
      {  id    = {  type = 14800 id = 179  }  
        name  = "Destroyer Division 58"  
        type  = destroyer  
        model = 4  
       }  
      Division =  
      {  id    = {  type = 14800 id = 180  }  
        name  = "Destroyer Division 59"  
        type  = destroyer  
        model = 4  
       }   
      Division =  
      {  id   = {  type = 14800 id = 136  }  
        name = "Transport Division 17"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 137  }  
        name = "Transport Division 19"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 707  }  
        name = "Transport Division 21"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 715  }  
        name = "Transport Division 29"  
        type = transport  
		model = 3
       }  
     } 
    # USN Destroyer Flotilla 8
    navalunit =  
    {  name     = "USN Destroyer Flotilla 8"  
      id       = {  type = 14800 id = 2609  }  
      location = 2658  
      prevprov = 2656 
      base = 25
      mission = { 
          type = asw 
          target = 2657 
          percentage = 0.5000 
          night = no 
          day = yes 
          startdate = { year = 1942 month = november day = 21 hour = 1 } 
          enddate = { year = 1943 month = february day = 21 hour = 1 }
          location = 2657 
      } 
      date = { 
          year = 1942 
          month = november 
          day = 21 
          hour = 0 
      } 
      Division =  
      {  id    = {  type = 14800 id = 2610 }  
        name  = "Destroyer Division 53"  
        type  = destroyer  
        model = 5  
       }   
      Division =  
      {  id    = {  type = 14800 id = 2611  }  
        name  = "Destroyer Division 54"  
        type  = destroyer  
        model = 5  
       }   
      Division =  
      {  id    = {  type = 14800 id = 2612 }  
        name  = "Destroyer Division 60"  
        type  = destroyer  
        model = 7  
       }   
      Division =  
      {  id    = {  type = 14800 id = 2613  }  
        name  = "Destroyer Division 61"  
        type  = destroyer  
        model = 7  
       }   
      Division =  
      {  id    = {  type = 14800 id = 2614  }  
        name  = "Destroyer Division 62"  
        type  = destroyer  
        model = 7  
       }   
     } 
    # USN Destroyer Flotilla 12
    navalunit =  
    {  name     = "USN Destroyer Flotilla 12"  
      id       = {  type = 14800 id = 2615  }  
      location = 2329  
      prevprov = 2335 
      base = 1812
      mission = { 
          type = asw 
          target = 2329 
          percentage = 0.5000 
          night = no 
          day = yes 
          startdate = { year = 1942 month = november day = 21 hour = 1 } 
          enddate = { year = 1943 month = february day = 21 hour = 1 } 
          location = 2329
      } 
      date = { 
          year = 1942 
          month = november 
          day = 21 
          hour = 0 
      } 
      Division =  
      {  id    = {  type = 14800 id = 2294  }  
        name  = "Destroyer Division 57"  
        type  = destroyer  
        model = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 2616  }  
        name  = "Destroyer Division 64"  
        type  = destroyer  
        model = 6  
       }   
      Division =  
      {  id    = {  type = 14800 id = 2617 }  
        name  = "Destroyer Division 70"  
        type  = destroyer  
        model = 7  
       }   
      Division =  
      {  id    = {  type = 14800 id = 2618  }  
        name  = "Destroyer Division 72"  
        type  = destroyer  
        model = 7  
       }   
      Division =  
      {  id    = {  type = 14800 id = 2619  }  
        name  = "Destroyer Division 81"  
        type  = destroyer  
        model = 7  
       }   
     } 
    # Submarine Flotilla 1
    navalunit =  
    {  name     = "USN Submarine Flotilla 1"  
      id       = {  type = 14800 id = 4213  }  
      location = 1739  
      base     = 1739 
      Division =  
      {  id    = {  type = 14800 id = 97  }  
        name  = "Submarine Division 11"  
        type  = submarine  
        model = 1 # O-class  
       }
      Division =  
      {  id    = {  type = 14800 id = 123  }  
        name  = "Submarine Division 12"  
        type  = submarine  
        model = 1 # R-class  
       }  
      Division =  
      {  id    = {  type = 14800 id = 4215  }  
        name  = "Submarine Division 31"  
        type  = submarine  
        model = 2 # S-class  
       }
      Division =  
      {  id    = {  type = 14800 id = 4216  }  
        name  = "Submarine Division 32"  
        type  = submarine  
        model = 3 # Barracuda-class  
       }  
      Division =  
      {  id    = {  type = 14800 id = 4218  }  
        name  = "Submarine Division 51"  
        type  = submarine  
        model = 2 # S-class  
       }
      Division =  
      {  id    = {  type = 14800 id = 4219  }  
        name  = "Submarine Division 52"  
        type  = submarine  
        model = 2 # S-class  
       }  
      Division =  
      {  id    = {  type = 14800 id = 4220  }  
        name  = "Submarine Division 53"  
        type  = submarine  
        model = 2 # S-class  
       }  
      Division =  
      {  id    = {  type = 14800 id = 4222  }  
        name  = "Submarine Division 71"  
        type  = submarine  
        model = 1 # R-class  
       }
      Division =  
      {  id    = {  type = 14800 id = 4223  }  
        name  = "Submarine Division 72"  
        type  = submarine  
        model = 2 # S-class  
       }  
     } 
    # Submarine Squadron 20
    navalunit =  
    {  name     = "USN Submarine Squadron 20"  
      id       = {  type = 14800 id = 4005  }  
      location = 1734  
      base     = 1734 
      Division =  
      {  id    = {  type = 14800 id = 4006  }  
        name  = "Submarine Division 21"  
        type  = submarine  
        model = 4 # Salmon-class
       } 
      Division =  
      {  id    = {  type = 14800 id = 4007  }  
        name  = "Submarine Division 22"  
        type  = submarine  
        model = 5 # Sargo-class  
       } 
      Division =  
      {  id    = {  type = 14800 id = 4008  }  
        name  = "Submarine Division 201"  
        type  = submarine  
        model = 2 # S-class  
       } 
      Division =  
      {  id    = {  type = 14800 id = 4224  }  
        name  = "Submarine Division 202"  
        type  = submarine  
        model = 5 # Sargo-class  
       } 
      Division =  
      {  id    = {  type = 14800 id = 4225  }  
        name  = "Submarine Division 203"  
        type  = submarine  
        model = 4 # Porpoise-class
       } 
     }
    # USN Southeast Pacific Force
    navalunit =  
    {  name     = "USN Southeast Pacific Force"  
      id       = {  type = 14800 id = 4031  }  
      location = 2352  
      base     = 889  
      Division =  
      {  id   = {  type = 14800 id = 4032  }  
        name  = "USS Albemarle"  
        type  = escort_carrier  
        model = 0    
       }
      Division =  
      {  id    = {  type = 14800 id = 41  }  
        name  = "USS Richmond"  
        type  = light_cruiser  
        model = 3  
       }  
     } 
    # USS Pocomoke
    navalunit =  
    {  name     = "USS Pocomoke"  
      id       = {  type = 14800 id = 3112  }  
      location = 2441  
      base     = 1582  
      Division =  
      {  id   = {  type = 14800 id = 3012  }  
        name  = "USS Pocomoke"  
        type  = escort_carrier  
        model = 0    
       }
     } 
    # USS Boise
    navalunit =  
    {  name     = "USS Boise"  
      id       = {  type = 14800 id = 5090  }  
      location = 1805  
      base     = 1805  
      Division =  
      {  id    = {  type = 14800 id = 509  }  
        name  = "USS Boise"  
        type  = light_cruiser  
        model = 5  
       }
     } 
    # USS St. Louis
    navalunit =  
    {  name     = "USS St. Louis"  
      id       = {  type = 14800 id = 5091  }  
      location = 1889  
      base     = 1889  
      Division =  
      {  id    = {  type = 14800 id = 2042  }  
        name  = "USS St. Louis"  
        type  = light_cruiser  
        model = 5  
       }
     } 
    # USS Chicago
    navalunit =  
    {  name     = "USS Chicago"  
      id       = {  type = 14800 id = 5093  }  
      location = 1889  
      base     = 1889  
      Division =  
      {  id    = {  type = 14800 id = 49  }  
		name  = "USS Chicago"  
		type  = heavy_cruiser  
		model = 3 
		extra1 = naval_torpedoes_l
		brigade_model1 = 4			
       }  
     }  
    # USS Chester
    navalunit =  
    {  name     = "USS Chester"  
      id       = {  type = 14800 id = 5094  }  
      location = 1705  
      base     = 1707  
      Division =  
      {  id    = {  type = 14800 id = 53  }  
        name  = "USS Chester"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
     } 
    # Battleship Division 3
    navalunit =  
    {  location = 1734  
      base     = 1734  
      id       = {  type = 14800 id = 98  }  
      name     = "USN Battleship Division 3"  
      Division =  
      {  id    = {  type = 14800 id = 99  }  
        name  = "USS New Mexico"  
        type  = battleship  
        model = 4  
       }  
      Division =  
      {  id    = {  type = 14800 id = 100  }  
        name  = "USS Mississippi"  
        type  = battleship  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
     } 
    # USS Idaho
    navalunit =  
    {  name     = "USS Idaho"  
      id       = {  type = 14800 id = 5095  }  
      location = 1874  
      base     = 1874  
      Division =  
      {  id    = {  type = 14800 id = 101  }  
		name  = "USS Idaho"  
		type  = battleship  
		model = 4  
		extra1 = naval_anti_air_l
		extra2 = naval_torpedoes_l
		brigade_model2 = 4	
       } 
     } 
    # USS North Carolina
    navalunit =  
    {  location = 1586  
      base     = 1586  
      id       = {  type = 14800 id = 4210  }  
      name     = "USS North Carolina"  
      Division =  
      {  id    = {  type = 14800 id = 4023  }  
        name  = "USS North Carolina"  
        type  = battleship  
        model = 7 
        extra1 = naval_anti_air_l 
	extra2 = naval_torpedoes_l
	brigade_model2 = 4
       }  
     }  
    # USS Columbia
    navalunit =  
    {  location = 1586  
      base     = 1586  
      id       = {  type = 14800 id = 5097  }  
      name     = "USS Columbia"  
      Division =  
      {  id    = {  type = 14800 id = 3019  }  
        name  = "USS Columbia"  
        type  = light_cruiser  
        model = 6  
       } 
     }  
    # USS Tangier
    navalunit =  
    {  location = 1734  
      base     = 1734  
      id       = {  type = 14800 id = 5101  }  
      name     = "USS Tangier"  
      Division =  
      {  id    = {  type = 14800 id = 3015  }  
        name  = "USS Tangier"  
        type  = escort_carrier  
        model = 0  
       } 
     }  
    # USS Montpelier
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 5098  }  
      name     = "USS Montpelier"  
      Division =  
      {  id    = {  type = 14800 id = 3020  }  
        name  = "USS Montpelier"  
        type  = light_cruiser  
        model = 6  
       } 
     }  
    # USS Denver
    navalunit =  
    {  location = 1805  
      base     = 1795  
      id       = {  type = 14800 id = 5099  }  
      name     = "USS Denver"  
      Division =  
      {  id    = {  type = 14800 id = 3021  }  
        name  = "USS Denver"  
        type  = light_cruiser  
        model = 6  
       } 
     }  
    # USS Chandeleur
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 5100  }  
      name     = "USS Chandeleur"  
      Division =  
      {  id    = {  type = 14800 id = 3014  }  
        name  = "USS Chandeleur"  
        type  = escort_carrier  
        model = 0  
       } 
     }  
    # Training Squadron
    navalunit =  
    {  name     = "Training Squadron"  
      id       = {  type = 14800 id = 4227  }  
      location = 1812  
      base     = 1812 
      Division =  
      {  id    = {  type = 14800 id = 64  }  
        name  = "Destroyer Division 3"  
        type  = destroyer  
        model = 3  
       }
      Division =  
      {  id    = {  type = 14800 id = 4229  }  
        name  = "Destroyer Division 32"  
        type  = destroyer  
        model = 3  
       }  
     } 
    # Fleet Train, Pacific
    navalunit =  
    {  name     = "Fleet Train, Pacific"  
      id       = {  type = 14800 id = 111  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id   = {  type = 14800 id = 134  }  
        name = "Transport Division 10"  
        type = transport
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7150  }  
        name = "Transport Division 12"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7151  }  
        name = "Transport Division 14"  
        type = transport  
		model = 3
       }  
     }  
    # 1st Naval District
    navalunit =  
    {  location = 1789  
      base     = 1789  
      id       = {  type = 14800 id = 92  }  
      name     = "1st Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 7152  }  
        name = "Transport Division 13"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 135  }  
        name = "Transport Division 15"  
        type = transport  
		model = 3
       }  
     }  
    # 11th Naval District
    navalunit =  
    {  location = 1886  
      base     = 1886  
      id       = {  type = 14800 id = 4231  }  
      name     = "11th Naval District"  
      Division =  
      {  id    = {  type = 14800 id = 4232  }  
        name  = "Transport Division 16"  
        type  = transport
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 4233  }  
        name  = "Destroyer Division 33"  
        type  = destroyer  
        model = 3 
       }  
     }  
    # 12th Naval District
    navalunit =  
    {  location = 1889  
      base     = 1889  
      id       = {  type = 14800 id = 4234  }  
      name     = "12th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 159  }  
        name = "Transport Division 18"  
        type = transport  
		model = 3
       }  
     }  
    # 13th Naval District
    navalunit =  
    {  location = 1874  
      base     = 1874  
      id       = {  type = 14800 id = 106  }  
      name     = "13th Naval District"  
      Division =  
      {  id   = {  type = 14800 id = 140  }  
        name = "Transport Division 20"  
        type = transport  
		model = 3
       }  
     }  
    # USN Pacific Transport Fleet
    navalunit =  
    {  location = 1586  
      base     = 1586
      id       = {  type = 14800 id = 133  }  
      name     = "USN Pacific Transport Fleet"  
      Division =  
      {  id   = {  type = 14800 id = 7153  }  
        name = "Transport Division 28"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7154  }  
        name = "Transport Division 30"  
        type = transport  
		model = 3
       }  
     }  
    # USN Eastern Task Force
    navalunit =  
    {  location = 727  
      base     = 727
      id       = {  type = 14800 id = 1330  }  
      name     = "USN Eastern Task Force"  
      Division =  
      {  id   = {  type = 14800 id = 7155  }  
        name = "Transport Division 32"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7156  }  
        name = "Transport Division 34"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7157  }  
        name = "Transport Division 36"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7158  }  
        name = "Transport Division 38"  
        type = transport  
		model = 3
       }  
     }  
    # USN Center Task Force
    navalunit =  
    {  location = 728  
      base     = 728
      id       = {  type = 14800 id = 1331  }  
      name     = "USN Center Task Force"  
      Division =  
      {  id   = {  type = 14800 id = 7159  }  
        name = "Transport Division 31"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7160  }  
        name = "Transport Division 33"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7161  }  
        name = "Transport Division 35"  
        type = transport  
		model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 7162  }  
        name = "Transport Division 37"  
        type = transport  
		model = 3
       }  
     }  

  airunit =
  { id       = { type = 14800 id = 5000 }
    name     = "First Air Force"
    location = 1795
    base     = 1795
    division =
    { id       = { type = 14800 id = 5001 }
      name     = "13th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5002 }
      name     = "302nd USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
  }
  airunit =
  { id       = { type = 14800 id = 5003 }
    name     = "Second Air Force"
    location = 1874
    base     = 1874
    division =
    { id       = { type = 14800 id = 5004 }
      name     = "16th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5005 }
      name     = "84th USAAF Bombardment Group"
      strength = 100
      type     = cas
      model    = 2
    }
  }
  airunit =
  { id       = { type = 14800 id = 5006 }
    name     = "Third Air Force"
    location = 1953
    base     = 1953
    division =
    { id       = { type = 14800 id = 5007 }
      name     = "10th USAAF Fighter Group"
      strength = 40
      type     = multi_role
      model    = 6
    }
    division =
    { id       = { type = 14800 id = 5008 }
      name     = "21st USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5009 }
      name     = "309th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5010 }
      name     = "85th USAAF Bombardment Group"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14800 id = 5011 }
      name     = "88th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 4
      extra    = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 14800 id = 5012 }
    name     = "Fourth Air Force"
    location = 1889
    base     = 1889
    division =
    { id       = { type = 14800 id = 5013 }
      name     = "412th USAAF Fighter Group"
      strength = 100
      type     = interceptor
      model    = 9
    }
  }
  airunit =
  { id       = { type = 14800 id = 5014 }
    name     = "Fifth Air Force"
    location = 1607
    base     = 1704
    division =
    { id       = { type = 14800 id = 5015 }
      name     = "8th USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 6
    }
    division =
    { id       = { type = 14800 id = 5016 }
      name     = "35th USAAF Fighter Group"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5017 }
      name     = "49th USAAF Fighter Group"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5018 }
      name     = "3rd USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5019 }
      name     = "22nd USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5020 }
      name     = "38th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5021 }
      name     = "43rd USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 14800 id = 5022 }
    name     = "Sixth Air Force"
    location = 889
    base     = 889
    division =
    { id       = { type = 14800 id = 5023 }
      name     = "16th USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 6
    }
  }
  airunit =
  { id       = { type = 14800 id = 5024 }
    name     = "Seventh Air Force"
    location = 1734
    base     = 1734
    division =
    { id       = { type = 14800 id = 5025 }
      name     = "15th USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 6
    }
    division =
    { id       = { type = 14800 id = 5026 }
      name     = "318th USAAF Interceptor Group"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5027 }
      name     = "41st USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 8
    }
  }
  airunit =
  { id       = { type = 14800 id = 5028 }
    name     = "Eighth Air Force"
    location = 25
    base     = 25
    division =
    { id       = { type = 14800 id = 5029 }
      name     = "100th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5030 }
      name     = "303rd USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5031 }
      name     = "305th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5032 }
      name     = "306th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5033 }
      name     = "4th USAAF Fighter Group"
      strength = 100
      type     = interceptor
      model    = 10
    }
    division =
    { id       = { type = 14800 id = 5034 }
      name     = "56th USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5035 }
      name     = "78th USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 6
    }
    division =
    { id       = { type = 14800 id = 5036 }
      name     = "91st USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5037 }
      name     = "92nd USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5038 }
      name     = "93rd USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 14800 id = 5039 }
    name     = "Ninth Air Force"
    location = 761
    base     = 761
    division =
    { id       = { type = 14800 id = 5040 }
      name     = "57th USAAF Fighter Group"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5041 }
      name     = "79th USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 6
    }
    division =
    { id       = { type = 14800 id = 5042 }
      name     = "324th USAAF Fighter Group"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5043 }
      name     = "12th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 8
    }
    division =
    { id       = { type = 14800 id = 5044 }
      name     = "322nd USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 8
    }
  }
  airunit =
  { id       = { type = 14800 id = 5045 }
    name     = "Tenth Air Force"
    location = 1459
    base     = 1459
    division =
    { id       = { type = 14800 id = 5046 }
      name     = "7th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 4
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5047 }
      name     = "311th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 8
    }
    division =
    { id       = { type = 14800 id = 5067 }
      name     = "23rd USAAF Fighter Group"
      strength = 100
      type     = interceptor
      model    = 9
    }
    division =
    { id       = { type = 14800 id = 5068 }
      name     = "51st USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 6
    }
  }
  airunit =
  { id       = { type = 14800 id = 5048 }
    name     = "Eleventh Air Force"
    location = 2142
    base     = 2142
    division =
    { id       = { type = 14800 id = 5049 }
      name     = "343rd USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 6
    }
  }
  airunit =
  { id       = { type = 14800 id = 5050 }
    name     = "Twelfth Air Force"
    location = 728
    base     = 728
    division =
    { id       = { type = 14800 id = 5051 }
      name     = "12th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5052 }
      name     = "17th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 14800 id = 5053 }
      name     = "310th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 8
    }
    division =
    { id       = { type = 14800 id = 5054 }
      name     = "319th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 8
    }
    division =
    { id       = { type = 14800 id = 5055 }
      name     = "320th USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 8
    }
    division =
    { id       = { type = 14800 id = 5056 }
      name     = "321st USAAF Bombardment Group"
      strength = 100
      type     = tactical_bomber
      model    = 8
    }
    division =
    { id       = { type = 14800 id = 5057 }
      name     = "86th USAAF Bombardment Group"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14800 id = 5058 }
      name     = "97th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 14800 id = 5059 }
    name     = "Cactus Air Force"
    location = 1593
    base     = 1586
    division =
    { id       = { type = 14800 id = 5060 }
      name     = "11th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5061 }
      name     = "18th USAAF Fighter Group"
      strength = 100
      type     = interceptor
      model    = 10
    }
    division =
    { id       = { type = 14800 id = 5062 }
      name     = "307th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
    division =
    { id       = { type = 14800 id = 5063 }
      name     = "347th USAAF Fighter Group"
      strength = 100
      type     = multi_role
      model    = 6
    }
    division =
    { id       = { type = 14800 id = 5064 }
      name     = "5th USAAF Bombardment Group"
      strength = 100
      type     = strategic_bomber
      model    = 5
      extra    = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 14800 id = 5065 }
    name     = "Transport Command"
    location = 1812
    base     = 1812
    division =
    { id       = { type = 14800 id = 5066 }
      name     = "50th USAAF Troop Carrier Wing"
      strength = 100
      type     = transport_plane
      model    = 3
    }
  }

   division_development =    
   {  name  = "USS Essex"  
      type  = carrier  
      model = 4  
      cost  = 0.5  
      id    = {  type = 14800 id = 3009  }  
      date  = {  year = 1942 month = december day = 30  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS Yorktown"  
      type  = carrier  
      model = 4  
      cost  = 0.5  
      id    = {  type = 14800 id = 3028  }  
      date  = {  year = 1943 month = april day = 15  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS Intrepid"  
      type  = carrier  
      model = 4  
      cost  = 0.5  
      id    = {  type = 14800 id = 3042  }  
      date  = {  year = 1943 month = august day = 16  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS Hornet"  
      type  = carrier  
      model = 4  
      cost  = 0.5  
      id    = {  type = 14800 id = 3043  }  
      date  = {  year = 1943 month = november day = 29  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS Lexington"  
      type  = carrier  
      model = 4  
      cost  = 0.5  
      id    = {  type = 14800 id = 3044  }  
      date  = {  year = 1943 month = february day = 17  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS Bunker Hill"  
      type  = carrier  
      model = 4  
      cost  = 0.5  
      id    = {  type = 14800 id = 3045  }  
      date  = {  year = 1943 month = may day = 24  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS Wasp"  
      type  = carrier  
      model = 4  
      cost  = 0.5  
      id    = {  type = 14800 id = 3046  }  
      date  = {  year = 1943 month = november day = 24  }  
      extra = cag  
      brigade_model = 4  
     }
   division_development =    
   {  name  = "USS Independence"  
      type  = escort_carrier  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3023  }  
      date  = {  year = 1943 month = january day = 14  }    
     }  
   division_development =    
   {  name  = "USS Princeton"  
      type  = escort_carrier  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3024  }  
      date  = {  year = 1943 month = february day = 25  }    
     }  
   division_development =    
   {  name  = "USS Belleau Wood"  
      type  = escort_carrier  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3047  }  
      date  = {  year = 1943 month = march day = 30  }    
     }  
   division_development =    
   {  name  = "USS Cowpens"  
      type  = escort_carrier  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3048  }  
      date  = {  year = 1943 month = may day = 28  }    
     }  
   division_development =    
   {  name  = "USS Monterey"  
      type  = escort_carrier  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3049  }  
      date  = {  year = 1943 month = june day = 17  }    
     }  
   division_development =    
   {  name  = "USS Langley"  
      type  = escort_carrier  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3050  }  
      date  = {  year = 1943 month = august day = 30  }    
     }  
   division_development =    
   {  name  = "USS Cabot"  
      type  = escort_carrier  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3051  }  
      date  = {  year = 1943 month = july day = 24  }    
     }  
   division_development =    
   {  name  = "USS Bataan"  
      type  = escort_carrier  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3052  }  
      date  = {  year = 1943 month = november day = 17  }    
     }  
   division_development =    
   {  name  = "USS Tennessee"  
      type  = battleship  
      model = 6 # modernized to resemble South Dakota-class, but still not a South Dakota; uses BB 1922 model
      cost  = 0.5  
      id    = {  type = 14800 id = 3039  }  
      date  = {  year = 1943 month = may day = 7  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     } 
   division_development =    
   {  name  = "USS California"  
      type  = battleship  
      model = 6 # modernized to resemble South Dakota-class, but still not a South Dakota; uses BB 1922 model
      cost  = 0.5  
      id    = {  type = 14800 id = 3040  }  
      date  = {  year = 1944 month = january day = 30  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     } 
   division_development =    
   {  name  = "USS West Virginia"  
      type  = battleship  
      model = 6 # modernized to resemble South Dakota-class, but still not a South Dakota; uses BB 1922 model
      cost  = 0.5  
      id    = {  type = 14800 id = 3041  }  
      date  = {  year = 1944 month = july day = 12  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     } 
   division_development =    
   {  name  = "USS Iowa"  
      type  = battleship  
      model = 8  
      cost  = 0.5  
      id    = {  type = 14800 id = 3005  }  
      date  = {  year = 1943 month = february day = 22  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS New Jersey"  
      type  = battleship  
      model = 8  
      cost  = 0.5  
      id    = {  type = 14800 id = 3006  }  
      date  = {  year = 1943 month = may day = 23  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS Missouri"  
      type  = battleship  
      model = 8  
      cost  = 0.5  
      id    = {  type = 14800 id = 3007  }  
      date  = {  year = 1944 month = june day = 11  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS Wisconsin"  
      type  = battleship  
      model = 8  
      cost  = 0.5  
      id    = {  type = 14800 id = 3008  }  
      date  = {  year = 1944 month = april day = 16  }
      extra1 = naval_torpedoes_l
      brigade_model1 = 4    
     }  
   division_development =    
   {  name  = "USS Alaska"  
      type  = battlecruiser  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3066  }  
      date  = {  year = 1944 month = june day = 17  }    
     }      
   division_development =    
   {  name  = "USS Guam"  
      type  = battlecruiser  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 3067  }  
      date  = {  year = 1944 month = september day = 17  }    
     }      
   division_development =    
   {  name  = "USS Santa Fe"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3022  }  
      date  = {  year = 1942 month = november day = 24  }    
     }      
   division_development =    
   {  name  = "USS Birmingham"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3025  }  
      date  = {  year = 1943 month = january day = 29  }    
     }      
   division_development =    
   {  name  = "USS Mobile"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3026  }  
      date  = {  year = 1943 month = march day = 24  }    
     }      
   division_development =    
   {  name  = "USS Vincennes"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3054  }  
      date  = {  year = 1944 month = january day = 21  }    
     }      
   division_development =    
   {  name  = "USS Biloxi"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3058  }  
      date  = {  year = 1943 month = august day = 30  }    
     }      
   division_development =    
   {  name  = "USS Houston"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3059  }  
      date  = {  year = 1943 month = december day = 20  }    
     }   
   division_development =    
   {  name  = "USS Cheyenne" # renamed Vicksburg 26.11.1942
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3060  }  
      date  = {  year = 1944 month = june day = 12  }    
     }         
   division_development =    
   {  name  = "USS Miami"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3061  }  
      date  = {  year = 1943 month = december day = 28  }    
     }      
   division_development =    
   {  name  = "USS Astoria"  
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3062  }  
      date  = {  year = 1944 month = may day = 17  }    
     }      
   division_development =    
   {  name  = "USS Oakland"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 3063  }  
      date  = {  year = 1943 month = july day = 17  }    
     }      
   division_development =    
   {  name  = "USS Reno"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 3064  }  
      date  = {  year = 1943 month = december day = 28  }    
     }      
   division_development =    
   {  name  = "USS Flint"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 3065  }  
      date  = {  year = 1944 month = august day = 30  }    
     }      
   division_development =    
   {  name  = "USS Newark" # renamed USS San Jacinto (escort_carrier-4) 30.01.1943
      type  = light_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3053  }  
      date  = {  year = 1943 month = november day = 15  }    
     }  
   division_development =    
   {  name  = "USS Baltimore"  
      type  = heavy_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3027  }  
      date  = {  year = 1943 month = april day = 15  }    
     }      
   division_development =    
   {  name  = "USS Boston"  
      type  = heavy_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3055  }  
      date  = {  year = 1943 month = june day = 30  }    
     }      
   division_development =    
   {  name  = "USS Canberra"  
      type  = heavy_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3056  }  
      date  = {  year = 1943 month = october day = 14  }    
     }      
   division_development =    
   {  name  = "USS Quincy"  
      type  = heavy_cruiser  
      model = 6  
      cost  = 0.3  
      id    = {  type = 14800 id = 3057  }  
      date  = {  year = 1943 month = december day = 15  }    
     }      
   division_development =    
   {  name  = "10th Mountain Division"  
      type  = bergsjaeger  
      model = 11  
      cost  = 0.1  
      id    = {  type = 14800 id = 3069  }  
      date  = {  year = 1943 month = july day = 15  }    
     }  
   division_development =    
   {  name  = "2nd Cavalry (Colored) Division"  
      type  = cavalry  
      model = 11  
      cost  = 0.1  
      id    = {  type = 14800 id = 3071  }  
      date  = {  year = 1943 month = february day = 25  }    
     }  
   division_development =    
   {  name  = "11th US Airborne 'The Angels' Division"  
      type  = paratrooper  
      model = 1  
      cost  = 0.1  
      id    = {  type = 14800 id = 3029  }  
      date  = {  year = 1943 month = february day = 23  }    
     }  
   division_development =    
   {  name  = "63rd 'Blood & Fire' Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3030  }  
      date  = {  year = 1943 month = june day = 15  }    
     }  
   division_development =    
   {  name  = "66th 'Black Panthers' Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3031  }  
      date  = {  year = 1943 month = april day = 15  }    
     }  
   division_development =    
   {  name  = "69th 'Fighting 69th' Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3032  }  
      date  = {  year = 1943 month = may day = 15  }    
     }  
   division_development =    
   {  name  = "70th 'Trailblazers' Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3033  }  
      date  = {  year = 1943 month = june day = 15  }    
     }  
   division_development =    
   {  name  = "75th Infantry Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3034  }  
      date  = {  year = 1943 month = april day = 15  }    
     }  
   division_development =    
   {  name  = "87th 'Golden Acorns' Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3035  }  
      date  = {  year = 1942 month = december day = 12  }    
     }  
   division_development =    
   {  name  = "97th 'Trident' Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3036  }  
      date  = {  year = 1943 month = february day = 25  }    
     }   
   division_development =    
   {  name  = "106th 'Golden Lions' Division"  
      type  = infantry  
      model = 10  
      cost  = 0.1  
      id    = {  type = 14800 id = 3037  }  
      date  = {  year = 1943 month = march day = 15  }    
     }   
   division_development =    
   {  name  = "20th Armored Division"  
      type  = armor  
      model = 1  
      cost  = 0.1  
      id    = {  type = 14800 id = 3038  }  
      date  = {  year = 1943 month = march day = 15  }    
     }   
   division_development =    
   {  name  = "Transport Division 39"  
      type  = transport  
      model = 3  
      cost  = 0.3  
      id    = {  type = 14800 id = 3068  }  
      date  = {  year = 1942 month = december day = 1  }    
     }      
   }  
  
