 
 ############################## 
 # Country definition for the British Raj # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = U02  
   regular_id             = IND 
   puppet                 = ENG 
   capital                = 1459 
   manpower               = 489 
   dissent = 9
   
   
   #relative_manpower = 0.6000 
   # Resource Reserves 
energy                 = 5520
metal                  = 2760
rare_materials         = 1380
   oil                    = 500 
   supplies               = 500 
   money                  = 70 
   transports             = 200 
   escorts                = 20 
  
   
   diplomacy = 
   {   
  relation = {  tag = ENG value = 50 access = yes  }  
    } 
   nationalprovinces      = {
  #Malaysia                 
  1439 1445 1442 1450 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1413 1418 1443 1421 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529    } 
   ownedprovinces         = {   
  #Malaysia                 
  1439 1445 1442 1450 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1413 1418 1443 1421 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529 
   } 
   controlledprovinces    = {    
  #Malaysia                 
  1439 1445 1442 1450 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1413 1418 1443 1421 1458 1455 1414 1440 1441 
  #India  
  1519 1520 1468 1528 1481 1469 1478 1451 1454 1486 1490 1508 1479 1480 1516 1488 1453 1489 1491 1505 1506 1507 1492 1485 1470 1444 1446 1447 1471 1476 1483 1477 1482 1484 1521 1522 1518 1523 1524 1459 1460 1461 1462 1530 1531 1463 1527 1525 1532 1517 1512 1487 1493 1494 1501  1502 1503 1495 1504 1448 1449 1536 1500 1496 1514 1472 1535 1526 1497 1452 1473 1464 1465 1498 1499 1474 1466 1515 1475 1467 
  #Pakistan 
  1278 1540 1533 1534 1537 1538  1539 1529 
   } 
  
   SpyInfo                = {  country = "U02" NumberOfSpies = 3  } 
  
   techapps               = {  
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060    
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240   
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980   
#1930 Cavalry Division 
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
#Motorised Inf
1396
#Basic Armoured Car 
2860 2870 2880 2020   
#Great War Heavy Field Artillery 
2290 2300 2310 
#SW Tank 
7600 7610 2620 2010 
#Engineers
1830 1840 1850 1860
#Early Static Anti-Air Artillery 
2800 2450
#Great War Destroyer
3010 3020 3030 3040
#Interwar Light Cruiser 
3110 3120 3130 3140
#Early Heavy Cruiser 
3210 3220 3230
#Interwar Fighter 
4500 4510 4520 4530 4540 4550 4010
#Interwar Bomber 
4600 4610 4620 4630 4120
#Computers & cryptografi
5310 54010 54020 54030 5316 5326
#Manufactoring
5810 5820 5050 5830
#Improved Construction Engineering 
5800 5080 5090 
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810
#Medicine
5600


#Naval Doctrines
8010 8020 8050
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
# Defensive Focus Grand Battleplan Path (FRA / UK)
6560
} 
inventions = { 3000027 }
  policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 5 
     political_left    = 3 
     freedom           = 3 
     free_market       = 5 
     professional_army = 2 # no conscription 
     defense_lobby     = 3 
     interventionism   = 3 
    } 
   #peacetime_ic_mod = 0.6
   #wartime_ic_mod = 0.7
   headofstate            = {  type = 9 id = 825001  } 
   headofgovernment       = {  type = 9 id = 825002  } 
   foreignminister        = {  type = 9 id = 825003  } 
   armamentminister       = {  type = 9 id = 825004  } 
   ministerofsecurity     = {  type = 9 id = 825005  } 
   ministerofintelligence = {  type = 9 id = 825006  } 
   chiefofstaff           = {  type = 9 id = 825007  } 
   chiefofarmy            = {  type = 9 id = 825008  } 
   chiefofnavy            = {  type = 9 id = 825009  } 
   chiefofair             = {  type = 9 id = 825010  } 
  
   landunit = 
   {  name     = "Bombay District" 
     location = 1517 
     id       = {  type = 12700 id = 1001  } 
     Division = 
     {  id       = {  type = 12700 id = 1002  } 
       name     = "Mhow Area" 
       type     = garrison
	   model    = 3
       strength = 100 
              } 
     } 
   landunit = 
   {  name     = "Deccan District" 
     location = 1503 
     id       = {  type = 12700 id = 1003  } 
     Division = 
     {  id            = {  type = 12700 id = 1004  } 
       name          = "4th Indian Division" 
       type          = infantry 
	   model    = 7
       strength      = 100 
       } 
 Division = 
     {  id       = {  type = 12700 id = 1005  } 
       name     = "4th Indian Cavalry Brigade" 
       type     = cavalry 
	   model    = 6
       strength = 40 
       }   
     Division = 
     {  id       = {  type = 12700 id = 1006  } 
       name     = "Poona Area" 
       type     = garrison
	   model    = 3
       strength = 100 
              } 
    } 
   landunit = 
   {  name     = "Kohat District" 
     location = 1537 
     id       = {  type = 12700 id = 1007  } 
     Division = 
     {  id       = {  type = 12700 id = 1008  } 
       name     = "Thal Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1009  } 
       name     = "Kohat Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
    } 
   landunit = 
   {  name     = "Lahore District" 
     location = 1530 
     id       = {  type = 12700 id = 1010  } 
     Division = 
     {  id       = {  type = 12700 id = 1011  } 
       name     = "Sialkot Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1012  } 
       name     = "Ferozepore Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1013  } 
       name     = "Jullundur Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1014  } 
       name     = "Lahore Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1015  } 
       name     = "Ambala Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
    } 
   landunit = 
   {  name     = "Lucknow District" 
     location = 1459 
     id       = {  type = 12700 id = 1016  } 
     Division = 
     {  id       = {  type = 12700 id = 1017  } 
       name     = "Allahabad Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      }
	       Division = 
     {  id       = {  type = 12700 id = 1018  } 
       name     = "Delhi Area" 
       type     = garrison
	   model    = 3
       strength = 100
	extra = artillery
	brigade_model = 5 
       } 	  
    } 
   landunit = 
   {  name     = "Madras District" 
     location = 1500 
     id       = {  type = 12700 id = 1019  } 
     Division = 
     {  id       = {  type = 12700 id = 1020  } 
       name     = "Madras Brigade" 
       type     = garrison
	   model    = 3
       strength = 100 
	extra = engineer
	brigade_model = 2 
      } 
    } 
   landunit = 
   {  name     = "Meerut District" 
     location = 1460 
     id       = {  type = 12700 id = 1021  } 
     Division = 
     {  id       = {  type = 12700 id = 1022  } 
       name     = "3rd Indian Division" 
       type     = infantry 
	   model    = 7
       extra    = armored_car 
	   brigade_model = 2
       strength = 100 
      } 
	Division = 
     {  id       = {  type = 12700 id = 1023  } 
       name     = "3rd Indian Cavalry Brigade" 
       type     = cavalry 
	   model    = 6
       strength = 40
       extra    = armored_car 
	   brigade_model = 2
        } 
    } 
   landunit = 
   {  name     = "Peshawar District" 
     location = 1537 
     id       = {  type = 12700 id = 1024  } 
     Division = 
     {  id       = {  type = 12700 id = 1025  } 
       name     = "Landikotal Brigade" 
       type     = militia
	   model    = 4
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1026  } 
       name     = "Peshawar Brigade" 
       type     = militia
	   model    = 4
       strength = 90 
	extra = artillery
	brigade_model = 5 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1027  } 
       name     = "Nowshera Brigade" 
       type     = militia
	   model    = 4
       strength = 90 
      } 
	Division = 
     {  id       = {  type = 12700 id = 1028  } 
       name     = "1st Indian Cavalry Brigade" 
       type     = cavalry 
	   model    = 6
       strength = 40
        } 
    } 
   landunit = 
   {  name     = "Presidency & Assam District" 
     location = 1447 
     id       = {  type = 12700 id = 1029  } 
     Division = 
     {  id       = {  type = 12700 id = 1030  } 
       name     = "Eastern Bengal Brigade" 
       type     = garrison
	   model    = 3
       strength = 100 
	extra = engineer
	brigade_model = 3 
      } 
    } 
   landunit = 
   {  name     = "Rawalpindi District" 
     location = 1534 
     id       = {  type = 12700 id = 1031  } 
     Division = 
     {  id       = {  type = 12700 id = 1032  } 
       name     = "1st Indian Division" 
       type     = infantry
		model    = 7	   
       strength = 100 
        extra = artillery
	brigade_model = 5
      } 
    } 
   landunit = 
   {  name     = "Waziristan District" 
     location = 1534 
     id       = {  type = 12700 id = 1033  } 
     Division = 
     {  id       = {  type = 12700 id = 1034  } 
       name     = "Razmak Brigade" 
       type     = militia
	   model    = 4
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1035  } 
       name     = "Bannu Brigade" 
       type     = militia
	   model    = 4
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1036  } 
       name     = "Wana Brigade" 
       type     = militia
	   model    = 4
       strength = 90 
      } 
    } 
   landunit = 
   {  name     = "Western District" 
     location = 1529 
     id       = {  type = 12700 id = 1037  } 
     Division = 
     {  id       = {  type = 12700 id = 1038  } 
       name     = "2nd Indian Division" 
       type     = infantry 
	   model    = 7
       strength = 100 
      }
     Division = 
     {  id       = {  type = 12700 id = 1039  } 
       name     = "Quetta Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1040  } 
       name     = "Khojak Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1041  } 
       name     = "Zhob Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
     Division = 
     {  id       = {  type = 12700 id = 1042  } 
       name     = "Sind Brigade" 
       type     = militia
	   model    = 4
       strength = 80 
      } 
    } 
   landunit = 
   {  name     = "Jammu & Kashmir State Forces" 
     location = 1540 
     id       = {  type = 12700 id = 1043  } 
      Division = 
     {  id       = {  type = 12700 id = 1044  } 
       name     = "Jammu Brigade" 
       type     = militia
	   model    = 3
       strength = 100 
	locked = yes
      } 
     Division = 
     {  id       = {  type = 12700 id = 1045  } 
       name     = "Kashmir Brigade" 
       type     = militia
	   model    = 3
       strength = 100 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Gwalior State Forces" 
     location = 1523 
     id       = {  type = 12700 id = 1046  } 
	Division = 
     {  id       = {  type = 12700 id = 1047  } 
       name     = "Gwalior Cavalry Brigade" 
       type     = cavalry 
	   model    = 5
       strength = 40
	locked = yes
        } 
     Division = 
     {  id       = {  type = 12700 id = 1048  } 
       name     = "Gwalior Infantry Brigade" 
       type     = militia
	   model    = 3
       strength = 100 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Hyderabad State Forces" 
     location = 1487 
     id       = {  type = 12700 id = 1049  } 
     Division = 
     {  id       = {  type = 12700 id = 1050  } 
       name     = "Hyderabad State Forces" 
       type     = militia
	   model    = 3
       strength = 100 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Bikaner State Forces" 
     location = 1527 
     id       = {  type = 12700 id = 1051  } 
     Division = 
     {  id       = {  type = 12700 id = 1052  } 
       name     = "Bikaner State Forces" 
       type     = militia
	   model    = 3
       strength = 80 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Patiala State Forces" 
     location = 1531 
     id       = {  type = 12700 id = 1053  } 
     Division = 
     {  id       = {  type = 12700 id = 1054  } 
       name     = "Patiala State Forces" 
       type     = militia
	   model    = 3
       strength = 80 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Mysore State Forces" 
     location = 1507 
     id       = {  type = 12700 id = 1055  } 
     Division = 
     {  id       = {  type = 12700 id = 1056  } 
       name     = "Mysore State Forces" 
       type     = militia
	   model    = 3
       strength = 70 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Burma Command" 
     location = 1415 
     id       = {  type = 12700 id = 1057  } 
     Division = 
     {  id       = {  type = 12700 id = 1058  } 
       name     = "Rangoon Brigade" 
       type     = militia
	   model    = 4
       strength = 100 
        extra = artillery
	brigade_model = 5
      } 
     Division = 
     {  id       = {  type = 12700 id = 1059  } 
       name     = "Mandalay Brigade" 
       type     = militia
	   model    = 4
       strength = 100 
        extra = police
	brigade_model = 1
      } 
    } 
  
	navalunit = { 
		id = { type = 12700 id = 288 } 
		name = "Royal Indian Navy" 
		location = 1517 
		base = 1517 
		division = { 
			id = { type = 12700 id = 284 } 
			name = "HMIS 2nd Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 286 } 
			name = "HMIS 4th Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 2318 } 
			name = "2nd DD. Division" 
			type = destroyer 
			} 
		division = { 
			id = { type = 12700 id = 2319 } 
			name = "3rd DD. Division" 
			type = destroyer 
			} 
		}  
	navalunit = { 
		id = { type = 12700 id = 2332 } 
		name = "1st Squadron" 
		location = 1517 
		base = 1517 
		division = { 
			id = { type = 12700 id = 289 } 
			name = "HMIS 1st Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 285 } 
			name = "HMIS 3rd Transport Flotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 12700 id = 287 } 
			name = "HMIS Destroyer Flotilla" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 12700 id = 2317 } 
			name = "1st DD. Division" 
			type = destroyer 
			} 
		} 
   airunit = 
   {  location = 1517 
     base     = 1517 
     id       = {  type = 12700 id = 80  } 
     name     = "Royal Indian Air Force" 
     Division = 
     {  id       = {  type = 12700 id = 81  } 
       name     = "Indian Group" 
       type     = tactical_bomber 
       model    = 4
       strength = 100 
      } 
    } 
  }