 
 ############################## 
 # Country definition for SIK # 
 ############################## 
  
 country = 
 {  tag                    = SIK 
   # Resource Reserves 
   puppet = SOV 
energy                 = 240
metal                  = 120
rare_materials         = 60
   oil                    = 5000 
   supplies               = 2000 
   money                  = 10 
   capital                = 1281 # Urumqi 
   manpower               = 0 
   dissent                = 40 
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 3 
     political_left    = 4 
     freedom           = 3 
     free_market       = 3 
     professional_army = 2 
     defense_lobby     = 5 
     interventionism   = 5 
    } 
   nationalprovinces      = {  1273 1278 1279 1280 1281 1277 1274 1275 1276 1282  } 
   ownedprovinces         = {  1273 1279 1280 1281 1277 1274 1275 1282 1276  } 
   controlledprovinces    = {  1273 1279 1280 1281 1277 1274 1275 1282 1276  } 
   # ROTW Minor Tech '36 
   # Group E 1936 techs 
   # ###################### 
   # GW fighter 
   techapps               = {  
#Interwar Fighter  
4500 4510 4520 4530
#Interwar Armoured Car  
2860
#Light Field Artillery  
2290
#SW Tank 
7600 7610
#Great War Infantry Division  
1010 1020 1030 1040 1050 1060 1070 1080
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#1916 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 
#Early Agriculture
5700 
#Landdoctrine ww2 - rest
6500 6510 6530 6910
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 
  } 
  inventions = { 3000027 }
   diplomacy = 
   {  relation = {  tag = CHC value = 40  } 
     relation = {  tag = SOV value = 125  } 
     relation = {  tag = TAN value = 125  } 
    } 
   SpyInfo                = {  country = "SIK" NumberOfSpies = 4  } 
   headofstate            = {  type = 9 id = 420001  } 
   headofgovernment       = {  type = 9 id = 420002  } 
   foreignminister        = {  type = 9 id = 420003  } 
   armamentminister       = {  type = 9 id = 420004  } 
   ministerofsecurity     = {  type = 9 id = 420005  } 
   ministerofintelligence = {  type = 9 id = 420006  } 
   chiefofstaff           = {  type = 9 id = 420007  } 
   chiefofarmy            = {  type = 9 id = 420008  } 
   chiefofnavy            = {  type = 9 id = 420009  } 
   chiefofair             = {  type = 9 id = 420010  } 
   landunit = 
   {  location = 1281 
     name     = "Xin'jiang JÅEtuan 1" 
     id       = {  type = 25600 id = 1  } 
     Division = 
     {  id   = {  type = 25600 id = 2  } 
       name = "1 Xin'jiang Shi" 
       type = infantry 
	   strength = 40 
	   model    = 6
      } 
     Division = 
     {  id   = {  type = 25600 id = 3  } 
       name = "7 Xin'jiang LÅE" 
       type = militia 
	   strength = 40 
	   model    = 3
      } 
     Division = 
     {  id   = {  type = 25600 id = 4  } 
       name = "8 Xin'jiang LÅE" 
       type = militia 
	   strength = 40 
	   model    = 3
      } 
    } 
  } 
 