 
 ############################## 
 # Country definition for SOV # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = SOV 
   regular_id             = RUS 
   intrinsic_gov_type     = leninist 
   capital                = 572 
   # Resource Reserves 
energy                 = 12000
metal                  = 6000
rare_materials         = 3000
   oil                    = 500 
   supplies               = 500 
   money                  = 30 
   manpower               = 1953 
   dissent                = 20 
   transports             = 300 
   escorts                = 20 
     research_mod = 0.75

   
   diplomacy = 
   {  relation = 
     {  tag        = AFG 
       value      = 1 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = BRA value = -50  } 
     relation = 
     {  tag        = BUL 
       value      = 15 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = CHC value = 100  } 
     relation = {  tag = CZE value = 100  } 
     relation = {  tag = ENG value = -25  } 
     relation = 
     {  tag        = EST 
       value      = -30 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = FIN value = 1  } 
     relation = 
     {  tag        = FRA 
       value      = 100 
       guaranteed = {  day = 7 month = january year = 1935  } 
      } 
     relation = {  tag = GER value = 1  } 
     relation = {  tag = GRE value = 15  } 
     relation = {  tag = IRE value = 1  } 
     relation = {  tag = JAP value = -10  } 
     relation = 
     {  tag        = LAT 
       value      = -30 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = 
     {  tag        = LIT 
       value      = 75 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = MON value = 150 access = yes  } 
     relation = 
     {  tag        = PER 
       value      = -20 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = POL value = -50  } 
     relation = {  tag = ROM value = 1  } 
     relation = {  tag = SAU value = 1  } 
     relation = {  tag = SIK value = 125  } 
     relation = {  tag = SPR value = -10  } 
     relation = 
     {  tag        = TAN 
       value      = 200 
       guaranteed = {  day = 16 month = may year = 1935  } 
       access     = yes 
      } 
     relation = 
     {  tag        = TUR 
       value      = 100 
       guaranteed = {  day = 30 month = december year = 1935  } 
      } 
     relation = {  tag = URU value = -100  } 
     relation = {  tag = USA value = 35  } 
     relation = 
     {  tag        = SCH 
       value      = 1 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
    } 
   SpyInfo                = {  country = "SOV" NumberOfSpies = 10  } 
    
   nationalprovinces      = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 
                              1153 1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 
                              568 615 625 564 621 588 584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 
                              1101 1118 502 501 1151 1130 1137 598 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 632 592 687 689 688 
                              542  686 681 543  547  538  539  537  536  534  535  706 702 704 703 709 708 710 701 696 695 694  691  692  
                              697  698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640  670 667 675 674 672 
                              664 671 673 684 663  693  618  655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  
                              554  569  572  570  585  574  540  541  559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  
                              620  626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  
                              580  652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648  1097 1098 1105 1104 1099 1103 
                              1106 1109 1108 1107 567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185 506 
                              1100 711 712 713 1149 1141 499 593 1542 
               714 576 555 705 
         1126 1127 1128 1069 1070 1161 1170 1171 
                             } 
   ownedprovinces         = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 1153 
                              1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 568 
                              615 625 564 621 588 584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 1101 
                              1118 502 501 1151 1130 1137 598 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 632 592 687 689 688 542  
                              686 681 543  547  538  539  537  536  534  535  706 702 704 703 709 708 710 701 696 695 694  691  692  697  
                              698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640  670 667 675 674 672 664 
                              671 673 684 663  693  618  655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  554  
                              569  572  570  585  574  540  541  559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  620  
                              626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  580  
                              652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648  1097 1098 1105 1104 1099 1103 1106 
                              1109 1108 1107 567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185 506 1100 
                              711 712 713 1149 1141 499 593 
               714 576 555 705 
         1126 1127 1128 1069 1070 1161 1170 1171 
                             } 
   controlledprovinces    = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180    1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154 507 505 498 1153 
                              1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 568 
                              615 625 564 621 588 584  500  1138 1139 583 1136 1135     1111 1110 504 1112 1102 1101 
                              1118 502 501 1151 1130 1137 598 1132 1131 1133 1115 1116 503 1117 1114 1113 690 699 632 592 687 689 688 542  
                              686 681 543  547  538  539  537  536  534  535  706 702 704 703 709 708 710 701 696 695 694  691  692  697  
                              698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640  670 667 675 674 672 664 
                              671 673 684 663  693  618  655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  554  
                              569  572  570  585  574  540  541  559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  620  
                              626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  580  
                              652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648  1097 1098 1105 1104 1099 1103 1106 
                              1109 1108 1107 567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185 506 1100 
                              711 712 713 1149 1141 499 593 
               714 576 555 705 
         1126 1127 1128 1069 1070 1161 1170 1171 
                             } 
	# ################ 
	techapps               = {
		#1931 Infantry Division  
		1010 1020 1030 1040 1050 1060 1070 1080 1090
		#1930 Mountain Division 
		1160 1170 1180 1190 1200 1210 1220 1230 1240
		#SEMI-MOTORIZED CAVALRY 
		13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
		#1935 Motorized Inf
		1396
		# Airborne Inf
		1670
		#Engineers
		1830 1840 1850
		#Interbellum 1930 Supply 
		1910 1920 1930 1940 1950 1960 1970
		#Early Tank 
		7600 7610 2620 2010 2630 2640 2646 2650 2030 2100
		#Basic Armoured Car  
		2860 2870 2880 2020
		#Early Field Artillery 
		2290 2300 2310 2900 2910 2920 2930 2940
		#Early Static Anti-Air Artillery 
		2800 2450 21180
		#Anti-Air Artillery Brigade
		2810 2820 
 
		#Improved Destroyer 
		3010 3020 3030 3040 3050 3060
		#Interwar Light Cruiser 
		3110 3120 3130 3140 3150 3160
		#Improved Heavy Cruiser 
		3210 3220 3230 3240 3250 3260
		#Great War Battlecruiser  
		3310 3320 3330 3340
		#Early Battleship 
		3410 3420 3430 3440 3450 3456 3460
		#Short Range Submarine 
		3610 3620 3630 3640 3650
		#Seaplane Carrier
		12100
		#Torpedo & ASW 18
		3720 3730 3736 3740 3750 3900
		#Troopships
		3810
	
		#Early Fighter  
		4500 4510 4520 4530 4540 4550 4010 4020
		#Early CAS
		4400
		#Early Bomber 
		4600 4610 4620 4630 4120 4130
		#Multirole fighter
		4300 4310 4320 4330 4340
		#ww1 strategic bomber
		4800 4810 4820
		#ww1 navalbomber
		4700 4710
		# Transports
		4290
		#SEAPLANES
		4740 4750 4760 4770
	
		#Modern Agriculture  
		5700 5710
		#Computers & cryptografi
		5310 54010 54020 54030 5316 5326
		#manufactoring
		5810 5820
		#Construction Engineering 
		5800 5080
		#Basic Oil Refining 
		5190
		#Medicine
		5600 5610 5620 
		#Exp. Rocket
		5560

		#Great War Hospital System 
		14000
		# Great War Land Doctrines (central powers)
		6500 6510 6530 6550 6590 6600 6620 6650 6670 6680 6690 6700 6710 6910
		#Land Doctrines
		6570 6300 6900

		# Naval Doctrines 
		# Theory
		8070 8010 8020 8030 8040 8050 8060 8070 8080
		# Amphib
		82300
		# Logistics
		82500
		# Naval Interdiction
		8500 8510 8550 8560 8600 8610
		# Indirect Approach
		81300 81310 81320 81330 81340
		# Naval Supremacy
		8100 8110 8120 8150 8160 8200

		#Air Doctrines - ww2 techs
		27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040
 
	} 
inventions = { 3000027 }
   blueprints             = {   } 
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 1 
     political_left    = 10 
     freedom           = 1 
     free_market       = 1 
     professional_army = 6 
     defense_lobby     = 6 
     interventionism   = 4 
    } 
	peacetime_ic_mod       = 0.70
	wartime_ic_mod       = 0.75
   headofstate            = {  type = 9 id = 30002  } # Stalin 
   headofgovernment       = {  type = 9 id = 30016  } # Molotov 
   foreignminister        = {  type = 9 id = 30003  } 
   armamentminister       = {  type = 9 id = 30004  } 
   ministerofsecurity     = {  type = 9 id = 30005  } 
   ministerofintelligence = {  type = 9 id = 30006  } 
   chiefofstaff           = {  type = 9 id = 30007  } 
   chiefofarmy            = {  type = 9 id = 30008  } 
   chiefofnavy            = {  type = 9 id = 30009  } 
   chiefofair             = {  type = 9 id = 30010  } 
#1936



# Moscow okrug - Belov I.P.
# Leningrad okrug - Shaposhnikov B.
# Kiev okrug - Yakir
# Kharkov okrug - Dubovoi I.N.
# Belorusskij okrug - Uborevich
# Severokavkazskij - Kashirin N.D.
# Privolzhskij - Dybenko P.E.
# Uralskij - Garkavyj I.I.
# Sredneaziatskij - Velikanov M.D.
# Sibirskij - Kujbyshev N.V.
# Zakavkazskij Voennyj Okrug - Levandovsky
# Zabajkalsky voennyj okrug - Gryaznov I.K.
# Osobaya Krasnoznamennaja Dalnevostochnaja Armiya - Blukher


   landunit = 
   {  id       = {  type = 10848 id =  1 } 
     name     = "Raboche-Krest'yanskaya Krasnaya Armyia" 
     location = 572 #Moscow 
     Division = 
     {  id       = {  type = 10848 id = 2  } 
       name     = "Generalnyi Shtab RKKA" 
       strength = 100
       type     = HQ
	   model    = 2
	   extra    = artillery
	   brigade_model    = 7	
	   } 
 } 
landunit = { 
	id = { type = 10848 id = 3 }
	name = "Vozdushno Desantnye Voiska" 
	location = 572 # Moscow 	

	division = { 
	id = { type = 10848 id = 4 } 
		name = "1-i Vozdushno-Desantnyi Korpus" 
		strength = 25 
		type = paratrooper
		model = 0
		} 
	}
landunit = { 
	id = { type = 10848 id = 5 }
	name = "Voiska NKVD" 
	location = 572 # Moscow 	

	division = { 
	id = { type = 10848 id = 6 } 
		name = "1-ya Konvoynaya Divizyia NKVD" 
		strength = 100 
		type = garrison 
		model = 4
		extra = engineer
		brigade_model = 1
			} 
	division = { 
	id = { type = 10848 id = 7 } 
		name = "Divizyia o. n. Dzerzhinskogo" 
		strength = 100 
		type = motorized 
		model = 0 
		extra = armored_car
		brigade_model = 3
		} 
	}

   landunit = 
   {  id       = {  type = 10848 id =  8 } 
     name     = "Leningradskyi Voennyi Okrug" 
     location = 553 #Leningrad 
     Division = 
     {  id       = {  type = 10848 id = 9  } 
       name     = "Leningradskyi Voennyi Okrug" 
       strength = 100 
       type     = HQ
	   model    = 2
	   extra    = anti_air
	   brigade_model = 0
	   } 
     Division = 
     {  id       = {  type = 10848 id =  10 } 
       name     = "25-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = heavy_armor
	brigade_model = 1
      } 
      Division = 
     {  id       = {  type = 10848 id = 11  } 
       name     = "7-i Mekhanizirovannyi Korpus" 
       strength = 100 
       type     = light_armor
	   model    = 0
	   extra    = heavy_armor
	   brigade_model    = 1	   
      } 	  
 } 
   landunit = 
   {  id       = {  type = 10848 id =  12 } 
     name     = "1-i Strelkovyi Korpus" 
     location = 553 #Leningrad 
     Division = 
     {  id       = {  type = 10848 id = 13  } 
       name     = "16-ya Ulianovskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      }
     Division = 
     {  id       = {  type = 10848 id = 14  } 
       name     = "18-ya Yaroslavskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	   extra    = artillery
	   brigade_model = 7
      }
     Division = 
     {  id       = {  type = 10848 id = 15  } 
       name     = "20-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
	   extra    = heavy_armor
	   brigade_model = 1
      }
 } 
   landunit = 
   {  id       = {  type = 10848 id =  16 } 
     name     = "19-i Strelkovyi Korpus" 
     location = 550 #Kingisepp 
     Division = 
     {  id       = {  type = 10848 id = 17  } 
       name     = "4-ya Turkestanskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
	   extra    = artillery
	   brigade_model = 6
      }
     Division = 
     {  id       = {  type = 10848 id = 18  } 
       name     = "56-ya Moskovskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      }
 } 
	landunit = 
   {  id       = {  type = 10848 id = 19  } 
     name     = "5-i Kavaleriiski Korpus" 
     location = 566 # Pskov
      Division = 
     {  id       = {  type = 10848 id = 20  } 
       name     = "3-ya Besarabskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
      Division = 
     {  id       = {  type = 10848 id = 21  } 
       name     = "14-ya Maykopskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
      Division = 
     {  id       = {  type = 10848 id = 22  } 
       name     = "16-ya Sibirskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
 }
   landunit = 
   {  id       = {  type = 10848 id =  23 } 
     name     = "33-i Strelkovyi Korpus" 
     location = 550 # Kingisepp
     Division = 
     {  id       = {  type = 10848 id = 24  } 
       name     = "11-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      }
     Division = 
     {  id       = {  type = 10848 id = 25  } 
       name     = "158-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      }
 } 
   landunit = 
   {  id       = {  type = 10848 id =  26 } 
     name     = "29-i Strelkovyi Korpus" 
     location = 553 #Leningrad 
     Division = 
     {  id       = {  type = 10848 id = 27  } 
       name     = "54-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      }
     Division = 
     {  id       = {  type = 10848 id = 28  } 
       name     = "153-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      }
 } 

   landunit = 
   {  id       = {  type = 10848 id = 29  } 
     name     = "Severnyi Voennyi Kommissariat" 
     location = 542 # Arkhangelsk
     Division = 
     {  id       = {  type = 10848 id =  30 } 
       name     = "10-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
      Division = 
     {  id       = {  type = 10848 id =  31 } 
       name     = "88-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 

   landunit = 
   {  id       = {  type = 10848 id = 32  } 
     name     = "Uralskyi Voennyi Okrug" 
     location = 1151 # Sverdlovsk
     Division = 
     {  id       = {  type = 10848 id =  34 } 
       name     = "65-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	extra = engineer
	brigade_model = 2
      } 
      Division = 
     {  id       = {  type = 10848 id =  35 } 
       name     = "82-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		extra = anti_air
		brigade_model = 0   
      } 
     Division = 
     {  id       = {  type = 10848 id = 36  } 
       name     = "85-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
      Division = 
     {  id       = {  type = 10848 id = 37  } 
       name     = "29-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
	extra = light_armor_brigade
	brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 10848 id = 38  } 
       name     = "110-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      }
     Division = 
     {  id       = {  type = 10848 id = 39  } 
       name     = "112-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      }
     Division = 
     {  id       = {  type = 10848 id = 40  } 
       name     = "86-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      }
     Division = 
     {  id       = {  type = 10848 id = 41  } 
       name     = "87-ya Strelkovaya Divizyia" 
       strength = 5 
       type     = infantry 
	   model    = 4
      }
	} 

   landunit = 
   {  id       = {  type = 10848 id = 42  } 
     name     = "Belorusskyi Voennyi Okrug" 
     location = 599 # Minsk
     Division = 
     {  id       = {  type = 10848 id = 43  } 
       name     = "Belorusskyi Voennyi Okrug" 
       strength = 100 
       type     = HQ
	   model    = 2
	extra = anti_air
	brigade_model = 0
	   } 
      Division = 
     {  id       = {  type = 10848 id = 44  } 
       name     = "24-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = armored_car
	brigade_model = 3
      } 
      Division = 
     {  id       = {  type = 10848 id = 45  } 
       name     = "27-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 46  } 
     name     = "4-i Strelkovyi Korpus" 
     location = 599 # Minsk
     Division = 
     {  id       = {  type = 10848 id = 47  } 
       name     = "27-ya Omskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      } 
      Division = 
     {  id       = {  type = 10848 id = 48  } 
       name     = "2-ya Belorusskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	extra = artillery
	brigade_model = 7
      } 
      Division = 
     {  id       = {  type = 10848 id = 49  } 
       name     = "8-ya Minskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      } 
	} 	
    landunit = 
   {  id       = {  type = 10848 id = 50  } 
     name     = "5-i Strelkovyi Korpus" 
     location = 598 # Rechytsa
      Division = 
     {  id       = {  type = 10848 id = 51  } 
       name     = "4-ya Smolenskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	extra = artillery
	brigade_model = 7
      } 
     Division = 
     {  id       = {  type = 10848 id = 52  } 
       name     = "37-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      } 
     Division = 
     {  id       = {  type = 10848 id = 53  } 
       name     = "43-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
	extra = engineer
	brigade_model = 2
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 54  } 
     name     = "11-i Strelkovyi Korpus" 
     location = 590 # Vitebsk
      Division = 
     {  id       = {  type = 10848 id = 55  } 
       name     = "5-ya Vitebskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	extra = artillery
	brigade_model = 7
      } 
     Division = 
     {  id       = {  type = 10848 id = 56  } 
       name     = "29-ya Finskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
     Division = 
     {  id       = {  type = 10848 id = 57  } 
       name     = "64-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
	} 	
    landunit = 
   {  id       = {  type = 10848 id = 58  } 
     name     = "16-i Strelkovyi Korpus" 
     location = 600 # Mogilev
     Division = 
     {  id       = {  type = 10848 id = 59  } 
       name     = "33-ya Belorusskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	extra = artillery
	brigade_model = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 60  } 
       name     = "48-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
     Division = 
     {  id       = {  type = 10848 id = 61  } 
       name     = "81-ya Kaluzhskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
	} 
		landunit = 
   {  id       = {  type = 10848 id = 62  } 
     name     = "3-i Kavaleriiski Korpus" 
     location = 599 # Minsk
      Division = 
     {  id       = {  type = 10848 id = 63  } 
       name     = "7-ya Samarskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
      Division = 
     {  id       = {  type = 10848 id = 64  } 
       name     = "11-ya Orenburgskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
 }		
landunit = 
   {  id       = {  type = 10848 id = 65  } 
     name     = "6-i Kavaleriiski Korpus" 
     location = 609 # Korosten
      Division = 
     {  id       = {  type = 10848 id = 66  } 
       name     = "6-ya Changarskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
 }		
landunit = 
   {  id       = {  type = 10848 id = 67  } 
     name     = "7-i Kavaleriiski Korpus" 
     location = 596 # Slutsk
      Division = 
     {  id       = {  type = 10848 id = 68  } 
       name     = "4-ya Leningradskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
 }
    landunit = 
   {  id       = {  type = 10848 id =  69 } 
     name     = "22-i Strelkovyi Korpus" 
     location = 599 # Minsk
     Division = 
     {  id       = {  type = 10848 id = 70  } 
       name     = "63-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 71  } 
       name     = "67-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 	
    landunit = 
   {  id       = {  type = 10848 id =  72 } 
     name     = "23-i Strelkovyi Korpus" 
     location = 598 # Rechytsa
     Division = 
     {  id       = {  type = 10848 id = 73  } 
       name     = "76-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 74  } 
       name     = "155-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 	
    landunit = 
   {  id       = {  type = 10848 id =  75 } 
     name     = "24-i Strelkovyi Korpus" 
     location = 590 # Vitebsk
     Division = 
     {  id       = {  type = 10848 id = 76  } 
       name     = "150-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 77  } 
       name     = "145-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 	
    landunit = 
   {  id       = {  type = 10848 id =  78 } 
     name     = "28-i Strelkovyi Korpus" 
     location = 600 # Mogilev
     Division = 
     {  id       = {  type = 10848 id = 79  } 
       name     = "62-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 80  } 
       name     = "66-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 81  } 
       name     = "120-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 		
	
   landunit = 
   {  id       = {  type = 10848 id = 82 } 
     name     = "Moskovskyi Voennyi Okrug" 
     location = 572 #Moscow 
     Division = 
     {  id       = {  type = 10848 id =  83 } 
       name     = "Moskovskyi Voennyi Okrug" 
       strength = 100 
       type     = HQ
	   model    = 2
		extra = anti_air
		brigade_model = 0   
	 } 
      Division = 
     {  id       = {  type = 10848 id = 84  } 
       name     = "Osobaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
      Division = 
     {  id       = {  type = 10848 id = 85  } 
       name     = "30-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = engineer
	brigade_model = 2
      } 
      Division = 
     {  id       = {  type = 10848 id = 86  } 
       name     = "5-i Mekhanizirovannyi Korpus" 
       strength = 100 
       type     = light_armor
	   model    = 0
	   extra    = heavy_armor
	   brigade_model    = 1	   
      } 
     Division = 
     {  id       = {  type = 10848 id = 87  } 
       name     = "Moskovskaya Proletarskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
      } 
     Division = 
     {  id       = {  type = 10848 id = 88  } 
       name     = "126-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
  } 
    landunit = 
   {  id       = {  type = 10848 id =  89 } 
     name     = "2-i Territorialnyi Korpus" 
     location = 678 # Vladimir
      Division = 
     {  id       = {  type = 10848 id =  90 } 
       name     = "14-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		} 
      Division = 
     {  id       = {  type = 10848 id =  91 } 
       name     = "49-ya Krasnozamennaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		} 
     Division = 
     {  id       = {  type = 10848 id = 92  } 
       name     = "55-ya Kurskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	   extra    = artillery
	   brigade_model    = 5		   
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id =  93 } 
     name     = "3-i Territorialnyi Korpus" 
     location = 584 # Tula
      Division = 
     {  id       = {  type = 10848 id =  94 } 
       name     = "6-ya Orlovskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		} 
     Division = 
     {  id       = {  type = 10848 id =  95 } 
       name     = "52-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
     Division = 
     {  id       = {  type = 10848 id =  96 } 
       name     = "84-ya Tulskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	   extra    = artillery
	   brigade_model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id =  97 } 
     name     = "10-i Territorialnyi Korpus" 
     location = 571 # Orekhovo
     Division = 
     {  id       = {  type = 10848 id =  98 } 
       name     = "17-ya Gorkovskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
     Division = 
     {  id       = {  type = 10848 id = 99  } 
       name     = "19-ya Voronezhskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	   extra    = artillery
	   brigade_model    = 5		   
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 100  } 
     name     = "20-i Strelkovyi Korpus" 
     location = 678 # Vladimir
      Division = 
     {  id       = {  type = 10848 id = 101  } 
       name     = "68-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 102  } 
       name     = "113-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 103  } 
       name     = "142-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 104  } 
     name     = "21-i Strelkovyi Korpus" 
     location = 584 # Tula
      Division = 
     {  id       = {  type = 10848 id = 105  } 
       name     = "77-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 106  } 
       name     = "38-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 107  } 
     name     = "30-i Strelkovyi Korpus" 
     location = 571 # Orekhovo
      Division = 
     {  id       = {  type = 10848 id = 108  } 
       name     = "59-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 109  } 
       name     = "39-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 110  } 
     name     = "40-i Strelkovyi Korpus" 
     location = 571 # Orekhovo
     Division = 
     {  id       = {  type = 10848 id = 111  } 
       name     = "60-ya Strelkovaya Divizyia" 
       strength = 5
       type     = infantry 
	   model    = 4
      } 
      Division = 
     {  id       = {  type = 10848 id = 112  } 
       name     = "42-ya Strelkovaya Divizyia" 
       strength = 5
       type     = infantry 
	   model    = 4
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 113  } 
     name     = "41-i Strelkovyi Korpus" 
     location = 678 # Vladimir
     Division = 
     {  id       = {  type = 10848 id = 114  } 
       name     = "127-ya Strelkovaya Divizyia" 
       strength = 5
       type     = infantry 
	   model    = 4
      } 
	} 

   landunit = 
   {  id       = {  type = 10848 id = 115 } 
     name     = "Privoljsyi Voennyi Okrug" 
     location = 672 # Kazan
      Division = 
     {  id       = {  type = 10848 id = 117  } 
       name     = "125-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 118  } 
       name     = "128-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 119  } 
       name     = "159-ya Strelkovaya Divizyia" 
       strength = 5
       type     = infantry 
	   model    = 4
      } 
      Division = 
     {  id       = {  type = 10848 id = 120  } 
       name     = "79-ya Strelkovaya Divizyia" 
       strength = 5
       type     = infantry 
	   model    = 4
      } 
  }
    landunit = 
   {  id       = {  type = 10848 id = 121  } 
     name     = "12-i Territorialnyi Korpus" 
     location = 672 # Kazan
     Division = 
     {  id       = {  type = 10848 id = 122  } 
       name     = "1-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	   extra    = artillery
	   brigade_model    = 5		   
      } 
      Division = 
     {  id       = {  type = 10848 id = 123  } 
       name     = "31-ya Stalingradskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		extra = anti_air
		brigade_model = 0   
      } 
     Division = 
     {  id       = {  type = 10848 id = 124  } 
       name     = "53-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		}
     Division = 
     {  id       = {  type = 10848 id = 125  } 
       name     = "61-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		}
     Division = 
     {  id       = {  type = 10848 id = 126  } 
       name     = "70-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		}
	} 
    landunit = 
   {  id       = {  type = 10848 id = 127  } 
     name     = "34-i Strelkovyi Korpus" 
     location = 672 # Kazan
     Division = 
     {  id       = {  type = 10848 id = 128  } 
       name     = "111-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 129  } 
       name     = "97-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 130  } 
     name     = "26-i Strelkovyi Korpus" 
     location = 672 # Kazan
     Division = 
     {  id       = {  type = 10848 id = 131  } 
       name     = "129-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 132  } 
       name     = "102-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 133  } 
     name     = "42-i Strelkovyi Korpus" 
     location = 672 # Kazan
     Division = 
     {  id       = {  type = 10848 id = 134  } 
       name     = "108-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 4
      } 
	} 

   landunit = 
   {  id       = {  type = 10848 id = 135 } 
     name     = "Kievskyi Voennyi Okrug" 
     location = 617 # Kiev 
     Division = 
     {  id       = {  type = 10848 id =  136 } 
       name     = "Kievskyi Voennyi Okrug" 
       strength = 100 
       type     = HQ
	   model    = 2
	extra = anti_air
	brigade_model = 0
	 } 
      Division = 
     {  id       = {  type = 10848 id = 137  } 
       name     = "23-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = armored_car
	brigade_model = 3
      } 
      Division = 
     {  id       = {  type = 10848 id = 138  } 
       name     = "26-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
      Division = 
     {  id       = {  type = 10848 id = 139  } 
       name     = "28-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = engineer
	brigade_model = 2
      } 
      Division = 
     {  id       = {  type = 10848 id = 140  } 
       name     = "45-i Mekhanizirovannyi Korpus" 
       strength = 100 
       type     = light_armor
	   model    = 0
	   extra    = heavy_armor
	   brigade_model    = 1	   
      } 
  } 
    landunit = 
   {  id       = {  type = 10848 id = 141  } 
     name     = "6-i Strelkovyi Korpus" 
     location = 617 # Kiev
     Division = 
     {  id       = {  type = 10848 id = 142  } 
       name     = "2-ya Kavkazskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      } 
     Division = 
     {  id       = {  type = 10848 id = 143  } 
       name     = "24-ya Zheleznaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	   extra    = artillery
	   brigade_model    = 7		   
      } 
      Division = 
     {  id       = {  type = 10848 id = 144  } 
       name     = "46-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 145  } 
     name     = "8-i Strelkovyi Korpus" 
     location = 611 # Vinnitsa
     Division = 
     {  id       = {  type = 10848 id = 146  } 
       name     = "44-ya Kievskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	   extra    = artillery
	   brigade_model    = 7		   
      } 
      Division = 
     {  id       = {  type = 10848 id = 147  } 
       name     = "51-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      } 
      Division = 
     {  id       = {  type = 10848 id = 148  } 
       name     = "95-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 149  } 
     name     = "15-i Strelkovyi Korpus" 
     location = 614 # Proskurov
     Division = 
     {  id       = {  type = 10848 id = 150  } 
       name     = "2-ya Turkestanskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		}
      Division = 
     {  id       = {  type = 10848 id = 151  } 
       name     = "99-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
	   extra    = heavy_armor
	   brigade_model    = 1
      } 
     Division = 
     {  id       = {  type = 10848 id = 152  } 
       name     = "100-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
	   extra    = artillery
	   brigade_model    = 6		   
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 153  } 
     name     = "17-i Strelkovyi Korpus" 
     location = 621 # Tiraspol
     Division = 
     {  id       = {  type = 10848 id = 154  } 
       name     = "7-ya Chernigovskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		}
     Division = 
     {  id       = {  type = 10848 id = 155  } 
       name     = "15-ya Sivashskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		}
      Division = 
     {  id       = {  type = 10848 id = 156  } 
       name     = "96-ya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
	   extra    = artillery
	   brigade_model    = 6		
      } 
     Division = 
     {  id       = {  type = 10848 id = 157  } 
       name     = "58-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
		}
    } 
   landunit = 
   {  id       = {  type = 10848 id = 158  } 
     name     = "1-i Kavaleriiski Korpus" 
     location = 611 # Vinnitsa
     Division = 
     {  id       = {  type = 10848 id = 159  } 
       name     = "1-ya Lenina Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
     Division = 
     {  id       = {  type = 10848 id = 160  } 
       name     = "2-ya Krasnogo Znameni Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
  }
   landunit = 
   {  id       = {  type = 10848 id = 161  } 
     name     = "2-i Kavaleriiski Korpus" 
     location = 612 # Zhitomir
     Division = 
     {  id       = {  type = 10848 id = 162  } 
       name     = "5-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
     Division = 
     {  id       = {  type = 10848 id = 163  } 
       name     = "9-ya Krimskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = light_armor_brigade
	brigade_model = 3
      } 
  }
    landunit = 
   {  id       = {  type = 10848 id = 164  } 
     name     = "35-i Strelkovyi Korpus" 
     location = 617 # Kiev
     Division = 
     {  id       = {  type = 10848 id = 165  } 
       name     = "159-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 166  } 
     name     = "36-i Strelkovyi Korpus" 
     location = 611 # Vinnitsa
      Division = 
     {  id       = {  type = 10848 id = 167  } 
       name     = "160-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 168  } 
       name     = "161-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 169  } 
     name     = "27-i Strelkovyi Korpus" 
     location = 614 # Proskurov
      Division = 
     {  id       = {  type = 10848 id = 170  } 
       name     = "89-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 171  } 
       name     = "101-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 172  } 
       name     = "130-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 173  } 
     name     = "37-i Strelkovyi Korpus" 
     location = 621 # Tiraspol
     Division = 
     {  id       = {  type = 10848 id = 174  } 
       name     = "131-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 175  } 
       name     = "140-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 176  } 
       name     = "152-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 177  } 
       name     = "47-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 

   landunit = 
   {  id       = {  type = 10848 id = 178 } 
     name     = "Kharkovskyi Voennyi Okrug" 
     location = 636 #Kharkov 
      Division = 
     {  id       = {  type = 10848 id = 180  } 
       name     = "75-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	   extra    = engineer
	   brigade_model    = 2	
      } 
      Division = 
     {  id       = {  type = 10848 id = 181  } 
       name     = "151-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
  }
    landunit = 
   {  id       = {  type = 10848 id = 182  } 
     name     = "7-i Territorialnyi Korpus" 
     location = 630 # Zaporozhie
     Division = 
     {  id       = {  type = 10848 id = 183  } 
       name     = "3-ya Krimskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = infantry 
	   model    = 7
	extra = anti_air
	brigade_model = 0
      } 
      Division = 
     {  id       = {  type = 10848 id = 184  } 
       name     = "25-ya Chapaeva Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	extra = artillery
	brigade_model = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 185  } 
       name     = "41-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 186  } 
     name     = "14-i Territorialnyi Korpus" 
     location = 636 # Kharkov
      Division = 
     {  id       = {  type = 10848 id = 187  } 
       name     = "30-ya Irkutskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
      Division = 
     {  id       = {  type = 10848 id = 188  } 
       name     = "80-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
      Division = 
     {  id       = {  type = 10848 id = 189  } 
       name     = "23-ya Kharkovskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	extra = artillery
	brigade_model = 5
      } 
	} 
    landunit = 
   {  id       = {  type = 10848 id = 190  } 
     name     = "25-i Strelkovyi Korpus" 
     location = 636 # Kharkov
     Division = 
     {  id       = {  type = 10848 id = 191  } 
       name     = "72-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 192  } 
       name     = "132-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 193  } 
       name     = "83-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 194  } 
       name     = "141-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 195  } 
       name     = "69-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 196  } 
       name     = "156-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 197  } 
       name     = "134-ya Strelkovaya Divizyia" 
       strength = 5
       type     = infantry 
	   model    = 4
      } 
      Division = 
     {  id       = {  type = 10848 id = 198  } 
       name     = "139-ya Strelkovaya Divizyia" 
       strength = 5
       type     = infantry 
	   model    = 4
      } 
	} 

   landunit = 
   {  id       = {  type = 10848 id = 199 } 
     name     = "Severokavkazskyi Voennyi Okrug" 
     location =  644 # Rostov
      Division = 
     {  id       = {  type = 10848 id =  201 } 
       name     = "10-ya Severokavkazskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 9
	extra = engineer
	brigade_model = 2
      } 
        Division = 
     {  id       = {  type = 10848 id = 202  } 
       name     = "28-ya Gorskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger
	   model    = 8
	extra = anti_air
	brigade_model = 0
      } 
	  Division = 
     {  id       = {  type = 10848 id = 203  } 
       name     = "12-ya Kubanskaya Kavaleriiskaya Diviziya" 
       strength = 100 
       type     = cavalry
	   model    = 9
      } 	 
    }
 landunit = 
   {  id       = {  type = 10848 id = 204  } 
     name     = "9-i Territorialnyi Korpus" 
     location =  691 # Krasnodar
     Division = 
     {  id       = {  type = 10848 id = 205  } 
       name     = "9-ya Krasnodarskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	extra = artillery
	brigade_model = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 206  } 
       name     = "13-ya Dagestanskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	extra = rocket_artillery
	brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 10848 id = 207  } 
       name     = "22-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
     Division = 
     {  id       = {  type = 10848 id = 208  } 
       name     = "74-ya Tamanskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
      } 
	}
    landunit = 
   {  id       = {  type = 10848 id = 209  } 
     name     = "38-i Strelkovyi Korpus" 
     location = 691
     Division = 
     {  id       = {  type = 10848 id = 210  } 
       name     = "103-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
      Division = 
     {  id       = {  type = 10848 id = 211  } 
       name     = "118-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 212  } 
       name     = "119-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
     Division = 
     {  id       = {  type = 10848 id = 213  } 
       name     = "157-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
      } 
	} 

   landunit = 
   {  id       = {  type = 10848 id = 214 } 
     name     = "Zakavkazskyi Voennyi Okrug" 
     location =  709 # Tbilisi
        Division = 
     {  id       = {  type = 10848 id = 217  } 
       name     = "1-ya Gorskaya Kavkazskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger
	   model    = 8
	extra = engineer
	brigade_model = 2
      } 
        Division = 
     {  id       = {  type = 10848 id = 218  } 
       name     = "3-ya Gorskaya Kavkazskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger
	   model    = 8
	extra = anti_air
	brigade_model = 0
      } 
        Division = 
     {  id       = {  type = 10848 id = 219  } 
       name     = "1-ya Gorskaya Gruzinskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = bergsjaeger
	   model    = 7
      } 
        Division = 
     {  id       = {  type = 10848 id = 220  } 
       name     = "Gorskaya Azerbaidzhanskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = bergsjaeger
	   model    = 7
      } 
        Division = 
     {  id       = {  type = 10848 id = 221  } 
       name     = "Gorskaya Armianskaya Strelkovaya Divizyia" 
       strength = 40 
       type     = bergsjaeger
	   model    = 7
      } 
        Division = 
     {  id       = {  type = 10848 id = 222  } 
       name     = "2-ya Gruzinskaya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry
	   model    = 6
      }  
    }

   landunit = 
   {  id       = {  type = 10848 id = 223 } 
     name     = "Sredneaziatskyi Voennyi Okrug" 
     location =  1103#
     Division = 
     {  id       = {  type = 10848 id = 225  } 
       name     = "1-ya Gorskaya Turkestanskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger
	   model    = 8
	extra = engineer
	brigade_model = 2
      }	 
     Division = 
     {  id       = {  type = 10848 id = 226  } 
       name     = "3-ya Gorskaya Turkestanskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = bergsjaeger
	   model    = 8
      }	 
  Division = #SAVO
     {  id       = {  type = 10848 id = 227  } 
       name     = "18-ya Turkmenskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
     } 
  Division = #SAVO
     {  id       = {  type = 10848 id = 228  } 
       name     = "19-ya Turkmenskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
     } 
  Division = #SAVO
     {  id       = {  type = 10848 id = 229  } 
       name     = "21-ya Turkmenskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
     } 
  Division = #SAVO
     {  id       = {  type = 10848 id = 230  } 
       name     = "20-ya Tadzhikskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
     } 
 }

 landunit = 
   {  id       = {  type = 10848 id = 231  } 
     name     = "Sibirskyi Voennyi Okrug" 
     location =  1142 #  Novosibirsk
     Division = 
     {  id       = {  type = 10848 id = 233  } 
       name     = "71-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
	   extra    = engineer 
	   brigade_model    = 2
     } 
     Division = 
     {  id       = {  type = 10848 id = 234  } 
       name     = "73-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
     } 
     Division = 
     {  id       = {  type = 10848 id = 235  } 
       name     = "78-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
     } 
     Division = 
     {  id       = {  type = 10848 id = 236  } 
       name     = "94-ya Strelkovaya Divizyia" 
       strength = 30 
       type     = infantry 
	   model    = 6
     } 
     Division = 
     {  id       = {  type = 10848 id = 237  } 
       name     = "133-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
     } 
     Division = 
     {  id       = {  type = 10848 id = 238  } 
       name     = "109-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
     } 
     Division = 
     {  id       = {  type = 10848 id = 239  } 
       name     = "107-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
     } 
     Division = 
     {  id       = {  type = 10848 id = 240  } 
       name     = "91-ya Strelkovaya Divizyia" 
       strength = 10 
       type     = infantry 
	   model    = 5
     } 
    }

 landunit = 
   {  id       = {  type = 10848 id = 241  } 
     name     = "Zabaikalskyi Voennyi Okrug" 
     location =  1169 #  Chita
     Division = 
     {  id       = {  type = 10848 id = 243 } 
       name     = "36-ya Strelkovaya Divizija" 
       strength = 80 
       type     = infantry 
	   model    = 8
	extra = rocket_artillery
	brigade_model = 6
     } 
     Division = 
     {  id       = {  type = 10848 id = 244 } 
       name     = "57-ya Strelkovaya Divizija" 
       strength = 80 
       type     = infantry 
	   model    = 8
	extra = anti_air
	brigade_model = 0
     } 
     Division = 
     {  id       = {  type = 10848 id = 245 } 
       name     = "93-ya Strelkovaya Divizija" 
       strength = 30 
       type     = infantry 
	   model    = 6
     } 
      Division = # ZabVO
     {  id       = {  type = 10848 id = 246  } 
       name     = "15-ya Kubanskaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
      } 
      Division = # ZabVO
     {  id       = {  type = 10848 id = 247  } 
       name     = "17-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
      } 
      Division = # ZabVO
     {  id       = {  type = 10848 id = 248  } 
       name     = "22-ya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
      } 
       Division = 
     {  id       = {  type = 10848 id =  249 } 
       name     = "11-i Mekhanizirovannyi Korpus" 
       strength = 100 
       type     = light_armor
	   model    = 0
	extra = engineer
	brigade_model = 2
      } 
    }


    landunit = 
   {  id       = {  type = 10848 id = 250 } 
     name     = "Osobaya Krasnozamennaya Dalnevostochnaya Armyia" 
     location =  1190 #Khabarovsk
     Division = 
     {  id       = {  type = 10848 id = 251  } 
       name     = "Dalnevostochnyi Voennyi Okrug" 
       strength = 100 
       type     = HQ
	   model    = 2
	   extra    = anti_air
	   brigade_model    = 0	
     } 
     Division = 
     {  id       = {  type = 10848 id = 252  } 
       name     = "12-ya 'SibRevKoma' Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
 	   extra    = artillery
	   brigade_model = 7
	  } 
     Division = 
     {  id       = {  type = 10848 id = 253  } 
       name     = "21-ya Permskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
 	   extra    = engineer
	   brigade_model = 2
	  } 
     Division = 
     {  id       = {  type = 10848 id = 254  } 
       name     = "34-ya Srednevolzhskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	  } 
     Division = 
     {  id       = {  type = 10848 id = 255  } 
       name     = "35-ya Sibirskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	  } 
     Division = 
     {  id       = {  type = 10848 id = 256  } 
       name     = "40-ya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	  } 
      Division = 
     {  id       = {  type = 10848 id = 257  } 
       name     = "8-ya Dalnevostochnaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
	extra = light_armor_brigade
	brigade_model = 3
      } 
 }
    landunit = 
	{  id       = {  type = 10848 id = 258  } 
     name     = "18-i Strelkovyi Korpus" 
     location = 1176 # Blagoveschensk
      Division = 
     {  id       = {  type = 10848 id = 259  } 
       name     = "1-ya Tikhookeanskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
 	   extra    = artillery
	   brigade_model = 7
	  } 
     Division = 
     {  id       = {  type = 10848 id = 260  } 
       name     = "26-ya Zlatoustovskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	  } 
     Division = 
     {  id       = {  type = 10848 id = 261  } 
       name     = "32-ya Saratovskaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	  } 
	} 	
    landunit = 
    {  id       = {  type = 10848 id = 262  } 
     name     = "Osobyi Kolkhoznyi Korpus" 
     location = 1191# Vladivostok
      Division = 
     {  id       = {  type = 10848 id = 263  } 
       name     = "1-ya Kolkhoznaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
 	   extra    = artillery
	   brigade_model = 7
	  } 
     Division = 
     {  id       = {  type = 10848 id = 264  } 
       name     = "2-ya Kolkhoznaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	  } 
     Division = 
     {  id       = {  type = 10848 id = 265  } 
       name     = "3-ya Kolkhoznaya Strelkovaya Divizyia" 
       strength = 80 
       type     = infantry 
	   model    = 8
	  } 
      Division = 
     {  id       = {  type = 10848 id = 266  } 
       name     = "Kolkhoznaya Kavaleriiskaya Divizyia" 
       strength = 100 
       type     = cavalry
	   model    = 8
      } 
	} 	


	
# Air OOB
#MVO
airunit = { 
	id = { type = 10848 id = 7000 } 
	name = "1 AviaKorpus" 
	location = 572 # Moscow 
	base = 572 # Moscow 

	division = { 
	id = { type = 10848 id = 7001 } 
		name = "403.IABR" 
		strength = 80 
		type = interceptor 
		model = 5 
			} 
	division = { 
	id = { type = 10848 id = 7002 } 
		name = "23.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
	}
airunit = { 
	id = { type = 10848 id = 7003 } 
	name = "11 TBABR MVO" 
	location = 654 # Voronezh 
	base = 654 # Voronezh 
 
	division = { 
	id = { type = 10848 id = 7004 } 
		name = "11.TBABR" 
		strength = 50 
		type = strategic_bomber 
		model = 2 
			}
	}

#LVO
airunit = { 
	id = { type = 10848 id = 7005 } 
	name = "4 AviaKorpus" 
	location = 553 # Leningrad 
	base = 553 # Leningrad 
	division = { 
	id = { type = 10848 id = 7006 } 
		name = "1.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
	division = { 
	id = { type = 10848 id = 7007 } 
		name = "2.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
	}
airunit = { 
	id = { type = 10848 id = 7008 } 
	name = "LVO" 
	location = 553 # Leningrad 
	base = 553 # Leningrad 

	division = { 
	id = { type = 10848 id = 7009 } 
		name = "53.LBABR" 
		strength = 70 
		type = multi_role 
		model = 3 
			} 
	division = { 
	id = { type = 10848 id = 7010 } 
		name = "100.LSHABR" 
		strength = 70 
		type = CAS 
		model = 0 
			}
	}	
airunit = { 
	id = { type = 10848 id = 7011 } 
	name = "3 ABRON LVO" 
	location = 553 # Leningrad 
	base = 553 # Leningrad 

	division = { 
	id = { type = 10848 id = 7012 } 
		name = "3.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 1 
			} 
	}	
airunit = { 
	id = { type = 10848 id = 7013 } 
	name = "200 IABR LVO" 
	location = 566 # Pskov 
	base = 566 # Pskov 

	division = { 
	id = { type = 10848 id = 7014 } 
		name = "3.IABR" 
		strength = 80 
		type = interceptor 
		model = 5 
			} 
	}
	
#BVO
airunit = { 
	id = { type = 10848 id = 7015 } 
	name = "6 AviaKorpus" 
	location = 588 # Bryansk 
	base = 588 # Bryansk 
	division = { 
	id = { type = 10848 id = 7016 } 
		name = "5.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
	division = { 
	id = { type = 10848 id = 7017 } 
		name = "9.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
	division = { 
	id = { type = 10848 id = 7018 } 
		name = "402.IABR" 
		strength = 80 
		type = interceptor 
		model = 5 
			} 
		}
airunit = { 
	id = { type = 10848 id = 7019 } 
	name = "40 LBABR BVO" 
	location = 590 #  Vitebsk
	base = 590 # Vitebsk	
	division = { 
	id = { type = 10848 id = 7020 } 
		name = "40.LBABR" 
		strength = 70 
		type = multi_role 
		model = 3  
			}
		}	
airunit = { 
	id = { type = 10848 id = 7021 } 
	name = "49 TBABR BVO" 
	location = 590 #  Vitebsk
	base = 590 # Vitebsk	
	division = { 
	id = { type = 10848 id = 7022 } 
		name = "49.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			extra = escort
			brigade_model = 0
			}
		}		
airunit = { 
	id = { type = 10848 id = 7023 } 
	name = "132 IABR BVO" 
	location = 600 # Mogilyev 
	base = 600 #  Mogilyev
	division = { 
	id = { type = 10848 id = 7024 } 
		name = "132. IABR" 
		strength = 80 
		type = interceptor 
		model = 5 
			} 
		}		
airunit = { 
	id = { type = 10848 id = 7025 } 
	name = "252 LSHABR BVO" 
	location = 600 # Mogilyev 
	base = 600 #  Mogilyev
	division = { 
	id = { type = 10848 id = 7026 } 
		name = "252.LSHABR" 
		strength = 70 
		type = CAS 
		model = 0 
			} 
		}		
airunit = { 
	id = { type = 10848 id = 7027 } 
	name = "116 TBABR BVO" 
	location = 589 # Smolensk 
	base = 589 # Smolensk	
	division = { 
	id = { type = 10848 id = 7028 } 
		name = "116.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			extra = escort
			brigade_model = 0
			}
		}		
airunit = { 
	id = { type = 10848 id = 7029 } 
	name = "47 ABRON BVO" 
	location = 589 # Smolensk 
	base = 589 # Smolensk	 
	division = { 
	id = { type = 10848 id = 7030 } 
		name = "47.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 1 
			}
		}
airunit = { 
	id = { type = 10848 id = 7031 } 
	name = "93 TBABR BVO" 
	location = 563 # Torzhok 
	base = 563 # Torzhok	
	division = { 
	id = { type = 10848 id = 7032 } 
		name = "93.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			extra = escort
			brigade_model = 0
			}
		}
#KVO
airunit = { 
	id = { type = 10848 id = 7033 } 
	name = "13 ABRON KVO" 
	location = 617 # Kiev
	base = 617 # Kiev
	division = { 
	id = { type = 10848 id = 7034 } 
		name = "13.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 0 
			}
		}
airunit = { 
	id = { type = 10848 id = 7035 } 
	name = "5 IABR KVO" 
	location = 617 # Kiev
	base = 617 # Kiev
	division = { 
	id = { type = 10848 id = 7036 } 
		name = "5.IABR" 
		strength = 80 
		type = interceptor 
		model = 5 
			} 
		}
airunit = { 
	id = { type = 10848 id = 7037 } 
	name = "404 IABR KVO" 
	location = 611 # Zhitomir
	base = 611 # Zhitomir
	division = { 
	id = { type = 10848 id = 7038 } 
		name = "404.IABR" 
		strength = 80 
		type = interceptor 
		model = 5 
			} 
		}
airunit = { 
	id = { type = 10848 id = 7039 } 
	name = "256 LSHABR KVO" 
	location = 617 # Kiev
	base = 617 # Kiev 
	division = { 
	id = { type = 10848 id = 7040 } 
		name = "256.LSHABR" 
		strength = 70 
		type = CAS 
		model = 0 
			} 
		}	
airunit = { 
	id = { type = 10848 id = 7041 } 
	name = "10 AviaKorpus" 
	location = 628 #  Kirovograd
	base = 628 # Kirovograd	
	division = { 
	id = { type = 10848 id = 7042 } 
		name = "15.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
		}
airunit = { 
	id = { type = 10848 id = 7043 } 
	name = "18 TBABR KVO" 
	location = 654 # Zaporozhye 
	base = 654 # Zaporozhye 
 
	division = { 
	id = { type = 10848 id = 7044 } 
		name = "18.TBABR" 
		strength = 50 
		type = strategic_bomber 
		model = 2 
			}
		}

#KhVO
airunit = { 
	id = { type = 10848 id = 7045 } 
	name = "43 TBABR KhVO" 
	location = 636 # Kharkov 
	base = 636 # Kharkov	
	division = { 
	id = { type = 10848 id = 7046 } 
		name = "43.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			extra = escort
			brigade_model = 0
			}
		}
airunit = { 
	id = { type = 10848 id = 7047 } 
	name = "16 TBABR KhVO" 
	location = 636 # Kharkov 
	base = 636 # Kharkov	
	division = { 
	id = { type = 10848 id = 7048 } 
		name = "16.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
		}

#ZabVO
airunit = { 
	id = { type = 10848 id = 7049 } 
	name = "5 AviaKorpus" 
	location = 1169 #  Chita
	base = 1169 # Chita	
	division = { 
	id = { type = 10848 id = 7050 } 
		name = "29.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
	division = { 
	id = { type = 10848 id = 7051 } 
		name = "32.LSHABR" 
		strength = 70 
		type = CAS 
		model = 0 
			} 
		}

#DVO
airunit = { 
	id = { type = 10848 id = 7052 } 
	name = "26 TBABR DVO" 
	location = 1190 #  Khabarovsk
	base = 1190 # Khabarovsk	
	division = { 
	id = { type = 10848 id = 7053 } 
		name = "26.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
		}
airunit = { 
	id = { type = 10848 id = 7054 } 
	name = "50 LSHABR DVO" 
	location = 1190 #  Khabarovsk
	base = 1190 # Khabarovsk
	division = { 
	id = { type = 10848 id = 7055 } 
		name = "50.LSHABR" 
		strength = 70 
		type = CAS 
		model = 0 
			} 
	}

#SibVO
airunit = { 
	id = { type = 10848 id = 7056 } 
	name = "134 LSHABR  SibVO" 
	location = 1143 #  Biysk
	base = 1143 # Biysk
	division = { 
	id = { type = 10848 id = 7057 } 
		name = "134.LSHABR" 
		strength = 70 
		type = CAS 
		model = 0 
			} 
	}

#SKVO
airunit = { 
	id = { type = 10848 id = 7058 } 
	name = "21 TBABR SKVO" 
	location = 644 # Rostov-na-Donu
	base = 644 # Rostov-na-Donu	
	division = { 
	id = { type = 10848 id = 7059 } 
		name = "21.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 3 
			}
		}
airunit = { 
	id = { type = 10848 id = 7080 } 
	name = "55 LBABR SKVO" 
	location = 644 # Rostov-na-Donu
	base = 644 # Rostov-na-Donu	
	division = { 
	id = { type = 10848 id = 7081 } 
		name = "55.LBABR" 
		strength = 70 
		type = multi_role 
		model = 3  
			}
		}

#TOF
airunit = { 
	id = { type = 10848 id = 7082 } 
	name = "20 TBABR TOF" 
	location = 1190 #  Khabarovsk
	base = 1190 # Khabarovsk
	division = { 
	id = { type = 10848 id = 7083 } 
		name = "20.TBABR" 
		strength = 80 
		type = naval_bomber 
		model = 1 
			}
		}

#CHF
airunit = { 
	id = { type = 10848 id = 7084 } 
	name = "106 TBABR CHF" 
	location = 641 #  Sevastopol
	base = 641 # Sevastopol
	division = { 
	id = { type = 10848 id = 7085 } 
		name = "106.TBABR" 
		strength = 80 
		type = naval_bomber 
		model = 1 
			}
		}
	
	
# Naval OOB
	navalunit = { # Galler L.M.
		id = { type = 10848 id = 5100 } 
		name = "Krasnoznamenny Baltijsky Flot" 
		location = 553 
		base = 553 
		division = { 
			id = { type = 10848 id = 5101 } 
			name = "Marat" 
			type = battleship 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 5102 } 
			name = "Oktyabrskaya Revolutsiya" 
			type = battleship 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 5103 } 
			name = "1 Brigada Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5104 } 
			name = "2 Brigada Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		}  	
	navalunit = { 
		id = { type = 10848 id = 5150 } 
		name = "1ya Brigada PL KBF" 
		location = 641 
		base = 641 
		division = { 
			id = { type = 10848 id = 5151 } 
			name = "1. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5152 } 
			name = "2. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5153 } 
			name = "3. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5154 } 
			name = "4. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		}
	navalunit = { 
		id = { type = 10848 id = 5160 } 
		name = "2ya Brigada PL KBF" 
		location = 641 
		base = 641 
		division = { 
			id = { type = 10848 id = 5161 } 
			name = "6. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5162 } 
			name = "7. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5163 } 
			name = "8. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		}		
	navalunit = { 
		id = { type = 10848 id = 5170 } 
		name = "Uchebnaya Brigada PL KBF" 
		location = 641 
		base = 641 
		division = { 
			id = { type = 10848 id = 5171 } 
			name = "9. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5172 } 
			name = "13. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5173 } 
			name = "14. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		}	
		
	navalunit = { # Kozhanov I.K.
		id = { type = 10848 id = 5200 } 
		name = "Chernomorskiy Flot" 
		location = 641 
		base = 641 
		division = { 
			id = { type = 10848 id = 5201 } 
			name = "Parizhskaya Kommuna" 
			type = battleship 
			model = 2
			} 
		division = { 
			id = { type = 10848 id = 5202 } 
			name = "Krasni Kavkaz" 
			type = heavy_cruiser 
			model = 2 
			extra1 = naval_torpedoes_l
			brigade_model1 = 3
			} 
		division = { 
			id = { type = 10848 id = 5203 } 
			name = "Profintern" 
			type = light_cruiser 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5204 } 
			name = "Komintern" 
			type = light_cruiser 
			model = 0 
			} 
		division = { 
			id = { type = 10848 id = 5205 } 
			name = "Chervonaya Ukraina" 
			type = light_cruiser 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5206 } 
			name = "1. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5207 } 
			name = "2. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		} 
       
	navalunit = { 
		id = { type = 10848 id = 5300 } 
		name = "1ya Brigada PL CHF" 
		location = 641 
		base = 641 
		division = { 
			id = { type = 10848 id = 5301 } 
			name = "5. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5302 } 
			name = "10. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5303 } 
			name = "11. Divizion Podlodok" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 10848 id = 5304 } 
			name = "12. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		} 
	navalunit = { 
		id = { type = 10848 id = 5350 } 
		name = "2ya Brigada PL CHF" 
		location = 641 
		base = 641 
		division = { 
			id = { type = 10848 id = 5351 } 
			name = "15. Divizion Podlodok" 
			type = submarine 
			model = 1 
			} 
		division = { 
			id = { type = 10848 id = 5352 } 
			name = "16. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5353 } 
			name = "17. Divizion Podlodok" 
			type = submarine 
			model = 4 
			} 
		} 

	navalunit = { # Dushenov K.I.
		id = { type = 10848 id = 5400 } 
		name = "Severnaya Voennaya Flotiliya" 
		location = 535 
		base = 535 
		division = { 
			id = { type = 10848 id = 5401 } 
			name = "3. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5402 } 
			name = "18. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		} 	

	navalunit = { # Viktorov M.V.
		id = { type = 10848 id = 5500 } 
		name = "Tikhookeanskiy Flot" 
		location = 1191 
		base = 1191 
		division = { 
			id = { type = 10848 id = 5501 } 
			name = "4. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		} 
	navalunit = { 
		id = { type = 10848 id = 5550 } 
		name = "1ya Brigada PL TOF" 
		location = 1191 
		base = 1191 
		division = { 
			id = { type = 10848 id = 5551 } 
			name = "19. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5552 } 
			name = "20. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5553 } 
			name = "21. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		} 	
	
	# Starting Build Queue
	division_development = {
		name  = "8. Flotiliya Esmintsev" 
		type  = destroyer 
		model = 4 
		cost  = 0.1 
		id    = {  type = 10848 id = 8500  } 
		date  = {  year = 1936 month = april day = 1  } 
	} 
	division_development = {
		name  = "29. Flotiliya Podlodok" 
		type  = submarine 
		model = 4 
		cost  = 0.1 
		id    = {  type = 10848 id = 8501  } 
		date  = {  year = 1936 month = february day = 1  } 
	} 
	division_development = {
		name  = "30. Flotiliya Podlodok" 
		type  = submarine 
		model = 4 
		cost  = 0.1 
		id    = {  type = 10848 id = 8502  } 
		date  = {  year = 1936 month = march day = 1  } 
	} 
	division_development = {
		name  = "Kirov"
		type  = heavy_cruiser
		model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 3
		cost  = 0.1
		id    = { type = 10848 id = 8503 }
		date  = { year = 1938 month = september day = 23 }
	}
	division_development = {
		name  = "Voroshilov"
		type  = heavy_cruiser
		model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 3
		cost  = 0.1
		id    = { type = 10848 id = 8504 }
		date  = { year = 1940 month = june day = 20 }
	}

 }	
