   
   ##############################   
   # Country definition for USA #   
   ##############################   
      
   #####################   
   # Country main data #   
   #####################   
      
   country =   
   {  tag                    = USA   
     # Resource Reserves   
energy                 = 30060
metal                  = 15030
rare_materials         = 7515  
     oil                    = 5000   
     supplies               = 5000   
     money                  = 100   
     manpower               = 102   
     transports             = 360   
     escorts                = 53   
     dissent = 15
     research_mod = 0.75
     
     capital                = 1809   
     diplomacy =   
     {  relation =   
       {  tag        = ARG   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = AST value = 125  }   
       relation = {  tag = BEL value = 75  }   
       relation = {  tag = BHU value = 100  }   
       relation =   
       {  tag        = BOL   
         value      = 85   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = BRA   
         value      = 120   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = CAN   
         value      = 175   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = CHL   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = COL   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = COS   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = CUB   
         value      = 200   
         guaranteed = {  day = 30 month = december year = 1935  }   
         access     = yes   
        }   
       relation = {  tag = DEN value = 75  }   
       relation =   
       {  tag        = DOM   
         value      = 125   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = ECU   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = ENG value = 150  }   
       relation = {  tag = FIN value = 90  }   
       relation = {  tag = FRA value = 65  }   
       relation = {  tag = GER value = -10  }   
       relation =   
       {  tag        = GUA   
         value      = 125   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = HAI   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = HOL value = 70  }   
       relation =   
       {  tag        = HON   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = IRE value = 75  }   
       relation = {  tag = IRQ value = 120  }   
       relation = {  tag = JAP value = 15  }   
       relation = {  tag = LIB value = 200 access = yes  }   
	   relation = {  tag = LIT value = 65  }
	   relation = {  tag = LAT value = 65  }
	   relation = {  tag = EST value = 65  }
       relation = {  tag = MAN value = 1  }   
       relation =   
       {  tag        = MEX   
         value      = 125   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = NEP value = 100  }   
       relation =   
       {  tag        = NIC   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = NOR value = 75  }   
       relation = {  tag = NZL value = 125  }   
       relation = {  tag = OMN value = 100  }   
       relation =   
       {  tag        = PAN   
         value      = 175   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = PAR   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = PHI value = 200 access = yes  }   
       relation =   
       {  tag        = PRU   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = SAF value = 125  }   
       relation =   
       {  tag        = SAL   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = SOV value = 35  }   
       relation =   
       {  tag        = SCH   
         value      = 1   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = SWE value = 75  }   
       relation =   
       {  tag        = URU   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = VEN   
         value      = 125   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = YEM value = 100  }   
      }   
     SpyInfo                = {  country = "USA" NumberOfSpies = 11  }   
        
     nationalprovinces      = {  1809 1953 1949 1948 1952 1951 1950 1947 1956 1954 1955 1960 1958 1963 1961   
      1962 1964 1813 1812 1814 1818 1815 1816 1817 1808 1807 1801 1797 1791 1795 1793    
      1792 1805 1803 1804 1790 1787 1788 1784 1785 1789 1796 1826 1806   
      1810 1811 1820 1819 1942 1943 1940 1939 1936 1937 1944 1931 1825 1821 1842 1845 1802   
      1957 1828 1934 1930 1929 1932 1918 1915 1925 1836 1833 1830 1829 1832 1839   
      1838 1841 1843 1834 1837 2140 2145 2144 2146 2151 1846 1850 1855 1856 1858 1857 1859   
      1860 1914 1913 1919 1910 1911 1924 1928 1926 1920 1921 1922   
      1905 1906 1904 1900 1901 1902 1898 1896 1907 1908 1897 1909  
     1868 1866 1862 1869 1865 1871 1873 1875 1876 1874  
      1877 1878 1882 1879 1880 1895 1893 1892 1899 1886 1887 1883  
     1888 1889 1884 2141  2142 2147 2143 2139  2174
     1923  
     1831 1847 1935 1945 1885 1872 1863 2150 1864 1778     
    # Panamacanal to prevent transfer to allies  
    889   
    1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
                              }  
    ownedprovinces         = {  1953  1949  1948  1952  1951  1950  1947  1956  1954    1955  1960  1958  1963    1961  1962  1964  1813  1812    1814  1818 1815 1816 1817  1809   
                               1808  1807  1801  1797  1791  1795  1793    1792  1805  1803  1804    1790    1787  1788  1784  1785    1789  1796  1826  1806   
                               1810  1811  1820  1819  1942  1943  1940   1939 1936 1937  1944  1931  1825  1821  1842  1845  1802  1957  1828  1934  1930  1929 1932  1918  1915     
                               1925    1836  1833  1830  1829  1832  1839  1838  1841  1843  1834  1837   2145 2144 2146 2151  1846  1850        1855  1856  1858  1857  1859   
                               1860    1914  1913    1919  1910  1911    1924  1928  1926  1920   1921  1922   1905  1906  1904  1900    1901   
                               1902  1898  1896  1907  1908  1897  1909  1868  1866      1862        1869    1865    1871    1873 1875 1876  1874     
                               1877  1878  1882    1879  1880    1895  1893    1892  1899  1886  1887  1883  1888  1889  1884  2141   2140  2142 2147 2143  2139     
                                         1923      1765  889  1736  1737  1735    1739  1734  1738  1673 1683   
                 1747  
               1733 1751 1745  
               1778 1831  
               1872 1863 2150 1864 1847 1935 1945 1885  2174
         1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
                              }  
    controlledprovinces    = {  1953  1949  1948  1952  1951  1950  1947  1956  1954   1955  1960  1958  1963    1961  1962  1964  1813  1812    1814  1818 1815 1816 1817  1809   
                               1808  1807  1801  1797  1791  1795  1793    1792  1805  1803  1804   1790    1787  1788  1784  1785    1789  1796  1826  1806   
                               1810  1811  1820  1819  1942  1943  1940    1939 1936 1937  1944  1931  1825  1821  1842  1845  1802  1957  1828  1934  1930  1929 1932  1918  1915     
                               1925    1836  1833  1830  1829  1832  1839  1838  1841  1843  1834  1837   2145 2144 2146 2151  1846  1850        1855  1856  1858  1857  1859   
                               1860    1914  1913    1919  1910  1911    1924  1928  1926  1920    1921  1922   1905  1906  1904  1900    1901   
                               1902  1898  1896  1907  1908  1897  1909  1868  1866      1862        1869    1865    1871    1873 1875 1876  1874    
                               1877  1878  1882    1879  1880    1895  1893    1892  1899  1886  1887  1883  1888  1889  1884  2141    2140  2142 2147 2143  2139     
                                         1923      1765  889  1736  1737  1735    1739  1734  1738  1673 1683  1747  
                1733 1751 1745  2174
               1778 1831  
               1872 1863 2150 1864 1847 1935 1945 1885  
         1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
                }  
    # early esc car  
    # USA 1936 techs  
    # ######################  
    techapps               = {  
#Improved Light carrier 
12100 12110 12120	
#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020	
#Early Bomber 
4600 4610 4620 4630 4120 4130	
#Basic Air Transport 
4290 4250	
#Basic Strategic Bomber 
4800 4810 4820 4220 	
#Armoured Cars 
2860 2870 2880 2020
#Great War Tank 
7600 7610 2620 2010 2630
#Great War Heavy Field Artillery 
2290 2300 2310 	
#Early Static Anti-Air Artillery 
2800 2450 21180 21190 21200
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 
#1930 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980
#Mechanized Agriculture 
5700 5710 5010 5020
#Basic Machine Tools 
5810 5820 5050 5830 5060 5070
#Improved Construction Engineering 
5800 5080 5090 
#Computers and cryptografi
5310 54010 54020 54030 5316 5326 5327
#Refining
5190
#Faculty of Atomic Research 
5470
#Medicine
5600 5610 5620 5630
#Exp. Rocket
5560
#Multirole fighter
4300 4310 4320 4330 4340
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#Naval Infantry
1560 1570 1580
#Mountain
1160  1170  1180  1190  
#Seaplanes
4740  4750  4760  4770
#Engineers
1830 1840 1850 1860
#CAG 34
4900 4910 4920
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Interwar Light Cruiser 
3110 3120 3130 3140 3150 3160
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250 3260
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250 3260
#Heavy Battlecruiser
3310 3320 3330
#Early Battleship 
3410 3420 3430 3440 3450 3456 3460 3470
#Fleet Carrier 
3510 3520 3530
#Short Range Submarine 
3610 3620 3630 3640 3650
#Great War Hospital System 
14000 14010 14020
#Troopships
3810 5820

# WWI Land Doctrines - Entente: eng fra ita usa bel hol jap 
6500 6510  6530 6540 6580 6600 6610 6620 6630 6640 6650 6660 6670 6910
# WWII Land Doctrines - Firepower Focus
6010 6020

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9140

# Engagement Theories
8010 8020 8030 8040 8050 8060 8070 8080
# Naval Supremacy
8100 8110 8120 8150 8160 8200
# Naval Interdiction
8500 8510 8550 8600
# Engagement Tactics - Fleet-in-Being colum
8900 8910 8920 8930 8940 8950
# Subsidiary Carrier Role
81650
# Carrier - Scouting Focus
81850
# Logistic Support
82500  
# Amphibious Warfare
82300

} 

blueprints = { 81880 81890 }

inventions = { 3000027 }
    policy =  
    {  date              = {  year = 1942 month = january day = 0  }  
     democratic        = 9 
      political_left    = 6  
      freedom           = 10  
      free_market       = 10  
      professional_army = 2  
      defense_lobby     = 1  
      interventionism   = 1  
     }  
	 peacetime_ic_mod       = 0.2
	 wartime_ic_mod       = 0.8
    headofstate            = {  type = 9 id = 240001  }  
    headofgovernment       = {  type = 9 id = 240232  } # Harry Hopkins  
    foreignminister        = {  type = 9 id = 240003  }  
    armamentminister       = {  type = 9 id = 240004  }  
    ministerofsecurity     = {  type = 9 id = 240005  }  
    ministerofintelligence = {  type = 9 id = 240006  }  
    chiefofstaff           = {  type = 9 id = 240007  }  
    chiefofarmy            = {  type = 9 id = 240008  }  
    chiefofnavy            = {  type = 9 id = 240121  }  
    chiefofair             = {  type = 9 id = 240010  }  
    landunit =  
    {  location = 1789  
      name     = "I Corps"  
      id       = {  type = 14800 id = 601  }  
      Division =  
      {  id   = {  type = 14800 id = 602  }  
        name = "26th 'Yankee' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 603  }  
        name = "43rd 'Winged Victory' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
     }  
    landunit =  
    {  location = 1795  
      name     = "II Corps"  
      id       = {  type = 14800 id = 604  }  
      Division =  
      {  id   = {  type = 14800 id = 605  }  
        name = "1st 'Big Red One' Division" 
		strength = 100
		type = infantry  
		model    = 7
		extra = artillery
		brigade_model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 606  }  
        name = "21st Cavalry Division"  
		strength = 10
        type = cavalry  
		model    = 5
       }  
      Division =  
      {  id   = {  type = 14800 id = 607  }  
        name = "44th Infantry Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 608  }  
        name = "78th 'Lightning' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1808  
      name     = "III Corps"  
      id       = {  type = 14800 id = 609  }  
     Division = 
     {  id       = {  type = 13500 id = 610  } 
       name     = "U.S. Army General Staff" 
       type     = hq 
       model    = 2 
       strength = 100 
      } 
      Division =  
      {  id   = {  type = 14800 id = 611  }  
        name = "28th 'Keystone' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 612  }  
        name = "29th 'Blue and Gray' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
     }  
    landunit =  
    {  location = 1955  
      name     = "IV Corps"  
      id       = {  type = 14800 id = 613  }  
      Division =  
      {  id   = {  type = 14800 id = 614  }  
        name = "23rd Cavalry Division"  
		strength = 10
        type = cavalry  
		model    = 5
       }  
      Division =  
      {  id   = {  type = 14800 id = 615  }  
        name = "31st Infantry Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
     }  
    landunit =  
    {  location = 1821  
      name     = "V Corps"  
      id       = {  type = 14800 id = 616  }  
      Division =  
      {  id   = {  type = 14800 id = 617  }  
        name = "22nd Cavalry Division"  
		strength = 10
        type = cavalry  
		model    = 5
       }  
      Division =  
      {  id   = {  type = 14800 id = 618  }  
        name = "37th 'Buckeye' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 619  }  
        name = "100th 'Century' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1832  
      name     = "VI Corps"  
      id       = {  type = 14800 id = 620  }  
      Division =  
      {  id   = {  type = 14800 id = 621  }  
        name = "94th 'Pilgrim' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1859  
      name     = "VII Corps"  
      id       = {  type = 14800 id = 622  }  
      Division =  
      {  id   = {  type = 14800 id = 623  }  
        name = "24th Cavalry Division"  
		strength = 10
        type = cavalry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 624  }  
        name = "34th 'Red Bull' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 625  }  
        name = "35th 'Santa Fe' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
     }  
    landunit =  
    {  location = 1926  
      name     = "VIII Corps"  
      id       = {  type = 14800 id = 626  }  
      Division =  
      {  id   = {  type = 14800 id = 627  }  
        name = "2nd 'Indianhead' Division" 
		strength = 100
		type = infantry  
		model    = 7
		extra = artillery
		brigade_model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 628  }  
        name = "1st Cavalry 'The 1st Team' Div."  
		strength = 100
        type = cavalry  
		model    = 7
	extra = armored_car
		brigade_model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 629  }  
        name = "45th 'Thunderbird' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 630  }  
        name = "95th 'Victory' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1889  
      name     = "IX Corps"  
      id       = {  type = 14800 id = 631  }  
      Division =  
      {  id   = {  type = 14800 id = 632  }  
        name = "3rd 'Rock of the Marne' Division" 
		strength = 100
		type = infantry  
		model    = 7
		extra = artillery
		brigade_model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 633  }  
        name = "40th 'Sunshine' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 634  }  
        name = "41st 'Sunsetters' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 635  }  
        name = "91st 'Wild West' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
      Division =  
      {  id   = {  type = 14800 id = 636  }  
        name = "104th 'Timberwolf' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1874  
      name     = "4th Marine Regiment"  
      id       = {  type = 14800 id = 637  }  
      Division =  
      {  id   = {  type = 14800 id = 638  }  
        name = "4th Marine Regiment" 
		strength = 35
		type = marine
		model    = 2
       }  
     }  
    landunit =  
    {  location = 1814  
      name     = "5th Marine Regiment"  
      id       = {  type = 14800 id = 639  }  
      Division =  
      {  id   = {  type = 14800 id = 640  }  
        name = "5th Marine Regiment" 
		strength = 35
		type = marine
		model    = 2
       }  
     }  
    landunit =  
    {  location = 1886  
      name     = "6th Marine Regiment"  
      id       = {  type = 14800 id = 641  }  
      Division =  
      {  id   = {  type = 14800 id = 642  }  
        name = "6th Marine Regiment" 
		strength = 35
		type = marine
		model    = 2
       }  
     }  
    landunit =  
    {  location = 1734  
      name     = "Hawaiian Department"  
      id       = {  type = 14800 id = 643  }  
      Division =  
      {  id     = {  type = 14800 id = 644  }  
        name   = "Hawaiian Division"  
        type   = infantry  
		model    = 7
        strength = 100 
	extra = engineer
		brigade_model = 3
       }  
     }  
    landunit =  
    {  location = 1565  
      name     = "Philippine Department"  
      id       = {  type = 14800 id = 645  }  
      Division =  
      {  id     = {  type = 14800 id = 646  }  
        name   = "Philippine Division"  
        type   = infantry  
		model    = 7
        strength = 100 
	extra = engineer
		brigade_model = 3
       }  
     }  
    landunit =  
    {  id       = {  type = 14800 id = 647  }  
      name     = "Panama Canal Department"  
      location = 889  
      Division =  
      {  id     = {  type = 14800 id = 648  }  
        name   = "Panama Canal Garrison"  
		strength = 100
        type   = garrison  
        model  = 3
        locked = yes  
       }  
     }  
    # US PACIFIC FLEET-SAN DIEGO, CALIFORNIA  
    # Battleship Division 1  
    navalunit =  
    {  name     = "USN Battleship Fleet 1"  
      id       = {  type = 14800 id = 26  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id    = {  type = 14800 id = 28  }  
        name  = "USS Nevada"  
        type  = battleship  
        model = 4
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 29  }  
        name  = "USS Arizona"  
        type  = battleship  
        model = 4
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 30  }  
        name  = "USS Pennsylvania"  
        type  = battleship
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 49  }  
		name  = "USS Chicago"  
		type  = heavy_cruiser  
		model = 3
		extra1 = naval_torpedoes_l
		brigade_model1 = 4	
       }  
      Division =  
      {  id    = {  type = 14800 id = 50  }  
        name  = "USS Indianapolis"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 52  }  
        name  = "USS Northampton"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 2291  }  
        name  = "Destroyer Division 11"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2292  }  
        name  = "Destroyer Division 12"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2293  }  
        name  = "Destroyer Division 28"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2294  }  
        name  = "Destroyer Division 30"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2295  }  
        name  = "Destroyer Division 33"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2296  }  
        name  = "Destroyer Division 34"  
        type  = destroyer  
        model = 3  
       }  
     }  
    # Battleship Division 2  
    navalunit =  
    {  name     = "USN Battleship Fleet 2"  
      id       = {  type = 14800 id = 31  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id    = {  type = 14800 id = 33  }  
        name  = "USS Oklahoma"  
        type  = battleship  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 34  }  
		name  = "USS Tennessee"  
		type  = battleship  
		model = 5
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		
       }  
      Division =  
      {  id    = {  type = 14800 id = 35  }  
        name  = "USS California"  
        type  = battleship  
        model = 5
	  extra1 = naval_torpedoes_l
	  brigade_model1 = 4 
       }  
      Division =  
      {  id    = {  type = 14800 id = 53  }  
        name  = "USS Chester"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 54  }  
        name  = "USS Louisville"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 55  }  
        name  = "USS Portland"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 2297  }  
        name  = "Destroyer Division 35"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2298  }  
        name  = "Destroyer Division 36"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2299  }  
        name  = "Destroyer Division 37"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2300  }  
        name  = "Destroyer Division 38"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2301  }  
        name  = "Destroyer Division 39"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2302  }  
        name  = "Destroyer Division 40"  
        type  = destroyer  
        model = 3  
       }  
     }  
    # Battleship Division 4  
    navalunit =  
    {  name     = "USN Battleship Fleet 4"  
      id       = {  type = 14800 id = 36  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id    = {  type = 14800 id = 37  }  
        name  = "USS Colorado"  
        type  = battleship  
        model = 6  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 38  }  
        name  = "USS West Virginia"  
        type  = battleship  
        model = 6
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 39  }  
        name  = "USS Maryland"  
        type  = battleship  
        model = 6
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 57  }  
        name  = "USS New Orleans"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 58  }  
        name  = "USS Astoria"  
        type  = heavy_cruiser  
        model = 4 
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		
       }  
      Division =  
      {  id    = {  type = 14800 id = 59  }  
        name  = "USS Minneapolis"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 41  }  
        name  = "USS Richmond"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 42  }  
        name  = "USS Trenton"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 43  }  
        name  = "USS Concord"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 44  }  
        name  = "USS Raleigh"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 45  }  
        name  = "USS Detroit"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 63  }  
        name  = "Destroyer Division 2"  
        type  = destroyer  
        model = 5  
       }  
     }  
    # Cruiser Division 3  
    navalunit =  
    {  name     = "USN Cruiser Fleet 3"  
      id       = {  type = 14800 id = 40  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id    = {  type = 14800 id = 47  }  
        name  = "USS Pensacola"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 48  }  
        name  = "USS Salt Lake City"  
        type  = heavy_cruiser  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 60  }  
		name  = "USS San Francisco"  
		type  = heavy_cruiser  
		model = 4  
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		
       }  
      Division =  
      {  id    = {  type = 14800 id = 2303  }  
        name  = "Destroyer Division 48"  
        type  = destroyer  
        model = 5
       }  
      Division =  
      {  id    = {  type = 14800 id = 2304  }  
        name  = "Destroyer Division 49"  
        type  = destroyer  
        model = 5
       }  
      Division =  
      {  id    = {  type = 14800 id = 2305  }  
        name  = "Destroyer Division 50"  
        type  = destroyer  
        model = 5
       }  
     }  
    navalunit =  
    {  name     = "USN Carrier Fleet 1"  
      id       = {  type = 14800 id = 46  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id            = {  type = 14800 id = 27  }  
        name          = "USS Lexington"  
        type          = carrier  
        model         = 0  
        extra         = CAG  
        brigade_model = 2  
       }  
      Division =  
      {  id            = {  type = 14800 id = 32  }  
        name          = "USS Saratoga"  
        type          = carrier  
        model         = 0  
        extra         = CAG  
        brigade_model = 2  
       }
      Division =  
      {  id   = {  type = 14800 id = 162  }  
        name = "USS Langley"  
        type = escort_carrier  
		model = 1
       } 
      Division =  
      {  id    = {  type = 14800 id = 2308  }  
        name  = "Destroyer Division 53"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 62  }  
        name  = "Destroyer Division 1"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 64  }  
        name  = "Destroyer Division 3"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  name     = "Pacific Transport Fleet 1"  
      id       = {  type = 14800 id = 51  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id   = {  type = 14800 id = 147  }  
        name = "Charles Goodyear Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 148  }  
        name = "Anthony Wayne Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 149  }  
        name = "John Hancock Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id    = {  type = 14800 id = 2306  }  
        name  = "Destroyer Division 51"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2307  }  
        name  = "Destroyer Division 52"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2309  }  
        name  = "Destroyer Division 54"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  name     = "Pacific Transport Fleet 2"  
      id       = {  type = 14800 id = 56  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id   = {  type = 14800 id = 153  }  
        name = "George A. Custer Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 154  }  
        name = "August Belmont Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 156  }  
        name = "Emily Dickinson Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id    = {  type = 14800 id = 2310  }  
        name  = "Destroyer Division 55"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2311  }  
        name  = "Destroyer Division 56"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2312  }  
        name  = "Destroyer Division 57"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  name     = "Pacific Transport Fleet 3"  
      id       = {  type = 14800 id = 61  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id   = {  type = 14800 id = 150  }  
        name = "Samuel Dexter Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 151  }  
        name = "Stephen C. Crane Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 152  }  
        name = "William McKinley Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id    = {  type = 14800 id = 2313  }  
        name  = "Destroyer Division 58"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2314  }  
        name  = "Destroyer Division 59"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2321  }  
        name  = "Destroyer Division 60"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  name     = "Pacific Submarine Fleet"  
      id       = {  type = 14800 id = 74  }  
      location = 1886  
      base     = 1886  
      Division =  
      {  id    = {  type = 14800 id = 75  }  
        name  = "Submarine Division 1"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 76  }  
        name  = "Submarine Division 2"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 77  }  
        name  = "Submarine Division 3"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 78  }  
        name  = "Submarine Division 4"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 79  }  
        name  = "Submarine Division 5"  
        type  = submarine  
        model = 2  
       }  
      Division =  
      {  id    = {  type = 14800 id = 80  }  
        name  = "Submarine Division 6"  
        type  = submarine  
        model = 2  
       }  
     }  
    navalunit =  
    {  location = 1565  
      base     = 1565  
      id       = {  type = 14800 id = 81  }  
      name     = "Asiatic Fleet"  
      Division =  
      {  id    = {  type = 14800 id = 82  }  
        name  = "Destroyer Division 13"  
        type  = destroyer  
        model = 5  
       }  
      Division =  
      {  id    = {  type = 14800 id = 83  }  
        name  = "Destroyer Division 14"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 84  }  
        name  = "Destroyer Division 15"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 179  }  
        name  = "Destroyer Division 31"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 180  }  
        name  = "Destroyer Division 32"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1565  
      base     = 1565  
      id       = {  type = 14800 id = 87  }  
      name     = "2nd USN Submarine Fleet"  
      Division =  
      {  id    = {  type = 14800 id = 85  }  
        name  = "Submarine Division 7"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 86  }  
        name  = "Submarine Division 8"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 88  }  
        name  = "Submarine Division 9"  
        type  = submarine  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1874  
      base     = 1874  
      id       = {  type = 14800 id = 89  }  
      name     = "USN Seattle Fleet"  
      Division =  
      {  id       = {  type = 14800 id = 93  }  
        name     = "USS Houston"  
        strength = 100  
        type     = heavy_cruiser  
        model    = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id       = {  type = 14800 id = 90  }  
        name     = "USS Marblehead"  
        strength = 100  
        type     = light_cruiser  
        model    = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 192  }  
        name  = "Destroyer Division 43"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 91  }  
        name  = "Destroyer Division 16"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 189  }  
        name  = "Destroyer Division 47"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1874  
      base     = 1874  
      id       = {  type = 14800 id = 92  }  
      name     = "3rd USN Submarine Fleet"  
      Division =  
      {  id    = {  type = 14800 id = 94  }  
        name  = "Submarine Division 10"  
        type  = submarine  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 889  
      base     = 889  
      id       = {  type = 14800 id = 95  }  
      name     = "USN Carribean Fleet"  
      Division =  
      {  id    = {  type = 14800 id = 96  }  
        name  = "Destroyer Division 17"  
        type  = destroyer  
        model = 3 
       }  
      Division =  
      {  id    = {  type = 14800 id = 190  }  
        name  = "Destroyer Division 41"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 191  }  
        name  = "Destroyer Division 42"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 889  
      base     = 889  
      id       = {  type = 14800 id = 2322  }  
      name     = "4th USN Submarine Fleet"  
      Division =  
      {  id    = {  type = 14800 id = 97  }  
        name  = "Submarine Division 11"  
        type  = submarine  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 98  }  
      name     = "USN Battleship Fleet 3"  
      Division =  
      {  id    = {  type = 14800 id = 99  }  
        name  = "USS New Mexico"  
        type  = battleship  
        model = 4  
       }  
      Division =  
      {  id    = {  type = 14800 id = 100  }  
        name  = "USS Mississippi"  
        type  = battleship  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 101  }  
		name  = "USS Idaho"  
		type  = battleship  
		model = 4
		extra1 = naval_torpedoes_l
		brigade_model1 = 4			
       }  
      Division =  
      {  id    = {  type = 14800 id = 103  }  
        name  = "USS Arkansas"  
        type  = battleship  
        model = 2 
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 104  }  
        name  = "USS New York"  
        type  = battleship  
        model = 3  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 105  }  
		name  = "USS Texas"  
		type  = battleship  
		model = 3
		extra1 = naval_torpedoes_l
		brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 107  }  
        name  = "USS Omaha"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 108  }  
        name  = "USS Milwaukee"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 109  }  
        name  = "USS Cincinnati"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 110  }  
        name  = "USS Memphis"  
        type  = light_cruiser  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 194  }  
        name  = "Destroyer Division 45"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 195  }  
        name  = "Destroyer Division 46"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 102  }  
      name     = "Atlantic Transport Fleet 1"  
      Division =  
      {  id   = {  type = 14800 id = 143  }  
        name = "Dolly Madison Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 144  }  
        name = "Frederick Douglass Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 145  }  
        name = "Clara Barton Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id    = {  type = 14800 id = 117  }  
        name  = "Destroyer Division 19"  
        type  = destroyer  
        model = 3
       }
      Division =  
      {  id    = {  type = 14800 id = 118  }  
        name  = "Destroyer Division 20"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 120  }  
        name  = "Destroyer Division 22"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 106  }  
      name     = "USN Cruiser Fleet 2"  
      Division =  
      {  id    = {  type = 14800 id = 112  }  
        name  = "USS Augusta"  
        type  = heavy_cruiser  
        model = 3  
		extra1 = naval_torpedoes_l
		brigade_model1 = 4			
       }  
      Division =  
      {  id    = {  type = 14800 id = 113  }  
        name  = "USS Tuscaloosa"  
        type  = heavy_cruiser  
        model = 4  
	extra1 = naval_torpedoes_l
	brigade_model1 = 4
       }  
      Division =  
      {  id    = {  type = 14800 id = 193  }  
        name  = "Destroyer Division 44"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 176  }  
        name  = "Destroyer Division 28"  
        type  = destroyer  
        model = 5  
       }  
     }  
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 111  }  
      name     = "Atlantic Transport Fleet 2"  
      Division =  
      {  id   = {  type = 14800 id = 134  }  
        name = "Abner Doubleday Flotilla"  
        type = transport
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 135  }  
        name = "Brigham Young Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 136  }  
        name = "William B. Travis Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id    = {  type = 14800 id = 121  }  
        name  = "Destroyer Division 23"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 172  }  
        name  = "Destroyer Division 24"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 173  }  
        name  = "Destroyer Division 25"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 114  }  
      name     = "USS Ranger Taskforce"  
      Division =  
      {  id            = {  type = 14800 id = 115  }  
        name          = "USS Ranger"  
        type          = carrier  
        model         = 1  
        extra         = cag  
        brigade_model = 2  
       }  
      Division =  
      {  id    = {  type = 14800 id = 116  }  
        name  = "Destroyer Division 18"  
        type  = destroyer  
        model = 5  
       }  
     }  
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 122  }  
      name     = "Atlantic Submarine Fleet"  
      Division =  
      {  id    = {  type = 14800 id = 123  }  
        name  = "Submarine Division 12"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 124  }  
        name  = "Submarine Division 13"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 125  }  
        name  = "Submarine Division 14"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 126  }  
        name  = "Submarine Division 15"  
        type  = submarine  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 127  }  
        name  = "Submarine Division 16"  
        type  = submarine  
        model = 4  
       }  
      Division =  
      {  id    = {  type = 14800 id = 128  }  
        name  = "Submarine Division 17"  
        type  = submarine  
        model = 4  
       }  
     }  
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 133  }  
      name     = "Atlantic Transport Fleet 3"  
      Division =  
      {  id   = {  type = 14800 id = 137  }  
        name = "Peter Stuyvesant Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 138  }  
        name = "Henry L. Benning Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 139  }  
        name = "Casimir Pulaski Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id    = {  type = 14800 id = 119  }  
        name  = "Destroyer Division 21"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 174  }  
        name  = "Destroyer Division 26"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 175  }  
        name  = "Destroyer Division 27"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1812  
      base     = 1812  
      id       = {  type = 14800 id = 2323  }  
      name     = "Atlantic Transport Fleet 4"  
      Division =  
      {  id   = {  type = 14800 id = 140  }  
        name = "Sam Houston Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 141  }  
        name = "Francis Scott Key Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 142  }  
        name = "Walter Reed Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id    = {  type = 14800 id = 2315  }  
        name  = "Destroyer Division 5"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2316  }  
        name  = "Destroyer Division 6"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2317  }  
        name  = "Destroyer Division 7"  
        type  = destroyer  
        model = 3  
       }  
     }  
    navalunit =  
    {  location = 1886  
      base     = 1886  
      id       = {  type = 14800 id = 146  }  
      name     = "Pacific Transport Fleet 4"  
      Division =  
      {  id   = {  type = 14800 id = 157  }  
        name = "Molly Pitcher Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 158  }  
        name = "Antonin Dvorak Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id   = {  type = 14800 id = 159  }  
        name = "J. E. B. Stuart Flotilla"  
        type = transport  
		model = 1
       }  
      Division =  
      {  id    = {  type = 14800 id = 2318  }  
        name  = "Destroyer Division 8"  
        type  = destroyer  
        model = 3
       }  
      Division =  
      {  id    = {  type = 14800 id = 2319  }  
        name  = "Destroyer Division 9"  
        type  = destroyer  
        model = 3  
       }  
      Division =  
      {  id    = {  type = 14800 id = 2320  }  
        name  = "Destroyer Division 10"  
        type  = destroyer  
        model = 3  
       }  
     }  
    airunit =  
    {  location = 1886  
      base     = 1886  
      id       = {  type = 14800 id = 13  }  
      name     = "1st USAAF Fighter Wing"  
      Division =  
      {  id    = {  type = 14800 id = 14  }  
        name  = "6th USAAF Fighter Wing"  
        type  = interceptor  
        model = 5
       }  
     }  
    airunit =  
    {  location = 1809  
      base     = 1809  
      id       = {  type = 14800 id = 17  }  
      name     = "1st USAAF Bombardment Wing"  
      Division =  
      {  id    = {  type = 14800 id = 18  }  
        name  = "1st USAAF Dive Bomb. Wing"  
        type  = tactical_bomber  
        model = 4
       }  
     }  
    airunit =  
    {  location = 889  
      base     = 889  
      id       = {  type = 14800 id = 19  }  
      name     = "5th USAAF Bombardment Wing"  
      Division =  
      {  id    = {  type = 14800 id = 20  }  
        name  = "5th USAAF Tactical Bomb. Wing"  
        type  = tactical_bomber  
        model = 4
       }  
     }  
    airunit =  
    {  location = 1874  
      base     = 1874  
      id       = {  type = 14800 id = 21  }  
      name     = "7th USAAF Bombardment Wing"  
      Division =  
      {  id    = {  type = 14800 id = 22  }  
        name  = "1st USAAF Tactical Bomb. Wing"  
        type  = tactical_bomber  
        model = 4
       }  
     }  
    airunit =  
    {  location = 1795  
      base     = 1795  
      id       = {  type = 14800 id = 23  }  
      name     = "US Army Airforce"  
      Division =  
      {  id    = {  type = 14800 id = 24  }  
        name  = "9th USAAF Fighter Wing"  
        type  = interceptor  
        model = 5
       }  
      Division =  
      {  id    = {  type = 14800 id = 25  }  
        name  = "2nd USAAF Tactical Bomb. Wing"  
        type  = tactical_bomber  
        model = 4
       }  
     }  
    division_development =    
   {  name  = "USS Yorktown"  
      type  = carrier  
      model = 2  
      cost  = 0.5  
      id    = {  type = 14800 id = 500  }  
      date  = {  year = 1937 month = september day = 30  }  
      extra = cag  
      brigade_model = 2  
     }  
    division_development =    
   {  name  = "USS Enterprise"  
      type  = carrier  
      model = 2  
      cost  = 0.5  
      id    = {  type = 14800 id = 501  }  
      date  = {  year = 1938 month = may day = 12  }  
      extra = cag  
      brigade_model = 2  
     }  
    division_development =  
    {  name  = "USS Quincy"  
      type  = heavy_cruiser  
      model = 4  
      cost  = 0.3  
      id    = {  type = 14800 id = 502  }  
      date  = {  year = 1936 month = june day = 9  } 
		extra1 = naval_torpedoes_l
		brigade_model1 = 4		  
     }  
    division_development =  
    {  name  = "USS Wichita"  
      type  = heavy_cruiser  
      model = 5  
      extra1 = naval_torpedoes_l
      brigade_model1 = 4
      cost  = 0.3  
      id    = {  type = 14800 id = 503  }  
      date  = {  year = 1939 month = february day = 16  }  
     }  
    division_development =  
    {  name  = "USS Brooklyn"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 504  }  
      date  = {  year = 1937 month = september day = 30  }  
     }  
    division_development =  
    {  name  = "USS Philadelphia"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 505  }  
      date  = {  year = 1937 month = september day = 23  }  
     }  
    division_development =  
    {  name  = "USS Savannah"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 506  }  
      date  = {  year = 1938 month = march day = 10  }  
     }  
    division_development =  
    {  name  = "USS Nashville"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 507  }  
      date  = {  year = 1938 month = june day = 6  }  
     }  
    division_development =  
    {  name  = "USS Phoenix"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 508  }  
      date  = {  year = 1938 month = october day = 3  }  
     }  
    division_development =  
    {  name  = "USS Boise"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 509  }  
      date  = {  year = 1938 month = august day = 12  }  
     }  
    division_development =  
    {  name  = "USS Honolulu"  
      type  = light_cruiser  
      model = 5  
      cost  = 0.3  
      id    = {  type = 14800 id = 510  }  
      date  = {  year = 1938 month = june day = 15  }  
     }  
    division_development =  
    {  name  = "Destroyer Division 4"  
      type  = destroyer  
      model = 5  
      cost  = 0.1  
      id    = {  type = 14800 id = 511  }  
      date  = {  year = 1936 month = february day = 1  }  
     }  
    division_development =  
    {  name  = "Destroyer Division 29"  
      type  = destroyer  
      model = 5  
      cost  = 0.1  
      id    = {  type = 14800 id = 512  }  
      date  = {  year = 1936 month = march day = 1  }  
     }  
    division_development =  
    {  name  = "Submarine Division 18"  
      type  = submarine  
      model = 4  
      cost  = 0.1  
      id    = {  type = 14800 id = 513  }  
      date  = {  year = 1936 month = may day = 1  }  
     }  
   }  
  
