 #.#.#   Afghanistan 
 
 province = { id = 2171   #  Kabul - Afghanistan - Afghanistan
   landfort = 4 
 } 
 
 province = { id = 2172   #  Herat - Afghanistan - Afghanistan
   landfort = 2 
 } 
 
  #.#.#   Albania 
 
 province = { id = 360   #  Korce - Albania - Balkan
   province_revoltrisk = 30 } 
 
 province = { id = 362   #  Vlore - Albania - Balkan
   naval_base = { size = 4 current_size = 4 } 
 } 
 
  #.#.#   Argentina 
 
 province = { id = 2048   #  La Plata - La Plata - Rio de la Plata
   naval_base = { size = 8 current_size = 5 } 
 } 
 
 province = { id = 2050   #  Buenos Aires - La Plata - Rio de la Plata
   naval_base = { size = 8 current_size = 8 } 
 } 
 
 #.#.#   Australia 
 
 province = { id = 1607   #  Port Moresby - Port Moresby - New Guinea
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 1694   #  Collie - Perth - Australia
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 1 
 } 
 
 province = { id = 1697   #  Darwin - Darwin - Australia
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1704   #  Brisbane - Brisbane - Australia
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 1 
 } 
 
 province = { id = 1707   #  Canberra - Sydney - Australia
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 2 
 } 
 
 province = { id = 1708   #  Melbourne - Melbourne - Australia
   coastalfort = 1 
 } 
 
 province = { id = 1726   #  Rabaul - Rabaul - Bismarck Archipelago
   naval_base = { size = 7 current_size = 7 } 
 } 
 
  #.#.#   Austria-Hungary 
 
 province = { id = 187   #  Linz - Austria - Austria
   ic = -1 } 
 province = { id = 188   #  Eisenstadt - Austria - Austria
   ic = -1 } 
 province = { id = 190   #  Graz - Austria - Austria
   ic = -1 } 
 province = { id = 195   #  Vienna - Austria - Austria
   air_base = { size = 1 current_size = 1 } 
 } 
 province = { id = 196   #  Brno - Bohemia - Czechoslovakia
   ic = -1 } 
 province = { id = 198   #  Hradec Kralove - Bohemia - Czechoslovakia
   ic = -1 } 
 province = { id = 200   #  Liberec - Bohemia - Czechoslovakia
   ic = -1 } 
 province = { id = 201   #  Ostrava - Bohemia - Czechoslovakia
   ic = -1 } 
 province = { id = 205   #  Karlovy Vary - Bohemia - Czechoslovakia
   ic = -2 } 
 province = { id = 206   #  Opava - Bohemia - Czechoslovakia
   ic = 1 } 
 province = { id = 207   #  Prague - Bohemia - Czechoslovakia
   ic = -1 } 
 province = { id = 210   #  Komarno - Slovakia - Czechoslovakia
   ic = -1 } 
 province = { id = 211   #  Banska Bystrica - Slovakia - Czechoslovakia
   ic = 2 } 
 province = { id = 212   #  Zilina - Slovakia - Czechoslovakia
   ic = 2 } 
 
 province = { id = 235   #  Krakow - Krakow - Poland
   landfort = 3 
   ic = -2 
 } 
 
 province = { id = 239   #  Przemysl - Lvov - Poland
   landfort = 4 
 } 
 
 province = { id = 242   #  Lwow - Lvov - Poland
   landfort = 2 
 } 
 
 province = { id = 277   #  Pecs - Western Hungary - Hungary
   ic = -1 } 
 province = { id = 279   #  Gyor - Western Hungary - Hungary
   ic = -2 } 
 province = { id = 280   #  Szeged - Eastern Hungary - Hungary
   ic = -2 } 
 province = { id = 281   #  Debrecen - Eastern Hungary - Hungary
   ic = -3 } 
province = { id = 282   #  Miskolc - Eastern Hungary - Hungary
  ic = -4 } 
 province = { id = 283   #  Bekescsaba - Eastern Hungary - Hungary
   ic = -1 } 
 province = { id = 284   #  Budapest - Eastern Hungary - Hungary
   ic = -6 } 
 province = { id = 286   #  Arad - Transylvania - Romania
   ic = -2 } 
 province = { id = 291   #  Sibiu - Transylvania - Romania
   ic = -3 } 
 province = { id = 344   #  Osijek - Croatia - Balkan
   ic = -1 } 
 province = { id = 345   #  Bjelovar - Croatia - Balkan
   ic = 1 } 
 province = { id = 401   #  Trento - North Italy - Italy
   landfort = 3 
 } 
 province = { id = 406   #  Pola - North Italy - Italy
   naval_base = { size = 6 current_size = 6 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.#   Belgium 
 
 province = { id = 108   #  Liege - Wallonia - Benelux
   landfort = 1 
 } 
 
 province = { id = 113   #  Namur - Wallonia - Benelux
   landfort = 1 
 
}

 province = { id = 114   #  Bruges - Flanders - Benelux
   naval_base = { size = 3 current_size = 3 } 
   coastalfort = 1
 } 
 
 province = { id = 116   #  Brussels - Flanders - Benelux
   air_base = { size = 2 current_size = 2 } 
   landfort = 3 
 } 
 
 province = { id = 894   #  Matadi - Angolan Coast - Central Africa
   naval_base = { size = 3 current_size = 3 } 
 } 
 
  #.#.#   Brasil 
 
 province = { id = 2058   #  Porto Alegre - Sao Paulo - Brazilian Highlands
   naval_base = { size = 8 current_size = 8 } 
 } 
 
 province = { id = 2059   #  Sao Paulo - Sao Paulo - Brazilian Highlands
   naval_base = { size = 6 current_size = 6 } 
 } 
 
 province = { id = 2075   #  Rio de Janeiro - Rio de Janeiro - Brazilian Highlands
   naval_base = { size = 6 current_size = 6 } 
 } 
 
  #.#.#   British Raj 
 
 province = { id = 1415   #  Rangoon - Burma - Indochine
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1517   #  Bombay - Bombay - India
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 7 current_size = 7 } 
 } 
 
 province = { id = 1533   #  Karachi - Pakistan - India
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 #.#.#   Bulgaria 
 
 province = { id = 325   #  Burgas - Bulgaria - Balkan
   naval_base = { size = 5 current_size = 5 } 
 } 
 
  #.#.#   Canada 
 
 province = { id = 2089   #  Vancouver - British Columbia - Western Canada
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 2132   #  Halifax - Nova Scotia - Eastern Canada
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 #.#.#   China 
 
 province = { id = 1199   #  Harbin - Heilongjiang - China
   ic = -1 } 
 province = { id = 1202   #  Jiamusi - Heilongjiang - China
   ic = -1 } 
 province = { id = 1215   #  Fushun - Liaoning - China
   ic = -1 } 
 province = { id = 1220   #  Dandong - Liaoning - China
   ic = -1 } 
 province = { id = 1252   #  Taiyuan - Shanxi - China
   ic = -1 } 
 province = { id = 1259   #  Yan'an - Shaanxi - China
   ic = -2 } 
 province = { id = 1264   #  Lanzhou - Gansu - China
   ic = -1 } 
 province = { id = 1279   #  Kashgar - Xinjiang - China
   ic = -1 } 
 province = { id = 1281   #  Urumqi - Xinjiang - China
   ic = -2 } 
 province = { id = 1301   #  Fuling - Sichuan - China
   ic = -1 } 
 province = { id = 1308   #  Changsha - Hunan - China
   ic = -2 } 

 province = { id = 1328   #  Quingdao - ? - China 
   naval_base = { size = 4 current_size = 4 } 
 } 

 province = { id = 1330   #  Jinan - Shandong - China
   ic = -1 } 
 
 province = { id = 1338   #  Shanghai - Jiangsu - China
   naval_base = { size = 2 current_size = 2 } 
  ic = -2 
 } 
 
 province = { id = 1352   #  Nanchang - Jiangxi - China
   air_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 1353   #  Jiujiang - Jiangxi - China
   ic = -1 } 
 province = { id = 1370   #  Lufeng - Guangdong - China
   ic = -1 } 
 province = { id = 1375   #  Shantou - Guangdong - China
   ic = -1 } 
 province = { id = 1379   #  Nanning - Guangxi - China
   ic = -1 } 
 province = { id = 1390   #  Kunming - Yunnan - China
   ic = -3 } 
 
 #.#.#   Chile 
 
 province = { id = 2023   #  Santiago de Chile - Chile - Andes
   naval_base = { size = 8 current_size = 8 } 
 } 
 
  #.#.#   Columbia 
 
 province = { id = 1986   #  Barranquilla - Panaman Ridge - Grand Colombia
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.#   Costa Rica 
 
 province = { id = 2081   #  San Jose - Nicaragua - Central America
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 #.#.#   Cuba 
 
 province = { id = 1776   #  Havana - Cuba - Caribbean
   naval_base = { size = 4 current_size = 4 } 
 } 
 
  #.#.#   Denmark 
 
 province = { id = 1   #  Reykjavik - Iceland - Iceland
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 218   #  Frederikshavn - Denmark - Denmark
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 294   #  Copenhagen - Denmark - Denmark
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
   landfort = 2 
 } 
 
 #.#.#   Dominica 
 
 province = { id = 1780   #  Ciudad Trujillo - Hispaniola - Caribbean
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.#   Ecuador 
 
 province = { id = 2040   #  Santiago de Guayaquil - Quito - Andes
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #.#.#   Ethiopia 
 
 province = { id = 827   #  Gode - Ethiopian Highland - Ethiopia
   landfort = 1 
 } 
 
 province = { id = 828   #  Harer - Ethiopian Highland - Ethiopia
   landfort = 1 
 } 
 
 #.#.#   France 
 
 province = { id = 37   #  Brest - Brittany - France
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 43   #  Cherbourg - Normandy - France
   naval_base = { size = 6 current_size = 6 } 
 } 

 province = { id = 50   #  Amiens - ? - France
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 51   #  Dunkirk - Pas de Calais - France
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 52   #  Lille - Pas de Calais - France
   air_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 55   #  Paris - Paris - France
   air_base = { size = 4 current_size = 4 } 
   landfort = 1
 } 

 province = { id = 64   #  Le Creusot- ? - France
   air_base = { size = 1 current_size = 1 } 
 } 

 province = { id = 65   #  Bourges - ? - France
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 68   #  Bordeaux - Aquitaine - France
   naval_base = { size = 6 current_size = 6 } 
 } 
 
 province = { id = 83   #  Pau - ? - France
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 85   #  Lyon - ? - France
   air_base = { size = 1 current_size = 1 } 
 } 

 province = { id = 86   #  Toulon - Alpes_Provence - France
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 87   #  Nice - Alpes_Provence - France
   landfort = 5 
 } 
 
 province = { id = 90   #  Grenoble - Alpes_Provence - France
   landfort = 3 
 } 
 
 province = { id = 96   #  Longwy - ? - France
   landfort = 2  } 

 province = { id = 97   #  Belfort - Bourgogne_Champagne - France
   ic = -1
   landfort = 2
   air_base = { size = 1 current_size = 1 }   } 

 province = { id = 99   #  Reims - ? - France
   air_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 100   #  Verdun - Bourgogne_Champagne - France
   landfort = 6 
   air_base = { size = 1 current_size = 1 } 
 } 
  
 province = { id = 106   #  Nancy - ? - France
   landfort = 2
   air_base = { size = 2 current_size = 2 }   } 

 province = { id = 717   #  Rabat - Morocco - Morocco
   naval_base = { size = 4 current_size = 4 } 
 } 
 province = { id = 727   #  Algiers - Oran - Algeria
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 province = { id = 729   #  Tlemcen - Oran - Algeria
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 747   #  Tunis - Tunis - Tunisia
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 province = { id = 833   #  Djibouti - Somaliland - Horn of Africa
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 915   #  Libreville - Cameroonian Jungle - Central Africa
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 978   #  Dakar - Senegambia - West Africa
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 1002   #  Tamatave - Madagascar - Madagascar
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 1586   #  Nouvelle-Caledonie - South New Hebrides - South Solomon Islands
   naval_base = { size = 3 current_size = 3 } 
 } 
 
  #.#.#   Germany 
 
 province = { id = 850   #  Dar es Salaam - Tanganyika - East Africa
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 909   #  Yaounde - Cameroonian Jungle - Central Africa
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 104   #  Metz - Lorraine_Alsace - France
   landfort = 3 
 } 

 province = { id = 110   #  Eupen - Wallonia - Benelux
   landfort = 1 
 } 

 province = { id = 105   #  Colmar - Lorraine_Alsace - France
   landfort = 2  } 

 province = { id = 107   #  Strasbourg - Lorraine_Alsace - France
   landfort = 2  } 
   
 province = { id = 131   #  Cologne - Etappen-Flugzeug-Park 4
   air_base = { size = 1 current_size = 1 } 
 } 

 province = { id = 132   #  Freiburg - Etappen-Flugzeug-Park 7
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 139   #  Darmstadt - Etappen-Flugzeug-Park 5
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 141   #  Munster - Flugplatz Wanne-Herten
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 142   #  Duesseldorf - Flugplatz Holten, Flugplatz Duisburg-Neuenkamp, Flugplatz Fredenbaum
   air_base = { size = 3 current_size = 3 } 
 }

 province = { id = 145   #  Essen - Flugplatz Essen-Gelsenkirchen-Rotthausen
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 146   #  Hannover - Etappen-Flugzeug-Park 2
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 147   #  Wilhelmshaven - Hannover_Magdeburg - Germany
   air_base = { size = 1 current_size = 1 } # Flugplatz Netter Heide
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 152   #  Kiel - Holstein_Mecklenburg - Germany
   air_base = { size = 1 current_size = 1 } # Fliegerhorst Kiel-Holtenau
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 1
 } 
 
 province = { id = 153   #  Rostock - Holstein_Mecklemburg - Germany
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 157   #  Potsdam - Etappen-Flugzeug-Park 1, Etappen-Flugzeug-Park 6
   air_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 172   #  Cottbus - Etappen-Flugzeug-Park 3
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 224   #  Poznan - Poznan - Germany
   air_base = { size = 1 current_size = 1 } #Etappen-Flugzeug-Park 8
   landfort = 1 
 } 

 province = { id = 181   #  Danzig - Poznan - Germany
   landfort = 2 
 } 
 
 province = { id = 184   #  Koenigsberg - East Prussia - Germany
   naval_base = { size = 10 current_size = 10 } 
   landfort = 4 
 } 
 
 province = { id = 185   #  Allenstein - East Prussia - Germany
   landfort = 4 
 } 
 
 province = { id = 221   #  Katowice - Silesia - Poland
   ic = -1 } 
 
 province = { id = 222   #  Torun - Poznan - Poland
   landfort = 2 
 } 
 
 province = { id = 225   #  Bydgoszcz - Poznan - Poland
   landfort = 2 
 } 
 
 province = { id = 226   #  Gdynia - Poznan - Poland
   landfort = 2 
 } 
 
 #.#.#   Greece 
 
 province = { id = 365   #  Thessaloniki - Thrace - Balkan
   landfort = 1 
 } 
 
 province = { id = 367   #  Ioannina - Thrace - Balkan
   landfort = 1 
 } 
 
 province = { id = 364   #  Kavala - Thrace - Balkan
   landfort = 3 
 } 
 
 province = { id = 377   #  Athens - Attica - Balkan
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 382   #  Irakleio - Greek Island - Balkan
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.#   Guatemala 
 
 province = 
 { id = 2088   #  Ciudad de Guatemala - Central Rainforests - Central America
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.#   Haiti 
 
 province = { id = 1781   #  Port-au-Prince - Hispaniola - Caribbean
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #.#.#   Holland 
 
 province = { id = 122   #  Amsterdam - Netherlands - Benelux
   naval_base = { size = 10 current_size = 10 } 
   landfort = 3 
   coastalfort = 3 
 } 
 
 province = { id = 125   #  Rotterdam - Netherlands - Benelux
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 2 
   landfort = 1 
 } 
 
 province = { id = 1638   #  Bengkulu - Sumatra - Indonesia
   naval_base = { size = 7 current_size = 7 } 
 } 
 
 province = { id = 1648   #  Tjilegon - West Java - Indonesia
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 1653   #  Soerabaja - East Java - Indonesia
   naval_base = { size = 7 current_size = 7 } 
 } 
 
 province = { id = 1659   #  Manado - Celebes - Indonesia
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #.#.#   Honduras 
 
 province = 
 { id = 2085   #  Tegucigalpa - Nicaragua - Central America
   naval_base = { size = 4 current_size = 4 } 
 } 
 
  #.#.#   Italy 
 
 province = { id = 378   #  Kalymnos - Greek Island - Balkan
   naval_base = { size = 6 current_size = 6 } 
   coastalfort = 4 
 } 
 
 province = { id = 396   #  Genoa - North Italy - Italy
   landfort = 5 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 395   #  Bergamo - North Italy - Italy
   landfort = 2 
 } 
 
 province = { id = 398   #  Turin - North Italy - Italy
   landfort = 4 
 } 
 
 province = { id = 399   #  Alessandria - North Italy - Italy
   landfort = 5 
 } 
 
 province = { id = 400   #  Venice - North Italy - Italy
   naval_base = { size = 6 current_size = 6 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 411   #  Bologna - Appennine Ridge - Italy
   ic = -2 
 } 
 
 province = { id = 412   #  Ancona - Appennine Ridge - Italy
   coastalfort = 1 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 421   #  Naples - South Italy - Italy
   naval_base = { size = 6 current_size = 6 } 
 } 
 
 province = { id = 422   #  Taranto - South Italy - Italy
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 426   #  Bari - South Italy - Italy
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 430   #  Palermo - Sicilian Gap - Italy
   coastalfort = 1 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 433   #  Siracuse - Sicilian Gap - Italy
   coastalfort = 2 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 434   #  Cagliari - Ligurian Islands - Italy
   coastalfort = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 435   #  Sassari - Ligurian Islands - Italy
   naval_base = { size = 6 current_size = 6 } 
 } 
 
 province = { id = 404   #  Trieste - North Italy - Italy
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 750   #  Tripoli - Tripoli - Libya
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 761   #  Benghazi - Bengazi - Libya
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 765   #  Tobruk - Tobruk - Libya
   naval_base = { size = 6 current_size = 6 } 
   landfort = 3 
   coastalfort = 2 
 } 
 
 province = { id = 815   #  Massawa - Red Sea Coast - Ethiopia
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 816   #  Assab - Red Sea Coast - Ethiopia
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 836   #  Mogadishu - Somalia - Horn of Africa
   naval_base = { size = 2 current_size = 2 } 
   landfort = 1 
 } 

 province = { id = 835   #  Galkayo - Somalia - Horn of Africa
   landfort = 2
} 
 
  #.#.#   Japan 
 
 province = { id = 1219   #  Port Arthur - Liaoning - China
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 province = { id = 1223   #  Wonsan - Pyongyang - Korea
   ic = -1 } 
 province = { id = 1227   #  Hamheung - Pyongyang - Korea
   ic = -1 } 
 province = { id = 1230   #  Gwangju - Seoul - Korea
   ic = -1 } 
 
 province = { id = 1232   #  Busan - Seoul - Korea
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1233   #  Chuncheon - Seoul - Korea
   ic = -3 } 
 
 province = { id = 1361   #  Gaoxiong - Taiwan - China
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1542   #  Toyohara - Sakhalin_Kuriles - Japan
   ic = -1 } 
 province = { id = 1543   #  Shana - Sakhalin_Kuriles - Japan
   ic = -1 } 
 province = { id = 1544   #  Kushiro - Hokkaido - Japan
   ic = -1 } 
 province = { id = 1545   #  Sapporo - Hokkaido - Japan
   ic = -2 } 
 province = { id = 1549   #  Sendai - Tohoku - Japan
   ic = -1 } 
 province = { id = 1550   #  Yokohama - Tohoku - Japan
   ic = -1 } 
 
 province = { id = 1551   #  Niigata - Tohoku - Japan
   naval_base = { size = 10 current_size = 10 } 
   ic = -1 
 } 
 
 province = { id = 1552   #  Tokyo - Tohoku - Japan
   ic = 1 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1553   #  Osaka - Honshu - Japan
   naval_base = { size = 10 current_size = 10 } 
   ic = -1 
 } 
 
 province = { id = 1554   #  Hiroshima - Honshu - Japan
   naval_base = { size = 10 current_size = 10 } 
   ic = -1 
 } 
 
 province = { id = 1555   #  Kobe - Honshu - Japan
   ic = -1 } 
 province = { id = 1556   #  Kanazawa - Honshu - Japan
   ic = -1 } 
 
 province = { id = 1557   #  Nagoya - Honshu - Japan
   naval_base = { size = 10 current_size = 10 } 
   ic = -1 
 } 
 
 province = { id = 1558   #  Kyoto - Honshu - Japan
   naval_base = { size = 10 current_size = 10 } 
   ic = -1 
 } 
 
 province = { id = 1559   #  Matsuyama - Kyushu_Shikoku - Japan
   naval_base = { size = 10 current_size = 10 } 
   ic = -1 
 } 
 
 province = { id = 1560   #  Nagasaki - Kyushu_Shikoku - Japan
   naval_base = { size = 10 current_size = 10 } 
   ic = -1 
 } 
 
 province = { id = 1561   #  Kagoshima - Kyushu_Shikoku - Japan
   ic = -1 } 
 province = { id = 1562   #  Amami - Ryukyusland - Japan
   ic = -1 } 
 
 province = { id = 1563   #  Southern Okinawa - Ryukyusland - Japan
   naval_base = { size = 6 current_size = 6 } 
   ic = -1 
 } 
 
 province = { id = 1661   #  Iwo Jima - Bonin - Asian Pacific
   ic = -1 } 
 province = { id = 1662   #  Chichi Jima - Bonin - Asian Pacific
   ic = -1 } 
 province = { id = 1663   #  Motoyama - Bonin - Asian Pacific
   ic = -1 } 
 province = { id = 1664   #  Mount Suribachi - Bonin - Asian Pacific
   ic = -2 } 
 
 province = { id = 1665   #  Ponape - Carolinese - Asian Pacific
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1672   #  Minami Torima - Marcus_Wake - Asian Pacific
   ic = -1 } 
 
 province = { id = 1675   #  Eniwetok - Marshalls - Asian Pacific
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 1676   #  Kwajalein - Marshalls - Asian Pacific
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 1683   #  Guam - North Marianes - Asian Pacific
   ic = -1 } 
 
 #.#.#   Liberia 
 
 province = { id = 969   #  Monrovia - Guinean Coast - West Africa
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.#   Mexico 
 
 province = { id = 1970   #  Oaxaca de Juarez - Vera Cruz - Mexico
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.#   New Zealand 
 
 province = { id = 1721   #  Wellington - New Zealand - Australia
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 #.#.#   Nicaragua 
 
 province = { id = 2080   #  Managua - Nicaragua - Central America
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.#   Norway 
 
 province = { id = 483   #  Oslo - Southern Norway - Norway
   coastalfort = 3 
 } 
 
 province = { id = 491   #  Alesund - Southcentral Norway - Norway
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
 province = { id = 493   #  Trondheim - Central Norway - Norway
   coastalfort = 2 
 } 
 
 province = { id = 495   #  Narvik - Central Norway - Norway
   naval_base = { size = 3 current_size = 3 } 
 } 
 
  #.#.#   Oman 
 
 province = { id = 1052   #  Masqat - Yemenite Mountains - Middle East
   naval_base = { size = 3 current_size = 3 } 
 } 
 
  #.#.#   Ottoman Empire 
 
province = { id = 409 # Constantinople - Bosporus - Anatolia
  landfort = 1 
  coastalfort = 1 } 

 province = { id = 385   #  Adrianople - Bosporus - Anatolia
   landfort = 3 
 } 

province = { id = 384 	# Gallipoli/Gelibolu - Bosporus - Anatolia
  coastalfort = 3 } 
 
 province = { id = 1075   #  Ankara - Central Turkey - Anatolia
 anti_air = 4 
   air_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 1076   #  Izmit - Bosporus - Anatolia
 anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
  #.#.#   Panama 
 
 province = { id = 2078   #  Ciudad de Panama - Panaman Ridge - Central America
   naval_base = { size = 3 current_size = 3 } 
 } 
 
  #.#.#   Persia 
 
 province = { id = 1091   #  Gameroon - East Persia - Persia
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #.#.#   Peru 
 
 province = { id = 2016   #  Lima - Lima - Andes
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #.#.#   Portugal 
 
 province = { id = 476   #  Lisbon - Portugal - Portugal
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 856   #  Maxixe - Mocambique - East Africa
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 892   #  Lobito - Angolan Coast - Central Africa
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 893   #  Cabinda - Angolan Coast - Central Africa
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 912   #  Sao Tome - Cameroonian Jungle - Central Africa
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 963   #  Bissau - Guinean Coast - West Africa
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 992   #  Cape Verde - Cap Verde Islands - West Africa
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 995   #  The Azores - The Azores - Portugal
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 1372   #  Macao - Guangdong - China
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 1617   #  Dili - Flores_Timor - Indonesia
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #.#.#   Romania 
 
 province = { id = 307   #  Dobrich - South Romania - Romania
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 316   #  Bucharest - South Romania - Romania
   air_base = { size = 1 current_size = 1 } 
   landfort = 1
 } 

 province = { id = 310   #  Constanta - South Romania - Romania
   coastalfort = 1
 } 
 
 #.#.#   Russia 
 
 province = { id = 227   #  Czestochowa - Poznan - Poland
   ic = -2 } 

 province = { id = 230   #  Plock - Warsaw - Poland
   landfort = 2 
 } 

 province = { id = 232   #  Warsaw - Warsaw - Poland
   landfort = 5 
   ic = -2 
 } 
 
 province = { id = 234   #  Radom - Krakow - Poland
   ic = -1 } 
 province = { id = 243   #  Lublin - Krakow - Poland
   landfort = 1 
   ic = -1 
 } 
 province = { id = 247   #  Brest-Litovsk - Brest Litovsk - Poland
   landfort = 4 
 } 
 province = { id = 251   #  Nowogrodek - Grodno - Poland
   landfort = 4 
 } 
 province = { id = 254   #  Bialystok - Polotsk - Poland
   landfort = 5 
 } 
 province = { id = 255   #  Grodno - Grodno - Poland
   landfort = 2 
 } 
 province = { id = 262   #  Kaunas - Lithuania - Baltic States
   landfort = 4 
   ic = -2 
 } 
 
 province = { id = 264   #  Riga - Latvia - Baltic States
   landfort = 2 
   coastalfort = 3 
   naval_base = { size = 7 current_size = 7 } 
   ic = -1 
 } 
 
 province = { id = 266   #  Daugavpils - Latvia - Baltic States
   landfort = 5 
   ic = -1 
 } 
 
 province = { id = 268   #  Liepaja - Latvia - Baltic States
   landfort = 1 
   coastalfort = 5 
   naval_base = { size = 10 current_size = 10 } 
   ic = -1 
 } 
 
 province = { id = 270   #  Tallinn - Estonia - Baltic States
   ic = -4 } 
 province = { id = 502   #  Akmolinsk - Kazakstan - Kazakstan
   ic = -1 } 
 province = { id = 503   #  Karaganda - Kazakstan - Kazakstan
   ic = -1 } 
 province = { id = 504   #  Alma-Ata - Turkestan - Kazakstan
   ic = -1 } 
 province = { id = 520   #  Oulu - Central Finland - Finland
   ic = -1 } 
 province = { id = 524   #  Turku - Oesterbotten - Finland
   ic = -1 } 
 province = { id = 525   #  Helsinki - South Finland - Finland
   ic = -1 } 
 province = { id = 527   #  Tampere - South Finland - Finland
   ic = -1 } 
 province = { id = 528   #  Mikkeli - South Finland - Finland
   ic = -1 } 
 province = { id = 529   #  Kouvola - South Finland - Finland
   ic = -1 } 
 
 province = { id = 526  #  Åland - South Finland - Finland
   landfort = 2
   coastalfort = 2 
   naval_base = { size = 1 current_size = 1 } 
 } 

 province = { id = 531   #  Viipuri - Karelia - Finland
   landfort = 1 
 } 
 
 province = { id = 535   #  Murmansk - Kola - White Sea Tundra
  naval_base = { size = 7 current_size = 7 } 
 } 
 
 province = { id = 536   #  Kandalaksha - Kola - White Sea Tundra
   ic = -1 } 
 
 province = { id = 542   #  Arkhangelsk - Arkhangelsk - Northern Russia
  naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 553   #  Leningrad - Leningrad - Russia
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 1 current_size = 1 } 
   landfort = 5 
   coastalfort = 5 
   name = PROV_PETROGRAD
 } 

 province = { id = 570   #  Zagorsk - Moscow - Russia
   landfort = 1 
 } 

 province = { id = 570   #  Tula - Ryazan - Russia
   landfort = 2 
 } 
 
 province = { id = 572   #  Moscow - Moscow - Russia
   air_base = { size = 1 current_size = 1 } 
   landfort = 3 
   ic = -5 
 } 
 
 province = { id = 594   #  Bobruisk - Rogachev - Belarus
   landfort = 1 
 } 

 province = { id = 604   #  Kursk - Kursk - Russia
   landfort = 2
 } 
 
 province = { id = 617   #  Kiev - Kiev - Ukraine
   landfort = 2 
 } 
 
 province = { id = 621   #  Tiraspol - Odessa - Ukraine
   landfort = 2 
 } 
 
 province = { id = 624   #  Kherson - Dnepropretovsk - Ukraine
   ic = -1 } 
 province = { id = 626   #  Odessa - Odessa - Ukraine
   ic = -1 } 
 province = { id = 633   #  Kupyansk - Kharkov - Ukraine
   ic = -1 } 
 province = { id = 634   #  Voroshilovgrad - Kharkov - Ukraine
   ic = -1 } 
 province = { id = 635   #  Stalino - Kharkov - Ukraine
   ic = -3 } 
 
 province = { id = 641   #  Sevastopol - Krim - Ukraine
   naval_base = { size = 10 current_size = 10 } 
   landfort = 3 
   coastalfort = 5 
   ic = -1 
 } 
 
 province = { id = 644   #  Rostov-on-Don - Rostov - Southern Russia
   ic = -2 } 
 
 province = { id = 663   #  Stalingrad - Stalingrad - Southern Russia
   landfort = 3 
   ic = -3 
   name = PROV_TSARITSYN
 } 

 province = { id = 666   #  Engels - Engels - Eastern Russia
   name = PROV_POKROVSK
 } 
 
 province = { id = 668   #  Kuybyshev - Kuybyshev - Russia
   ic = -2 } 
 province = { id = 669   #  Saratov - Penza - Southern Russia
   ic = -2 } 
 province = { id = 672   #  Kazan - Kazan - Northern Russia
   ic = -2 } 
 province = { id = 680   #  Gorky - Nizhnij Novgorod - Northern Russia
   ic = -1 } 
 province = { id = 684   #  Kirov - Kazan - Northern Russia
   ic = -1 } 
 province = { id = 687   #  Perm - Perm - Urals
   ic = -5 } 
 province = { id = 688   #  Ukhta - Kirov - Northern Russia
   ic = -1 } 
 province = { id = 690   #  Sterlitamak - Orenburg - Eastern Russia
   ic = -1 } 
 province = { id = 706   #  Astrakhan - Astrakhan - Kaukasus
  ic = -2 } 
 
 province = { id = 708   #  Kutaisi - Georgien - Kaukasus
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 709   #  Tbilisi - Georgien - Kaukasus
   ic = -1 } 
 province = { id = 711   #  Yerevan - Armenia_Azerbaijan - Kaukasus
   ic = -1 } 
 province = { id = 713   #  Baku - Armenia_Azerbaijan - Kaukasus
   ic = -1 } 
 province = { id = 1097   #  Ashkhabad - Turkmenistan - Central Asia
  ic = -1 } 
 province = { id = 1008   #  Tel Aviv - Palestine - Middle East
   ic = -1 } 
 province = { id = 1098   #  Merv - Turkmenistan - Central Asia
   ic = -1 } 
 province = { id = 1099   #  Samarkand - Uzbekistan - Central Asia
   ic = -1 } 
 province = { id = 1100   #  Bukhara - Uzbekistan - Central Asia
   ic = -1 } 
 province = { id = 1113   #  Uralsk - Kirgiz Steppe - Kazakstan
   ic = -1 } 
 province = { id = 1118   #  Shevchenko - Kirgiz Steppe - Kazakstan
   ic = -1 } 
 province = { id = 1119   #  Kyzyl - Mongolia - Krasnoyarsk
   ic = -4 } 
 province = { id = 1128   #  Nizhny Tagil - Sverdlovsk - Urals
   ic = -1 } 
 province = { id = 1129   #  Vorkuta - Vorkuta - Urals
   ic = -1 } 
province = { id = 1130   #  Berezniki - Perm - Urals
  ic = -1 } 
 province = { id = 1131   #  Ufa - Ufa - Eastern Russia
   ic = -1 } 
 province = { id = 1132   #  Chelyabinsk - Ufa - Eastern Russia
   ic = -1 } 
 province = { id = 1134   #  Orenburg - Orenburg - Eastern Russia
   ic = -1 } 
 province = { id = 1137   #  Kurgan - Tyumen - Novosibirsk
   ic = -1 } 
 province = { id = 1138   #  Omsk - Omsk - Novosibirsk
   ic = -1 } 
 province = { id = 1140   #  Barnaul - Novosibirsk - Novosibirsk
   ic = -1 } 
 province = { id = 1142   #  Novosibirsk - Novosibirsk - Novosibirsk
   ic = -1 } 
province = { id = 1144   #  Kemerovo - Novosibirsk - Novosibirsk
   ic = -1 } 
 province = { id = 1145   #  Stalinsk - Novosibirsk - Novosibirsk
   ic = -1 } 
 province = { id = 1148   #  Tomsk - Tomsk - Tomsk
   ic = -1 } 
 province = { id = 1151   #  Sverdlovsk - Sverdlovsk - Urals
   ic = -2 } 
 province = { id = 1156   #  Krasnoyarsk - North Krasnoyarsk - Krasnoyarsk
   ic = -1 } 
 province = { id = 1162   #  Irkutsk - Irkutsk - Irkutsk
   ic = -1 } 
 province = { id = 1170   #  Never - Amur - Far East Siberia
   ic = -1 } 
 
 province = { id = 1191   #  Vladivostok - Primorski - Far East Siberia
   naval_base = { size = 10 current_size = 10 } 
   landfort = 1 
   coastalfort = 3 
 } 
 
  #.#.#   San Salvador 
 
 province = { id = 2079   #  San Salvador - Nicaragua - Central America
   naval_base = { size = 1 current_size = 1 } 
 } 
 
  #.#.#   Saudi Arabia 
 
 province = { id = 1048   #  Medina - Hedjaz - Middle East
   naval_base = { size = 3 current_size = 3 } 
 } 
 
  #.#.#   Serbia 
 
 province = { id = 327   #  Krusevac - ? - Balkan
   points = 1
 } 

 province = { id = 332   #  Cetinje - East Serbia - Balkan
   naval_base = { size = 3 current_size = 3 } 
 } 

 province = { id = 333   #  Skopje - ? - Balkan
   points = 1
 } 
 
 province = { id = 350   #  Split - Croatia - Balkan
   naval_base = { size = 3 current_size = 3 } 
 } 

 province = { id = 338   #  Belgrade - Central Serbia - Balkan
   landfort = 2 
 } 

 province = { id = 339   #  Bor - Central Serbia - Balkan
   landfort = 1
 } 
 
  #.#.#   Siam 
 
 province = { id = 1424   #  Nakhon Sawan - Siam - Indochine
   naval_base = { size = 8 current_size = 8 } 
 } 
 
 #.#.#   South Africa 
 
 province = { id = 872   #  Pretoria - Transvaal_Natal - South Africa
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 880   #  Cape Town - Cape - South Africa
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 882   #  Swakopmund - Nambia - Southwest Africa
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #.#.#   Spain 
 
 province = { id = 436   #  Tarragona - Catalonia - Spain
   naval_base = { size = 7 current_size = 7 } 
 } 
 
 province = { id = 441   #  Coruna - Cantabric Chain - Spain
   naval_base = { size = 7 current_size = 7 } 
 } 
 
 province = { id = 460   #  Madrid - Aeródromo de Cuatro Vientos, Aeródromo de Getafe
   air_base = { size = 2 current_size = 2 } 
 }  
 
 province = { id = 464   #  Valencia - Levant - Spain
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 473   #  Cadiz - West Andalucia - Spain
   naval_base = { size = 5 current_size = 7 } 
 } 
 
 province = { id = 475   #  Palma de Mallorca - Baleares - Spain
   naval_base = { size = 7 current_size = 7 } 
 } 
 
 province = { id = 715   #  Tangier - Aeródromo de Tetuán, Aeródromo de Larache
   air_base = { size = 2 current_size = 2 } 
 }
 
 province = { id = 716   #  Nador - Aeródromo de Melilla
   air_base = { size = 1 current_size = 1 } 
 }
 
 province = { id = 988   #  Villa Cisneros - Rio de Oro - Sahara
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 990   #  Las Palmas de Gran Canaria - Canarias - Sahara
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.#   Sweden 
 
 province = { id = 2153   #  Gothenburg - Goetaland - Sweden
   naval_base = { size = 5 current_size = 5 } 
   landfort = 1
   coastalfort = 1
 } 
 
 province = { id = 2159   #  Stockholm - Oestra Svealand - Sweden
   naval_base = { size = 7 current_size = 7 } 
   coastalfort = 2 
 } 
 
 province = { id = 2152   #  Malmo - Goetaland - Sweden
   coastalfort = 2 
 } 

 province = { id = 2166   #  Lulea - Oevre Norrland - Sweden
   landfort = 2 
 } 

 #.#.#   Swiss 
 
province = { id = 390   #  Lugano - Switzerland - Switzerland
  landfort = 4 
} 
 
 province = { id = 391   #  Geneva - Switzerland - Switzerland
   landfort = 5 
 } 
 
 province = { id = 392   #  Bern - Switzerland - Switzerland
   landfort = 5 
 } 
 
 province = { id = 533   #  Joensuu - Central Finland - Finland
   landfort = 5 
 } 
 
  #.#.#   United Kingdom 
 
 province = { id = 5   #  Scapa Flow - North Scotland - Scotland
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 13   #  Sunderland - North England - England
   ic = 3 } 
 
 province = { id = 17   #  Manchester - North England - England
   naval_base = { size = 8 current_size = 8 } 
   ic = 5 
 } 
 
 province = { id = 18   #  Sheffield - North England - England
   ic = 6 } 
 province = { id = 22   #  Cardiff - West England - England
   ic = 4 } 
 
 province = { id = 23   #  Plymouth - West England - England
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 24   #  Birmingham - West England - England
   ic = 4 } 
 
 province = { id = 25   #  Norwich - East England - England
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 26   #  Dover - East England - England
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
 province = { id = 27   #  Portsmouth - East England - England
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 29   #  London - East England - England
   air_base = { size = 2 current_size = 2 } 
   ic = 3 
 } 
 
 province = { id = 429   #  Malta - Sicilian Gap - Italy
   naval_base = { size = 5 current_size = 5 } 
   coastalfort = 1 
 } 
 
 province = { id = 348   #  Gibraltar - West Andalucia - Spain
   naval_base = { size = 10 current_size = 10 } 
   landfort = 6 
 } 
 
 province = { id = 789   #  Alexandria - Delta - Egypt
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 838   #  Kismayo - Somalia - Horn of Africa
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 929   # Lagos - South Nigeria - West Africa
   naval_base = { size = 1 current_size = 1 } 
 } 

 province = { id = 964   #  Freetown - Guinean Coast - West Africa
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 1008   #  Tel Aviv - Palestine - Middle East
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 province = { id = 1371   #  Hong Kong - Guangdong - China
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 1 
 } 
 
 province = { id = 1432   #  Singapore - Malacka - Indochine
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
 
 province = { id = 1511   #  Colombo - Ceylon - India
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
 province = { id = 1773   #  The Bermudas - Bermuda - Caribbean
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 1611   #  Male - Diego Garcia Island - Diego Garcia Island
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 2045   #  Falkland Islands - The Falklands - Patagonia
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 province = { id = 2137   #  St. John's - New Foundland - Eastern Canada
   naval_base = { size = 10 current_size = 10 } 
 } 

 province = { id = 836   #  Hargeysa - Somalia - Horn of Africa
   landfort = 1  
 } 
 
 #.#.#   Uruguay 
 
 province = { id = 2052   #  Montevideo - La Plata - Rio de la Plata
   naval_base = { size = 4 current_size = 4 } 
 } 
 
  #.#.#   USA 
 
 province = { id = 889   #  Balboa - Panaman Ridge - Central America
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 1673   #  Wake - Marcus_Wake - Asian Pacific
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 1683   #  Guam - North Marianes - Asian Pacific
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = { id = 1734   #  Pearl Harbor - Hawaii - American Pacific
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 province = { id = 1778   #  Guantanamo Bay Naval Base - Cuba - Caribbean
   naval_base = { size = 6 current_size = 6 } 
 } 
 
 province = { id = 1785   #  Lewiston - Maine - Northeast US
   ic = -1 } 
 province = { id = 1788   #  Hartford - Massachussets - Northeast US
   ic = -3 } 
 
 province = { id = 1789   #  Boston - Massachussets - Northeast US
   naval_base = { size = 10 current_size = 10 } 
   ic = -4 
 } 
 
 province = { id = 1791   #  Buffalo - New York - Northeast US
   ic = -3 } 
 province = { id = 1792   #  Syracuse - New York - Northeast US
   ic = -2 } 
 province = { id = 1793   #  Albany - New York - Northeast US
   ic = -2 } 
 
 province = { id = 1795   #  New York - New York - Northeast US
   naval_base = { size = 10 current_size = 10 } 
   ic = -7 
 } 
 
 province = { id = 1797   #  Newark - New Jersey - Northeast US
   ic = -2 } 
 province = { id = 1801   #  Harrisburg - Pennsylvania - Northeast US
   ic = -2 } 
 province = { id = 1805   #  Philadelphia - Pennsylvania - Northeast US
   ic = -6 } 
 province = { id = 1806   #  Pittsburgh - Pennsylvania - Northeast US
   ic = -4 } 
 province = { id = 1808   #  Baltimore - Maryland_Delaware - Northeast US
   ic = -4 } 
 
 province = { id = 1809   #  Washington - Maryland_Delaware - Northeast US
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1812   #  Norfolk - Virginia - Northeast US
   naval_base = { size = 10 current_size = 10 } 
   ic = -2 
 } 
 
 province = { id = 1813   #  Richmond - Virginia - Northeast US
   ic = -2 } 
 province = { id = 1821   #  Columbus - Ohio - Northeast US
   ic = -2 } 
 province = { id = 1823   #  Cincinnati - Ohio - Northeast US
   ic = -4 } 
 province = { id = 1824   #  Erie - Ohio - Northeast US
   ic = -1 } 
 province = { id = 1825   #  Cleveland - Ohio - Northeast US
   ic = -6 } 
 province = { id = 1826   #  Fort Wayne - Indiana - Northeast US
   ic = -2 } 
 province = { id = 1828   #  Indianapolis - Indiana - Northeast US
   ic = -2 } 
 province = { id = 1832   #  Chicago - Illinois - Midwest US
   ic = -7 } 
 province = { id = 1833   #  Saint Louis - Missouri - Midwest US
   ic = -4 } 
 province = { id = 1839   #  Milwaukee - Wisconsin - Midwest US
   ic = -4 } 
 province = { id = 1844   #  Flint - Michigan - Midwest US
   ic = -3 } 
 province = { id = 1845   #  Detroit - Michigan - Midwest US
   ic = -5 } 
 province = { id = 1847   #  Minneapolis - Minnesota - Midwest US
   ic = -2 } 
 
 province = { id = 1874   #  Seattle - Washington - Northwest US
   naval_base = { size = 10 current_size = 10 } 
   ic = -3 
 } 
 
province = { id = 1878   #  Portland - Oregon - Northwest US
  ic = -3 } 
 province = { id = 1879   #  Eugene - Oregon - Northwest US
   ic = -1 } 
 
 province = { id = 1886   #  San Diego - California - Southwest US
   naval_base = { size = 10 current_size = 10 } 
   ic = -3 
 } 
 
 province = { id = 1887   #  Los Angeles - California - Southwest US
   naval_base = { size = 8 current_size = 8 } 
   ic = -3 
 } 
 
 province = { id = 1889   #  San Francisco - California - Southwest US
   naval_base = { size = 10 current_size = 10 } 
   ic = -2 
 } 
 
 province = { id = 1890   #  Eureka - California - Southwest US
   ic = -1 } 
 province = { id = 1896   #  Salt Lake City - Utah - Southwest US
   ic = -3 } 
 
 province = { id = 1908   #  Denver - Colorado - Southcentral US
   ic = -2 } 
 province = { id = 1914   #  Kansas City - Kansas - Southcentral US
   ic = -1 } 
 
 Province = { id = 1922   #  Corpus Christi - Texas - Southcentral US
   naval_base = { size = 8 current_size = 8 } 
   ic = -1 
 }  
 
 province = { id = 1924   #  Dallas - Texas - Southcentral US
   ic = -4 } 
 province = { id = 1925   #  Austin - Texas - Southcentral US
   ic = -1 } 
 province = { id = 1926   #  San Antonio - Texas - Southcentral US
   ic = -1 } 
 province = { id = 1928   #  Houston - Texas - Southcentral US
   ic = -6 } 
 province = { id = 1931   #  New Orleans - Louisiana - Southcentral US
   ic = -3 } 
 province = { id = 1940   #  Memphis - Tennessee - Southeast US
   ic = -4 } 
 province = { id = 1942   #  Knoxville - Tennessee - Southeast US
   ic = -2 } 
 
 province = { id = 1953   #  Miami - Florida - Southeast US
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1955   #  Atlanta - Georgia - Southeast US
   ic = -2 } 
 
 province = { id = 2142   #  Anchorage - Alaska - Alaska
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.#   Venezuela 
 
 province = { id = 1988   #  Maracaibo - Maracaibo - Grand Colombia
   naval_base = { size = 6 current_size = 6 } 
 } 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 