 
 ############################## 
 # Country definition for MEX # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag          = MEX 
 ai             = "MEX_1914.ai"
 flag_ext = _14
  # Resource Reserves 
energy                 = 1140
metal                  = 570
rare_materials         = 285
  oil          = 500 
  supplies        = 500 
  money         = 20 
  capital        = 1974 
  dissent = 5
  manpower        = 112 
  transports       = 100 
  policy = 
  {  date       = {  year = 0 month = january day = 0  } 
   democratic    = 5 
   political_left  = 3 
   freedom      = 4 
   free_market    = 6 
   professional_army = 4 
   defense_lobby     = 6 
   interventionism  = 3 
   } 

   headofstate            = {  type = 9 id = 170106  } # Victoriano Huerta
   headofgovernment       = {  type = 9 id = 170108  } # Victoriano Huerta
   foreignminister        = {  type = 9 id = 170118  } # Francisco S. Carbajal
   armamentminister       = {  type = 9 id = 170120  } # Querido Moheno
   ministerofsecurity     = {  type = 9 id = 170126  } # Ignacio Alcocer
   ministerofintelligence = {  type = 9 id = 170142  } #Aureliano Blanquet
   chiefofstaff           = {  type = 9 id = 170127  } # Pascual Orozco 
   chiefofarmy            = {  type = 9 id = 170134  } # José Refugio Velasco
   chiefofnavy            = {  type = 9 id = 170137  } # José Refugio Velasco
   chiefofair             = {  type = 9 id = 170139  } # Juan Guillermo Villasana

  	peacetime_ic_mod       = 1 
    wartime_ic_mod       = 1 
 	nationalprovinces   = {  1966 1965 1970 1968 1974 1972 1971 1973 1967 1975 1976 1969 1978 1980 1977 1979 1981 1982  } 
	ownedprovinces     = {  1966 1965 1970 1974 1973 1981 1982 1969 } 
	controlledprovinces  = { 1970 1974 1973 1969  } 

    dormant_teams = {
		170016 #Álvaro Obregón
		170020 #Emiliano Zapata
		170021 #Pancho Villa
		170025 #Alberto Salinas Carranza
	}
	dormant_ministers = { 
		#Constitucionalistas
		170200 #Venustiano Carranza
		170201 #Adolfo de la Huerta
		170202 #Álvaro Obregón
		170203 #Plutarco Elías Calles
		170204 #Venustiano Carranza
		170205 #Adolfo de la Huerta
		170206 #Álvaro Obregón
		170207 #Plutarco Elías Calles
		170208 #Francisco Escudero
		170209 #Isidro Fabela Alfaro
		170210 #Jesús Acuña
		170211 #Cándido Aguilar
		170212 #Alfonso Siller
		170213 #Ernesto Garza Pérez
		170214 #Salvador Diego Fernández
		170215 #Hilario Medina
		170216 #Juan Sánchez Azcona
		170217 #Miguel Covarrubias Acosta
		170218 #Cutberto Hidalgo
		170219 #Alberto José Pani
		170220 #Aarón Sáenz
		170221 #Francisco Escudero
		170222 #Pastor Rouaix
		170223 #Alberto José Pani
		170224 #Plutarco Elías Calles
		170225 #Jacinto Blas Treviño
		170226 #Rafael Zubarán Capmany
		170227 #Miguel Alessio Robles
		170228 #Manuel Pérez Treviño
		170229 #Luis Napoleón Morones
		170230 #Rafael Zubarán Capmany
		170231 #Adolfo de la Huerta
		170232 #Manuel Aguirre Berlanga
		170233 #Gilberto Valenzuela
		170234 # José Inocente Lugo
		170235 #Plutarco Elías Calles
		170236 #Enrique Colunga
		170237 #Romeo Ortega
		170239 #Eduardo Hay
		170240 #Jacinto Blas Treviño
		170241 #Ignacio L. Pesqueira
		170242 #Álvaro Obregón
		170243 #Jesús Agustín Castro
		170244 #Juan José Ríos
		170245 #Francisco L. Urquizo
		170246 #Plutarco Elías Calles
		170247 #Benjamín Hill
		170248 #Enrique Estrada Reynoso
		170249 #Francisco Roque Serrano
		170250 #Joaquín Amaro Domínguez
		170252 #Eduardo Hay
		170253 #Jacinto Blas Treviño
		170254 #Ignacio L. Pesqueira
		170255 #Álvaro Obregón
		170256 #Jesús Agustín Castro
		170257 #Juan José Ríos
		170258 #Francisco L. Urquizo
		170259 #Plutarco Elías Calles
		170260 #Benjamín Hill
		170261 #Enrique Estrada Reynoso
		170262 #Francisco Roque Serrano
		170263 #Joaquín Amaro Domínguez
		170265 #Eduardo Hay
		170266 #Jacinto Blas Treviño
		170267 #Ignacio L. Pesqueira
		170268 #Álvaro Obregón
		170269 #Jesús Agustín Castro
		170270 #Juan José Ríos
		170271 #Francisco L. Urquizo
		170272 #Plutarco Elías Calles
		170273 #Benjamín Hill
		170274 #Enrique Estrada Reynoso
		170275 #Francisco Roque Serrano
		170276 #Joaquín Amaro Domínguez
		#Villistas / Zapatistas
		170150 #Francisco Lagos Cházaro
		170151 #Eulalio Gutiérrez Ortiz
		170152 #Francisco 'Pancho' Villa
		170153 #Emiliano Zapata
		170154 #Francisco Lagos Cházaro
		170155 #Eulalio Gutiérrez Ortiz
		170156 #Francisco 'Pancho' Villa
		170157 #Emiliano Zapata
		170158 #José Ortiz Rodriguez
		170159 #Miguel Díaz Lombardo
		170160 #Ignacio Borrego
		170161 #Francisco Lagos Cházaro
		170162 #Alberto B. Piña
		170163 #Julio Ramírez Wiella
		170164 #Francisco Escudero
		170165 #Valentín Gama y Cruz
		170166 #Luis Zubiría y Campa
		170167 #Adolfo Francisco Salinas
		170168 #Santiago González Cordero
		170169 #José Lucio Blanco Fuentes
		170170 #Francisco Lagos Cházaro
		170171 #José Quevedo
		170172 #José Isabel Robles
		170173 #Francisco 'Pancho' Villa
		170174 #Francisco Pacheco
		170175 #Alfredo Serratos Amador
		170176 #Emiliano Zapata
		170177 #Francisco Pacheco
		170178 #Alfredo Serratos Amador
		170179 #José Isabel Robles
		170180 #Francisco Pacheco
		170181 #Alfredo Serratos Amador
		170182 #Pedro Caloca Larios
		170183 #Emiliano Zapata
		170184 #José Isabel Robles
	}
	dormant_leaders = { 
		#Constitucionalistas
		170330 #Acosta
		170331 #Aguilar
		170332 #Aguirre
		170333 #Aguirre Escobar
		170334 #Aguirre Santiago
		170335 #Albañez
		170336 #Alemán González
		170337 #Alessio Robles
		170338 #Alvarado
		170339 #Álvarez
		170340 #Álvarez Rábago
		170341 #Amaro Domínguez
		170342 #Arévalo Vera
		170343 #Arrieta León, D.
		170344 #Arrieta León, E.
		170345 #Azuara 
		170346 #Baca Calderón
		170347 #Beltrán
		170348 #Blanco Fuentes
		170349 #Caballero
		170350 #Cabral
		170351 #Calderon
		170352 #Calles
		170353 #Camacho
		170354 #Cárdenas Zepeda
		170355 #Carranza, J.
		170356 #Carranza, V.
		170357 #Carrasco
		170358 #Castrejón
		170359 #Castro
		170360 #Coss
		170361 #Cossio Robelo
		170362 #Cruz
		170363 #Dávila Aguirre
		170364 #Díaz de León
		170365 #Diéguez
		170366 #Domínguez Suárez
		170367 #Durazo
		170368 #Estrada
		170369 #Flores
		170370 #García Alvarado
		170371 #García Robles
		170372 #García, G.
		170373 #García, M.
		170374 #Garfias Espinosa
		170375 #González
		170376 #González Garza
		170377 #González Peña
		170378 #Greene Ramírez
		170379 #Guajardo
		170380 #Hay
		170381 #Herrera
		170382 #Herrera Cano
		170383 #Herrero Hernández
		170384 #Hill
		170385 #Huerta, A. de la
		170386 #Kloss
		170387 #Lárraga Orta
		170388 #Leyva
		170389 #Maciel
		170390 #MacKinney
		170391 #Maycotte
		170392 #Montes Alanis
		170393 #Múgica Velázquez
		170394 #Murguía López de Lara
		170395 #Natera García
		170396 #Obregón
		170397 #Pesqueira
		170398 #Piña
		170399 #Ríos
		170400 #Treviño
		170401 #Vidal
		170402 #Villarreal González
		170403 #Malpica
		170404 #Carranza, A.S.
		170405 #Salinas Carmiña
		170406 #Cardenas
		170407 #Cota
		#Villistas
		170150 #Aguirre Benavides
		170151 #Álvarez Borboa
		170152 #Ángeles
		170153 #Arroyo
		170154 #Ávila
		170155 #Baca
		170156 #Barraza
		170157 #Bañuelos
		170158 #Beltrán
		170159 #Buelna
		170160 #Calzada
		170161 #Caloca Larios, P.
		170162 #Caloca
		170163 #Caloca Larios, M.
		170164 #Cantú
		170165 #Carranza Sainz
		170166 #Carrera Torres, A.
		170167 #Carrera Torres, F.
		170168 #Casas
		170169 #Casso López
		170170 #Castro
		170171 #Cedillo, C.
		170172 #Cedillo, M.
		170173 #Cedillo, S.
		170174 #Ceniceros
		170175 #Cervantes, C.
		170176 #Cervantes, F.
		170177 #Chao
		170178 #Contreras
		170179 #Corral, A.
		170180 #Corral, J.
		170181 #Delgado
		170182 #Dozal
		170183 #Echeverría
		170184 #Escárcega
		170185 #Espada
		170186 #Fernández
		170187 #Fierro
		170188 #Fraire
		170189 #Fuentes
		170190 #García Chávez
		170191 #Garay, A.
		170192 #Garay, N.
		170193 #González
		170194 #González Garza
		170195 #Granados
		170196 #Gutiérrez Ortiz, E.
		170197 #Gutiérrez Ortiz, L.
		170198 #Gutiérrez
		170199 #Hernández, P.
		170200 #Hernández, R.
		170201 #Herrera Cano
		170202 #Herrera
		170203 #Hernández
		170204 #Licon
		170205 #López, E.
		170206 #López, M.
		170707 #López Aguirre, P.
		170208 #López Aguirre, M.
		170209 #Luján
		170210 #Montalvo
		170211 #Mendoza
		170212 #Méndez
		170213 #Meléndez
		170214 #Madinabeitia
		170215 #Medina, Julián
		170216 #Medina, Juan
		170217 #Maytorena
		170218 #Matus
		170219 #Martín del Campo
		170220 #Márquez
		170221 #Marín Loya
		170222 #Mapula
		170223 #Madero
		170224 #Ortiz, E.
		170225 #Ornelas Galindo
		170226 #Ortega, M.
		170227 #Ortega, P.
		170228 #Ortega Ramírez
		170229 #Ortiz, J.
		170230 #Ortiz, T.
		170231 #Ortiz Rojas
		170232 #Páez
		170233 #Pereyra
		170234 #Pérez
		170235 #Priego
		170236 #Prieto
		170237 #Quevedo Moreno
		170238 #Quevedo
		170239 #Quiñones
		170240 #Reyes
		170241 #Ríos
		170242 #Robles
		170243 #Rodríguez, J.
		170244 #Rodríguez Carrasco
		170245 #Rodríguez, T.
		170246 #Rosa
		170247 #Ruiz
		170248 #Saavedra
		170249 #Sánchez
		170250 #Sarabia
		170251 #Serratos
		170252 #Servín
		170253 #Silva
		170254 #Solís
		170255 #Soto
		170256 #Silva
		170257 #Urbina
		170258 #Valdivieso;
		170259 #Vargas, C.;
		170260 #Vargas, J.
		170261 #Velásquez
		170262 #Villa, F.
		170263 #Villa, H.
		170264 #Zamora
		170265 #Barlow
		170266 #Parsons	
		#Zapatistas
		170270 #Galindo S.
		170271 #Saavedra Brito
		170272 #Galán S.
		170273 #Sanchez Flores M.
		170274 #Serna C.
		170275 #Silva M.
		170276 #Vazquez Herrera L.
		170277 #Ortiz Vazquez G.
		170278 #Vergara C.S.
		170279 #Rangel M.
		170280 #Mendoza Palma F.
		170281 #Rodriguez M.
		170282 #Rodríguez J.
		170283 #Robles Avila A.
		170284 #Salgado J. H. 
		170285 #Reyes Nava V.
		170286 #Reyes Nava M.
		170287 #Castillo H.
		170288 #Díaz Encarnación
		170289 #Reynoso Díaz L.
		170290 #Ocampo C.
		170291 #Ortega Mendoza Z.
		170292 #V. Pacheco F.
		170293 #Pantaleón García E.
		170294 #Palma J.
		170295 #Pazuengo M.
		170296 #Pliego F.
		170297 #Navarro García J.
		170298 #Caamaño J.
		170299 #Flores D.
		170300 #Farfán Campos C.
		170301 #Cherizola T.
		170302 #Chávez Carrera C.
		170303 #Carnalla Sanchéz C.
		170304 #Cásares A.
		170305 #Casas Medina P.
		170306 #Castrejón A.
		170307 #Cazales P.
		170308 #Barrios Á.
		170309 #Bastida Flores I.
		170310 #Ayaquica Rangel F.
		170311 #Magaña Cerda O.
		170312 #Martínez Carona M.
		170313 #Mejía M.
		170314 #Mariaca G.
		170315 #Palafox M.
		170316 #Burgos S.
		170317 #Zapata Emiliano
		170318 #Robles Morales S.M.
		170319 #Sanchez T.
		170320 #Diaz Soto y Gama A.
		170321 #Neri Jiménez
		170322 #Montaño
		170323 #de la O
		170324 #Palafox M.
		170325 #Salazar
		170326 #Zapata Eufemio
	}
  # Semi-Major Tech '14 
  # Group D 1914 techs 
  # ###################### 
  # GW fighter 
   techapps               = { 
	#Early Infantry Division  
	1010  1020   
	#Early Mountain Division 
	1160  1170   
	#Great War Cavalry Division  
	13060    
	#Basic Armoured Car  

	#Great War Heavy Field Artillery 
	2290  
	#Early Static Anti-Air Artillery 

	#Basic Anti-Air Artillery Brigade 

	#Interwar Fighter  

	#Modern Agriculture  
	5700
	#Improved Construction Engineering 

	#Basic Oil Refining 

	#Naval Infantry

	#Engineers
	1830  
	#Landdoctrine ww1 - rest
	6500 6510 6530 
	#Air Doctrines - ww1 techs
	#Naval Doctrines
	8010 8020 8050 8100

	#Troopships
	3810
} 
  diplomacy = 
  {  relation = {  tag = ENG value = 50  } 
   relation = {  tag = HOL value = 25  } 
   relation = {  tag = USA value = 75  } 
   relation = {  tag = U57 value = -200  }
   relation = {  tag = U58 value = -200  }
   relation = {  tag = U59 value = -200  }   
   relation = {  tag = U08 value = 50  } 
   relation = {  tag = U09 value = -15  } 
   relation = {  tag = GUA value = -15  } 
   } 
  SpyInfo        = {  country = "MEX" NumberOfSpies = 5  } 
  # Firepower   
landunit = { 
        id = { type = 24000 id = 1 } 
        name   = "Ejercito de Mexico" 
        location = 1973
        division = { 
            id = { type = 24000 id = 2 } 
            name   = "I División de Infantería"
            type = infantry
			strength = 50
			morale = 20
			experience = 30
			model = 2 
        	}		
	}   
   
landunit = { 
        id = { type = 24000 id = 3 } 
        name   = "I Cuerpo del Ejército"
        location = 1973
        division = { 
            id = { type = 24000 id = 4 } 
            name   = "II División de Infantería"
            type = infantry
			strength = 50
			morale = 20
			experience = 30
			model = 2 
        	}		
	}   
	
landunit = { 
        id = { type = 24000 id = 5 } 
        name   = "II Cuerpo del Ejército"
        location = 1974
        division = { 
            id = { type = 24000 id = 6 } 
            name   = "III División de Infantería" 
            type = infantry
			experience = 30
			model = 2 
        	}		
	}   
   
landunit = { 
        id = { type = 24000 id = 7 } 
        name   = "Milicia de Mexico"
        location = 1974
        division = { 
            id = { type = 24000 id = 8 } 
            name = "Guardia Rural" 
            type = militia
			experience = 30
			model = 2 
        	}		
	}    
   
   navalunit = {   
   id = {  type = 29500 id = 9  } 
   name = "Armada de Mexico" 
   location = 1970 
   base = 1970 
   division = { id = { type = 29500 id = 10 } name = "Zaragosa" type = light_cruiser model = 0 } 
 
    } 

  } 
 
