country = {
    tag = U05
    
    puppet = HOL
    control = HOL
 ai             = "U05_1914.ai"
		
	capital = 1647
	manpower = 20

	# Resource Reserves
	energy	=	1000   
	metal	= 1000		
	rare_materials =	500	
	oil =	500	
	supplies =	500
	money	=	40

   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
   democratic    = 10 
   political_left  = 4 
   free_market    = 9 
   freedom      = 9 
   professional_army = 5 
   defense_lobby     = 2 
   interventionism  = 2 
    } 

	transports = 150
	escorts = 21
	
    ownedprovinces =      
{
	### Sumatra
	1639 #Bangka=>Bangka Island 
	1642 #Medan
	1640 #Koeta-Radja=>Medan(split)
	1635 #Djambi=>Dumai
	1634 #Pakan Baharoe=>Dumai(split) 
	1637 #Padang 
	1636 #Palembang 
	1641 #Oosthaven
	1638 #Bengkulu=>Oosthaven(split) 	

	### Java
	1647 #Batavia
	1648 #Tjilegon
	1646 #Tjilatjap
	1651 #Bandoeng=>Tjilatjap(split)
	1650 #Semarang
	1649 #Tjirebon=>Semarang
	1654 #Jogjakarta 
	1653 #Soerabaja
	1652 #Rembang=>Soerabaja(split) 
	1655 #Malang 
	1656 #Madura 

	### Flores
	1643 #Bali
	1645 #Waingapoe=>Sumba
	1615 #Flores
	1616 #Koepang=>West Timor
	1619 #Yamdena=>Flores(split)
	1644 #Sumbawa

	### Molukken
	1657 #Makassar 
	1658 #Kendari
	1660 #Paloe 
	1659 #Manado=>Menado
	1620 #Halmahera
	1621 #Buru
	1622 #Ceram

	### Neu Guinea
	1599 #Manoekwari=>Sorong
	1600 #Fak-Fak=>Babo
	1595 #Ansoes=>Arare
	1601 #Wakia=>Kokonau
	1618 #Aru=>Biak Islands
	1598 #Birab=>Agats
	1597 #Merauke
	1596 #Hollandia
	1594 #Wamena=>Sarmi

	### Borneo
	1633 #Bandjarmasin 
	1631 #Poentianak
	1628 #Bakon=>Semitau 
	1623 #Longmerah=>Mahakam 
	1627 #Tarakan/Samarinda
	1632 #Balikpapan 
	1629 #Singkawang=>Poentianak(split)
	1630 #Sampit=>Poentianak(split)

}
    controlledprovinces = 
{
	### Sumatra
	1639 #Bangka=>Bangka Island 
	1642 #Medan
	1640 #Koeta-Radja=>Medan(split)
	1635 #Djambi=>Dumai
	1634 #Pakan Baharoe=>Dumai(split) 
	1637 #Padang 
	1636 #Palembang 
	1641 #Oosthaven
	1638 #Bengkulu=>Oosthaven(split) 	

	### Java
	1647 #Batavia
	1648 #Tjilegon
	1646 #Tjilatjap
	1651 #Bandoeng=>Tjilatjap(split)
	1650 #Semarang
	1649 #Tjirebon=>Semarang
	1654 #Jogjakarta 
	1653 #Soerabaja
	1652 #Rembang=>Soerabaja(split) 
	1655 #Malang 
	1656 #Madura 

	### Flores
	1643 #Bali
	1645 #Waingapoe=>Sumba
	1615 #Flores
	1616 #Koepang=>West Timor
	1619 #Yamdena=>Flores(split)
	1644 #Sumbawa

	### Molukken
	1657 #Makassar 
	1658 #Kendari
	1660 #Paloe 
	1659 #Manado=>Menado
	1620 #Halmahera
	1621 #Buru
	1622 #Ceram

	### Neu Guinea
	1599 #Manoekwari=>Sorong
	1600 #Fak-Fak=>Babo
	1595 #Ansoes=>Arare
	1601 #Wakia=>Kokonau
	1618 #Aru=>Biak Islands
	1598 #Birab=>Agats
	1597 #Merauke
	1596 #Hollandia
	1594 #Wamena=>Sarmi

	### Borneo
	1633 #Bandjarmasin 
	1631 #Poentianak
	1628 #Bakon=>Semitau 
	1623 #Longmerah=>Mahakam 
	1627 #Tarakan/Samarinda
	1632 #Balikpapan 
	1629 #Singkawang=>Poentianak(split)
	1630 #Sampit=>Poentianak(split)
}
    nationalprovinces =   
{
	### Sumatra
	1639 #Bangka=>Bangka Island 
	1642 #Medan
	1640 #Koeta-Radja=>Medan(split)
	1635 #Djambi=>Dumai
	1634 #Pakan Baharoe=>Dumai(split) 
	1637 #Padang 
	1636 #Palembang 
	1641 #Oosthaven
	1638 #Bengkulu=>Oosthaven(split) 	

	### Java
	1647 #Batavia
	1648 #Tjilegon
	1646 #Tjilatjap
	1651 #Bandoeng=>Tjilatjap(split)
	1650 #Semarang
	1649 #Tjirebon=>Semarang
	1654 #Jogjakarta 
	1653 #Soerabaja
	1652 #Rembang=>Soerabaja(split) 
	1655 #Malang 
	1656 #Madura 

	### Flores
	1643 #Bali
	1645 #Waingapoe=>Sumba
	1615 #Flores
	1616 #Koepang=>West Timor
	1619 #Yamdena=>Flores(split)
	1644 #Sumbawa

	### Molukken
	1657 #Makassar 
	1658 #Kendari
	1660 #Paloe 
	1659 #Manado=>Menado
	1620 #Halmahera
	1621 #Buru
	1622 #Ceram

	### Neu Guinea
	1599 #Manoekwari=>Sorong
	1600 #Fak-Fak=>Babo
	1595 #Ansoes=>Arare
	1601 #Wakia=>Kokonau
	1618 #Aru=>Biak Islands
	1598 #Birab=>Agats
	1597 #Merauke
	1596 #Hollandia
	1594 #Wamena=>Sarmi

	### Borneo
	1633 #Bandjarmasin 
	1631 #Poentianak
	1628 #Bakon=>Semitau 
	1623 #Longmerah=>Mahakam 
	1627 #Tarakan/Samarinda
	1632 #Balikpapan 
	1629 #Singkawang=>Poentianak(split)
	1630 #Sampit=>Poentianak(split)
}

  diplomacy = 
  {  relation = {  tag = BEL value = 125  } 
   relation = {  tag = CAN value = 25  } 
   relation = {  tag = DEN value = 100  } 
   relation = {  tag = ENG value = 75  } 
   relation = {  tag = FRA value = 50  } 
   relation = {  tag = U08 value = 50  } 
   relation = {  tag = ITA value = 20  } 
   relation = {  tag = JAP value = 25  } 
   relation = {  tag = LUX value = 150  } 
   relation = {  tag = MEX value = 25  } 
   relation = {  tag = NOR value = 100  } 
   relation = {  tag = SWE value = 100  } 
   relation = {  tag = USA value = 70  } 
   } 
  SpyInfo                = { country = "U05" NumberOfSpies = 4 }


  # Semi-Major Tech '14 
  # Group C 1914 techs 
  # ###################### 
   techapps               = { 
	#Early Fighter  

	#Interwar Bomber 

	#Multirole fighter

	#ww1 strategic bomber

	#ww1 navalbomber

	#Naval Infantry

	#Engineers
	1830
	#Basic Armoured Car  

	#Great War Heavy Field Artillery 
	2290  
	#Early Static Anti-Air Artillery

	#Basic Anti-Air Artillery Brigade 

	#Early Infantry Division
	1010  1020 1030
	#1930 Cavalry Division
	13060 13070 13080
	#Early Mountain Division


	#Mechanized Agriculture 
	5700
	#Improved Construction Engineering 

	#Basic Oil Refining 
	5190
	#Faculty of Atomic Research 
	#Medicine
	5600
	#Improved Destroyer 
	3010 3020 3030
	#Interwar Light Cruiser 
	3110 3120
	#Improved Heavy Cruiser 
	3210 3220 
	#Interwar Battlecruiser 
	3310 3320
	#Great War Battleship 
	3410 3420  
	#Med Range Submarine 
	3610 3620
	#ASW 18

	#Troopships
	3810

	#Landdoctrine ww1 - rest
	6500 6510   
	#Air Doctrines - ww1 techs

	#Naval Doctrines
	8010 8020 8040 8050 8060 8070 8080 8100 8110 8120 8150 8500 8900
	#Great War Hospital System 
	14000
} 

  landunit = 
  {  id    = {  type = 18500 id = 13  } 
   location = 1648 
   name   = "Koninklijk Nederlands Indisch Leger" 
   Division = 
   {  id  = {  type = 18500 id = 14  } 
    name = "Ie Divisie 'Java'" 
    type = militia 
	model = 0
	experience = 0
    } 
   } 
navalunit = { 
        id = { type = 18500 id = 510 } 
        name = "East Indies Squadron" 

        location = 1653 
        base = 1653 
 
        division = { id = { type = 18500 id = 511 } name = "Koningin Regentes" type = heavy_cruiser model = 1 } 
        division = { id = { type = 18500 id = 512 } name = "De Ruyter" type = heavy_cruiser model = 1 } 
        division = { id = { type = 18500 id = 513 } name = "Hertog Hendrik" type = heavy_cruiser model = 1 } 
        division = { id = { type = 18500 id = 514 } name = "3e Flotilla" type = destroyer model = 1 } 
        division = { id = { type = 18500 id = 515 } name = "5e Flotilla" type = transport model = 0 } 
    	} 
}
