 
 ############################## 
 # Country definition for U51 # 
 ############################## 
  
 country = 
 {   tag          = U51 
  manpower        = 5 
  # Resource Reserves 
energy                 = 180
metal                  = 90
rare_materials         = 45
  oil          = 200 
  supplies        = 200 
  money         = 10 
  capital        = 1038
  policy = 
  {   date       = {   year = 0 month = january day = 0   } 
   democratic    = 3 
   political_left  = 4 
   free_market    = 8 
   freedom      = 9 
   professional_army = 2 
   defense_lobby     = 5 
   interventionism  = 1 
    } 
	peacetime_ic_mod       = 1 
    wartime_ic_mod       = 1

   headofstate            = {  type = 9 id = 1070001  } # Abdullah bin Jassim Al Thani
   headofgovernment       = {  type = 9 id = 1070002  } # Abdullah bin Jassim Al Thani 
   foreignminister        = {  type = 9 id = 1070003  } # Abdullah bin Jassim Al Thani 
   armamentminister       = {  type = 9 id = 1070004  } # Abdullah bin Jassim Al Thani 
   ministerofsecurity     = {  type = 9 id = 1070005  } # Abdullah bin Jassim Al Thani 
   ministerofintelligence = {  type = 9 id = 1070006  } # Abdullah bin Jassim Al Thani
   chiefofstaff           = {  type = 9 id = 1070007  } # Abdullah bin Jassim Al Thani 
   chiefofarmy            = {  type = 9 id = 1070008  } # Abdullah bin Jassim Al Thani 
   #chiefofnavy            = {  type = 9 id = ###  } # ? 
   #chiefofair             = {  type = 9 id = ###  } # ?
	
	
  nationalprovinces   = {   1038  } 
  ownedprovinces     = {   1038  } 
  controlledprovinces  = {   1038  } 
  # ROTW Minor Tech '14 
  # Group E 1914 techs 
  # ###################### 
  # GW fighter 
   techapps               = {  
	#Interwar Fighter  

	#Interwar Armoured Car  

	#Light Field Artillery  

	#Early Infantry Division
	1010  1020 
	#1930 Cavalry Division
	13060 
	#Early Mountain Division
	1160  
	#Early Agriculture
	#Landdoctrine ww1 - rest
	6500 6510   
	#Air Doctrines - ww1 techs
	#Engineers
  } 
  diplomacy = 
  {  
    } 
  SpyInfo        = {   country = "U51" NumberOfSpies = 1   } 
 # landunit = 

   } 
 