 country = { 
  tag       	 = REB
  
  nationalprovinces    = {  } 
  ownedprovinces       = {  } 
  controlledprovinces  = { 1981 1982 1965 1966 } 
  capital	= 1981
  
landunit = { 
        id = { type = 24100 id = 1 } 
        location = 1965 #Tuxtla Gutierrez
        division = { 
            id = { type = 24100 id = 2 } 
            #name =
            type = militia
			model = 0 
			strength = 5
			locked = yes
        	} 
	}			 
landunit = { 
        id = { type = 24100 id = 3 } 
        location = 1966 #Merida
        division = { 
            id = { type = 24100 id = 4 } 
            #name =
            type = militia
			model = 0 
			strength = 5
			locked = yes
        	} 
	}			
landunit = { 
        id = { type = 24100 id = 5 } 
        location = 1981 #Tijuana
        division = { 
            id = { type = 24100 id = 6 } 
            #name =
            type = militia
			model = 0 
			strength = 5
			locked = yes
        	} 
	}			
landunit = { 
        id = { type = 24100 id = 7 } 
        location = 1982 #Guadalajara
        division = { 
            id = { type = 24100 id = 8 } 
            #name =
            type = militia
			model = 0 
			strength = 5
			locked = yes
        	} 
	}			
} 
 