############################## 
 # Country definition for U53 # 
 ############################## 
  
 country = 
 {   tag          = U53 
  puppet 		  = ENG
  manpower        = 5 
  # Resource Reserves 
energy                 = 180
metal                  = 90
rare_materials         = 45
  oil          = 200 
  supplies        = 200 
  money         = 10 
  capital        = 1039 
  policy = 
  {   date       = {   year = 0 month = january day = 0   } 
   democratic    = 3 
   political_left  = 4 
   free_market    = 8 
   freedom      = 9 
   professional_army = 2 
   defense_lobby     = 1 
   interventionism  = 1 
    } 
	peacetime_ic_mod       = 1 
    wartime_ic_mod       = 1	
	
   headofstate            = {  type = 9 id = 1080001  } # Hamdan bin Zayed bin Khalifa Al Nahyan
   headofgovernment       = {  type = 9 id = 1080002  } # Hamdan bin Zayed bin Khalifa Al Nahyan
   foreignminister        = {  type = 9 id = 1080003  } # Hamdan bin Zayed bin Khalifa Al Nahyan
   armamentminister       = {  type = 9 id = 1080004  } # Hamdan bin Zayed bin Khalifa Al Nahyan
   ministerofsecurity     = {  type = 9 id = 1080005  } # Hamdan bin Zayed bin Khalifa Al Nahyan
   ministerofintelligence = {  type = 9 id = 1080006  } # Hamdan bin Zayed bin Khalifa Al Nahyan
   chiefofstaff           = {  type = 9 id = 1080013  } # Percy Zachariah Cox
   chiefofarmy            = {  type = 9 id = 1080014  } # Percy Zachariah Cox
   chiefofnavy            = {  type = 9 id = 1080015  } # Percy Zachariah Cox
   #chiefofair             = {  type = 9 id = ###  } # ?
	
  nationalprovinces   = {   1039  1043 } 
  ownedprovinces     = {   1039 } 
  controlledprovinces  = {   1039  } 
  # ROTW Minor Tech '14 
  # Group E 1914 techs 
  # ###################### 
  # GW fighter 
   techapps               = {  
	#Interwar Fighter  

	#Interwar Armoured Car  

	#Light Field Artillery  

	#Early Infantry Division
	1010  1020 
	#1930 Cavalry Division
	13060 
	#Early Mountain Division
	1160  
	#Early Agriculture
	#Landdoctrine ww1 - rest
	6500 6510   
	#Air Doctrines - ww1 techs
	#Engineers
  } 
  diplomacy = 
  {  
    } 
  SpyInfo        = {   country = "U53" NumberOfSpies = 1   } 
 # landunit = 

   } 