 
 ############################## 
 # Country definition for ENG # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
 
 country = 
 {  tag          = ENG 
  ai           = "ENG_1914.ai" 
  capital        = 29 
   
  manpower        = 50 
  # Resource Reserves 
energy                 = 9060
metal                  = 4530
rare_materials         = 2265
  oil          = 500 
  supplies        = 500 
  money         = 70 
  transports       = 1000 
  escorts        = 150 
  diplomacy = 
  {  relation = 
   {  tag    = AFG 
    value   = 150
    guaranteed = {  day = 1 month = june year = 1914  } 
    } 
   relation = {  tag = ARG value = 75  } 
   relation = {  tag = AST value = 200 access = yes }
   relation = {  tag = BEL value = 150 guaranteed = {  day = 1 month = june year = 1914  }  } 
   relation = {  tag = BHU value = 200 access = yes } 
   relation = {  tag = BUL value = -20  } 
   relation = {  tag = CAN value = 200 access = yes }
   relation = {  tag = CUB value = 30  } 
   relation = 
   {  tag    = DEN 
    value   = 100 
    guaranteed = {  day = 1 month = june year = 1914  }
    } 
   relation = {  tag = ETH value = 50  } 
   relation = {  tag = FRA value = 150  } 
   relation = {  tag = U08 value = 1  } 
   relation = 
   {  tag    = GRE 
    value   = 50 
    guaranteed = {  day = 1 month = june year = 1914  } 
    } 
   relation = {  tag = GUA value = 50  } 
   relation = {  tag = HOL value = 125  } 
   relation = {  tag = HON value = 50  } 
   relation = {  tag = ITA value = -50  } 
   relation = {  tag = JAP value = 25  } 
   relation = {  tag = MEX value = 50  } 
   relation = {  tag = U69 value = -50  } 
   relation = {  tag = NEP value = 200 access = yes  } 
   relation = 
   {  tag    = NOR 
    value   = 90 
    guaranteed = {  day = 1 month = june year = 1914  }
    } 
   relation = {  tag = NZL value = 200 access = yes }
   relation = 
   {  tag    = OMN 
    value   = 150 
    access   = yes 
    guaranteed = {  day = 1 month = june year = 1914  } 
    } 
   relation = {  tag    = OTT value   = -75 } 
   relation = 
   {  tag    = PER 
    value   = 25 
    guaranteed = {  day = 1 month = june year = 1914  } 
    } 
   relation = 
   {  tag    = POR 
    value   = 100 
    guaranteed = {  day = 1 month = june year = 1914  } 
    } 
   relation = {  tag = ROM value = 50  } 
   relation = {  tag = SAF value = 200 access = yes }
   relation = 
   {  tag    = SAU 
    value   = 100 
    guaranteed = {  day = 1 month = june year = 1914  } 
    } 
   relation = 
   {  tag    = SCH 
    value   = 50 
    guaranteed = {  day = 1 month = june year = 1914  } 
    } 
   relation = {  tag = SIA value = 70  } 
   relation = {  tag = SPA value = -10  } 
   relation = 
   {  tag    = SWE 
    value   = 80 
    guaranteed = {  day = 1 month = june year = 1914  }
    } 
   relation = {  tag = USA value = 150  } 
   relation = {  tag = VEN value = -10  } 
   relation = {  tag = YEM value = 50 } 
   } 
  SpyInfo        = {  country = "ENG" NumberOfSpies = 12  } 
  
  # GREAT BRITAIN 
  nationalprovinces   = {  29 9 5 4 6 7 12 11 10 36 35 13 14 15 18 17 16 24 25 28 
    19 26 27 20 23 22 21  8 
               } 
  # GREAT BRITAIN 
  ownedprovinces     = {  4 796 5 6  7 11 10 13 15 17 18 24 22 28 25 29 26 27 19 20 36 35 429 348 387 388 1773 1760 1772 1774 1753 1754 1755 1771 2086 1757 1770 1763 1764 1769 1758 2045 1998 1997 1782 1766 1759 900 791 786 787 788 792 790 789 778 783 784 799 779 785 780 874 979 964 937 952 956 939 929 940 941 930 931 800 801 793 794 797 795 798 803 804 813 814 805 832 811 812 843 841 842 844 807 810 806 808 809 932 859 860 871 869 870 866 867 861 863 864 997 938 993 896 23 16 9 12 1371 1435 1436 1437 1438 1432 21  1510 1511 1433 1434 1509 1678 1679 1680 1728 1687 1729 1588 1590 1624 1625 1626 1589 1591 1592 1682  1749 1750 1746  1004 1005 998 1611 877 1612 1613 1614 14 8 845 852 
    839 865 862 934 935 954 953 1007 1006 802 781 782 868 1593 
    33 32 31 30 34 1331 838
               } 
  # GREAT BRITAIN 
  controlledprovinces  = {  4 796 5 6 7 11 10 13 15 17 18 24 22 28 25 29 26 27 19 20 36 35 429 348 387 388 1773 1760 1772 1774 1753 1754 1755 1771 2086 1757 1770 1763 1764 1769 1758 2045 1998 1997 1782 1766 1759 900 791 786 787 788 792 790 789 778 783 784 799 779 785 780 874 979 964 937 952 956 939 929 940 941 930 931 800 801 793 794 797 795 798 803 804 813 814 805 832 811 812 843 841 842 844 807 810 806 808 809 932 859 860 871 869 870 866 867 861 863 864 997 938 993 896 23 16 9 12 1371 1435 1436 1437 1438 1432 21  1510 1511 1433 1434 1509 1678 1679 1680 1728 1687 1729 1588 1590 1624 1625 1626 1589 1591 1592 1682  1749 1750 1746   1004 1005 998 1611 877 1612 1613 1614 14 8 845 852 
     839 865 862 934 935 954 953 1007 1006 802 781 782 868 1593 
    33 32 31 30 34 1331 838
               } 
   claimedprovinces = { 
                        348 429 387 388 900 #Gibraltar + Malta + Cyprus + Suez
						1371 #Hong Kong
						
						1432 1433 1434 1435 1436 1437 1438 1624 1625 1626 #Malaysia
						2045 2086 1998 1997 #Falkland Islands + Belize + Guyana
						896 993 1753 1754 1755 1757 1758 1759 1760 1763 1764 1766 1769 1770 1771 1772 1773 1774 1782 #Atlantic Ocean Islands
						929 930 931 932 934 935 937 938 939 940 941 952 953 954 956 964 979 #West African possessions
						803 804 805 806 807 808 809 810 811 812 813 814 832 
						839 841 842 843 844 845 859 860 861 862 863 864 865 866 867 868 869 870 871 874 877 #East African possessions
						997 998 1509 1510 1511 1611 1612 1613 1614 #Indian Ocean Islands
						1588 1589 1590 1591 1592 1593 1678 1679 1680 1682 1687 1728 1729 1746 1749 1750 #Pacific Ocean Islands       
838 # Kismayo  						       
                } 
  # Commonwealth Tech '14 
  # UK 1914 techs 
  # ###################### 
   techapps               = {
	#Infantry Division  
	1010  1020 1030 
	#CAVALRY 
	13060 13070 13080 
	#Mountain Division 
	1160   
	#Naval Infantry
	#Engineers
	1830
	#Logistics 
	1910 1920
	
	#Basic Armoured Car  
	2860
	#Tankette 
	#Great War Heavy Field Artillery 
	2290 
	#Static Anti-Air Artillery 
	#Anti-Air Artillery Brigade
	#Anti-Tank Artillery 

	#Destroyer 
	3010 3020 3030
	#Light Cruiser 
	3110 3120 3130
	#Heavy Cruiser 
	3210 3220 3230
	#Battleship 
	3410 3420 3430 3440
	#Battlecruiser
	3310
	#Submarine 
	3610 3620
	#Light carrier 
	12100
	#Fleet Carrier
	#Troopships
	3810
	#ASW
	#TORPEDOES
	3720 3730
	
	#Interceptors  
	4500
	#Exp.  Bomber 
	4600
	#Multirole fighter
	#Strategic bomber
	#Navalbomber
	#SEAPLANES
	4740
	#CAG
	
	#Census Tabulating Machine 
	5310
	#Medicine
	5600
	#Agriculture 
	5700
	#Construction Engineering 
	5800 5080
	#MANUFACTURING 
	5810
	#Basic Oil Refining 
	#Basic Decimetric Radar Warning Sites
	#Faculty of Atomic Research 

	#Great War Hospital System
	#Landdoctrine ww1 - exp entente eng fra ita USA bel HOL jap 
	6500 6510  6580 6530 
	#Naval Doctrines
	8010 8020 8040 8050 8060 8070 8080 8100 8110 8120 8150 8500 8510
	8900 8910 8920 82500
	#Air Doctrines - ww1 techs
	27480 27490 27500 27510
} 
  policy = 
  {  date       = {  year = 0 month = january day = 0  } 
   democratic    = 8 
   political_left  = 2 
   freedom      = 9 
   free_market    = 10 
   professional_army = 4 
   defense_lobby     = 3 
   interventionism  = 5 
   } 
   
   headofstate            = {  type = 9 id = 10282  } # George V
   headofgovernment       = {  type = 9 id = 10264  } # Herbert Henry Asquith
   foreignminister        = {  type = 9 id = 10250  } # Edward Grey
   armamentminister       = {  type = 9 id = 10291  } # David Lloyd George
   ministerofsecurity     = {  type = 9 id = 10312  } # Reginald McKenna 
   ministerofintelligence = {  type = 9 id = 10274  } # George MacDonogh
   chiefofstaff           = {  type = 9 id = 10243  } # Charles W. H. Douglas
   chiefofarmy            = {  type = 9 id = 10220  } # Charles W. H. Douglas
   chiefofnavy            = {  type = 9 id = 10232  } # Louis Alexander Mountbatten
   chiefofair             = {  type = 9 id = 10211  } # David Henderson
   
	peacetime_ic_mod       = 0.8 
    wartime_ic_mod       = 0.8   
   
  # ## United Kingdom Land OOB ### 

landunit = { 
	id = { type = 27111 id = 1 } 
	name = "Aldershot Command"
	location = 28 
	division = { 
		id = { type = 27111 id = 2 } 
		name = "General Headquarters" 
		strength = 100 
		type = hq
		model = 1
		experience = 15
		} 
	division = { 
		id = { type = 27111 id = 3 } 
		name = "1st Infantry Division" 
		strength = 100 
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 0
		experience = 15
		} 
	division = { 
		id = { type = 27111 id = 4 } 
		name = "2nd Infantry Division" 
		strength = 100 
		type = infantry 
		model = 3
		experience = 10
		} 
	division = { 
		id = { type = 27111 id = 5 } 
		name = "1st Cavalry Division" 
		strength = 100 
		type = cavalry
		model = 3
		experience = 10
		} 
	division = { 
		id = { type = 27111 id = 6 } 
		name = "63rd (Royal Naval) Division" 
		strength = 5
		type = infantry 
		model = 1
		experience = 5
		} 
	} 
landunit = { 
	id = { type = 27111 id = 7 } 
	name = "Eastern Command"
        location = 25 
        division = { 
		id = { type = 27111 id = 8 } 
		name = "4th Infantry Division" 
		strength = 100 
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 0
		experience = 5
		} 
	division = { 
		id = { type = 27111 id = 9 } 
		name = "2nd Cavalry Division" 
		strength = 40
		type = cavalry
		model = 3
		experience = 0
		} 
	division = { 
		id = { type = 27111 id = 10 } 
		name = "43rd (Wessex) Division" 
		strength = 5
		type = infantry 
		model = 2
		experience = 0
		} 
	division = { 
		id = { type = 27111 id = 11 } 
		name = "44th (Home Counties) Division" 
		strength = 5
		type = infantry 
		model = 2
		experience = 0
		} 
	division = { 
		id = { type = 27111 id = 12 } 
		name = "54th (East Anglian) Division" 
		strength = 5
		type = infantry 
		model = 2
		experience = 0
		} 
	} 
landunit = { 
	id = { type = 27111 id = 13 } 
	name = "Irish Command"
        location = 34
        division = { 
		id = { type = 27111 id = 14 } 
		name = "5th Infantry Division" 
		strength = 100 
		type = infantry 
		model = 3
		experience = 5
        	} 
        division = { 
		id = { type = 27111 id = 15 } 
		name = "6th Infantry Division" 
		strength = 100 
		type = infantry 
		model = 3
		experience = 2
        	} 
    	} 
landunit = { 
	id = { type = 27111 id = 16 } 
	name = "London District"
        location = 29
	division = { 
		id = { type = 27111 id = 17 } 
		name = "47th (1/2nd London) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
	division = { 
		id = { type = 27111 id = 18 } 
		name = "56th (1/1st London) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
    	} 
landunit = { 
        id = { type = 27111 id = 19 } 
        name = "Northern Command"
        location = 18
	division = { 
		id = { type = 27111 id = 20 } 
		name = "46th (North Midland) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
	division = { 
		id = { type = 27111 id = 21 } 
		name = "49th (West Riding) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
	division = { 
		id = { type = 27111 id = 22 } 
		name = "50th (Northumbrian) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
	division = { 
		id = { type = 27111 id = 23 } 
		name = "2nd Mounted Division" 
		strength = 5
		type = cavalry
		model = 2
		} 
    	} 
landunit = { 
	id = { type = 27111 id = 24 } 
	name = "Scottish Command"
	location = 12
	division = { 
		id = { type = 27111 id = 25 } 
		name = "51st (Highland) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
	division = { 
		id = { type = 27111 id = 26 } 
		name = "52nd (Lowland) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
    	} 
landunit = { 
	id = { type = 27111 id = 27 } 
	name = "Southern Command"
        location = 27
        division = { 
		id = { type = 27111 id = 28 } 
		name = "3rd Infantry Division" 
		strength = 100 
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 0
		experience = 5
		} 
	division = { 
		id = { type = 27111 id = 29 } 
		name = "48th (South Midland) Division" 
		strength = 5
		type = infantry 
		model = 2
		experience = 0
		} 
	} 
landunit = { 
        id = { type = 27111 id = 30 } 
        name = "Western Command"
        location = 24
	division = { 
		id = { type = 27111 id = 31 } 
		name = "42nd (East Lancashire) Division" 
		strength = 5
		type = infantry 
		model = 2
		experience = 0
		} 
	division = { 
		id = { type = 27111 id = 32 } 
		name = "53rd (Welsh) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
	division = { 
		id = { type = 27111 id = 33 } 
		name = "55th (West Lancashire) Division" 
		strength = 5
		type = infantry 
		model = 2
		} 
	division = { 
		id = { type = 27111 id = 34 } 
		name = "1st Mounted Division" 
		strength = 5
		type = cavalry
		model = 2
		} 
    	} 
landunit = { 
        id = { type = 27111 id = 35 } 
        name = "Aden Force"
        location = 1053
        division = { 
            	id = { type = 27111 id = 36 } 
            	name = "Aden Brigade" 
           	strength = 30
            	type = garrison
		model = 1 
        	} 
    	} 	
landunit = { 
        id = { type = 27111 id = 37 } 
        name = "Bermuda Force"
        location = 1773
        division = { 
            	id = { type = 27111 id = 38 } 
            	name = "Bermuda Garrison" 
           	strength = 10
            	type = garrison
		model = 1 
        	} 
    	} 
landunit = { 
        id = { type = 27111 id = 39 } 
        name = "East Africa Force" 
        location = 841
        division = { 
            	id = { type = 27111 id = 40 } 
            	name = "King's African Rifles" 
            	strength = 80 
            	type = militia
		model = 1 
        	} 
    	} 
landunit = { 
        id = { type = 27111 id = 41 } 
        name = "Gibraltar Force"
        location = 348
        division = { 
            	id = { type = 27111 id = 42 } 
            	name = "Gibraltar Fortress" 
           	strength = 20
            	type = garrison
		model = 1 
        	} 
    	} 
landunit = { 
        id = { type = 27111 id = 143 } 
        name = "Gold Coast Force" 
        location = 956
        division = { 
            	id = { type = 27111 id = 144 } 
            	name = "The Gold Coast Regiment" 
            	strength = 40 

            	type = militia
		model = 0  
        	} 
    	} 
landunit = { 
        id = { type = 27111 id = 145 } 
        name = "Malaya Force" 
        location = 1432
        division = { 
            	id = { type = 27111 id = 146 } 
            	name = "Singapore Fortress" 
            	strength = 10
            	type = garrison
		model = 1 
       		} 
    	} 
landunit = { 
        id = { type = 27111 id = 147 } 
        name = "Malta Force" 
        location = 429
        division = { 
            	id = { type = 27111 id = 148 } 
            	name = "7th Infantry Division" 
            	strength = 40
		
            	type = infantry
		model = 3
        	} 
    	} 
landunit = { 
        id = { type = 27111 id = 49 } 
        name = "Mauritius Force" 
        location = 997
        division = { 
            	id = { type = 27111 id = 50 } 
            	name = "Mauritius Garrison" 
            	strength = 10
		
            	type = garrison
		model = 1
        	} 
    	} 
landunit = { 
        id = { type = 27111 id = 51 } 
        name = "North China Force"
        location = 1331
        division = { 
            	id = { type = 27111 id = 52 } 
            	name = "Wei Hai Wei Garrison" 
            	strength = 20
		
            	type = garrison
		model = 1
        	} 
        division = { 
            	id = { type = 27111 id = 53 } 
            	name = "The Chinese Regiment" 
            	strength = 20
		
            	type = militia
		model = 0
        	} 
    	} 

landunit = { 
        id = { type = 27111 id = 54 } 
        name = "Sierra Leone Force" 
        location = 964
        division = { 
            	id = { type = 27111 id = 55 } 
            	name = "The West African Regiment" 
            	strength = 40
		
            	type = militia
		model = 0 
        	} 
    	}
landunit = { 
        id = { type = 27111 id = 56 } 
        name = "South Africa Force" 
        location = 880
        division = { 
            	id = { type = 27111 id = 57 } 
            	name = "27th Infantry Division" 
            	strength = 30
		max_strength = 100
            	type = infantry 
		model = 3
		experience = 5
        	}  
        division = { 
            	id = { type = 27111 id = 58 } 
            	name = "3rd Cavalry Division" 
            	strength = 30
		max_strength = 100
            	type = cavalry
		model = 3
		experience = 5
        	}  
    	}
landunit = { 
        id = { type = 27111 id = 59 } 
        name = "South China Force"
        location = 1371
        division = { 
            	id = { type = 27111 id = 60 } 
            	name = "Hong Kong Garrison" 
            	strength = 10
		
            	type = garrison
		model = 1
        	} 
    	} 
landunit = { 
        id = { type = 27111 id = 61 } 
        name = "The Force in Egypt" 
        location = 789
        division = { 
            	id = { type = 27111 id = 62 } 
            	name = "8th Infantry Division" 
            	strength = 40
		max_strength = 100
            	type = infantry 
		model = 3
		experience = 10
        	}  
        division = { 
            	id = { type = 27111 id = 63 } 
            	name = "28th Infantry Division" 
            	strength = 25
		max_strength = 100
            	type = infantry 
		model = 3
		experience = 7
        	}  
        division = { 
            	id = { type = 27111 id = 64 } 
            	name = "29th Infantry Division" 
            	strength = 30
		max_strength = 100
            	type = infantry 
		model = 3
		experience = 5
        	}  
    	}
landunit = { 
        id = { type = 27111 id = 65 } 
        name = "West African Frontier Force" 
        location = 929
        division = { 
            	id = { type = 27111 id = 66 } 
            	name = "The Nigeria Regiment" 
            	strength = 100
		
            	type = militia
		model = 0 
        	} 
    	}

airunit = { 
	id = { type = 27111 id = 900 } 
	name = "Royal Flying Corps" 
	location = 29
	base = 29

	division = { 
		id = { type = 27111 id = 901 } 
		name = "1st Group" 
		strength = 10 
		type = tactical_bomber 
		model = 1 
		}
	}

airunit = { 
	id = { type = 27111 id = 902 } 
	name = "Royal Naval Air Service" 
	location = 26
	base = 26

	division = { 
		id = { type = 27111 id = 903 } 
		name = "2nd Group" 
		strength = 10 
		type = tactical_bomber 
		model = 1 
		}
	}


navaldivision = {
	dormant = yes id = { type = 27111 id = 497 } name = "HMS Agincourt" type = battleship model = 3
	}

navaldivision = {
	dormant = yes id = { type = 27111 id = 498 } name = "HMS Erin" type = battleship model = 3
	}

navaldivision = {
	dormant = yes id = { type = 27111 id = 499 } name = "HMS Canada" type = battleship model = 3
	}



navalunit = { 
        id = { type = 27111 id = 500 } 
        name = "Grand Fleet" 
        location = 5 # Scapa Flow 
        base = 5 # Scapa Flow 

	division = { id = { type = 27111 id = 761 } name = "HMS Iron Duke" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 501 } name = "HMS King George V" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 502 } name = "HMS Conqueror" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 503 } name = "HMS Monarch" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 504 } name = "HMS Orion" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 505 } name = "HMS Thunderer" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 506 } name = "HMS Centurion" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 507 } name = "HMS Audacious" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 508 } name = "HMS Ajax" type = battleship model = 3 } 
        division = { id = { type = 27111 id = 509 } name = "HMS Dreadnought" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 510 } name = "HMS Superb" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 511 } name = "HMS Collingwood" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 512 } name = "HMS St Vincent" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 513 } name = "HMS Vanguard" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 514 } name = "HMS Neptune" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 515 } name = "HMS Colossus" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 516 } name = "HMS Hercules" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 517 } name = "HMS Bellerophon" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 518 } name = "HMS Temeraire" type = battleship model = 2 } 
        division = { id = { type = 27111 id = 519 } name = "HMS Africa" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 520 } name = "HMS Britannia" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 521 } name = "HMS Commonwealth" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 522 } name = "HMS Dominion" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 523 } name = "HMS Hibernia" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 524 } name = "HMS Hindustan" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 525 } name = "HMS King Edward VII" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 526 } name = "HMS Zealandia" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 527 } name = "HMS Antrim" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 528 } name = "HMS Argyll" type =  heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 529 } name = "HMS Devonshire" type =  heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 530 } name = "HMS Roxburgh" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 531 } name = "HMS Bellona" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 795 } name = "HMS Boadicea" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 532 } name = "HMS Liverpool" type = light_cruiser model = 2 } 
        division = { id = { type = 27111 id = 533 } name = "HMS Falmouth" type = light_cruiser model = 2 } 
        division = { id = { type = 27111 id = 534 } name = "HMS Blanche" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 535 } name = "HMS Blonde" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 536 } name = "HMS Sapphire" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 537 } name = "HMS Active" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 538 } name = "HMS Fearless" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 539 } name = "HMS Drake" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 540 } name = "HMS Good Hope" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 541 } name = "HMS King Alfred" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 542 } name = "HMS Leviathan" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 543 } name = "HMS Sappho" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 544 } name = "2nd Flotilla (A)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 545 } name = "2nd Flotilla (B)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 546 } name = "4th Flotilla (A)" type = destroyer model = 2 } 	
        division = { id = { type = 27111 id = 547 } name = "4th Flotilla (B)" type = destroyer model = 2 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 548 } 
        name = "Battlecruiser Force" 
        location = 5 # scapa flow
        base = 5 # scapa flow

        division = { id = { type = 27111 id = 549 } name = "HMS Lion" type = battlecruiser model = 0 } 
        division = { id = { type = 27111 id = 550 } name = "HMS Invincible" type = battlecruiser model = 0 } 
        division = { id = { type = 27111 id = 551 } name = "HMS New Zealand" type = battlecruiser model = 0 } 
        division = { id = { type = 27111 id = 552 } name = "HMS Princess Royal" type = battlecruiser model = 0 } 
        division = { id = { type = 27111 id = 553 } name = "HMS Queen Mary" type = battlecruiser model = 1 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 555 } 
        name = "2nd Cruiser Squadron" 
        location = 5 # scapa flow
        base = 5 # scapa flow
 
        division = { id = { type = 27111 id = 556 } name = "HMS Achilles" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 557 } name = "HMS Cochrane" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 558 } name = "HMS Natal" type = heavy_cruiser model = 2 } 
        division = { id = { type = 27111 id = 559 } name = "HMS Shannon" type = heavy_cruiser model = 1 } 
	division = { id = { type = 27111 id = 774 } name = "HMS Birmingham" type = light_cruiser model = 2 }
	}

navalunit = { 
        id = { type = 27111 id = 560 } 
        name = "Channel Fleet" 
        location = 27 # Southampton
        base = 27 # Southampton
 
        division = { id = { type = 27111 id = 561 } name = "HMS Lord Nelson" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 562 } name = "HMS Formidable" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 563 } name = "HMS Irresistible" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 564 } name = "HMS Implacable" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 565 } name = "HMS Bulwark" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 566 } name = "HMS London" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 567 } name = "HMS Venerable" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 568 } name = "HMS Queen" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 569 } name = "HMS Prince of Wales" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 570 } name = "HMS Agamemnon" type = battleship model = 1 } 	
        division = { id = { type = 27111 id = 571 } name = "HMS Albemarle" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 572 } name = "HMS Cornwallis" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 573 } name = "HMS Duncan" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 574 } name = "HMS Exmouth" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 575 } name = "HMS Russell" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 576 } name = "HMS Majestic" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 577 } name = "HMS Albion" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 578 } name = "HMS Canopus" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 579 } name = "HMS Glory" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 580 } name = "HMS Goliath" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 581 } name = "HMS Ocean" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 582 } name = "HMS Vengeance" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 583 } name = "HMS Diamond" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 584 } name = "HMS Topaze" type = light_cruiser  model = 0 } 
        division = { id = { type = 27111 id = 585 } name = "HMS Proserpine" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 797 } name = "HMS Hermione" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 586 } name = "Channel Flotilla" type = destroyer model = 1 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 587 } 
        name = "Harwich Force" 
        location = 27 # Portsmouth 
        base = 27 # Portsmouth 

        division = { id = { type = 27111 id = 588 } name = "HMS Caesar" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 589 } name = "HMS Prince George" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 590 } name = "HMS Jupiter" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 591 } name = "HMS Illustrious" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 592 } name = "HMS Amethyst" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 593 } name = "HMS Amphion" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 594 } name = "HMS St George" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 595 } name = "HMS Dido" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 596 } name = "HMS Hermes" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 598 } name = "1st Flotilla (A)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 599 } name = "1st Flotilla (B)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 600 } name = "3rd Flotilla"type = destroyer model = 1 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 601 } 
        name = "East Coast Force" 
        location = 17 # Sheffield
        base = 17 # Sheffield
 
        division = { id = { type = 27111 id = 602 } name = "HMS Magnificent" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 603 } name = "HMS Mars" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 604 } name = "HMS Victorious" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 605 } name = "HMS Hannibal" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 606 } name = "HMS Skirmisher" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 607 } name = "7th Flotilla (A)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 608 } name = "7th Flotilla (B)" type = destroyer model = 1 }	 
    	}
 
navalunit = { 
        id = { type = 27111 id = 609 } 
        name = "Dover Patrol" 
        location = 26 # Dover
        base = 26 # Dover

        division = { id = { type = 27111 id = 610 } name = "HMS Adventure" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 611 } name = "HMS Attentive" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 612 } name = "HMS Forward" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 613 } name = "HMS Aboukir" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 614 } name = "HMS Hogue" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 615 } name = "HMS Cressy" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 616 } name = "HMS Euryalus" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 617 } name = "HMS Bacchante" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 618 } name = "6th Flotilla (A)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 619 } name = "6th Flotilla (B)" type = destroyer model = 1 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 620 } 
        name = "Forth Patrol" 
        location = 5 # scapa flow
        base = 5 # scapa flow
 
        division = { id = { type = 27111 id = 621 } name = "HMS Pathfinder" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 622 } name = "HMS Patrol" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 623 } name = "HMS Sentinel" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 624 } name = "8th Flotilla (A)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 625 } name = "8th Flotilla (B)" type = destroyer model = 0 } 
        division = { id = { type = 27111 id = 626 } name = "9th Flotilla (A)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 627 } name = "9th Flotilla (B)" type = destroyer model = 1 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 628 } 
        name = "Northern Patrol" 
        location = 17 # Manchester  
        base = 17 # Manchester  

        division = { id = { type = 27111 id = 629 } name = "HMS Foresight" type = light_cruiser model = 1 } 
        division = { id = { type = 27111 id = 630 } name = "HMS Crescent" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 631 } name = "HMS Edgar" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 632 } name = "HMS Grafton" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 633 } name = "HMS Endymion" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 634 } name = "HMS Gibraltar" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 635 } name = "HMS Hawke" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 636 } name = "HMS Royal Arthur" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 637 } name = "HMS Heseus" type = light_cruiser model = 0 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 638 } 
        name = "11th Cruiser Squadron" 
        location = 17 # manchester 
        base= 17 # manchester 
 
	division = { id = { type = 27111 id = 776 } name = "HMS Lowestoft" type = light_cruiser model = 2 } 
        division = { id = { type = 27111 id = 639 } name = "HMS Doris" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 640 } name = "HMS Isis" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 641 } name = "HMS Juno" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 642 } name = "HMS Minerva" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 643 } name = "HMS Venus" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 816 } name = "HMS Theseus" type = light_cruiser model = 0 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 644 } 
        name = "12th Cruiser Squadron" 
        location = 23 # Plymouth
        base = 23 # Plymouth
 
	division = { id = { type = 27111 id = 775 } name = "HMS Nottingham" type = light_cruiser model = 2 }
        division = { id = { type = 27111 id = 645 } name = "HMS Diana" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 646 } name = "HMS Charybdis" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 647 } name = "HMS Eclipse" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 648 } name = "HMS Talbot" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 649 } name = "HMS Pelorus" type = light_cruiser model = 0 } 
  	} 

navalunit = { 
        id = { type = 27111 id = 650 } 
        name = "2nd Flotilla" 
        location = 27 # Southampton
        base = 27 # Southampton
 
        division = { id = { type = 27111 id = 651 } name = "2nd Flotilla" type = submarine model = 0 } 
    	}

navalunit = { 
        id = { type = 27111 id = 652 } 
        name = "4th Flotilla" 
        location = 27 # Portsmouth 
        base = 27 # Portsmouth 

        division = { id = { type = 27111 id = 653 } name = "4th Flotilla" type = submarine model = 1 } 	
    	} 

navalunit = { 
        id = { type = 27111 id = 654 } 
        name = "5th Flotilla" 
        location = 27 # Portsmouth 
        base = 27 # Portsmouth 

        division = { id = { type = 27111 id = 655 } name = "5th Flotilla" type = submarine model = 1 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 656 } 
        name = "6th Flotilla" 
        location = 17 # Sheffield 
        base = 17 # Sheffield 

        division = { id = { type = 27111 id = 657 } name = "6th Flotilla" type = submarine model = 1 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 658 } 
        name = "7th Flotilla" 
        location = 5 # Rosyth
        base = 5 # Rosyth
 
        division = { id = { type = 27111 id = 659 } name = "7th Flotilla" type = submarine model = 1 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 660 } 
        name = "8th Flotilla" 
        location = 17 # Sheffield 
        base = 17 # Sheffield 

        division = { id = { type = 27111 id = 661 } name = "8th Flotilla" type = submarine model = 1 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 662 } 
        name = "10th Flotilla" 
        location = 23 # Plymouth
        base = 23 # Plymouth
 
        division = { id = { type = 27111 id = 663 } name = "10th Flotilla" type = submarine model = 0 } 	
    	}
 
navalunit = { 
        id = { type = 27111 id = 664 } 
        name = "Mediterranean Flotilla" 
        location = 429 # Valetta 
        base = 429 # Valetta 

        division = { id = { type = 27111 id = 665 } name = "Mediterranean Flotilla" type = submarine model = 0 } 
    	}

navalunit = { 
        id = { type = 27111 id = 666 } 
        name = "Mediterranean Fleet" 
        location = 429 # Valetta
        base = 429 # Valetta 
 
        division = { id = { type = 27111 id = 667 } name = "HMS Inflexible" type = battlecruiser model = 0 } 
        division = { id = { type = 27111 id = 668 } name = "HMS Indomitable" type = battlecruiser model = 0 } 
        division = { id = { type = 27111 id = 669 } name = "HMS Indefatigable" type = battlecruiser model = 0 } 
        division = { id = { type = 27111 id = 670 } name = "HMS Black Prince" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 671 } name = "HMS Duke of Edinburgh" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 672 } name = "HMS Warrior" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 673 } name = "HMS Defence" type = heavy_cruiser model = 2 } 
        division = { id = { type = 27111 id = 674 } name = "HMS Gloucester" type = light_cruiser model = 2 } 
        division = { id = { type = 27111 id = 675 } name = "HMS Weymouth" type = light_cruiser model = 2  } 
        division = { id = { type = 27111 id = 676 } name = "HMS Chatham" type = light_cruiser model = 2 } 
        division = { id = { type = 27111 id = 677 } name = "HMS Dublin" type = light_cruiser model = 2 } 
        division = { id = { type = 27111 id = 678 } name = "5th Flotilla (A)" type = destroyer model = 1 } 
        division = { id = { type = 27111 id = 679 } name = "5th Flotilla (B)" type = destroyer model = 2 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 680 } 
        name = "9th Cruiser Squadron" 
        location = 348 # Gibraltar 
        base = 348 # Gibraltar 

        division = { id = { type = 27111 id = 681 } name = "HMS Vindictive" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 682 } name = "HMS Highflyer" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 683 } name = "HMS Challenger" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 684 } name = "HMS Amphitrite" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 685 } name = "HMS Argonaut" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 686 } name = "HMS Europa" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 687 } name = "HMS Sutlej" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 688 } name = "Gibraltar Flotilla" type = destroyer model = 2 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 689 } 
        name = "China Squadron" 
        location = 1371 # Hong Kong 
        base = 1371 # Hong Kong 

        division = { id = { type = 27111 id = 690 } name = "HMS Triumph" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 691 } name = "HMS Hampshire" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 692 } name = "HMS Minotaur" type = heavy_cruiser model = 2 } 
        division = { id = { type = 27111 id = 693 } name = "HMS Newcastle" type = light_cruiser model = 2 } 
        division = { id = { type = 27111 id = 694 } name = "HMS Yarmouth" type = light_cruiser model = 2 } 
	division = { id = { type = 27111 id = 815 } name = "HMS Pyramus" type = light_cruiser model = 0 }
        division = { id = { type = 27111 id = 695 } name = "China Flotilla" type = destroyer model = 3 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 696 } 
        name = "East Indies Squadron" 
        location = 1511 # Colombo
        base = 1511 # Colombo
 
        division = { id = { type = 27111 id = 697 } name = "HMS Swiftsure" type = battleship model = 1 } 
        division = { id = { type = 27111 id = 698 } name = "HMS Dartmouth" type = light_cruiser model = 2 } 
        division = { id = { type = 27111 id = 699 } name = "HMS Fox" type = light_cruiser model = 0 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 700 } 
        name = "N. America & W. Indies Squadron" 
		location = 1773		# Bermudas 
		base = 1773		# Bermudas 

        division = { id = { type = 27111 id = 701 } name = "HMS Berwick" type = heavy_cruiser model = 1 } 	
        division = { id = { type = 27111 id = 702 } name = "HMS Essex" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 704 } name = "HMS Suffolk" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 705 } name = "HMS Bristol" type = light_cruiser model = 2 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 706 } 
        name = "5th Cruiser Squadron" 
        location = 964 # Freetown 
        base = 964 # Freetown 

        division = { id = { type = 27111 id = 707 } name = "HMS Cornwall" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 708 } name = "HMS Cumberland" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 709 } name = "HMS Monmouth" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 813 } name = "HMS Lancaster" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 710 } name = "HMS Carnarvon" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 711 } name = "HMS Donegal" type = heavy_cruiser model = 1 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 712 } 
        name = "S.E. Coast of America Squadron" 
        location = 2045 # Port Stanley
        base = 2045 # Port Stanley
 
        division = { id = { type = 27111 id = 713 } name = "HMS Kent" type = heavy_cruiser model = 1 } 
        division = { id = { type = 27111 id = 714 } name = "HMS Glasgow" type = light_cruiser model = 2 } 
    	} 

navalunit = { 
        id = { type = 27111 id = 715 } 
        name = "Cape Squadron" 
        location = 880 # Cape Town 
		base = 880
		
        division = { id = { type = 27111 id = 716 } name = "HMS Astraea" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 717 } name = "HMS Pegasus" type = light_cruiser model = 0 } 
        division = { id = { type = 27111 id = 718 } name = "HMS Hyacinth" type = light_cruiser model = 0 } 
    	}
 

navalunit = { 
        id = { type = 27111 id = 731 } 
        name = "1st Transport Squadron" 
        location = 1517 # Bombay
        base = 1517 # Bombay
 
        division = { id = { type = 27111 id = 732 } name = "1st Transport Flotilla (A)"type = transport model = 0 } 
        division = { id = { type = 27111 id = 733 } name = "1st Transport Flotilla (B)"type = transport model = 0 } 
        division = { id = { type = 27111 id = 734 } name = "2nd Transport Flotilla (A)"type = transport model = 0 } 
        division = { id = { type = 27111 id = 735 } name = "2nd Transport Flotilla (B)"type = transport model = 0 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 736 } 
        name = "2nd Transport Squadron" 
        location = 27 # Southampton 
        base = 27 # Southampton 

        division = { id = { type = 27111 id = 737 } name = "3rd Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 738 } name = "3rd Transport Flotilla (B)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 739 } name = "4th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 740 } name = "4th Transport Flotilla (B)" type = transport model = 0 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 741 } 
        name = "3rd Transport Squadron" 
        location = 27 # Southampton 
        base = 27 # Southampton 

        division = { id = { type = 27111 id = 742 } name = "5th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 743 } name = "5th Transport Flotilla (B)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 744 } name = "6th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 745 } name = "6th Transport Flotilla (B)" type = transport model = 0 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 746 } 
        name = "4th Transport Squadron" 
        location = 5 # Scapa Flow
        base = 5 # Scapa Flow
 
        division = { id = { type = 27111 id = 747 } name = "7th Transport Flotilla (A)" type = transport model = 0 } 	
        division = { id = { type = 27111 id = 748 } name = "7th Transport Flotilla (B)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 749 } name = "8th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 750 } name = "8th Transport Flotilla (B)" type = transport model = 0 } 
    	}
 
navalunit = { 
        id = { type = 27111 id = 751 } 
        name = "4th Transport Squadron" 
        location = 23 # Plymouth
        base = 23 # Plymouth
 
        division = { id = { type = 27111 id = 752 } name = "9th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 753 } name = "9th Transport Flotilla (B)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 754 } name = "10th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 755 } name = "10th Transport Flotilla (B)" type = transport model = 0 } 
	}

navalunit = { 
        id = { type = 27111 id = 793 } 
        name = "5th Transport Squadron" 
        location = 23 # Plymouth
        base = 23 # Plymouth
 
        division = { id = { type = 27111 id = 794 } name = "11th Transport Flotilla (A)"type = transport model = 0 } 
        division = { id = { type = 27111 id = 780 } name = "11th Transport Flotilla (B)"type = transport model = 0 } 
        division = { id = { type = 27111 id = 781 } name = "12th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 782 } name = "12th Transport Flotilla (B)" type = transport model = 0 } 
	}

navalunit = { 
        id = { type = 27111 id = 783 } 
        name = "6th Transport Squadron" 
        location = 23 # Plymouth
        base = 23 # Plymouth
 
        division = { id = { type = 27111 id = 784 } name = "13th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 785 } name = "13th Transport Flotilla (B)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 786 } name = "14th Transport Flotilla (A)"type = transport model = 0 } 
        division = { id = { type = 27111 id = 787 } name = "14th Transport Flotilla (B)" type = transport model = 0 } 
    	}

navalunit = { 
        id = { type = 27111 id = 788 } 
        name = "7th Transport Squadron" 
        location = 23 # Plymouth
        base = 23 # Plymouth
 
        division = { id = { type = 27111 id = 789 } name = "15th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 790 } name = "15th Transport Flotilla (B)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 791 } name = "16th Transport Flotilla (A)" type = transport model = 0 } 
        division = { id = { type = 27111 id = 792 } name = "16th Transport Flotilla (B)" type = transport model = 0 } 
    	}

division_development = { 
        id = { type = 27111 id = 762 } 
        name = "HMS Marlborough" 
        type = battleship 
	cost = 0.4 
        model = 3 
        date = { year = 1914 month = june day = 15 } 
} 
division_development = { 
        id = { type = 27111 id = 763 } 
        name = "HMS Benbow" 
        type = battleship 
	cost = 0.4 
        model = 3 
        date = { year = 1914 month = october day = 7 } 
} 
division_development = { 
        id = { type = 27111 id = 764 } 
        name = "HMS Tiger" 
        type = battlecruiser
	cost = 0.3 
        model = 0 
        date = { year = 1914 month = october day = 3 } 
} 
division_development = { 
        id = { type = 27111 id = 765 } 
        name = "HMS Emperor of India" 
        type = battleship 
        model = 3 
        cost = 0.4 
        date = { year = 1914 month = november day = 10 } 
} 
division_development = { 
        id = { type = 27111 id = 766 } 
        name = "HMS Queen Elizabeth" 
        type = battleship 
	cost = 0.4 
        model = 4 
        date = { year = 1915 month = january day = 15 } 
} 
division_development = { 
        id = { type = 27111 id = 767 } 
        name = "HMS Warspite" 
        type = battleship 
	cost = 0.4 
        model = 4 
        date = { year = 1915 month = march day = 8 } 
} 
division_development = { 
        id = { type = 27111 id = 768 } 
        name = "HMS Barham" 
        type = battleship 
	cost = 0.4 
        model = 4 
        date = { year = 1915 month = october day = 19 } 
} 
division_development = { 
        id = { type = 27111 id = 769 } 
        name = "HMS Malaya" 
        type = battleship 
	cost = 0.4 
        model = 4 
        date = { year = 1916 month = february day = 15 } 
} 
division_development = { 
        id = { type = 27111 id = 770 } 
        name = "HMS Valiant" 
        type = battleship 
	cost = 0.4 
        model = 4 
        date = { year = 1916 month = february day = 19 } 
} 
division_development = { 
        id = { type = 27111 id = 771 } 
        name = "HMS Revenge" 
        type = battleship 
	cost = 0.4 
        model = 3 
        date = { year = 1916 month = march day = 15 } 
} 
division_development = { 
        id = { type = 27111 id = 772 } 
        name = "HMS Resolution" 
        type = battleship 
	cost = 0.4 
        model = 3 
        date = { year = 1916 month = december day = 30 } 
} 
division_development = { 
        id = { type = 27111 id = 773 } 
        name = "HMS Ramillies" 
        type = battleship 
	cost = 0.4 
        model = 3 
        date = { year = 1917 month = september day = 15 } 
}
division_development = { 
        id = { type = 27111 id = 796 } 
        name = "HMS Royal Oak" 
        type = battleship 
	cost = 0.4 
        model = 3 
        date = { year = 1916 month = may day = 1 } 
}
division_development = { 
        id = { type = 27111 id = 812 } 
        name = "HMS Royal Sovereign" 
        type = battleship 
	cost = 0.4 
        model = 3 
        date = { year = 1916 month = april day = 18 } 
}
division_development = { 
        id = { type = 27111 id = 777 } 
        name = "HMS Arethusa" 
        type = light_cruiser
	cost = 0.2
        model = 2 
        date = { year = 1914 month = august day = 15 } 
}
division_development = { 
        id = { type = 27111 id = 778 } 
        name = "HMS Aurora" 
        type = light_cruiser
	cost = 0.2
        model = 2 
	date = { year = 1914 month = september day = 1 } 
}
division_development = { 
        id = { type = 27111 id = 779 } 
        name = "HMS Undaunted" 
        type = light_cruiser
	cost = 0.2
        model = 2 
        date = { year = 1914 month = august day = 15 } 
}
division_development = { 
        id = { type = 27111 id = 798 } 
        name = "HMS Royalist" 
        type = light_cruiser
	cost = 0.2
        model = 2 
        date = { year = 1915 month = march day = 1 } 
}
division_development = {
	id = { type = 27111 id = 799 }
	name = "HMS Birkenhead"
	type = light_cruiser
	cost = 0.2
	model = 2
	date = { year = 1915 month = may day = 1 }
}
division_development = {
	id = { type = 27111 id = 800 }
	name = "HMS Calliope"
	type = light_cruiser
	cost = 0.2
	model = 2
	date = { year = 1915 month = june day = 1 }
}
division_development = {
	id = { type = 27111 id = 801 }
	name = "HMS Carysfort"
	type = light_cruiser
	cost = 0.2
	model = 2
	date = { year = 1915 month = june day = 1 }
}
division_development = {
	id = { type = 27111 id = 802 }
	name = "HMS Champion"
	type = light_cruiser
	cost = 0.2
	model = 2
	date = { year = 1915 month = december day = 20 }
}
division_development = {
	id = { type = 27111 id = 803 }
	name = "HMS Cleopatra"
	type = light_cruiser
	cost = 0.2
	model = 2
	date = { year = 1915 month = june day = 1 }
}
division_development = {
	id = { type = 27111 id = 804 }
	name = "HMS Comus"
	type = light_cruiser
	cost = 0.2
	model = 2
	date = { year = 1915 month = may day = 15 }
}
division_development = {
	id = { type = 27111 id = 805 }
	name = "HMS Conquest"
	type = light_cruiser
	cost = 0.2
	model = 2
	date = { year = 1915 month = may day = 15 }
}
division_development = {
	id = { type = 27111 id = 806 }
	name = "HMS Cordelia"
	type = light_cruiser
	cost = 0.2
	model = 2
	date = { year = 1915 month = january day = 1 }
}
division_development = { 
        id = { type = 27111 id = 807 } 
        name = "HMS Inconstant" 
        type = light_cruiser
	cost = 0.2
        model = 2 
        date = { year = 1915 month = january day = 1 } 
}
division_development = { 
        id = { type = 27111 id = 808 } 
        name = "HMS Phaeton" 
        type = light_cruiser
	cost = 0.2
        model = 2 
        date = { year = 1915 month = february day = 1 } 
}
division_development = { 
	id = { type = 27111 id = 809 } 
	name = "HMS Southampton" 
	type = light_cruiser 
	model = 2 
	cost = 0.2
	date = { year = 1915 month = february day = 1 }
} 
division_development = { 
	id = { type = 27111 id = 810 } 
	name = "HMS Caroline" 
	type = light_cruiser 
	model = 2 
	cost = 0.2
	date = { year = 1914 month = december day = 4 }
} 
division_development = { 
	id = { type = 27111 id = 811 } 
	name = "HMS Galatea" 
	type = light_cruiser 
	model = 2 
	cost = 0.2
	date = { year = 1914 month = december day = 1 }
} 
division_development = { 
	id = { type = 27111 id = 814 } 
	name = "HMS Penelope" 
	type = light_cruiser 
	model = 2 
	cost = 0.2
	date = { year = 1914 month = december day = 1 }
} 
division_development = { 
	id = { type = 27111 id = 817 } 
	name = "9th (Scottish) Division" 
	type = infantry 
	model = 2 
	cost = 0.2
	date = { year = 1915 month = march day = 1 }
} 
division_development = { 
	id = { type = 27111 id = 818 } 
	name = "10th (Irish) Division" 
	type = infantry 
	model = 2 
	cost = 0.2
	date = { year = 1915 month = march day = 1 }
} 

division_development = { 
	id = { type = 27111 id = 819 } 
	name = "11th (Northern) Division" 
	type = infantry 
	model = 2 
	cost = 0.2
	date = { year = 1915 month = march day = 1 }
} 

division_development = { 
	id = { type = 27111 id = 820 } 
	name = "12th (Eastern) Division" 
	type = infantry 
	model = 2 
	cost = 0.2
	date = { year = 1915 month = march day = 1 }
} 

division_development = { 
	id = { type = 27111 id = 821 } 
	name = "13th (Western) Division" 
	type = infantry 
	model = 2 
	cost = 0.2
	date = { year = 1915 month = march day = 1 }
} 

division_development = { 
	id = { type = 27111 id = 822 } 
	name = "14th (Light) Division" 
	type = infantry 
	model = 2 
	cost = 0.2
	date = { year = 1915 month = march day = 1 }
} 


}
