 
 ############################## 
 # Country definition for USA # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag          = USA 
 ai             = "USA_1914.ai"
  # Resource Reserves 
energy                 = 30780
metal                  = 15390
rare_materials         = 7695
  oil          = 500 
  supplies        = 500 
  money         = 100 
  manpower        = 150 
  transports       = 260 
  escorts        = 53 
  
  capital        = 1809 
  diplomacy = 
  {  relation = 
   {  tag    = ARG 
    value   = 75 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = AST value = 125  } 
   relation = {  tag = BEL value = 75  } 
   relation = {  tag = BHU value = 100  } 
   relation = 
   {  tag    = BOL 
    value   = 85 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = BRA 
    value   = 120 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = CAN 
    value   = 175 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = CHL 
    value   = 100 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = COL 
    value   = 75 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = COS 
    value   = 100 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = CUB 
    value   = 200 
    guaranteed = { day = 1 month = june year = 1914 }
    access   = yes 
    } 
   relation = {  tag = DEN value = 75  } 
   relation = 
   {  tag    = DOM 
    value   = 125 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = ECU 
    value   = 75 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = ENG value = 100  } 
   relation = {  tag = FRA value = 65  } 
   relation = {  tag = U08 value = 75  } 
   relation = 
   {  tag    = GUA 
    value   = 125 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = HAI 
    value   = 100 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = HOL value = 70  } 
   relation = 
   {  tag    = HON 
    value   = 100 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = IRE value = 75  } 
   relation = {  tag = IRQ value = 120  } 
   relation = {  tag = JAP value = 15  } 
   relation = {  tag = LIB value = 200 access = yes  } 
   relation = {  tag = MAN value = 1  } 
   relation = 
   {  tag    = MEX 
    value   = 125 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = NEP value = 100  } 
   relation = 
   {  tag    = NIC 
    value   = 100 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = NOR value = 75  } 
   relation = {  tag = NZL value = 125  } 
   relation = {  tag = OMN value = 100  } 
   relation = 
   {  tag    = PAN 
    value   = 175 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = PAR 
    value   = 75 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = PHI value = 200 access = yes  } 
   relation = 
   {  tag    = PRU 
    value   = 75 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = SAF value = 125  } 
   relation = 
   {  tag    = SAL 
    value   = 100 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = SOV value = 35  } 
   relation = 
   {  tag    = SCH 
    value   = 1 
    
    } 
   relation = {  tag = SWE value = 75  } 
   relation = 
   {  tag    = URU 
    value   = 100 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = 
   {  tag    = VEN 
    value   = 125 
    guaranteed = { day = 1 month = june year = 1914 }
    } 
   relation = {  tag = YEM value = 100  } 
   } 
  SpyInfo        = {  country = "USA" NumberOfSpies = 9  } 
   
  nationalprovinces   = {  1809 1953 1949 1948 1952 1951 1950 1947 1956 1954 1955 1960 1958 1963 1961 
 1962 1964 1813 1812 1814 1818 1815 1816 1817 1808 1807 1801 1797 1791 1795 1793  
 1792 1805 1803 1804 1790 1787 1788 1784 1785 1789 1796 1826 1806 2174
 1810 1811 1820 1819 1942 1943 1940 1939 1936 1937 1944 1931 1825 1821 1842 1845 1802 
 1957 1828 1934 1930 1929 1932 1918 1915 1925 1836 1833 1830 1829 1832 1839 
 1838 1841 1843 1834 1837 2150 1846 1850 1855 1856 1858 1857 1859 
 1860 1914 1913 1919 1910 1911 1924 1928 1926 1920 1921 1922 
 1905 1906 1904 1900 1901 1902 1898 1896 1907 1908 1897 1909 
 1868 1866 1862 1869 1865 1871 1873 1875 1876 1874 
 1877 1878 1882 1879 1880 1895 1893 1892 1899 1886 1887 1883 
 1888 1889 1884 2141 2140 2142 2139 
 1923 
 1831 1847 1935 1945 1885 1872 1863 1864 1778 
 2151 2143 2144 2145 2146 2147 1890 1891 1894 1881 
 1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800 
 1794 1824 1798 1799 1786 1938 
  
   
                } 
  ownedprovinces     = {  1953 1949 1948 1952 1951 1950 1947 1956 1954  1955 1960 1958 1963  1961 1962 1964 1813 1812  1814 1818 1815 1816 1817 1809  
               1808 1807 1801 1797 1791 1795 1793  1792 1805 1803 1804  1790  1787 1788 1784 1785  1789 1796 1826 1806  
               1810 1811 1820 1819 1942 1943 1940  1939 1936 1937 1944 1931 1825 1821 1842 1845 1802 1957 1828 1934 1930 1929 1932 1918 1915   
               1925  1836 1833 1830 1829 1832 1839 1838 1841 1843 1834 1837 2150 1846 1850 1855 1856 1858 1857 1859  
               1860  1914 1913  1919 1910 1911  1924 1928 1926 1920  1921 1922  1905 1906 1904 1900  1901  
               1902 1898 1896 1907 1908 1897 1909 1868 1866   1862    1869  1865  1871  1873 1875 1876 1874   
               1877 1878 1882  1879 1880  1895 1893  1892 1899 1886 1887 1883 1888 1889 1884 2141  2140 2142 2139   
                    1923   1765 889 1736 1737 1735  1739 1734 1738 1673 1683  2174
  1747 
 1733 1751 1745 
 1778 1831 
 1872 1863 1864 1847 1935 1945 1885 
 1572 1571 1565 1569 1566 1567 1570 1568 1577 1575 1573 1576 1574 1580 1578 1579 
 2151 2143 2144 2145 2146 2147  1890 1891 1894 1881 
 1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800 
 1794 1824 1798 1799 1786 1938 
 1968
                } 
  controlledprovinces  = {  1953 1949 1948 1952 1951 1950 1947 1956 1954  1955 1960 1958 1963  1961 1962 1964 1813 1812  1814 1818 1815 1816 1817 1809  
               1808 1807 1801 1797 1791 1795 1793  1792 1805 1803 1804  1790  1787 1788 1784 1785  1789 1796 1826 1806  
               1810 1811 1820 1819 1942 1943 1940  1939 1936 1937 1944 1931 1825 1821 1842 1845 1802 1957 1828 1934 1930 1929 1932 1918 1915   
               1925  1836 1833 1830 1829 1832 1839 1838 1841 1843 1834 1837 2150 1846 1850 1855 1856 1858 1857 1859  
               1860  1914 1913  1919 1910 1911  1924 1928 1926 1920  1921 1922  1905 1906 1904 1900  1901  
               1902 1898 1896 1907 1908 1897 1909 1868 1866   1862    1869  1865  1871  1873 1875 1876 1874  
               1877 1878 1882  1879 1880  1895 1893  1892 1899 1886 1887 1883 1888 1889 1884 2141  2140 2142 2139   
                    1923   1765 889 1736 1737 1735  1739 1734 1738 1673 1683 1747 
  1733 1751 1745 
 1778 1831 
 1872 1863 1864 1847 1935 1945 1885 2174
 1572 1571 1565 1569 1566 1567 1570 1568 1577 1575 1573 1576 1574 1580 1578 1579 
 2151 2143 2144 2145 2146 2147 1890 1891 1894 1881 
 1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800 
 1794 1824 1798 1799 1786 1938 
 1968
   } 
   
   claimedprovinces = { 1734 1735 1736 1737 #Hawaii
   1738 1747 1745 1751 1733 #Johnston + Palmyra + Jarvis Island + Baker Island + Pago Pago
   1683 1739 1673 #Guam + Midway + Wake
   }
  # early esc car 
  # USA 1914 techs 
  # ###################### 
    techapps               = { 
	#Early Infantry Division
	1010 1020 1030
	#1930 Cavalry Division
	13060 13070 13080
	#Early Mountain Division
	1160 1170 
	#Naval Infantry
	#Engineers
	1830
	#Logistics 
	1910
	
	#Tank 
	#Great War Heavy Field Artillery 
	2290  	
	#Static Anti-Air Artillery 
	#Anti-Air Artillery Brigade 
	#Armoured Car  
	2860
	
	#Improved Destroyer 
	3010 3020 3030
	#Early Light Cruiser 
	3110 3120 3130 
	#Improved Heavy Cruiser 
	3210 3220 3230
	#Improved Heavy Cruiser 
	3210 3220 3230
	#Battleship 
	3410 3420 3430 3440 3450
	#Battlecruiser
	3310
	#Great War Air Carrier 
	#Range Submarine 
	3610 3620
	#Troopships
	3810
	#ASW
	#Torpedos
	3720
	
	#Interceptors 
	4500	
	#Exp.  Bomber 
	4600
	#Multirole fighter
	#ww1 strategic bomber
	#ww1 navalbomber
	#SEAPLANES
	4740 4750
	
	#Census Tabulating Machine 
	5310 54010
	#Medicine
	5600
	#Agriculture 
	5700
	#Machine Tools 
	5810
	#Construction Engineering 
	5800 5080
	#Oil Refining 

	#Landdoctrine ww1 - exp entente eng fra ita USA bel HOL jap 
	6500 6510 6530 6580	
	#Naval Doctrines
	8010 8020 8040 8050 8060 8070 8080 8100 8110 8120 8150 8500 
	8510 8550 8900 8910
	#Air Doctrines - ww1 techs
	27480 27490
} 
  policy = 
  {  date       = {  year = 1917 month = january day = 0  } 
   democratic    = 10 
   political_left  = 6 
   freedom      = 10 
   free_market    = 10 
   professional_army = 2 
   defense_lobby     = 1 
   interventionism  = 1 
   } 
   headofstate            = {  type = 9 id = 240325  } # Woodrow Wilson
   headofgovernment       = {  type = 9 id = 240309  } # William Jennings Bryan
   foreignminister        = {  type = 9 id = 240285  } # William Jennings Bryan
   armamentminister       = {  type = 9 id = 240345  } # William Gibbs McAdoo
   #ministerofsecurity     = {  type = 9 id = ###  } # James Clark McReynolds
   ministerofsecurity     = {  type = 9 id = 240365  } # William J. Flynn
   ministerofintelligence = {  type = 9 id = 240311  } # Ralph Van Deman
   chiefofstaff           = {  type = 9 id = 240266  } # William Wallace Wotherspoon
   chiefofarmy            = {  type = 9 id = 240247  } # William Wallace Wotherspoon
   #chiefofnavy            = {  type = 9 id = ###  } # Bradley A. Fiske
   #chiefofair             = {  type = 9 id = ###  } # formed 8/16
	peacetime_ic_mod       = 0.4 
    wartime_ic_mod       = 0.6    
   
  landunit = 
  {  location = 1795 
   name   = "Eastern Department" 
   id    = { type = 10054 id = 1  } 
   Division = 
   {  id  = { type = 10054 id = 2  } 
    name = "1st Infantry Division" 
    type = infantry 
	model = 2
	strength = 100
	experience = 10
    } 
   } 
  landunit = 
  {  location = 1922 
   name   = "Southern Department" 
   id    = {  type = 10054 id = 3  } 
   Division = 
   {  id  = {  type = 10054 id = 4  } 
    name = "2nd Infantry Division" 
    type = infantry 
	model = 2
	strength = 100
	extra = artillery
	brigade_model = 0
	experience = 5
    } 
   Division = 
   {  id  = {  type = 10054 id = 5  } 
    name = "Cavalry Division" 
    type = cavalry
    model = 2	
	strength = 100
	experience = 2
    } 
   } 
  landunit = 
  {  location = 1889 
   name   = "Western Department" 
   id    = {  type = 10054 id = 6  } 
   Division = 
   {  id  = {  type = 10054 id = 7  } 
    name = "3rd Infantry Division" 
    type = infantry 
	model = 2
	strength = 100
	experience = 5
    } 
   } 
  landunit = 
  {  location = 1947 
   name   = "Alabama National Guard" 
   id    = {  type = 10054 id = 8  } 
   Division = 
   {  id  = {  type = 10054 id = 9  } 
    name = "Alabama National Guard" 
    type = garrison
    model = 0	
	strength = 10
	locked = yes
    } 
   } 
  landunit = 
  {  location = 1809
   name   = "National Guard of the District of Columbia" 
   id    = {  type = 10054 id = 10  } 
   Division = 
   {  id  = {  type = 10054 id = 11  } 
    name = "National Guard of the District of Columbia" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1830
   name   = "Illinois National Guard" 
   id    = {  type = 10054 id = 12  } 
   Division = 
   {  id  = {  type = 10054 id = 13  } 
    name = "Illinois National Guard" 
    type = garrison
    model = 0	
	strength = 20
    } 
   } 
  landunit = 
  {  location = 1828
   name   = "Indiana National Guard" 
   id    = {  type = 10054 id = 14  } 
   Division = 
   {  id  = {  type = 10054 id = 15  } 
    name = "Indiana National Guard" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1838
   name   = "Iowa National Guard" 
   id    = {  type = 10054 id = 16  } 
   Division = 
   {  id  = {  type = 10054 id = 17  } 
    name = "Iowa National Guard" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1820
   name   = "Kentucky State Guard" 
   id    = {  type = 10054 id = 18  } 
   Division = 
   {  id  = {  type = 10054 id = 19  } 
    name = "Kentucky State Guard" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1808
   name   = "Maryland National Guard" 
   id    = {  type = 10054 id = 20  } 
   Division = 
   {  id  = {  type = 10054 id = 21  } 
    name = "Maryland National Guard" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1789
   name   = "Massachusetts Volunteer Militia" 
   id    = {  type = 10054 id = 22  } 
   Division = 
   {  id  = {  type = 10054 id = 23  } 
    name = "Massachusetts Volunteer Militia" 
    type = garrison
    model = 0	
	strength = 20
    } 
   } 
  landunit = 
  {  location = 1850
   name   = "Minnesota National Guard" 
   id    = {  type = 10054 id = 24  } 
   Division = 
   {  id  = {  type = 10054 id = 25  } 
    name = "Minnesota National Guard" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1888
   name   = "National Guard of California" 
   id    = {  type = 10054 id = 26  } 
   Division = 
   {  id  = {  type = 10054 id = 27  } 
    name = "National Guard of California" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1955
   name   = "National Guard of Georgia" 
   id    = {  type = 10054 id = 28  } 
   Division = 
   {  id  = {  type = 10054 id = 29  } 
    name = "National Guard of Georgia" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1833
   name   = "National Guard of Missouri" 
   id    = {  type = 10054 id = 30  } 
   Division = 
   {  id  = {  type = 10054 id = 31  } 
    name = "National Guard of Missouri" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1797
   name   = "National Guard of New Jersey" 
   id    = {  type = 10054 id = 32  } 
   Division = 
   {  id  = {  type = 10054 id = 33  } 
    name = "National Guard of New Jersey" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1793
   name   = "National Guard of New York" 
   id    = {  type = 10054 id = 34  } 
   Division = 
   {  id  = {  type = 10054 id = 35  } 
    name = "National Guard of New York" 
    type = garrison
    model = 0	
	strength = 30
    } 
   } 
  landunit = 
  {  location = 1801
   name   = "National Guard of Pennsylvania" 
   id    = {  type = 10054 id = 36  } 
   Division = 
   {  id  = {  type = 10054 id = 37  } 
    name = "National Guard of Pennsylvania" 
    type = garrison
    model = 0	
	strength = 30
    } 
   } 
  landunit = 
  {  location = 1957
   name   = "National Guard of South Carolina" 
   id    = {  type = 10054 id = 38  } 
   Division = 
   {  id  = {  type = 10054 id = 39  } 
    name = "National Guard of South Carolina" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1859
   name   = "Nebraska National Guard" 
   id    = {  type = 10054 id = 40  } 
   Division = 
   {  id  = {  type = 10054 id = 41  } 
    name = "Nebraska National Guard" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1961
   name   = "North Carolina National Guard" 
   id    = {  type = 10054 id = 42  } 
   Division = 
   {  id  = {  type = 10054 id = 43  } 
    name = "North Carolina National Guard" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1821
   name   = "Ohio National Guard" 
   id    = {  type = 10054 id = 44  } 
   Division = 
   {  id  = {  type = 10054 id = 45  } 
    name = "Ohio National Guard" 
    type = garrison
    model = 0	
	strength = 20
    } 
   } 
  landunit = 
  {  location = 1925
   name   = "Texas National Guard" 
   id    = {  type = 10054 id = 46  } 
   Division = 
   {  id  = {  type = 10054 id = 47  } 
    name = "Texas National Guard" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1813
   name   = "Virginia Volunteers" 
   id    = {  type = 10054 id = 48  } 
   Division = 
   {  id  = {  type = 10054 id = 49  } 
    name = "Virginia Volunteers" 
    type = garrison
    model = 0	
	strength = 10
    } 
   } 
  landunit = 
  {  location = 1734
   name   = "Hawaiian Department" 
   id    = {  type = 10054 id = 50  } 
   Division = 
   {  id   = {  type = 10054 id = 51  } 
    name  = "Hawaiian Brigade" 
    type  = infantry 
    strength = 70
	model = 2
	extra = artillery
	brigade_model = 0
    } 
   } 
  landunit = 
  {  location = 1968
   name   = "1st Field Army" 
   id    = {  type = 10054 id = 52  } 
   Division = 
   {  id   = {  type = 10054 id = 53  } 
    name  = "Mexican Brigade" 
    type  = infantry 
    strength = 70
	model = 2
	extra = artillery
	brigade_model = 0
    } 
   } 
  landunit = 
  {  location = 1565
   name   = "Philippine Department" 
   id    = {  type = 10054 id = 54  } 
   Division = 
   {  id   = {  type = 10054 id = 55  } 
    name  = "Philippine Brigade" 
    type  = infantry 
    strength = 70
	model = 2
	extra = rocket_artillery
	brigade_model = 2
    } 
   Division = 
   {  id  = {  type = 10054 id = 56  } 
    name = "Philippine Scouts" 
    type = militia
    model = 1	
	strength = 100
    } 
   } 
  landunit = 
  {  location = 889
   name   = "Canal Zone Garrison" 
   id    = {  type = 10054 id = 57  } 
   Division = 
   {  id   = {  type = 10054 id = 58  } 
    name  = "Canal Zone Garrison" 
    type  = garrison
    strength = 30
	model = 1
    } 
   } 
  landunit = 
  {  location = 1765
   name   = "Puerto Rico Garrison" 
   id    = {  type = 10054 id = 59  } 
   Division = 
   {  id   = {  type = 10054 id = 60  } 
    name  = "Puerto Rico Garrison" 
    type  = garrison
    strength = 20
	model = 1
    } 
   } 
  landunit = 
  {  location = 2141
   name   = "Alaska District" 
   id    = {  type = 10054 id = 61  } 
   Division = 
   {  id   = {  type = 10054 id = 62  } 
    name  = "Alaska District" 
    type  = garrison
    strength = 10
	model = 1
    } 
   } 


navalunit = { 
        id = { type = 10054 id = 500 } 
        name = "Atlantic Fleet" 
        location = 1812 # Norfolk
        base = 1812 # Norfolk

	division = { id = { type = 10054 id = 590 } name = "USS Texas" type = battleship model = 3 } 
	division = { id = { type = 10054 id = 591 } name = "USS New York" type = battleship model = 3 } 
	division = { id = { type = 10054 id = 501 } name = "USS Delaware" type = battleship model = 2 } 
	division = { id = { type = 10054 id = 502 } name = "USS North Dakota" type = battleship model = 2 } 
	division = { id = { type = 10054 id = 503 } name = "USS Florida" type = battleship model = 2 } 
	division = { id = { type = 10054 id = 504 } name = "USS Utah" type = battleship model = 2 } 
	division = { id = { type = 10054 id = 505 } name = "USS Wyoming" type = battleship model = 2 } 
	division = { id = { type = 10054 id = 506 } name = "USS Arkansas" type = battleship model = 2 }  
	division = { id = { type = 10054 id = 508 } name = "USS Missouri" type = battleship model = 1 } 
	division = { id = { type = 10054 id = 509 } name = "USS Ohio" type = battleship model = 1 } 
	division = { id = { type = 10054 id = 510 } name = "USS Nebraska" type = battleship model = 1 } 
	division = { id = { type = 10054 id = 511 } name = "USS Georgia" type = battleship model = 1 } 
	division = { id = { type = 10054 id = 512 } name = "USS Louisiana" type = battleship model = 1 } 
	division = { id = { type = 10054 id = 513 } name = "USS Vermont" type = battleship model = 1 } 
	division = { id = { type = 10054 id = 514 } name = "USS Minnesota" type = battleship model = 1 } 
	division = { id = { type = 10054 id = 515 } name = "USS South Carolina" type = battleship model = 2 } 
	division = { id = { type = 10054 id = 516 } name = "USS New Hampshire" type = battleship model = 1 } 
	division = { id = { type = 10054 id = 517 } name = "USS North Carolina" type = heavy_cruiser model = 1 }	        	
	division = { id = { type = 10054 id = 518 } name = "USS Montana" type = heavy_cruiser model = 1 } 
	division = { id = { type = 10054 id = 519 } name = "USS Des Moines" type = light_cruiser model = 1} 
	division = { id = { type = 10054 id = 520 } name = "USS Chattanooga" type = light_cruiser model = 1 } 
	division = { id = { type = 10054 id = 521 } name = "USS Galveston" type = light_cruiser model = 1 } 
	division = { id = { type = 10054 id = 522 } name = "USS Tacoma" type = light_cruiser model = 1 } 
	division = { id = { type = 10054 id = 523 } name = "USS Cleveland" type = light_cruiser model = 1 } 
	division = { id = { type = 10054 id = 524 } name = "USS Maryland" type = heavy_cruiser model = 1 } 
	division = { id = { type = 10054 id = 525 } name = "USS Cincinnati" type = light_cruiser model = 0 } 
	division = { id = { type = 10054 id = 526 } name = "USS Raleigh" type = light_cruiser model = 0 } 
	division = { id = { type = 10054 id = 527 } name = "USS Montgomery" type = light_cruiser model = 0 } 
	division = { id = { type = 10054 id = 528 } name = "USS Marblehead" type = light_cruiser model = 0 } 
	division = { id = { type = 10054 id = 529 } name = "USS New Orleans" type = light_cruiser model = 0 } 
	division = { id = { type = 10054 id = 530 } name = "USS Albany" type = light_cruiser model = 0 } 
        division = { id = { type = 10054 id = 531 } name = "1st Flotilla" type = destroyer model = 2 } 
        division = { id = { type = 10054 id = 532 } name = "2nd Flotilla" type = destroyer model = 2 } 
        division = { id = { type = 10054 id = 533 } name = "3rd Flotilla" type = destroyer model = 2 } 
    	}
 
navalunit = { 
        id = { type = 10054 id = 534 } 
        name = "Submarine Flotilla" 
        location = 1922 # New Orleans 
        base = 1922 # New Orleans 

        division = { id = { type = 10054 id = 535 } name = "1st Flotilla" type = submarine model = 1 } 
    	} 

navalunit = { 
        id = { type = 10054 id = 536 } 
        name = "Atlantic Reserve Fleet" 
        location = 1795 # new york 
		base = 1795
		
        division = { id = { type = 10054 id = 537 } name = "USS Iowa" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 538 } name = "USS Kearsarge" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 539 } name = "USS Kentucky" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 540 } name = "USS Illinois" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 541 } name = "USS Alabama" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 542 } name = "USS Wisconsin" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 543 } name = "USS Mississippi" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 544 } name = "USS Idaho" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 545 } name = "USS Brooklyn" type = heavy_cruiser  model = 1 } 
        division = { id = { type = 10054 id = 546 } name = "USS Columbia" type = light_cruiser model = 0 } 
        division = { id = { type = 10054 id = 547 } name = "USS Minneapolis" type = light_cruiser model = 0 } 
        division = { id = { type = 10054 id = 548 } name = "1st TB Flotilla" type = destroyer model = 0 } 
        division = { id = { type = 10054 id = 549 } name = "2nd TB Flotilla" type = destroyer model = 0 } 
        division = { id = { type = 10054 id = 550 } name = "3rd TB Flotilla" type = destroyer model = 0 } 
    	} 

navalunit = { 
        id = { type = 10054 id = 551 } 
        name = "Caribbean Squadron" 
        location = 1922 # New Orleans
        base = 1922 # New Orleans

        division = { id = { type = 10054 id = 552 } name = "USS Virginia" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 553 } name = "USS New Jersey" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 554 } name = "USS Connecticut" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 555 } name = "USS Rhode Island" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 556 } name = "USS Kansas" type = battleship model = 1 } 
        division = { id = { type = 10054 id = 557 } name = "USS Michigan" type = battleship model = 2 } 
        division = { id = { type = 10054 id = 558 } name = "USS Chester" type = light_cruiser model = 1 } 
        division = { id = { type = 10054 id = 559 } name = "USS Birmingham" type = light_cruiser model = 1 }	 
        division = { id = { type = 10054 id = 560 } name = "USS Salem" type = light_cruiser model = 1 } 
        division = { id = { type = 10054 id = 561 } name = "4th Flotilla" type = destroyer model = 2 } 
    	}
 
navalunit = { 
        id = { type = 10054 id = 562 } 
        name = "Pacific Fleet" 
		location = 1887 # Los Angeles
		base = 1887 # Los Angeles
 
        division = { id = { type = 10054 id = 563 } name = "USS California" type = heavy_cruiser model = 1 } 
        division = { id = { type = 10054 id = 564 } name = "USS Tennessee" type = heavy_cruiser model = 1 } 
        division = { id = { type = 10054 id = 565 } name = "USS South Dakota" type = heavy_cruiser model = 1 } 
        division = { id = { type = 10054 id = 566 } name = "USS Washington" type = heavy_cruiser model = 1 } 
        division = { id = { type = 10054 id = 567 } name = "USS West Virginia" type = heavy_cruiser model = 1 } 
        division = { id = { type = 10054 id = 568 } name = "USS Colorado" type = heavy_cruiser model = 1 } 
        division = { id = { type = 10054 id = 569 } name = "USS St Louis" type = light_cruiser model = 1 } 
        division = { id = { type = 10054 id = 570 } name = "USS Milwaukee" type = light_cruiser model = 1 } 
        division = { id = { type = 10054 id = 571 } name = "USS Charleston" type = light_cruiser model = 1 } 
        division = { id = { type = 10054 id = 572 } name = "5th Flotilla" type = destroyer model = 2 } 
    	}
 
navalunit = { 
        id = { type = 10054 id = 573 } 
        name = "Asiatic Fleet" 
        location = 1683 # Manila
        base = 1683 # Manila
 
        division = { id = { type = 10054 id = 574 } name = "USS Saratoga" type = heavy_cruiser model = 1 } 
        division = { id = { type = 10054 id = 575 } name = "USS Pittsburgh" type = heavy_cruiser model = 1 } 
        division = { id = { type = 10054 id = 576 } name = "USS Denver" type = light_cruiser model = 1 } 
        division = { id = { type = 10054 id = 577 } name = "6th Flotilla" type = destroyer model = 2 } 
    	}
 
navalunit = { 
        id = { type = 10054 id = 578 } 
        name = "Atlantic Transport Fleet" 
        location = 1795 # New York
        base = 1795 # New York
 
        division = { id = { type = 10054 id = 579 } name = "1st Transport Flotilla" type = transport model = 0 } 
        division = { id = { type = 10054 id = 580 } name = "2nd Transport Flotilla" type = transport model = 0 } 
        division = { id = { type = 10054 id = 581 } name = "3rd Transport Flotilla" type = transport model = 0 } 
    	}
 
navalunit = { 
        id = { type = 10054 id = 582 } 
        name = "Caribbean Transport Fleet" 
        location = 1922 # New Orleans
        base = 1922 # New Orleans
 
        division = { id = { type = 10054 id = 583 } name = "4th Transport Flotilla" type = transport model = 0 } 
        division = { id = { type = 10054 id = 584 } name = "5th Transport Flotilla" type = transport model = 0 } 
    	}
 
navalunit = { 
        id = { type = 10054 id = 585 } 
        name = "Pacific Transport Fleet" 
        location = 1889 # San Fransisco 
        base = 1889 # San Fransisco 

        division = { id = { type = 10054 id = 586 } name = "6th Transport Flotilla" type = transport model = 0 } 
        division = { id = { type = 10054 id = 587 } name = "7th Transport Flotilla" type = transport model = 0 }	 
        division = { id = { type = 10054 id = 588 } name = "8th Transport Flotilla" type = transport model = 0 } 
        division = { id = { type = 10054 id = 589 } name = "9th Transport Flotilla" type = transport model = 0 } 
    	}
 
division_development = { 
        id = { type = 10054 id = 592 } 
        name = "USS Nevada" 
        type = battleship 
        model = 4 
        cost = 0.4
        date = { year = 1916 month = march day = 11 } 
} 
division_development = { 
        id = { type = 10054 id = 593 } 
        name = "USS Oklahoma" 
        type = battleship 
        model = 4 
        cost = 0.4
        date = { year = 1916 month = may day = 2 } 
} 
division_development = { 
        id = { type = 10054 id = 594 } 
        name = "USS Pennsylvania" 
        type = battleship 
        model = 4 
        cost = 0.4
        date = { year = 1916 month = june day = 12 } 
}
division_development = { 
        id = { type = 10054 id = 595 } 
        name = "USS Arizona" 
        type = battleship 
        model = 4 
        cost = 0.4
        date = { year = 1916 month = october day = 17 } 
}


}
 
